### ISSUE TITLE
gpu_info crashes because it cannot parse "N/A"

### ISSUE THREAD

**Issue by BlackHC** [pytorch/ignite#1040]
## 🐛 Bug description

When trying to use gpu_info, it throws:

```
 File "/home/blackhc/anaconda3/envs/hello-mnist/lib/python3.7/site-packages/ignite/contrib/metrics/gpu_info.py", line 91, in completed
    engine.state.metrics[util_name] = int(util_report['gpu_util'])
ValueError: invalid literal for int() with base 10: 'N/A'
```

There is error handling code above it, but it does not catch the issue ("N/A" is returned).

I assume my GPU does not support it. However, it would be neat to have a graceful failure mode.

Thank you!
Andreas

## Environment

torch 1.5 on a GTX 780 TI (source)
ignite 0.3.0 (conda)
pynvml 8.0.4 (pip)

**Comment by vfdev-5** [comment]
Hi Andreas, thanks for catching that !

Maybe, we can cast it to -1 or 0 if no support of `gpu_util`. 
Actually, what shows `nvidia-smi` on your GPU ?

**Comment by BlackHC** [comment]
Thank you! And sorry for the reply! nvidia-smi also displays N/A
