### ISSUE TITLE
Use decorator one_rank_only on Checkpoint and BaseLogger

### ISSUE THREAD

**Issue by sdesrozis** [pytorch/ignite#1055]
## 🚀 Feature

Handlers may not be parallel and be triggered on the master proc (rank=0). The idea is to use the decorator `one_rank_only` (in branch `idist`) on `__call__` methods or specific working methods for `Checkpoint` and `BaseLogger`.

**Comment by erip** [comment]
One thing to keep in mind is that in the XLA context, this constraint is maintained internally in `xm.save`. I haven't looked at the implementation of `one_rank_only` yet, so it might be a moot point. 😄
