### ISSUE TITLE
Some way of dodging ReproducibleBatchSampler

### ISSUE THREAD

**Issue by samedii** [pytorch/ignite#1070]
## 🚀 Feature

I want to be able to change the weights of my sampler while training and let it have an effect before the next epoch

Doing this at the moment requires some type of ugly hack. I'm currently doing:
```
    ignite.engine.engine.ReproducibleBatchSampler.__iter__ = (
        lambda self: iter(self.batch_sampler)
    )
```

_Note that I've never told ignite to do anything deterministically anyway_

Sidenote: I also had issues with ReproducibleBatchSampler earlier because of large/infinite length of the sampler (even if the dataset was limited in length)

**Comment by vfdev-5** [comment]
@samedii thanks asking. This behaviour will be removed in v0.4.0 (which RC will be released very soon). At the moment, please, nightly release which has default `Engine` without patching dataloader and `DeterministicEngine` which replicates current v0.3.0 behaviour.
Please, tell me if it handles your problem ?

**Comment by samedii** [comment]
Sounds great! Cannot use it without some pain so I will hold off until it's released then. (CallableEvents cannot be imported)

**Comment by vfdev-5** [comment]
> Cannot use it without some pain so I will hold off until it's released then. (CallableEvents cannot be imported)

@samedii is it with nightly release ? If yes, could you please detail what is the problem you have with it ?

**Comment by samedii** [comment]
I could not import CallableEvents

`from ignite.engine.engine import CallableEvents`

Guessing we are not supposed to use it since it's under `engine.engine`

**Comment by vfdev-5** [comment]
Thanks for pointing out this ! We need to backport that for v0.4.0 as we reworked events system.

Replacement of `CallableEvents` is `Events` as now all events are callable.
