### ISSUE TITLE
Is there a place to keep track of the newly added features?

### ISSUE THREAD

**Issue by snie2012** [pytorch/ignite#1073]
I can see a list of features when a new version in released. However, is there a place to track of the features added to the latest master?

**Comment by vfdev-5** [comment]
Yes, you can see them here : https://github.com/pytorch/ignite/compare/v0.3.0...master

**Comment by snie2012** [comment]
Thanks @vfdev-5. Apart from that, any documentation of the major features added?

**Comment by sdesrozis** [comment]
We don’t have yet ChangeLog or ReleaseNote. Thanks for the suggestion @snie2012 👍🏻

**Comment by vfdev-5** [comment]
@snie2012 now you can track newly added features etc here : 

https://github.com/pytorch/ignite/releases/tag/v0.4rc.0.post1

I close the issues as soved. Please, feel free to reopen if needed.
