### ISSUE TITLE
Length check fails for IterableDataset

### ISSUE THREAD

**Issue by snie2012** [pytorch/ignite#1076]
I am using IterableDataset with unknown length. It fails inside the following `if` clause:

https://github.com/pytorch/ignite/blob/cc78b3bbd764da9ae7dee0df21676b2b8a50fba8/ignite/engine/engine.py#L642

Here is the logic why it fails: 
1. Data is PyTorch DataLoader, which has the `__len__` attr, so it goes into the `if` clause
2. It runs the code `epoch_length = len(data)`, and leads to `length = self._IterableDataset_len_called = len(self.dataset)` in `dataloader.py` in pytorch
3. Since dataset is an IterableDataset, it doesn't have length so it throws sth like `TypeError: object of type 'IterableDataset' has no len()`

My concern is that we shouldn't expect IterableDataset to have `__len__` and the code should not fail because of it. Any thoughts on this?

**Comment by vfdev-5** [comment]
@snie2012 thanks for the report. Yes, you are right about that. We have a test with `IterableDataset` but it has gone to deterministic engine and now default engine has escaped the checking. Yes, definitely, we need to support that !

**Comment by SantoshGuptaML** [comment]
Should `DistributedSampler` also support `IterableDataset` ? I get this error message

```
    train_sampler = DistributedSampler(TrainDataset(config))
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/distributed.py", line 63, in __init__
    self.num_samples = int(math.ceil(len(self.dataset) * 1.0 / self.num_replicas))
TypeError: object of type 'TrainDataset' has no len()
```

Where `TrainDataset` is an extension of `IterableDataset`

**Comment by vfdev-5** [comment]
@SantoshGuptaML no, torch's `DistributedSampler` does not support iterable datasets, only map-style datasets.

There are various way to route samples depending on process (distributed or simply mp):
- https://pytorch.org/docs/stable/data.html#single-and-multi-process-data-loading
- https://discuss.pytorch.org/t/ddp-and-iterable-datasets/79180

In case of distributed training, the simplest way to distribute it (if possible) is to set up your iterable dataset depending on the rank:
```python
import ignite.distributed as idist
rank = idist.get_rank()
ws = idist.get_world_size()
dataset = get_iterable_dataset(..., rank=rank, world_size=ws, ...)
```
where `get_iterable_dataset` is your custom method that fetches unique data for a rank.
