### ISSUE TITLE
Create notes about concepts in ignite

### ISSUE THREAD

**Issue by alykhantejani** [pytorch/ignite#108]
These should be put in a sphinx compatible format like what is [done in pytorch](https://github.com/pytorch/pytorch/tree/master/docs/source/notes)

**Comment by vfdev-5** [comment]
@alykhantejani what do you think to write in these notes? Today we have empty files : 
```
 	concepts.rst
	engines.rst
	exceptions.rst 
	handlers.rst 
	index.rst 
	metrics.rst
	quickstart.rst 
```
In pytorch similar notes cover some particular notions or best practices.

**Comment by alykhantejani** [comment]
I think we need to cover a few things:
1) An overview of the event system
2) Defining your own event handlers
3) An overview of the metrics API

These files were put in as a stub initially, but if you fancy making a start on this feel free to re-arrange/delete as you see fit.

cc @jasonkriss in case he had some thoughts around this

**Comment by jasonkriss** [comment]
Agreed with @alykhantejani. The way I had envisioned this and stubbed it out is to have a "Concepts" note that has the 3 things @alykhantejani mentioned. And then a "Quickstart" guide that just gives a barebones run through of getting a project up and running. The other .rst files will be filled in with `autodoc` but we certainly may want to add some additional context to each one at the top before the actual `autodoc` parts.

That being said, this can definitely change if you wanna get started on it and prefer a different arrangement.

**Comment by vfdev-5** [comment]
I see what you mean @alykhantejani  @jasonkriss, I can start with "Quickstart". 
What do we put in `index.rst` or it will be filled with `autodoc` ?

**Comment by jasonkriss** [comment]
`engines.rst` should still be `engines` because of how we have structured the code. You shouldn't have to put anything in index.rst unless you really want to. You can just add stuff to quickstart.rst. That would be awesome!

**Comment by vfdev-5** [comment]
@jasonkriss you can check the first version of quickstart [here](https://github.com/vfdev-5/ignite/blob/issue_108/docs/source/quickstart.rst) ;-)

**Comment by jasonkriss** [comment]
@vfdev-5 That looks like a great start!

**Comment by alykhantejani** [comment]
I think this is done now @vfdev-5 @jasonkriss? Let me know if you think this should still stay open

**Comment by vfdev-5** [comment]
@alykhantejani following your [comment](https://github.com/pytorch/ignite/issues/108#issuecomment-377281414) there is missing:
3. An overview of the metrics API
But I do not know where to put it : `concepts.rst` or `metrics.rst` (however `metrics` is at Package Reference)

**Comment by jasonkriss** [comment]
@vfdev-5 I think `concepts.rst` is a good place for high-level overview of how to to use metrics but i think `metrics.rst` is a good place to explain the `Metric` API and what methods need to be implemented to create your own metrics.

**Comment by alykhantejani** [comment]
ok I think this task is now done. I will open new ones for the `metrics.rst`, `engines.rst` and `handlers.rst` package references. 

Once these are done I think we're ready to release 0.1

**Comment by vfdev-5** [comment]
@alykhantejani  and `exceptions.rst` too or not ?
