### ISSUE TITLE
Create wheels and conda tar builds

### ISSUE THREAD

**Issue by alykhantejani** [pytorch/ignite#109]

**Comment by elanmart** [comment]
@alykhantejani where should conda build scripts live? Perhaps with the rest of `pytorch`, so they're on the same conda channel?

Pytorch scripts seem to be [here](https://github.com/pytorch/builder/tree/master/conda)

**Comment by vfdev-5** [comment]
So, I started working on this issue and I have some points to discuss. As @elanmart pointed out pytorch and torchvision conda stuff is built in [pytorch/builder](https://github.com/pytorch/builder/tree/master/conda).  So if we aim to integrate ignite in the pytorch/builder: add build_ignite.sh script and meta.yaml to the repository, I have an impression that we may be limited by pytorch releases and can not make our own releases independently of pytorch. Correct me if I'm wrong.

Another point is on release workflow, following [build_vision.sh](https://github.com/pytorch/builder/blob/master/conda/build_vision.sh):
```
rm -rf torchvision-src
git clone https://github.com/pytorch/vision torchvision-src
pushd torchvision-src
git checkout v$VISION_BUILD_VERSION
popd
```
we need first to make a tag and then create wheels+tars.

So I created these meta.yaml and build_ignite.sh [here](https://github.com/vfdev-5/ignite/tree/wheels_tars/conda) but something goes wrong with error:
```
raise CondaValueError("Empty version string.")
```
if womebody could assist me with that would be great !

On PyPI everything is more simple :) just run 
```
# Added setup.cfg with universal = 1
python3 setup.py sdist bdist_wheel
twine upload --repository-url https://test.pypi.org/legacy/ dist/*
```
so you can checkout a preliminary 0.1.0 version at [test.pypi](https://test.pypi.org/project/pytorch-ignite/)

**Comment by alykhantejani** [comment]
I think we should have an independent release cycle and process. We can update the wheels on pypi and the tar on conda ourselves.

As for the conda error, I'm not quite sure what could cause this. I can try and reproduce on my side

**Comment by alykhantejani** [comment]
@vfdev-5 Trying to find out what the problem is with the conda build. From the [conda docs](https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#build-section) it seems like the build command should also contain `https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#build-section`

As for your `Empty version string` error, not 100% sure but this may be related to the fact that the conda build wont be able to install `pytorch` (as it's only available in the `pytorch` channel). This works for the vision build as the `ANACONDA_USER=pytorch`. 

According to this [stackoverflow post](https://stackoverflow.com/a/25632265), its not easy to specify this in the `meta.yaml` but instead we can add this line before the call to build:

```
conda config --add channels pytorch
```
