### ISSUE TITLE
DistributedDataParallel support

### ISSUE THREAD

**Issue by beyondyoni** [pytorch/ignite#1091]
## ❓ Questions/Help/Support

Hi,
When trying to use DistributedDataParallel, I'm getting the following error: 
TypeError: can't pickle _thread.lock objects

Can anyone help?

**Comment by vfdev-5** [comment]
@beyondyoni normally, DDP is fully supported with ignite. Please, share a minimal code to reproduce your problem. Thanks !

**Comment by beyondyoni** [comment]
@vfdev-5 Thanks! do you have a working example of a model trained using DDP?
I'm pretty sure that I'm doing some silly mistakes - we're creating Ignite engines for every spawned process. Is this the right approach?

Anyways, this is the method we try to spawn:
```   
def single_gpu_run(
            self,
            gpu_num: int,
            max_epochs: int,
            train: bool = True,
            optimizers_genrator: Callable,
    ):
        rank = gpu_num
        dist.init_process_group(backend='nccl', init_method='env://', world_size=self.number_of_gpus, rank=rank)

        torch.manual_seed(0)
        torch.cuda.set_device(gpu_num)
        data_loaders = self._generate_data_loaders()
        optimizers = self.create_optimizers()
        model = self._generate_architecture(self.restore_path)
        model.cuda(gpu_num)

        model = nn.parallel.DistributedDataParallel(model, device_ids=[gpu_num])

        for engine in self.create_engines(train, model, optimizres, data_loaders):
            engine.run(max_epochs)
```

create_engines creates a set of trainer + evaluator, define handlers, and returns the engines to run. 
In DDP case, _generate_data_loaders creates the data loaders using DistributedSampler

below is the spawn:
```
        if self.multi_gpu:
            os.environ['MASTER_ADDR'] = 'localhost'
            os.environ['MASTER_PORT'] = '6666'
            mp.spawn(self.single_gpu_run, nprocs=self.number_of_gpus, args=(max_epochs,
                                                                            train,
                                                                            optimizers_dict,
                                                                            engine_args))
```

**Comment by vfdev-5** [comment]
> do you have a working example of a model trained using DDP?

@beyondyoni yes, please see https://github.com/pytorch/ignite#distributed-cifar10-example or https://github.com/pytorch/ignite#reproducible-training-examples
However, those examples, however, are not using spawn. 

What is your version of pytorch-ignite ?

Looking at your code, seems like it mp.spawn is called from class method and should insert its own method ... I have a slight doubt about how it would work. 
Another point is args you pass. Your method would like : 
```
max_epochs: int,
train: bool = True,
optimizers_genrator: Callable,
```
but you pass
```
max_epochs,
train,
optimizers_dict,
engine_args
```

**Comment by vfdev-5** [comment]
@beyondyoni if you can use the latest nightly release, something similar to your example can be done like that:
```python
# script file: check_idist_spawn.py

import ignite
import ignite.distributed as idist

class A:
    
    def __init__(self, nprocs=4):
        idist.spawn("gloo", self.training, (1, 2, 3), {"a": "a", "b": "b"}, num_procs_per_node=nprocs)
        
    def training(self, local_rank, *args, **kwargs):
        print(local_rank, idist.get_world_size(), args, kwargs)

if __name__ == '__main__':
    
    print(ignite.__version__)
    a = A(4)

```
and 
```
# python check_idist_spawn.py 
0.4.0.dev20200601
0 4 (1, 2, 3) {'a': 'a', 'b': 'b'}
3 4 (1, 2, 3) {'a': 'a', 'b': 'b'}
2 4 (1, 2, 3) {'a': 'a', 'b': 'b'}
1 4 (1, 2, 3) {'a': 'a', 'b': 'b'}
```
HTH

**Comment by beyondyoni** [comment]
Works perfectly!!!

@vfdev-5 thank you very very much!
