### ISSUE TITLE
Misleading ValueError - Accuracy Metric Multilabel

### ISSUE THREAD

**Issue by niowniow** [pytorch/ignite#1100]
## 🐛 Bug description

When using Accuracy.update() with both inputs having the second dimension 1, e.g. in my case `torch.Size([256,1])` the raised error message is misleading.

To reproduce 
```
from ignite.metrics import Accuracy
import torch
acc = Accuracy(is_multilabel=True)
acc.update((torch.zeros((256,1)), torch.zeros((256,1))))
```
`ValueError: y and y_pred must have same shape of (batch_size, num_categories, ...).`

In this case the y and y_pred do have the same shape but the issue is that it's not an accepted multilabel input (the `and y.shape[1] != 1` in the following code block from `_check_shape` in `_BaseClassification`). This should be indicated in the error message (or the if statement changed).

What is the argument to not allow a `y.shape[1]` of 1?

```
if self._is_multilabel and not (y.shape == y_pred.shape and y.ndimension() > 1 and y.shape[1] != 1):
            raise ValueError("y and y_pred must have same shape of (batch_size, num_categories, ...).")
```

## Environment

 - PyTorch Version (e.g., 1.4): 
 - Ignite Version (e.g., 0.3.0): 0.3.0
 - OS (e.g., Linux): Linux
 - How you installed Ignite (`conda`, `pip`, source): conda
 - Python version:
 - Any other relevant information:

**Comment by niowniow** [comment]
Ok, I'm still working through this. Sorry for having posted too early. Maybe the issue is that the two [lines](https://github.com/pytorch/ignite/blob/01a2bc0f79ca03565dd0c112b73d6508bc81b070/ignite/metrics/accuracy.py#L145) 
```
        self._check_shape((y_pred, y))
        self._check_type((y_pred, y))
```
should be in reverse order!? 
Maybe someone could have a look at it.

**Comment by vfdev-5** [comment]
@niowniow thanks for posting ! 
I agree with your fist message about misleading error message regarding the input as in your example. Maybe, even the condition `y.shape[1] != 1` is a bit wrong and should be `y.shape[1] > 1` (to cover cases like `t = torch.zeros(10, 0, 2)`).

I think, we just need to improve the error message to 
```
"y and y_pred must have same shape of (batch_size, num_categories, ...) and num_categories > 1"
```

What do you think ?

**Comment by sdesrozis** [comment]
@niowniow Thank you for the question. 

@vfdev-5 You are too fast!! :)

**Comment by niowniow** [comment]
@vfdev-5 That would probably do it. However, I'm don't know if it holds for `y.shape[1] > 1`
@sdesrozis Yes, it should be greater than one. However, I ran multiple tests with varying number of categories. Some happen to have only one category. And I didn't check for it before instantiating Accuracy.

But would there be a difference in the output of the binary case and the multilabel case with `num_categories==1`?

**Comment by sdesrozis** [comment]
> @sdesrozis Yes, it should be greater than one. However, I ran multiple tests with varying number of categories. Some happen to have only one category. And I didn't check for it before instantiating Accuracy.

Ok it makes sense, thank you for that clarification.
 
> But would there be a difference in the output of the binary case and the multilabel case with `num_categories==1`?

Actually we don't have the same implementation but I agree that should not be different. Let's see what we can do.

**Comment by vfdev-5** [comment]
If `num_categories` changes, another error is raised:
https://github.com/pytorch/ignite/blob/01a2bc0f79ca03565dd0c112b73d6508bc81b070/ignite/metrics/accuracy.py#L88-L91

**Comment by niowniow** [comment]
Thanks. It's fine for me to have another if-condition checking if my input should use `binary`.

**Comment by sdesrozis** [comment]
@niowniow Perfect!
