### ISSUE TITLE
ProgressBar does not close the bar on Colab if every is used

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1115]
## 🐛 Bug description

Progress bar is set with `common.setup_common_training_handlers(... log_every_iters=15, ...)` and it does not close itself as being not terminated ...

<img width="451" alt="Screen Shot 2020-06-09 at 16 34 53" src="https://user-images.githubusercontent.com/2459423/84161178-48effa80-aa6f-11ea-9fd1-5b6c673c940f.png">

## Environment

 - PyTorch Version (e.g., 1.4): 
 - Ignite Version (e.g., 0.3.0):
 - OS (e.g., Linux):
 - How you installed Ignite (`conda`, `pip`, source):
 - Python version:
 - Any other relevant information:

**Comment by erip** [comment]
The expected behavior is the `Epoch [...]: [...]` line should be replaced on each epoch?

**Comment by sdesrozis** [comment]
Do you have the notebook ?

**Comment by sdesrozis** [comment]
It seems that if `pbar` doesn't reach `pbar_total` on notebook, the bar persists... Actually I don't know why.

**Comment by sdesrozis** [comment]
Found why here
https://github.com/tqdm/tqdm/blob/0cd9448b2bc08125e74538a2aea6af42ee1a7b6f/tqdm/notebook.py#L240-L250

```python
    def close(self, *args, **kwargs):
        super(tqdm_notebook, self).close(*args, **kwargs)
        # Try to detect if there was an error or KeyboardInterrupt
        # in manual mode: if n < total, things probably got wrong
        if self.total and self.n < self.total:
            self.sp(bar_style='danger')
        else:
            if self.leave:
                self.sp(bar_style='success')
            else:
                self.sp(close=True)
```

**Comment by vfdev-5** [comment]
@sdesrozis thanks for digging up the cause of the problem !
