### ISSUE TITLE
Ignite on multiple GPUs 

### ISSUE THREAD

**Issue by Ceceu** [pytorch/ignite#1118]
The [Ignite quickstart](https://pytorch.org/ignite/quickstart.html#code) is an exciting guide showing the essentials for define and training a simple model. But the examples provided which use multi GPU training do not seem to follow the same simplicity.

Would it be difficult to do something as shown in the code snippet below?
```pyton
trainer.run(train_loader, max_epochs=100, gpus=[0,1,2,3])
```
Is there a tutorial that shows how simple it would be to train a model in a multi GPU environment using Ignite?

**Comment by vfdev-5** [comment]
@Ceceu thanks for asking ! Currently, in stable v0.3.0 release we relies only on native torch distributed API. Example of that can be found [here](https://github.com/pytorch/ignite/blob/v0.3.0/examples/contrib/cifar10/main.py). User need to manually setup distributed proc group and execute the script with `torch.distributed.launch` tool. Or use `mp.spawn`...

However, we aim to simplify this by providing a helper API to work on GPUs, TPUs etc. 
The API is still experimental and will be available with v0.4.0 (probably released the next week). 

In [nightly version](https://github.com/pytorch/ignite#nightly-releases) we provide a part of the newer API `idist`: https://pytorch.org/ignite/distributed.html#ignite-distributed
- [spawn](https://pytorch.org/ignite/distributed.html#ignite.distributed.spawn)
- [initialize/finalize](https://pytorch.org/ignite/distributed.html#ignite.distributed.initialize)

For a complete example of newer API, please, checkout [the same cifar10 example in the branch `parallel_api`](https://github.com/pytorch/ignite/tree/ba8a6a19c47ff1bcb3318c1d1f8e5961a9489bd0/examples/contrib/cifar10).

HTH

**Comment by Ceceu** [comment]
@vfdev-5,
These are great news.
