### ISSUE TITLE
Improve usage of contrib common methods with other save handlers

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1123]
## 🚀 Feature

Currently, methods like `common.save_best_model_by_val_score` and `common.setup_common_training_handlers` work with local storage setup by `output_path`.

If we would like to use other save handlers than `DiskSaver`, it is almost impossible to use those helpers.

Idea is to be able user's setup of save handler for internal `Checkpoint` class. 
There can be several ways, I see, how to accomplish that:
- make `output_path` accept instances of `BaseSaveHandler`

```python
from ignite.contrib.engines import common

save_handler = TrainsSaver(dirname=output_path)

common.save_best_model_by_val_score(
        save_handler, evaluator, model=model, metric_name="accuracy", n_saved=3, trainer=trainer, tag="test"
)
```

- set module-wise default save handler as DiskSaver and allow user to replace it by another save hander:

```python
from ignite.contrib.engines import common

common.default_save_handler = TrainsSaver(dirname=output_path)

common.save_best_model_by_val_score(
        None, evaluator, model=model, metric_name="accuracy", n_saved=3, trainer=trainer, tag="test"
)
```

- add another argument `save_handler=None`

```python
save_handler = TrainsSaver(dirname=output_path)

common.save_best_model_by_val_score(
        None, evaluator, model=model, metric_name="accuracy", n_saved=3, trainer=trainer, tag="test", save_handler=save_handler
)
```

Any other ideas @sdesrozis @erip ?

**Comment by sdesrozis** [comment]
The first solution sounds good. We can keep `output_path` which create `DiskSaver` internally and add a new parameter `saver` (type `BaseSaveHandler`) mutually exclusive with `output_path`.

I really don't like others alternatives with `None` argument...

**Comment by vfdev-5** [comment]
If we add another argument we have set none to output_path, right ?

**Comment by sdesrozis** [comment]
> If we add another argument we have set none to output_path, right ?

Yes. I didn't catch arguments without default. It's a problem. And I suppose you are thinking about BC...

**Comment by vfdev-5** [comment]
Another idea is to introduce argument `output` and deprecate `output_path` and `output` can be str and `BaseSaveHandler`...
