### ISSUE TITLE
Auto dataloader - ValueError: batch_size should be a positive integer value, but got batch_size=0

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1130]
## 🐛 Bug description

The following code will brake if `batch_size` is smaller than world size :
```python
import torch
import ignite.distributed as idist

def foo(i):
    data = torch.arange(100).reshape(25, 4)
    data_loader = idist.auto_dataloader(data, batch_size=6, num_workers=12)


if __name__ == "__main__":
    idist.spawn("gloo", foo, args=(), nproc_per_node=8)    
```
```
ValueError: batch_size should be a positive integer value, but got batch_size=0
```

A fix can be:
- keep batch size as provided if smaller than world size
- same for `num_workers`

## Environment

 - PyTorch Version (e.g., 1.4): 1.5.0
 - Ignite Version (e.g., 0.3.0): master
 - OS (e.g., Linux): linux
 - How you installed Ignite (`conda`, `pip`, source):
 - Python version: 3.7
 - Any other relevant information:

@InCogNiTo124 would you like to fix this as you recently played around `auto_*` ?

**Comment by InCogNiTo124** [comment]
Sure, I will look into it sometime this week. Is there a deadline I should know of?

**Comment by vfdev-5** [comment]
@InCogNiTo124 thanks! I'd say sooner is better. Let's say to have it done before this friday. Anyway, no worries about if you haven't time for that. If it becomes urgent, we'll do it :)

**Comment by InCogNiTo124** [comment]
@vfdev-5 alright, I'll let you know if I can't fix it by then :)

**Comment by InCogNiTo124** [comment]
I think I know the source of the bug, the `world_size` in this example is `8`, but `batch_size` is `6`, so `ignite/distributed/auto.py:L68` makes it `0`.

**Comment by vfdev-5** [comment]
@InCogNiTo124 yes, you are correct about that: 6 // 8 = 0

> >   A fix cant be:
> @vfdev-5 I'm not sure if this is a typo or not

And yes, it is a typo .
