### ISSUE TITLE
Allow setting initial epoch in trainer.

### ISSUE THREAD

**Issue by veugene** [pytorch/ignite#116]
The initial epoch when training is assumed to always be 0; it would be useful for a user to be able to initialize this value when resuming training.

https://github.com/pytorch/ignite/blob/master/ignite/engines/trainer.py#L31

**Comment by alykhantejani** [comment]
I think a better solution for this would be to implement `engine.save` and `engine.load` so that you can resume from a engine checkpoint seamlessly. There is already a ticket for this #62 so closing in favor of that. Feel free to comment on this ticket if you think that wont solve the issue
