### ISSUE TITLE
PiecewiseLinear dict support

### ISSUE THREAD

**Issue by g-karthik** [pytorch/ignite#1162]
In ignite 0.2.1, `PiecewiseLinear` didn't expect the optimizer to be strictly a sub-class of `torch.optim.Optimizer` and allowed generic parameter group [dicts](https://github.com/pytorch/ignite/blob/v0.2.1/ignite/contrib/handlers/param_scheduler.py#L26) as well.

But it looks like in later versions, this generic support was withdrawn.

What's the context behind this change?

I had been successfully using `PiecewiseLinear` from ignite 0.2.1 along with Microsoft's DeepSpeed [ZeRO](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/pt/deepspeed_zero_optimizer.py#L91) optimizer, which isn't strictly a sub-class of `torch.optim.Optimizer` and Microsoft addressed the reasons for this in their repo. However, due to some useful features in later versions of ignite, we decided to upgrade to a newer version of ignite (0.3 and later also 0.4). In the process of this upgrade, we realized `PiecewiseLinear` no longer works with the ZeRO optimizer.

It would be great if support for generic parameter group dicts is added back.

**Comment by g-karthik** [comment]
@vfdev-5

**Comment by sdesrozis** [comment]
@g-karthik @vfdev-5 I think we should consider such optimizers ! Thank you for report this!

An alternative could be to introduce a wrapper in a similar way to LRScheduler. It could bind optimizer non native PyTorch. Maybe it could facilitate others kinds of optimizers not considered here. 

At the moment, the most pragmatic thing to do is what @vfdev-5 said 😉

**Comment by g-karthik** [comment]
@vfdev-5 @sdesrozis yes, I agree with the supplementary check approach for `param_groups`. Do you think you could add this small change and release this?

**Comment by g-karthik** [comment]
One more thing, even `OptimizerParamsHandler` expects a sub-class of `torch.optim.Optimizer` -- perhaps this check could be put in there too.

**Comment by vfdev-5** [comment]
@g-karthik thanks for the update ! Yes, this is our plan, we will delay the release until merging the PR closing this issue.

**Comment by vfdev-5** [comment]
@g-karthik PR is under testing and hopefully will be merged soon.

I was also wondering if in your use-cases using this DeepSpeed zero optimizer is that fast, works on large models as its docs says ?

**Comment by g-karthik** [comment]
@vfdev-5 cool, thanks! yep, the ZeRO optimizer is pretty cool and works reasonably well for larger models!

**Comment by vfdev-5** [comment]
@g-karthik I saw it sometime ago, however the API is a bit strange with required `args` and python argparser... Even constructing `DeepSpeedLight` is not obvious... 
If not speaking about large models, how would you compare it vs only nvidia/apex (which they use internally), any gains by deepspeed ?

**Comment by g-karthik** [comment]
@vfdev-5 I actually haven't used deepspeed for smaller models, but it is just using `torch.distributed` with NCCL backend under the hood. I haven't tried it for smaller models but there will be reduced memory footprint even with those, so you could train those smaller models with larger batch sizes and longer sequence lengths.

**Comment by vfdev-5** [comment]
@g-karthik I now take a look a bit closer on deep speed and seems like the evaluation in their code is done on a single device... as in training they use `model_engine`, but in evaluation it is still initially defined `model` is used. Is it correct and how are you doing with that ? Thanks !

**Comment by g-karthik** [comment]
@vfdev-5 yes, I am using `model_engine` during training and `model` for evaluation, that's correct. As for DDP, you can use the `dist_init_required` flag in `initialize()` for it.
