### ISSUE TITLE
idist initialize with nccl backend without GPU

### ISSUE THREAD

**Issue by sdesrozis** [pytorch/ignite#1165]
## 🐛 Bug description

Call `idist.initialize("nccl", ...)` without GPU (but pytorch providing `nccl`) raises an error 
```commandline
Floating point exception
```
Exception is thrown in barrier following `dist.initialize`.

Case `nccl` + no GPU should raise an explicit exception.

## Environment

 - PyTorch Version (e.g., 1.4): 1.5
 - Ignite Version (e.g., 0.3.0): 0.4
 - OS (e.g., Linux): Linux
 - How you installed Ignite (`conda`, `pip`, source): conda
 - Python version: 3.7
 - Any other relevant information:

**Comment by vfdev-5** [comment]
Similar code on pure pytorch
```python
> CUDA_VISIBLE_DEVICES="" python -m torch.distributed.launch --use_env --nproc_per_node=1 ddp-no-gpu.py 
import torch.distributed as dist

if __name__ == '__main__':
    dist.init_process_group("nccl", init_method="env://")
    dist.barrier()
```
just say 
```
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'ddp-no-gpu.py']' died with <Signals.SIGFPE: 8>.
```
