### ISSUE TITLE
Suddenly failing tests with a NotImplementedError

### ISSUE THREAD

**Issue by pseeth** [pytorch/ignite#1172]
## 🐛 Bug description

Getting a strange bug in recent commits to nussl with the latest ignite version. They look like this:

```
tests/separation/test_deep.py:62: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
nussl/ml/train/trainer.py:300: in add_stdout_handler
    pause=ValidationEvents.VALIDATION_COMPLETED
/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/ignite/handlers/timing.py:115: in attach
    engine.add_event_handler(pause, self.pause)
/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/ignite/engine/engine.py:269: in add_event_handler
    if event_name not in self._allowed_events:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Events.EPOCH_STARTED: 'epoch_started'>
other = <ValidationEvents.VALIDATION_COMPLETED: 'validation_completed'>

    def __eq__(self, other):
        if isinstance(other, CallableEventWithFilter):
            return self.name == other.name
        elif isinstance(other, str):
            return self.name == other
        else:
>           raise NotImplementedError
E           NotImplementedError

```

The full log is here:

https://github.com/nussl/nussl/runs/827399639

Did something in the Events API change? This worked in ignite 0.3 no problem.

Thanks!

**Comment by sdesrozis** [comment]
@pseeth Thank you for this report. We will have a look on that!!

**Comment by vfdev-5** [comment]
@pseeth the issue is about that all events and custom ones should inherit from `EventEnum`.
As `ValidationEvents` is an extension of `Enum`, that's why it fails, I think. @pseeth could you please check it ? 

We need to update Migration note and documentation to clearly state this in `Events` class description.

The only place where it is stated is https://pytorch.org/ignite/engine.html#ignite.engine.engine.Engine.register_events

**Comment by sdesrozis** [comment]
@pseeth 

Your custom events are defined inheriting `Enum`. For now, you have to inherit from `EventEnum`. 

Have a look here https://github.com/pytorch/ignite#custom-events-to-go-beyond-standard-events

HTH

**Comment by vfdev-5** [comment]
@sdesrozis you can be faster in doc fix :)

**Comment by sdesrozis** [comment]
I plan to update the doc this weekend 😉
