### ISSUE TITLE
Add integration with tensorboard?

### ISSUE THREAD

**Issue by alykhantejani** [pytorch/ignite#12]

**Comment by rooa** [comment]
+1 for this. I personally like [tensorboard-pytorch](https://github.com/lanpa/tensorboard-pytorch) very much, but I'm not sure about the policy regarding integration of an external module into ignite.

**Comment by alykhantejani** [comment]
Integration with Visdom was super easy as the API for visdom worked really well with the event handlers. See [the example with MNIST](https://github.com/pytorch/ignite/blob/master/examples/mnist_with_visdom.py) for details.

Ideally tensorboard would be as simple and we can just provide examples

**Comment by alykhantejani** [comment]
Closed as example of how to do this with tensorboard-pytorch has been merged in #60
