### ISSUE TITLE
Ignite + Ray Tune

### ISSUE THREAD

**Issue by VladimirIsakov91** [pytorch/ignite#1202]
Hello Team, I have recently started using the Ignite library for Deep Learning, and would like to thank you for creating such a high quality library.
I have a question which I ran into while playing around with the tutorials. Is there any way to integrate Ignite with the Ray Tune library? I would like to perform hyperparameter optimization for a model, but I keep running into serialization issues with Ray. 
Is there any example code? I do not paste my code, since it is trivial, and is mostly dummy classes and functions from the tutorials, but I've tried a lot of options and it just refuses to work, I would appreciate help if possible.
Thanks in advance.

**Comment by sdesrozis** [comment]
Hi @VladimirIsakov91 ! Thank you for your comments 😊

From my side, I don't use Ray but I think it should be a huge contribution to provide an example of how this lib could be used with ignite. We can support if you need and are interested to help on this! What do you think?

Maybe @vfdev-5 has more inputs about this.

**Comment by vfdev-5** [comment]
@VladimirIsakov91 I tried ray tune some time ago by porting cifar10 example, but I didn't pushed it into examples, I do not remember why. Anyway, I think it shouldn't be much more different from Optuna or Ax:
- https://github.com/optuna/optuna/blob/master/examples/pytorch_ignite_simple.py
- https://github.com/pytorch/ignite/blob/master/examples/notebooks/Cifar10_Ax_hyperparam_tuning.ipynb

As @sdesrozis said, yes, we can try to provide an example of using ignite and ray tune based on https://docs.ray.io/en/master/tune/tutorials/tune-pytorch-cifar.html and if you would like to help with.

**Comment by VladimirIsakov91** [comment]
Thanks for the links, I will look into them and see if I can come up with an example.
