### ISSUE TITLE
EpochMetric should be compatible with regression tasks.

### ISSUE THREAD

**Issue by Minys233** [pytorch/ignite#1209]
## 🚀 Feature

`EpochMetric` should be accept both `float32` output and target.

## Description
Currently, `EpochMetric` only accept `float32`  output and `long` target. This is good for classification tasks. However, for regression tasks, such as: Input_Data --> Network --> [Real_Target_1, Real_Target_2,...], EpochMetric does not work. (Note: here `metrics.MeanSquaredError` also does not fit the problem since there are multiple regression targets.)

In this case, the class is useless and the code will fail in `_check_shape()` function with message "Targets should be binary (0 or 1)." 

I think the original intention of this class is providing a simple way to wrap external metric functions. So it's more reasonable to make less shape check or type check on input data.

## Relevant code
https://github.com/pytorch/ignite/blob/68d3ba1baa70d16d7bc35771538a3213300177c4/ignite/metrics/epoch_metric.py#L61-L111

There are TOO many checks!

**Comment by vfdev-5** [comment]
@Minys233 thanks for the report ! 

> I think the original intention of this class is providing a simple way to wrap external metric functions. So it's more reasonable to make less shape check or type check on input data.

Yes, the last time I was checking the code of `EpochMetric`, I also thought that several conditions can be relaxed.

Concerning regression type of output, we have a bunch of regression metrics too (with a support of epoch-wise type of metrics) : 
- https://pytorch.org/ignite/contrib/metrics.html#module-ignite.contrib.metrics.regression
- https://github.com/pytorch/ignite/blob/master/ignite/contrib/metrics/regression/_base.py#L54


PS: if you would like to help us with improving `EpochMetric` class, we can discuss here on that and if you would like to send a PR, it would be awesome !

**Comment by vfdev-5** [comment]
Fixed by #1748
