### ISSUE TITLE
Docker for users

### ISSUE THREAD

**Issue by sdesrozis** [pytorch/ignite#1214]
## 🚀 Feature

Ignite should provide prebuilt docker images for users stored on dockerhub to handle different configurations.

Base should be latest PyTorch images, stable pip versioned ignite, maybe some recurrent tools like opencv, albumentations, etc.

Images could be
* ignite-examples (including all stuff to reproduce examples, meaning trains, albumentations, fire, py_config_runner, etc.)
* ignite + hovorod
* ignite + deepspeed

**Comment by vfdev-5** [comment]
I can provide some basic instruction on how to build `ignite + hovorod`. Mostly based on https://github.com/pytorch/ignite/blob/6488587a3be6d22b4de2dced48f177514207e71c/.circleci/config.yml#L233

**Comment by FrAnCOisCokELaER** [comment]
Hi! I'm a first-time contributor, I could give a try on this issue if it's ok for you.

**Comment by vfdev-5** [comment]
@FrAnCOisCokELaER yes, please, go ahead :)

**Comment by vfdev-5** [comment]
Close the issue as solved
