### ISSUE TITLE
Create a logo for Ignite

### ISSUE THREAD

**Issue by isabela-pf** [pytorch/ignite#1221]
### 🚀 Feature

@vfdev-5  asked me to work on a logo to represent Ignite and its relation to main PyTorch, so I’m opening this issue to post iterations and provide a place for discussion. 

All feedback is welcome! I'm looking forward to hearing the community's thoughts.

These first iterations use the same orange as PyTorch (`#ee4c2c`)and maintain similar line weight (and sometimes the small circle) in order to show a visual relationship between the projects. The potential directions for Ignite’s logomark are meant to highlight Ignite’s strengths of simplicity and speed as well as the kick starting nature of some of its “out-of-the-box” features.

### Option 1-1
Compared to the current PyTorch logo, Option 1 is meant to be more a energetic spark than a steady, symmetrical flame.
<img width="502" alt="1-1" src="https://user-images.githubusercontent.com/50221806/88605197-19e91480-d02e-11ea-9d97-5fc07286dc95.png">
<img width="502" alt="1-1color" src="https://user-images.githubusercontent.com/50221806/88605198-1a81ab00-d02e-11ea-8771-2f2713077df9.png">

### Option 2-1
Option 2 is the furthest from the current PyTorch logo and revolves around the idea of a matchstick. The flame shape is closest to the current PyTorch logo of the different options.
<img width="502" alt="2-1" src="https://user-images.githubusercontent.com/50221806/88605212-22d9e600-d02e-11ea-8678-eb0785fcd140.png">
<img width="502" alt="2-1color" src="https://user-images.githubusercontent.com/50221806/88605215-23727c80-d02e-11ea-89cf-b5ac451839ac.png">

### Option 3-1
Another idea around a spark originating from a single point. Different flame shape and direction.
<img width="502" alt="3-1" src="https://user-images.githubusercontent.com/50221806/88605221-2a998a80-d02e-11ea-85d0-8e9ac7b711c3.png">
<img width="502" alt="3-1color" src="https://user-images.githubusercontent.com/50221806/88605222-2a998a80-d02e-11ea-8372-87e1aa4eaca7.png">

### Option 4-1
This developed as a variation of Option 3. While it is my least favorite, I wanted to provide an option that feels sharper and more explosive.
<img width="502" alt="4-1" src="https://user-images.githubusercontent.com/50221806/88605232-2ff6d500-d02e-11ea-8078-e4d25c48d10b.png">
<img width="502" alt="4-1color" src="https://user-images.githubusercontent.com/50221806/88605234-308f6b80-d02e-11ea-99c9-8ba077afe688.png">

**Comment by isabela-pf** [comment]
I’ve also been experimenting with different type that has a little more character, but also aligns a little less with PyTorch’s current logo. Here it is mocked up next to each of the directions.
<img width="502" alt="varta1" src="https://user-images.githubusercontent.com/50221806/88605380-92e86c00-d02e-11ea-98dd-f5d176cb96c6.png">
<img width="502" alt="varta2" src="https://user-images.githubusercontent.com/50221806/88605381-94199900-d02e-11ea-88f3-ba2e5ed0dc65.png">
<img width="502" alt="varta3" src="https://user-images.githubusercontent.com/50221806/88605382-94199900-d02e-11ea-8ac0-fd097ece7450.png">
<img width="502" alt="varta4" src="https://user-images.githubusercontent.com/50221806/88605383-94199900-d02e-11ea-9478-799758509be7.png">

Additionally, just because it needs to match with PyTorch’s logo doesn’t mean we have to stick with the same orange. I think either a similar warm color or a contrasting blue could work if there’s interest in breaking from the orange. I’ve only mocked these up on one option, but I’d be willing to try them on other options if there is interest.

<img width="750" alt="colors" src="https://user-images.githubusercontent.com/50221806/88605401-a1cf1e80-d02e-11ea-9b38-c56cb646e629.png">

**Comment by sdesrozis** [comment]
@isabela-pf thank you very much for this amazing work 😊 

Personally I enjoy the option 4 😊 I think that moving from orange to another colour is a good idea. 

However, if it's a small task, could you try with another font? I'm not convinced but the "y" rendering.

Thank you again!!

**Comment by ericspod** [comment]
Looks good! My choice would be option 1 and definitely some other could be nice, maybe a thematic colour for different parts of the library.

**Comment by fco-dv** [comment]
All these proposals are great, my choices would go more towards design 1 and 4. Proposition 4 reminds me a little bit of the Apache Spark logo. A change of colour is a great idea to mark the differentiation.

**Comment by isabela-pf** [comment]
To try and make the options easier to track, I’m putting each direction in a separate comment. That way people can add reactions if they want (though comments are still greatly appreciated!) and it should feel like a more manageable post. 

While I cleaned each idea, the most noticeable change is the color experimentation and switching all type to [Varta](https://fonts.google.com/specimen/Varta?category=Sans+Serif&subset=latin&sort=alpha). Each option keeps an element of the original orange, but adds a color designed to compliment it. All options are shown with the same color set of combos.

### Option 1-2
The flame shape is modified spark resized. Overall, it is closest to 1-1.
Orange
<img width="502" alt="12orange" src="https://user-images.githubusercontent.com/50221806/89671554-08a6d000-d898-11ea-9e7b-ed684fbf7571.png">
<img width="502" alt="12orange2" src="https://user-images.githubusercontent.com/50221806/89671555-09d7fd00-d898-11ea-9ae4-9d6eb646b482.png">

Yellow
<img width="502" alt="12yellow" src="https://user-images.githubusercontent.com/50221806/89671581-14929200-d898-11ea-9a1b-39f60f6010ca.png">
<img width="502" alt="12yellow2" src="https://user-images.githubusercontent.com/50221806/89671585-152b2880-d898-11ea-8aaf-ca739576e881.png">

Violet
<img width="502" alt="12violet" src="https://user-images.githubusercontent.com/50221806/89671595-1b210980-d898-11ea-920a-037068ba76d3.png">
<img width="502" alt="12violet2" src="https://user-images.githubusercontent.com/50221806/89671598-1bb9a000-d898-11ea-85a0-eb4cdd76efdc.png">

Red
<img width="502" alt="12red" src="https://user-images.githubusercontent.com/50221806/89671613-21af8100-d898-11ea-8c1d-ad2ee214d627.png">
<img width="502" alt="12red2" src="https://user-images.githubusercontent.com/50221806/89671614-21af8100-d898-11ea-8832-0baa3ec90316.png">

**Comment by isabela-pf** [comment]
### Option 1-3
Also close to 1-1, this version has a slightly wider flame and has the spark moved to the base.  When I was experimenting, I thought this gave the logo a greater sense of upward motion.
Orange
<img width="502" alt="13orange" src="https://user-images.githubusercontent.com/50221806/89671677-44da3080-d898-11ea-88b1-9298d34840b5.png">
<img width="502" alt="13orange2" src="https://user-images.githubusercontent.com/50221806/89671678-4572c700-d898-11ea-856c-06b9c7318ac0.png">

Yellow
<img width="502" alt="13yellow" src="https://user-images.githubusercontent.com/50221806/89671696-4b68a800-d898-11ea-9b07-8c512f57da6b.png">
<img width="502" alt="13yellow2" src="https://user-images.githubusercontent.com/50221806/89671698-4c013e80-d898-11ea-9d91-96245dcae74a.png">

Violet
<img width="502" alt="13violet" src="https://user-images.githubusercontent.com/50221806/89671706-502d5c00-d898-11ea-9d8f-0856c5e10d6c.png">
<img width="502" alt="13violet2" src="https://user-images.githubusercontent.com/50221806/89671708-50c5f280-d898-11ea-8109-1799525ccbd6.png">

Red
<img width="502" alt="13red" src="https://user-images.githubusercontent.com/50221806/89671721-56233d00-d898-11ea-8792-2aaed613eabd.png">
<img width="502" alt="13red2" src="https://user-images.githubusercontent.com/50221806/89671724-56233d00-d898-11ea-9c32-a11ff0181f8b.png">

**Comment by isabela-pf** [comment]
### Option 4-2
This is the requested combination of 1-1 and 4-1. Interpreting the 4-1’s spikes to have the curved flame also meant cutting down the number of peaks. I also tried out a square spark to line up with the sharp ends of the flame. Out of all the options, I think this one has the greatest sense of motion. It also has the most details, which means it is just a little harder to read at small sizes than 1-2 and 1-3.
Orange
<img width="502" alt="42orange" src="https://user-images.githubusercontent.com/50221806/89671780-73580b80-d898-11ea-8b3c-ae35c8fb4a07.png">
<img width="502" alt="42orange2" src="https://user-images.githubusercontent.com/50221806/89671782-73f0a200-d898-11ea-96bb-51079bf90ef3.png">

Yellow
<img width="502" alt="42yellow" src="https://user-images.githubusercontent.com/50221806/89671805-78b55600-d898-11ea-8a9a-7ff08b3fcfb1.png">
<img width="502" alt="42yellow2" src="https://user-images.githubusercontent.com/50221806/89671807-794dec80-d898-11ea-838a-0eb2a54fee03.png">

Violet
<img width="502" alt="42violet" src="https://user-images.githubusercontent.com/50221806/89671822-7eab3700-d898-11ea-93e3-aa48d38b967a.png">
<img width="502" alt="42violet2" src="https://user-images.githubusercontent.com/50221806/89671826-7f43cd80-d898-11ea-8f75-d7bb14146b8f.png">

Red
<img width="502" alt="42red" src="https://user-images.githubusercontent.com/50221806/89671832-82d75480-d898-11ea-818f-445bd745193e.png">
<img width="502" alt="42red2" src="https://user-images.githubusercontent.com/50221806/89671833-82d75480-d898-11ea-9680-5be9d726fd8c.png">

**Comment by sdesrozis** [comment]
@isabela-pf 

It seems not so easy to find good colors for the logo. You provided a lot of color scheme's alternatives and I don't have a preference atm. But I really enjoyed the sharper option 4 :)

About logo composition, I think I prefer when the dot (or square) is in bottom left rather than in middle or right. I feel more flowing (in a sense) maybe related to reading from left to right.

**Comment by fco-dv** [comment]
Personally, my choice would go towards the 4-2 option and with the "first violet" color, awesome work!

**Comment by vfdev-5** [comment]
I was talking to @isabela-pf in a private discussion and proposed to explore the following direction. 

I was inspired of the option 1-2 and 4-2 and drawn quickly this :

![image](https://user-images.githubusercontent.com/2459423/90438996-1c8ed500-e0d5-11ea-9179-bb739de836a7.png)

In some sense, behind the form there is pytorch's droplet but I would like to keep 3 flames like in 4-2 (well 2 flames are just "silhouttes") instead of 2 as in 1-2 but keeping everything in the same layout as in 1-2...

@sdesrozis @fco-dv what do you guys think about ?

**Comment by sdesrozis** [comment]
It reminds me of a candle in a circular urn. Why isn't the circular shape closed? It's a nice idea.

**Comment by sdesrozis** [comment]
![image](https://user-images.githubusercontent.com/10013598/90440118-fbc77f00-e0d6-11ea-963f-b47fe55474d2.jpeg)

It inspires something like that as well. Maybe we should work on the circular shape.

**Comment by vfdev-5** [comment]
> It reminds me of a candle in a circular urn. Why isn't the circular shape closed? It's a nice idea.

I was thinking that there is an invisible match going up to the red circle. And as for side flames I didn't manage to draw nice second parts of them and left open...

**Comment by isabela-pf** [comment]
Blending the flame shapes we’ve been looking at ended up being more difficult than I anticipated, but I also think it’s a great idea so I was happy to experiment with it. Thanks for your patience!

It sounded like there was more interest in keeping the original PyTorch orange with the touch of a yellow, so I continued that here. I’m happy to try out other colors again as we continue to whittle the options for shape down.

This addition of 1-2’s shape and 4-2’s flame style makes up 5 (fitting, and not even planned!). 
All the 5s are very close to each other, so I’m pointing them out to make it easier for you all to choose what you like. 
There are three main areas to look at:
- Flames: Some have three flame peaks, others have two flame peaks and a curve similar to the pure PyTorch logo.
- Dot/Spark: The placement of the dot/spark can fit the upper right or the lower right in most cases.
- Line: Options either have one continuous line or multiple segmented lines making up the flames

Thanks for all the continual feedback! I look forward to hearing what you think about these.

### Option 5-1
Two flame peaks and curve, upper right dot, and continuous line.

<img width="502" alt="5-1" src="https://user-images.githubusercontent.com/50221806/91493351-0c60bd80-e86c-11ea-8e05-eb8f20247131.png">
<img width="502" alt="5-1color" src="https://user-images.githubusercontent.com/50221806/91493355-0cf95400-e86c-11ea-9fbd-81427b9daffa.png">

### Option 5-2
Two flame peaks and curve, lower right dot, and continuous line.

<img width="502" alt="5-2" src="https://user-images.githubusercontent.com/50221806/91493368-1387cb80-e86c-11ea-824e-408be0cf299e.png">
<img width="502" alt="5-2color" src="https://user-images.githubusercontent.com/50221806/91493370-14206200-e86c-11ea-9ea3-2011e2a2c288.png">

### Option 5-3
Three flame peaks, upper right dot, and segmented lines.

<img width="502" alt="5-3" src="https://user-images.githubusercontent.com/50221806/91493381-17b3e900-e86c-11ea-9734-d8a8b482b5b1.png">
<img width="502" alt="5-3color" src="https://user-images.githubusercontent.com/50221806/91493383-17b3e900-e86c-11ea-9632-d60101f1ce55.png">

### Option 5-4
Three flame peaks, lower right dot, segmented lines.

<img width="502" alt="5-4" src="https://user-images.githubusercontent.com/50221806/91493398-1da9ca00-e86c-11ea-8b1c-11b19ab514da.png">
<img width="502" alt="5-4color" src="https://user-images.githubusercontent.com/50221806/91493400-1e426080-e86c-11ea-8d67-c7d500ab2349.png">

**Comment by isabela-pf** [comment]
6 is different, but calls in more of pure PyTorch’s angles (just like 5 starts to) I think it also has a sense of looping together that reiterates the relationships between projects. Just throwing in a more geometric approach since that hasn’t been represented much in this process and it is a possible solution.

### Option 6-1

<img width="502" alt="6-1" src="https://user-images.githubusercontent.com/50221806/91493559-5d70b180-e86c-11ea-81cd-cba4c6ec2baf.png">
<img width="502" alt="6-1color" src="https://user-images.githubusercontent.com/50221806/91493562-5e094800-e86c-11ea-8380-bea0a5f040f4.png">

**Comment by vfdev-5** [comment]
@isabela-pf thanks a lot for your huge work on our logo ! I really appreciate all those ideas you put here with the description for each image. 

I like 5-2 and 5-4. I played with them mixing them up with some rescale and rotation. 

<img width="502" alt="logo1+2" src="https://user-images.githubusercontent.com/2459423/91496815-1b239080-e8bd-11ea-9d1c-8e664a413e26.png">

If we could remove this visible skew in the bottom (more symmetric) it would be perfect for me.  What do you think ?

**Comment by isabela-pf** [comment]
Hi @vfdev-5, that's actually one of the options I mocked up already when exploring the concept, so I had it ready to go. Here's it is:

### Option 5-5
Three flame peaks, lower right dot, continuous line.

<img width="502" alt="5-5" src="https://user-images.githubusercontent.com/50221806/91500450-6798ad00-e878-11ea-95ef-328c01146c1c.png">
<img width="502" alt="5-5color" src="https://user-images.githubusercontent.com/50221806/91500452-68314380-e878-11ea-8ed6-330cb93249c7.png">

**Comment by vfdev-5** [comment]
@isabela-pf that's great ! Is it possible to turn it such that yellow point and central flame were more vertically aligned and make it less wide and more subtle ?

**Comment by sdesrozis** [comment]
@isabela-pf I really enjoy your last works!!

To me, the 5.2 is good. I don't know how to express it correctly but I think shapes should be as more as possible arcs of circles. I feel that it's ok for right part of external shape but not for left (near "flame").

Btw, it's very nice, bravo !!

**Comment by isabela-pf** [comment]
Since this round was focused on polishing, changes might be more difficult to spot. Once again, I’ve listed them here to help:
- **Type:** The font is changed from [Varta](https://fonts.google.com/specimen/Varta?category=Sans+Serif&subset=latin&sort=alpha) to [Oxygen](https://fonts.google.com/specimen/Oxygen). This brings back the single-story g with a typeface that has a little more geometry overall. (Side note: I am amused by the idea that a flame logo might be accompanied by a font named Oxygen.)
- **Color:** Orange remains the same `#ee4c2c` and the yellow has been slightly lightened to be `#eaa700` for greater contrast.
- **Flame shape:** Adjusted shape and proportions. 5-6 has very minor changes in shape while 5-7 demonstrates the narrower proportions @vfomin suggested. I keep changing my mind on which direction I like better, so it’d be great to hear what people think. (React with :heart: for 5-6 and :rocket: for 5-7, maybe?)

I think we're getting close to a decision, so let me know if there's a specific way we want to make the final choice (is is a vote, is it a specific group's choice, etc.).

### 5-6

<img width="502" alt="5-6orange" src="https://user-images.githubusercontent.com/50221806/93248847-46bfcb00-f745-11ea-894c-898c9d463545.png">
<img width="502" alt="5-6white" src="https://user-images.githubusercontent.com/50221806/93248852-47f0f800-f745-11ea-8ee1-a585a432ee99.png">
<img width="1104" alt="5-6favicon" src="https://user-images.githubusercontent.com/50221806/93248894-58a16e00-f745-11ea-8061-0b91f851f558.png">

### 5-7

<img width="502" alt="5-7white" src="https://user-images.githubusercontent.com/50221806/93248907-5e974f00-f745-11ea-990b-c87acf065419.png">
<img width="502" alt="5-7orange" src="https://user-images.githubusercontent.com/50221806/93248918-62c36c80-f745-11ea-99c1-42dd0e94d738.png">
<img width="1104" alt="5-7favicon" src="https://user-images.githubusercontent.com/50221806/93248979-77a00000-f745-11ea-8632-281226b8e26a.png">

### Curious about how the transition between shapes?

This section is for you! All 5's started with a three by three grid like this:
<img width="394" alt="grid-square" src="https://user-images.githubusercontent.com/50221806/93249161-b930ab00-f745-11ea-87c5-e92d941c4006.png">

So to work with the "slim" idea, I shifted to a roughly two by three grid: 
<img width="440" alt="grid-narrow" src="https://user-images.githubusercontent.com/50221806/93249218-d2395c00-f745-11ea-9694-52bc546abff6.png">

This seems to be the smallest I can go and still manage to have three smooth peaks to the flames. While it might not be as narrow as expected, I think this grid still feels more vertical in a way that 5-5 does not. Switching to this grid also meant switching from a circle base for the flames (more like the main PyTorch logo) to an oval and greatly changed how the curves needed to flow.

**Comment by isabela-pf** [comment]
I’m following up with a polished version of 5-7 based on comments from @vfdev-5 . Thanks to all the lovely feedback on this issue, I think this logo is refined and ready to be wrapped up. Is there any final approval it needs to go through? 

<img width="502" alt="5-10orange" src="https://user-images.githubusercontent.com/50221806/94309632-3a99f180-ff2d-11ea-8bff-a4ed14a1b1e2.png">
<img width="502" alt="5-10white" src="https://user-images.githubusercontent.com/50221806/94309638-3bcb1e80-ff2d-11ea-8aed-c57a534003b6.png">

It’d also be helpful to know where it makes sense to keep the final logo and related pieces. Should this be a PR or does it belong elsewhere?

**Comment by ydcjeff** [comment]
Shall we further do favicon for documentation as well?

**Comment by vfdev-5** [comment]
@ydcjeff good idea ! Could you, please, open an issue for that ?
