### ISSUE TITLE
TensorboardLogger: TypeError: __init__() got an unexpected keyword argument 'another_engine'

### ISSUE THREAD

**Issue by VikasRajashekar** [pytorch/ignite#1223]
Here is my sample code:

```
from ignite.contrib.handlers.tensorboard_logger import TensorboardLogger
tb_logger = TensorboardLogger(log_dir)
 tb_logger.attach(evaluator, log_handler=OutputHandler(tag="validation", metric_names=list(metrics.keys()), another_engine=trainer), event_name=Events.EPOCH_COMPLETED)
```

But seems like There is no "another_engine".

I set up my environment using req.txt from conda:

```
torch
pytorch-ignite
transformers==2.5.1
tensorboardX==1.8
tensorflow  # for tensorboardX 
```

Was keyword another_engine removed?

**Comment by vfdev-5** [comment]
yes, it was deprecated since 0.3.0 and removed since 0.4.0. Please, use
global step transform :

https://pytorch.org/ignite/contrib/handlers.html#ignite.contrib.handlers.tensorboard_logger.TensorboardLogger

**Comment by VikasRajashekar** [comment]
@vfdev-5 thanks for the info. Just in case if I wish to use 0.3.0 of ignite. Which version of PyTorch is compatible? Is there a table  of compatibility for the Pytorch version and ignite version.

**Comment by vfdev-5** [comment]
Ignite 0.3.0 can run with pytorch >= 1.0 I think.
There is a sort of compatibility table here :

https://github.com/pytorch/ignite/actions/runs/186425963

But it is for 0.4.0 and master...
Unfortunately, there is no table with pytorch / ignite compatibility
versions.

**Comment by vfdev-5** [comment]
@VikasRajashekar can we close this issue or you need more support on that ?

**Comment by vfdev-5** [comment]
@VikasRajashekar I close the issue, if needed please reopen.
