### ISSUE TITLE
Setup Github Actions workflow CI for horovod on CPU

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1236]
## 🚀 Feature

Idea is to add run Horovod tests on CPU via Github Actions. We can either: 1) install horovod using pip or 2) otherwise compile horovod from source as it is [done for Circle CI](https://github.com/pytorch/ignite/blob/master/.circleci/config.yml#L229) (without NCCL support). The goal is to be able to run CPU distributed tests with Horovod backend.

TODO:
- create new file `hvd-tests.yml` in `.github/workflows` like https://github.com/pytorch/ignite/blob/master/.github/workflows/tpu-tests.yml
- setup horovod (described above)
- run horovod tests like in [circle ci yaml](https://github.com/pytorch/ignite/blob/master/.circleci/config.yml#L241)

Quick play around github actions can be done in a separate repository like https://github.com/vfdev-5/github-actions-playground

**Comment by ramesht007** [comment]
hey, @vfdev-5 Can I work on this issue

**Comment by vfdev-5** [comment]
Hey @ramesht007, sure, go ahead !
Thanks !

**Comment by sdesrozis** [comment]
@ramesht007 any update on this issue ?

**Comment by ramesht007** [comment]
hey @sdesrozis , I am working on this. will give a PR in few days. 🙂

**Comment by vfdev-5** [comment]
@ramesht007 how's your PR is going ?

**Comment by ramesht007** [comment]
Hi @vfdev-5 , I have started working on this (please have a look into [this](https://github.com/ramesht007/ignite/blob/hvd-tests/.github/workflows/hvd-tests.yml)). I have some queries reagrding same. 

Our goal is to run distributed tests for CPU, and the tests reffered to are in circleCI which use docker. So i have to use docker for the same?

sorry, for the silly question.

**Comment by vfdev-5** [comment]
> Our goal is to run distributed tests for CPU, and the tests reffered to are in circleCI which use docker. So i have to use docker for the same?

@ramesht007 in circle ci we use docker env to easily have pytorch distribution without installing conda etc as in github actions. For github actions, let's follow the same setup as https://github.com/pytorch/ignite/blob/master/.github/workflows/unittests.yml#L29 , Setup Miniconda and Install dependencies steps. Let's use python 3.7 and the latest pytorch version.
