### ISSUE TITLE
Remove useless prints from tests

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1240]
## 🚀 Feature

Some tests contain `print`s that probably were used for debugging and were not removed. It is better to remove them.

For example, 
https://github.com/pytorch/ignite/blob/44c60564bf59a3028ab89091cbd3d73def8be86f/tests/ignite/contrib/engines/test_common.py#L71

https://github.com/pytorch/ignite/blob/44c60564bf59a3028ab89091cbd3d73def8be86f/tests/ignite/contrib/engines/test_common.py#L244

https://github.com/pytorch/ignite/blob/44c60564bf59a3028ab89091cbd3d73def8be86f/tests/ignite/contrib/handlers/test_param_scheduler.py#L631

etc

**Comment by Yogendra0Sharma** [comment]
@vfdev-5 I am working on this.

**Comment by vfdev-5** [comment]
Thanks @Yogendra0Sharma ! Feel free to send a draft PR to iterate over if you wish

**Comment by sdesrozis** [comment]
@Yogendra0Sharma  Thank you!

One more 

https://github.com/pytorch/ignite/blob/ddb1eab80efb5404e9887a1ce31d21d6b2fd3957/tests/ignite/metrics/test_metric.py#L784

and maybe 

https://github.com/pytorch/ignite/blob/ef5fbd6cdd467f41428e1711e6817a8ecc538b74/tests/ignite/distributed/utils/test_serial.py#L12

https://github.com/pytorch/ignite/blob/00ef5710b10191f412d33b32baa1e01148b985ff/tests/ignite/engine/test_deterministic.py#L182

What do you think ?

**Comment by vfdev-5** [comment]
This issue is still open as previous draft PR could not be finalized by the author.
