### ISSUE TITLE
Backwards compability for torch.save in ModelCheckpoint

### ISSUE THREAD

**Issue by kilsenp** [pytorch/ignite#1244]
## 🚀 Feature

Pytorch made some changes to torch.save (https://pytorch.org/docs/stable/generated/torch.save.html)

> The 1.6 release of PyTorch switched torch.save to use a new zipfile-based file format. torch.load still retains the ability to load files in the old format. If for any reason you want torch.save to use the old format, pass the kwarg _use_new_zipfile_serialization=False.

It would be useful to have control over this flag when instantiating ModelCheckpoint.

Possible ways that I can think of:
- Have some *args, **kwargs passed on to the save function
- Be able to pass the save function itself to ModelCheckpoints

**Comment by vfdev-5** [comment]
@kilsenp thanks for the suggestion ! 

Maybe, passing args/kwargs would make sense. We also have `Checkpoint` class where user can specify how to save checkpoints. For example, for local storage we can use `DiskSaver` which calls `torch.save`. Forwarding `args/kwargs` to `DiskSaver` can be possible...
