### ISSUE TITLE
CycleGAN notebook is broken with updated ParamGroupScheduler

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1249]
https://github.com/pytorch/ignite/blob/c2c4a368a8666070633242c478c3b4151a05d49d/ignite/contrib/handlers/param_scheduler.py#L960

@sdesrozis above code brakes our cycle gan notebook where we do
```python
gen_lr_scheduler = PiecewiseLinear(optimizer_D, param_name='lr', milestones_values=milestones_values)
desc_lr_scheduler = PiecewiseLinear(optimizer_G, param_name='lr', milestones_values=milestones_values)

lr_scheduler = ParamGroupScheduler([gen_lr_scheduler, desc_lr_scheduler], 
                                   names=['gen_lr_scheduler', 'desc_lr_scheduler'])
```

Can we simply remove that check ?

**Comment by sdesrozis** [comment]
Ok, I didn't add this usecase in mind.

It need more fixes than simply remove the test
https://github.com/pytorch/ignite/blob/c2c4a368a8666070633242c478c3b4151a05d49d/ignite/contrib/handlers/param_scheduler.py#L1047

**Comment by vfdev-5** [comment]
Thanks @sdesrozis !
