### ISSUE TITLE
R2score calculation

### ISSUE THREAD

**Issue by fco-dv** [pytorch/ignite#1253]
## ❓ Questions/Help/Support

The R2score [implementation](https://pytorch.org/ignite/_modules/ignite/contrib/metrics/regression/r2_score.html#R2Score) seems to not agree with the doc (which is ok with  [wikipedia](https://en.wikipedia.org/wiki/Coefficient_of_determination)
 
Actual code is:
```python
return 1 - self._sum_of_errors / (self._y_sq_sum - (self._y_sum ** 2) / self._num_examples)
```
Shouldn't it be: ?
```python
return 1 - self._sum_of_errors / torch.sum( torch.pow(  y - torch.mean(y), 2 ) ).item() 
```

**Comment by vfdev-5** [comment]
@fco-dv this is a online convenient way to compute variable's variation:
```
sum_i[ (y_i - sum_j (y_j) ) ^ 2 ] = sum_i[ y_i ^ 2 - 2 * [sum_j (y_j) ]^2 +  [sum_j (y_j) ]^2 ] = sum_i[ y_i ^ 2 ] -  [sum_j (y_j) ]^2
```
What do you think ?

**Comment by fco-dv** [comment]
ah yes my mistake !
