### ISSUE TITLE
Improve docs for common.setup_common_training_handlers

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1256]
## 🚀 Feature

Idea is to fix rendering (see below) and add an example of usage and a link where [it is used](https://github.com/pytorch/ignite/blob/c6673710fcd78949e0bf203ed9155e82ef639061/examples/contrib/cifar10/main.py#L322).

<img width="715" alt="Screen Shot 2020-08-29 at 22 56 07" src="https://user-images.githubusercontent.com/2459423/91645982-db8aaf00-ea4a-11ea-96d2-e284819cb767.png">

What is wrong: gray frame with red vertical line should be absent for the text "Helper method to setup trainer with common handlers "

https://pytorch.org/ignite/contrib/engines.html#ignite.contrib.engines.common.setup_common_training_handlers

Same for other methods:
- common.setup_common_distrib_training_handlers
- common.setup_*_logging

For Hacktoberfest contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at [CONTRIBUTING guide](https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md).

**Comment by rexdivakar** [comment]
Assign it to me I shall work on it.

**Comment by vfdev-5** [comment]
@rexdivakar sure

**Comment by vfdev-5** [comment]
@rexdivakar any updates on this ?

**Comment by rexdivakar** [comment]
Working on this will raise a PR soon

**Comment by vfdev-5** [comment]
@rexdivakar sounds good. It would be nice to have the PR on tuesday. As you have 3 issues assigned we'd like to have some activity on these issues without blocking other users who'd like to help out.

**Comment by rexdivakar** [comment]
oh k will do it soon @vfdev-5

**Comment by vfdev-5** [comment]
@rexdivakar could you please send a PR for this issue within 2 days, otherwise unfortunately I'll have to unassign you.

**Comment by BanzaiTokyo** [comment]
I’d like to look into this

**Comment by BanzaiTokyo** [comment]
@vfdev-5 should the gray frame with red vertical line be present for "Parameters" title?

**Comment by vfdev-5** [comment]
@BanzaiTokyo yes, this is OK, see the docs for other correctly rendered methods, e.g. https://pytorch.org/ignite/contrib/engines.html#ignite.contrib.engines.tbptt.create_supervised_tbptt_trainer
