### ISSUE TITLE
 ImportError: cannot import name 'Checkpoint'

### ISSUE THREAD

**Issue by NEUdeep** [pytorch/ignite#1262]
## 🐛 Bug description

>>> from ignite.engine import Engine
>>> from ignite.handlers import Checkpoint, DiskSaver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Checkpoint'

## Environment

 - PyTorch Version (e.g., 1.4):1.4
 - Ignite Version (e.g., 0.2.1):0.2.1
 - OS (e.g., Linux):linux
 - How you installed Ignite (`conda`, `pip`, source):pip
 - Python version:3.6.9
 - Any other relevant information:

**Comment by vfdev-5** [comment]
@NEUdeep in 0.2.1 there were no `Checkpoint`, it was introduced in since `0.3.0`. Can you upgrade the version of ignite ?

**Comment by vfdev-5** [comment]
Let me close the issue as answered. Feel free to reopen if needed.
