### ISSUE TITLE
Recheck and udpate link in docstring to pytorch classes

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1264]
## 🚀 Feature

PyTorch's new documentation changed the links to the classes and for example previously correct link : 
- https://pytorch.org/docs/stable/nn.html#torch.nn.parallel.DistributedDataParallel
becomes now
- https://pytorch.org/docs/stable/generated/torch.nn.parallel.DistributedDataParallel.html

This issue is about to recheck all our docstring links to `https://pytorch.org/docs` and update them accordingly.

See [this guidelines](https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md#local-documentation-building-and-deploying) on how to generate the docs locally.

For Hacktoberfest contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at [CONTRIBUTING guide](https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md).

**Comment by kamahori** [comment]
Hi can I work on this issue?

**Comment by vfdev-5** [comment]
Hi @kamahori sure, go ahead ! 

I can assign it to you and you can start working on that.

PS: Notes for Hacktoferfest

> September is Preptember – a full month for maintainers to groom your repositories and **for contributors to learn about making quality pull requests.**

> Contributions during September don't count toward Hacktoberfest. Only pull requests submitted between October 1st to 31st will count.
