### ISSUE TITLE
Will my PR is considered if I submit it before October?

### ISSUE THREAD

**Issue by UjwalKandi** [pytorch/ignite#1267]
This is my first time participating in Hacktoberfest. If I submit a PR before the event starts (i.e. Oct 1st), will it be considered as one of the four pull requests?

**Comment by vfdev-5** [comment]
@UjwalKandi thanks for the question, according to the organizers:

> Contributions during September don't count toward Hacktoberfest. Only pull requests submitted between October 1st to 31st will count.

https://discord.com/channels/720788516837261322/735506302784110652/750804457473966191

**Comment by vfdev-5** [comment]
However, starting contributing in September can help you to understand better the project and give you more chances to have your PR accepted.

**Comment by UjwalKandi** [comment]
Thank you for clarifying @vfdev-5
