### ISSUE TITLE
Improve CI configuration

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1269]
## 🚀 Feature

For github acitons we can set a tag to trigger workflow run depending on modified files:
- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths
- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-paths

Idea is to add those tags to our github CI yaml such that we do not trigger the workflow if, for example, `*.md` is modified etc.

Nice to have : 
- find a similar feature for circle-ci and travis ci if any
- add to the corresponding configuration file.

For Hacktoberfest contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at [CONTRIBUTING guide](https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md).

**Comment by rexdivakar** [comment]
I would love to work on it @vfdev-5

**Comment by sdesrozis** [comment]
@rexdivakar  Thank you for your help !!

**Comment by vfdev-5** [comment]
Hi @rexdivakar I wonder if you plan to work on this issue soon ? This is something we'd like to have quick :) Thanks

**Comment by rexdivakar** [comment]
I'm working on it will raise the PR soon @sdesrozis

**Comment by vfdev-5** [comment]
@rexdivakar it would be nice to have the PR on tuesday. Thanks !

**Comment by rexdivakar** [comment]
PR has been raised appologies for the delay i had to do testing to confirm my changes 
Please validate it and approve my PR @vfdev-5 

https://github.com/pytorch/ignite/pull/1367
