### ISSUE TITLE
Preview of built docs in the PR

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1270]
## 🚀 Feature

Idea is to be able to preview built docs on the CI to simplify PR review.
This issue may be a bit tricky to solve, here some guidelines:
- we build our docs with travis ci : https://github.com/pytorch/ignite/blob/master/.travis.yml#L62
- find out how we could keep built docs as artifacts and make them accessible after the build
- update .travis.yml for that
- update https://github.com/pytorch/ignite/blob/master/.github/PULL_REQUEST_TEMPLATE.md with some details on how to fetch the link of built docs.

For Hacktoberfest contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at [CONTRIBUTING guide](https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md).

**Comment by sroy8091** [comment]
@vfdev-5 currently are we using github pages for deploying docs?

**Comment by vfdev-5** [comment]
@sroy8091 yes, docs are built and deployed as a Travis CI job on master push: https://github.com/pytorch/ignite/blob/master/.travis.yml#L62

**Comment by sroy8091** [comment]
We can upload the artifact on build success to s3, including the build number as s3 bucket path. Next step would be to include that link in the pr.

**Comment by sroy8091** [comment]
Any better approach @vfdev-5

**Comment by vfdev-5** [comment]
@sroy8091 I'm eager to do it with netlify like here : https://github.com/beeware/beeware.github.io/pull/426
Let me check it first and conifgure it on netlify side. You can then provide additional info...

**Comment by vfdev-5** [comment]
Here is netlify configured: 
- a test PR : https://github.com/pytorch/ignite/pull/1348
and docs preview for the PR : https://deploy-preview-1348--pytorch-ignite-preview.netlify.app/

Currently, it builds the docs as described in CONTRIBUTING and not as in travis (maybe OK).
What remains is to do:
- add condition to travis yaml to run Docs stage on master only
- update CONTRIBUTING guide saying that there "netlify/pytorch-ignite-preview/deploy-preview" check available to visualize the docs.

**Comment by sroy8091** [comment]
awesome. will push the travis changes

**Comment by vfdev-5** [comment]
Close this as done
