### ISSUE TITLE
Rename Epoch to Iterations when using epoch_length with max_epochs=1

### ISSUE THREAD

**Issue by g-karthik** [pytorch/ignite#1276]
## 🚀 Feature

Per the discussion in https://github.com/pytorch/ignite/issues/1263, we'd like to ensure that the progress bar uses the name "Iterations" instead of "Epoch" when the `epoch_length` is passed to the trainer for `max_epochs=1`.

**Comment by M3L6H** [comment]
I'm looking to get into open source, and managed to get a working development build of ignite on my system. This looks like a good issue to start on. If nobody is currently working on it, I would like to give it a shot. 

An initial look through the source code seems to have the word "Epoch" located in a number of places throughout the code. Particularly in `mnist_with_tqdm_logger.py`, `handlers.py`, `dcgan.py`, `mnist_save_resume_engine.py`, `mnist_with_tensorboard_on_tpu.py`, `mnist_with_tensorboard.py`, `mnist_with_visdom.py`, `mnist.py`, `tqdm_logger.py`, `engine.py`, `events.py`, and in the test files `test_common.py` and `test_tqdm_logger.py`.

If these instances of "Epoch" do in fact need to change to "Iterations", I'm thinking that some kind of flag should be set on the initial run of the trainer when we detect that `epoch_length` is passed with `max_epochs=1`.

If this solution seems reasonable, I would appreciate guidance on where command-line arguments are passed in, as well as whether there is an already established way for passing this kind of "global information" throughout the rest of the code.

**Comment by vfdev-5** [comment]
@M3L6H thanks for proposing to work on this issue !
Here idea is to tweak this part of the code : 
https://github.com/pytorch/ignite/blob/2778893db943e9869c2ce266c740c1310bc3b9de/ignite/contrib/handlers/tqdm_logger.py#L253
By default, if no "desc" is provided, it is set as "Epoch" and tqdm description uses that here : 
https://github.com/pytorch/ignite/blob/2778893db943e9869c2ce266c740c1310bc3b9de/ignite/contrib/handlers/tqdm_logger.py#L57

We can check engine's information before setting 
```python
default_desc = "Epoch" if ...
desc = self.tqdm_kwargs.get("desc", default_desc)
```
In other places, where you see "Epoch" is hard-coded, I think it is OK for those cases.

To make sure that everything is OK and in a good format, please take a look at [CONTRIBUTING](https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md) for details about code formatting and unit tests to add.

And feel free to ask here if you need more guidance.

**Comment by M3L6H** [comment]
@vfdev-5 thanks for the reply!

I've started work on the fix. Currently my solution looks like the following
```python
state_dict = engine.state_dict()
max_epochs = state_dict["max_epochs"] if "max_epochs" in state_dict else None

default_desc = "Iterations" if max_epochs and max_epochs == 1 else "Epoch"
desc = self.tqdm_kwargs.get("desc", default_desc)
```

I have also written a test
```python
def test_pbar_with_max_epochs_set_to_one(capsys):
    n_epochs = 1
    loader = [1, 2]
    engine = Engine(update_fn)

    pbar = ProgressBar()
    pbar.attach(engine, ["a"])

    engine.run(loader, max_epochs=n_epochs)

    captured = capsys.readouterr()
    err = captured.err.split("\r")
    err = list(map(lambda x: x.strip(), err))
    err = list(filter(None, err))
    expected = "Iterations [1/1]: [1/2]  50%|█████     , a=1 [00:00<00:00]"
    assert err[-1] == expected
```

However, when running the test, it fails, with the following output
```python
capsys = <_pytest.capture.CaptureFixture object at 0x7f540d32b9e8>

    def test_pbar_with_max_epochs_set_to_one(capsys):
        n_epochs = 1
        loader = [1, 2]
        engine = Engine(update_fn)
    
        pbar = ProgressBar()
        pbar.attach(engine, ["a"])
    
        engine.run(loader, max_epochs=n_epochs)
    
        captured = capsys.readouterr()
        err = captured.err.split("\r")
        err = list(map(lambda x: x.strip(), err))
        err = list(filter(None, err))
        expected = "Iterations [1/1]: [1/2]  50%|█████     , a=1 [00:00<00:00]"
>       assert err[-1] == expected
E       AssertionError: assert 'Epoch: [1/2]  50%|█████     , a=1 [00:00<00:00]' == 'Iterations [1/1]: [1/2]  50%|█████     , a=1 [00:00<00:00]'
E         - Iterations [1/1]: [1/2]  50%|█████     , a=1 [00:00<00:00]
E         ? ^^^^^^^ ^^^^^^^^
E         + Epoch: [1/2]  50%|█████     , a=1 [00:00<00:00]
E         ? ^^ ^^
```

From what I can see, it looks like the code just isn't working. However, I'm not sure if it is an issue with how I am trying to access max_epochs, (maybe using `state_dict` is not correct?), or whether it is an issue with one of the hard coded "Epochs" in code? My other concern is that maybe I wrote the test incorrectly, since in the output it is saying "Epoch: [1/2]", which I would imagine should be "Epoch: [1/1]" if the `max_epochs` was correctly set?

**Comment by vfdev-5** [comment]
@M3L6H 👍 for working on the issue 

I think you are right, my bad, we can not fetch correctly `max_epochs` at this step. Let me explain that with the example of how would we use the progress bar : 
```python
engine = Engine(update_fn)
# engine.state.max_epochs is None

pbar = ProgressBar()
pbar.attach(engine, ["a"])
# but engine.state.max_epochs is still None

# only here it will be set up as n_epochs    
engine.run(loader, max_epochs=n_epochs)
```

Well, we have to do it differently, I think. For example, let's set `desc` as None by default:
```python
desc = self.tqdm_kwargs.get("desc", None)
```
and when it is used with tqdm bar, provided engine is fully set up, thus we can set desc if `self.tag is None` by either "Epoch" or "Iteration" : 
https://github.com/pytorch/ignite/blob/2778893db943e9869c2ce266c740c1310bc3b9de/ignite/contrib/handlers/tqdm_logger.py#L52


Btw, please open a draft PR and we can iterate over the modifications to get it right.
