### ISSUE TITLE
Ensure that all core and contrib metrics can work in DDP

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1284]
## 🚀 Feature

Tracking issue. All core metrics are working in DDP, except special case #1283.
The idea is to check all core and contrib metrics if work in DDP and open new issues if we need to work on some metric.

**Comment by vfdev-5** [comment]
Remaining metrics:
- [ ] https://github.com/pytorch/ignite/blob/master/ignite/contrib/metrics/regression/mean_error.py
- [ ] https://github.com/pytorch/ignite/blob/master/ignite/contrib/metrics/regression/geometric_mean_relative_absolute_error.py

**Comment by sayantan1410** [comment]
@vfdev-5 Hey, just a small question, to make precision_recall_curve.py work in DDP,  to write the metric from scratch instead of using the one from sci-kit learn ? Or there is some other way of doing it ?
