### ISSUE TITLE
Include PyTorch v1.5.x to pytorch-version-tests.yml

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1286]
## 🚀 Feature

Idea is to add pytorch v1.5.x version to [pytorch-version-tests.yml](https://github.com/pytorch/ignite/blob/master/.github/workflows/pytorch-version-tests.yml). Please ensure which python version are supported by this pytorch version.

For Hacktoberfest contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at [CONTRIBUTING guide](https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md).

**Comment by benji011** [comment]
Hi @vfdev-5 

I checked from [the docs](https://pytorch.org/blog/pytorch-1-dot-5-released-with-new-and-updated-apis/) that python `3.5-8` are supported with PyTorch `1.5`
Is it ok for me to do these changes from October 1st?

**Comment by vfdev-5** [comment]
Hi @benji011 , yes, this issue is rather trivial. I was thinking to add only 1.5.1 . 

> Is it ok for me to do these changes from October 1st?

Well, yes, it is possible

**Comment by vfdev-5** [comment]
Seems like this issue is already fixed by https://github.com/pytorch/ignite/pull/1325
I close the issue. @benji011 feel free to pick other HF issues if interested to help the project. Thanks !
