### ISSUE TITLE
Set tqdm version in CI as <=4.48.0

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1287]
## 🐛 Bug description

Currently, the CI is broken due to recent changes of tqdm v4.49.0 :
- https://travis-ci.org/github/pytorch/ignite/jobs/726808846#L4137

Idea is to fix tqdm's version to v4.48.0 for all CI here: 
- https://github.com/pytorch/ignite/blob/master/requirements-dev.txt#L9

For Hacktoberfest contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at CONTRIBUTING guide.

**Comment by benji011** [comment]
@vfdev-5 Hi, I'd like to give this a try for my first Hacktoberfest issue. Can you assign this to me and I will give it ago

**Comment by vfdev-5** [comment]
@benji011 sure, thanks !

**Comment by vfdev-5** [comment]
@benji011 could you please send a PR in coming days (monday, tuesday) as fixing CI is important ? 
If you need any guidelines or you have any questions, please ask.

**Comment by benji011** [comment]
@vfdev-5 I thought this was a Hacktoberfest issue, Is it still ok to submit before October 1st?

**Comment by vfdev-5** [comment]
@benji011 well, it is a HF issue. As organizers are stated in their docs:

> September is Preptember – a full month for maintainers to groom your repositories and for contributors to learn about making quality pull requests.

So, yes, it is OK to submit before October 1st to "learn about making quality pull requests"
