### ISSUE TITLE
How is this different from torchnet?

### ISSUE THREAD

**Issue by versatran01** [pytorch/ignite#13]
This is not an issue, but just curious how does this compare to tnt.Engine? Looks very similar to me.

**Comment by alykhantejani** [comment]
Hi @versatran01,

Indeed it is very similar to tnt's Engine (and was inspired by tnt). The main differences are:
- Ignite allows for multiple handlers per event
- Ignite doesn’t assume a single model to be trained (and has a higher level of abstraction), which makes it easier to train things like GANs

Ignite is something we've been using for some time privately, and as tnt is not being actively developed for new features, we decided to push this to pytorch and develop it in the open.

That being said, there are some things from tnt we really like and would like to port over, such as the integration with Visdom (and possibly add integration with TensorBoard). 

As always, PRs are welcome :)

**Comment by versatran01** [comment]
Thanks! This is very nice, I was trying to get Engine to work with GAN, but now I don't have to!
It would be nice if you could add the above explanation to the README, so that people can learn the motivation behind this.
Closing.

**Comment by alykhantejani** [comment]
@versatran01 that's a good idea, will do
