### ISSUE TITLE
Automatic docker build and publishing

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1305]
## 🚀 Feature

Idea is to rebuild and publish [pytorch ignite images](https://github.com/pytorch/ignite/tree/master/docker) once a new tag/release is published or a push to the master inside docker folder.

How to publish docker image: 
- https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-docker-hub-and-github-packages

TODO for maintainers:
- create secrets for username/tokens
- ensure that we can build apex, horovod etc on CPU-only machines

**Comment by vfdev-5** [comment]
Current state of the issue:
- we provide scripts to build and push images: 
  - https://github.com/pytorch/ignite/blob/master/docker/hvd/build_all.sh
  - https://github.com/pytorch/ignite/blob/master/docker/main/build_all.sh
  - https://github.com/pytorch/ignite/blob/master/docker/msdp/build_all.sh
  - https://github.com/pytorch/ignite/blob/master/docker/push_all.sh

What remains to do:
- ensure that we can build apex, horovod etc on CPU-only machines
- create a github action which is triggered on "new tag/release is published" or "push to the master inside docker folder"
this action should call 3 build_all.sh in parallel and finally call push_all.sh

**Comment by trsvchn** [comment]
@vfdev-5 I think I can help with this part:

> create a github action which is triggered on "new tag/release is published" or "push to the master inside docker folder"

But

> this action should call 3 build_all.sh in parallel and finally call push_all.sh

I'm not sure that it's possible with GH Actions: [Steps in parallel?](https://github.community/t/steps-in-parallel/16343): 

>  Not at this moment. Only jobs can run in parallel, but steps always run sequentially. I don’t know if there are any plans to ever support this.
