### ISSUE TITLE
Update SSIM metric

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1309]
## 🚀 Feature

Current implementation of [SSIM](https://github.com/pytorch/ignite/blob/master/ignite/metrics/ssim.py) does not use torch tensor as internal storage and hasn't device in the constructor. Following #1238 we expect all metrics to have a similar structure.

@n2cholas , could you please work on that ?

**Comment by n2cholas** [comment]
@vfdev-5 Will do!
