### ISSUE TITLE
Fix link to reinit__is_reduced, sync_all_reduce

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1315]
## 🚀 Feature

Quick issue to add the links to `reinit__is_reduced` and `sync_all_reduce`  in the docs:  https://pytorch.org/ignite/metrics.html#metrics-and-distributed-computations

In addition, please check if `reinit__is_reduced` and `sync_all_reduce` are used elsewhere in the docs and do not contain a link to their docs.

For Hacktoberfest contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at CONTRIBUTING guide.

**Comment by AnshuTrivedi** [comment]
Hi @vfdev-5 , I want to work on this issue.Please assign to me.

**Comment by sdesrozis** [comment]
@AnshuTrivedi Thank you for your help !!

**Comment by AnshuTrivedi** [comment]
@sdesrozis Can you help me in this i explored tutorial about link referening in reStructuredText files. Do i have to replace  decorated with ``reinit__is_reduced``,  ``sync_all_reduce`` with 
.. autofunction:: reinit__is_reduced  .. autofunction:: sync_all_reduce inside metrics file?

**Comment by vfdev-5** [comment]
@AnshuTrivedi idea is at first replace 
```diff
In the above example, ``CustomAccuracy`` has ``reset``, ``update``, ``compute`` methods
- decorated with ``reinit__is_reduced``, ``sync_all_reduce``.
In the above example, ``CustomAccuracy`` has ``reset``, ``update``, ``compute`` methods
+ decorated with :meth:`~ignite.metrics.metric.reinit__is_reduced`, :meth:`~ignite.metrics.metric.sync_all_reduce`.
```
or something like that and **make sure** that in builded docs those words have links. See CONTRIBUTING on how to build locally the docs. Thanks !

**Comment by guptadhaval18** [comment]
Hi @vfdev-5 , I want to work on this issue.

**Comment by vfdev-5** [comment]
@guptadhaval18 unfortunately, this one is also assigned to @AnshuTrivedi . 
Please, take another Hactorberfest issue that is not yet assigned to someone: https://github.com/pytorch/ignite/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest+no%3Aassignee
Thanks !

**Comment by vfdev-5** [comment]
@AnshuTrivedi any updates on this issue from your side ?

**Comment by AnshuTrivedi** [comment]
@vfdev-5 i'm working on it ,due to  difficulty in dependenies i couldn't proceed further.I'm trying another way between @guptadhaval18  can work on it if he wants.

**Comment by vfdev-5** [comment]
@AnshuTrivedi which dependenies difficulty you have ? Maybe we can help with that to guide how to setup a dev environment ?

**Comment by vfdev-5** [comment]
@AnshuTrivedi due to no response from your side, I have to unassign you.

**Comment by josselineperdomo** [comment]
Hello! I would like to work on this issue :) I'm a participant in Hacktoberfest, could you please give me more details about it?

**Comment by vfdev-5** [comment]
@josselineperdomo sounds good, thanks ! Please, check above messages: https://github.com/pytorch/ignite/issues/1315#issue-707446851 and https://github.com/pytorch/ignite/issues/1315#issuecomment-699494631

**Comment by josselineperdomo** [comment]
The idea is add these links: [reinit__is_reduced](https://pytorch.org/ignite/metrics.html?highlight=reinit__is_reduced#ignite.metrics.metric.reinit__is_reduced) and [sync_all_reduce](https://pytorch.org/ignite/metrics.html?highlight=sync_all_reduce#ignite.metrics.metric.sync_all_reduce) to the list of metrics in **Metrics and distributed computations**?

**Comment by vfdev-5** [comment]
Correct and

> In addition, please check if reinit__is_reduced and sync_all_reduce are used elsewhere in the docs and do not contain a link to their docs.

**Comment by josselineperdomo** [comment]
> Correct and
> 
> > In addition, please check if reinit__is_reduced and sync_all_reduce are used elsewhere in the docs and do not contain a link to their docs.

Got it! If you agree, could you please assign me this issue? :blush:

**Comment by vfdev-5** [comment]
@josselineperdomo sure! Thanks
