### ISSUE TITLE
Remove tqdm<=4.48.0 requirements

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1316]
## 🚀 Feature

Due to https://github.com/pytorch/ignite/issues/1287 we downgraded tqdm to <= 4.48.0, this FR is to remove the restriction and update our tests to make them pass.

For Hacktoberfest contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at CONTRIBUTING guide.

**Comment by AnshuTrivedi** [comment]
Hello @vfdev-5 , i want to contribute and fix ssue. Please assign this issue to to me.

**Comment by sdesrozis** [comment]
@AnshuTrivedi Thank you very much for your help !!

**Comment by AnshuTrivedi** [comment]
@sdesrozis can you help me to understand `remove the restriction and update our tests to make them pass `?
Is it removing rquirement line in reqirement file and make change in test files?

**Comment by vfdev-5** [comment]
@AnshuTrivedi yes, there are two modifications to do:
- "revert" what was done here : https://github.com/pytorch/ignite/pull/1293/files
- update tqdm tests here : https://github.com/pytorch/ignite/blob/master/tests/ignite/contrib/handlers/test_tqdm_logger.py
such that they pass.

I suggest you to follow CONTIBUTING guide: clone the repository, [install all dependencies](https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md#installation) and run tqdm tests only:
```
pytest tests/ignite/contrib/handlers/test_tqdm_logger.py
```
As for instance, we do not modify anything, normally, they should pass locally. However, don't be surprised if they fail showing that expected progress bar is smaller/larger then found etc. Depending on the terminal it can fail. Just, pay attention on where it fails if it happend.

Next, you can start modifications and rerun tests. With tqdm 4.49 test should fail differently. Idea is to fix only the difference introduced by 4.49 version.
I let you begin with that. Keep us updated and feel free to ask other questions.

**Comment by vfdev-5** [comment]
@guptadhaval18 currently, this issue is assigned to @AnshuTrivedi

**Comment by vfdev-5** [comment]
@AnshuTrivedi any updates from your side ?

**Comment by crysoar** [comment]
There's help wanted label on this. Is this open for assigning?

**Comment by vfdev-5** [comment]
@crysoar @guptadhaval18 @AnshuTrivedi This issue is now unassigned, if interested in working on that, please, send a PR to fix it

**Comment by trsvchn** [comment]
> @crysoar @guptadhaval18 @AnshuTrivedi This issue is now unassigned, if interested in working on that, please, send a PR to fix it

Good! I am going to join as well!

**Comment by vfdev-5** [comment]
@trsvchn could you also please consider other currently unassigned HF issue : https://github.com/pytorch/ignite/issues?q=is%3Aopen+label%3AHacktoberfest+no%3Aassignee

It would be more helpful instead of picking a single PR from 2 or 3 others fixing the same issue.

**Comment by MinchinWeb** [comment]
@vfdev-5 This issue is coming up (near the top, actually) using the search you provided.... It would seem no one has been "assigned" this on GitHub.

**Comment by vfdev-5** [comment]
@MinchinWeb sorry about that.
