### ISSUE TITLE
Missing links in the doc

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1336]
## 🐛 Bug description

Missing links in the docs : https://pytorch.org/ignite/contrib/engines.html#module-ignite.contrib.engines.common for methods:
- add_early_stopping_by_val_score -> EarlyStopping
- gen_save_best_models_by_val_score -> Checkpoint
- save_best_model_by_val_score -> Checkpoint

**Comment by sroy8091** [comment]
@vfdev-5  Please assign this issue to. I am working on this.

**Comment by vfdev-5** [comment]
@sroy8091 sure!

**Comment by sroy8091** [comment]
I found that below all logger setup functions return also doesn't have hyperlinks, should I add those also?
@vfdev-5

**Comment by vfdev-5** [comment]
Yes, please
