### ISSUE TITLE
MyPy: improve ignite.utils module

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1341]
## 🚀 Feature

Currently, mypy ignores all errors for all modules. We have to rework our typing such that mypy checks the code.
In this issue, let's improve https://github.com/pytorch/ignite/blob/master/ignite/utils.py module such that mypy passes on it.

For Hacktoberfest contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at CONTRIBUTING guide.

**Comment by gruebel** [comment]
Should be no problem, happy to help 😄

**Comment by vfdev-5** [comment]
Nice, thanks @gruebel !
