### ISSUE TITLE
MyPy: improve ignite.base module

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1342]
## 🚀 Feature

Currently, mypy ignores all errors for all modules. We have to rework our typing such that mypy checks the code.
In this issue, let's improve https://github.com/pytorch/ignite/tree/master/ignite/base module such that mypy passes on it.

For Hacktoberfest contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at CONTRIBUTING guide.

**Comment by thescripted** [comment]
Hey, would love to contribute!  I've read through the contributing guide & should be able to complete this over the weekend.

**Comment by vfdev-5** [comment]
Thanks @thescripted ! Let me assign it to you.

**Comment by vfdev-5** [comment]
@thescripted will you work on this issue today or tomorrow ? As we have another PR dependent on this issue, it would be nice to have this one resolved quickly.

**Comment by thescripted** [comment]
Writing up a PR as we speak (:

**Comment by vfdev-5** [comment]
@thescripted thanks !
