### ISSUE TITLE
MyPy: improve improve ignite.handlers module

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1343]
## 🚀 Feature

Currently, mypy ignores all errors for all modules. We have to rework our typing such that mypy checks the code.
In this issue, let's improve https://github.com/pytorch/ignite/tree/master/ignite/handlers module such that mypy passes on it.

For Hacktoberfest contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at CONTRIBUTING guide.

**Comment by trsvchn** [comment]
Hi! I would like to work on this issue!

**Comment by vfdev-5** [comment]
@trsvchn thanks! Sure, go for it :)
