### ISSUE TITLE
Expose EventEnum in the docs and fix custom events example

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1345]
## 🚀 Feature

Currently, `EventEnum` is absent in the docs and below there is no link in the docs:

<img width="663" alt="Screen Shot 2020-10-03 at 23 34 44" src="https://user-images.githubusercontent.com/2459423/95002160-565a6300-05d1-11eb-9af2-a79886069af0.png">

https://pytorch.org/ignite/master/engine.html#ignite.engine.events.Events

Idea is to introduce it in the docs by adding a docstring here 
https://github.com/pytorch/ignite/blob/d384dc664b0e9d7241b5f688ca0f92b600a3cb4d/ignite/engine/events.py#L144-L145

and improve above and all other examples where `EventEnum` is mentioned (please, search for it in the whole repository) by adding
```
from ignite.engine import EventEnum
```

For Hacktoberfest contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at CONTRIBUTING guide.

**Comment by harsh8398** [comment]
I would like to work on this. Could you please assign this to me? Also one quick question, can you elaborate on `improve above and all other examples where EventEnum is mentioned`?

**Comment by vfdev-5** [comment]
@harsh8398 sure !

> Also one quick question, can you elaborate on improve above and all other examples where EventEnum is mentioned?

Please, search for all `EventEnum` mentions in the repository in addition to its definition. It should be mentioned in several docstrings and example that probably missing an explanation on how to import it. Idea is to add `from ignite.engine import EventEnum` to all those examples.
