### ISSUE TITLE
Improve examples using Ignite Trains server

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1347]
## 🚀 Feature

A follow-up of https://github.com/pytorch/ignite/issues/1334 and idea is to setup `output_uri` to `TrainsSaver` if we are using Ignite Trains server to upload artifacts.

**Comment by sdesrozis** [comment]
Note that Trains fileserver can be configured in `trains.config` in `sdk.developpment.default_output_uri` that means no modification in code.

`TrainsSaver(..., output_uri=<path>)` will forward `output_uri` to related `Trains.Task.init(...)`.

**Comment by vfdev-5** [comment]
> Note that Trains fileserver can be configured in trains.config in sdk.developpment.default_output_uri that means no modification in code.

This is nice ! In this case we can only update docs for the examples.
