### ISSUE TITLE
Failing GPU horovod tests 

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1359]
## 🐛 Bug description

`apt-get update` command constantly fails : https://app.circleci.com/pipelines/github/pytorch/ignite/767/workflows/ce6c78f3-39e3-4856-95af-c31987164263/jobs/1758

**Comment by gruebel** [comment]
I did some digging and it seems to be an issue with repo, nvidia updated the package, but not the hash file 🤦 
https://forums.developer.nvidia.com/t/apt-update-failing-on-ubuntu-cuda-repo/140815/4

**Comment by vfdev-5** [comment]
Yeah, seems like that 🤦 
Let's see if they fix it soon or we should do something without running `apt-get update`.

**Comment by vfdev-5** [comment]
Let's close this issue as seems like it was fixed from their side.
