### ISSUE TITLE
Improve typing of distributed.comp_modules.utils.all_gather

### ISSUE THREAD

**Issue by gruebel** [pytorch/ignite#1368]
## 🚀 Feature

As a followup to the issue #1344 and comment https://github.com/pytorch/ignite/pull/1355#discussion_r499854850 it is needed to rework the typing of the `utils.all_gather` and the different realizations serial, native, hvd, xla.

**Comment by gruebel** [comment]
@vfdev-5 I took a look on the code again and your suggested typing, is not feasible.
```
def all_gather(tensor: Union[torch.Tensor, Number, str]) -> Union[torch.Tensor, List[Number], List[str]]:
```
Looking at the definition of `all_gather` inside the `ComputationModel` class
https://github.com/pytorch/ignite/blob/380dd3b0de3c8b4459b2ef221fcefb29f42f9458/ignite/distributed/comp_models/base.py#L163-L167
there is a reference to the function `_collective_op` and there is no possibility to get a result of type `List[Number]`
https://github.com/pytorch/ignite/blob/380dd3b0de3c8b4459b2ef221fcefb29f42f9458/ignite/distributed/comp_models/base.py#L137-L155
except I change the return in line 152 to
```
if tensor_to_number and tensor.numel() == 1:
    return [tensor.item()]
```
If it is ok for you, then I would make the change and adjust all the typings and create the PR.

**Comment by vfdev-5** [comment]
@gruebel you are right, `_collective_op` implementation does not handle this case properly. Let me detail it, in case of all gather, collective op does the following for the input as number:
```
Number -> Tensor[1] -> Tensor[N] returns Tensor[N]
```
comparing with in case of all reduce, collective op does:
```
Number -> Tensor[1] -> Tensor[1] -> Number returns Number
```

Probably, we can add the following case
```python
if tensor_to_number:
    if tensor.numel() == 1:
        return cast(Number, tensor.item())
    else:
        return case(List[Number], tensor.tolist())
```

I think "return" type annotations of `_collective_op` is not complete, I'd say it should be 
```python
    def _collective_op(...) -> Union[torch.Tensor, Number, List[Number], List[str]]:
```
and cover all reduce and all gather cases.

**Comment by gruebel** [comment]
ok, that makes sense. I also saw the reference to `~Tensot.tolist` there. I will give it try 💪
