### ISSUE TITLE
[DOCS] Rendered class and method signature overlaps with [source] after sphinx update

### ISSUE THREAD

**Issue by trsvchn** [pytorch/ignite#1369]
## 🐛 Bug description

I've noticed that after updating to `sphinx=3.1`, documentation has some problem with class header layout, if you go to the docs webpage, you can find that in some cases type hits overlap with [SOURCE] button, in some cases even definition overlaps as well. Zooming-in/out doesn't help.

Here is what I get:
![docs1](https://user-images.githubusercontent.com/30748114/95250758-35894c00-0823-11eb-9cb1-cfc463e64afb.png)
![docs2](https://user-images.githubusercontent.com/30748114/95250768-391cd300-0823-11eb-8a8e-b20e8ad44885.png)
![doc3](https://user-images.githubusercontent.com/30748114/95250941-7da86e80-0823-11eb-84a0-b6cdadee6205.png)

After roll back to old version everything works fine, Also, I've noticed in [pytorch repo](https://github.com/pytorch/pytorch/blob/0da6730f029863b3c812e05ddb3cec8a316c7c1c/docs/requirements.txt#L1) that they're using `sphinx==2.4.4`, I've tried that version and it works well too.

## Environment

`sphinx==3.1`

**Comment by vfdev-5** [comment]
@trsvchn thanks for the report, yes, I noticed that too but I thought that it was due to newly introduced type annotations. 

> After roll back to old version everything works fine

Does it mean, you have you tested current master branch with `sphinx==1.8.5` ?

If yes, maybe we can try the latest version of sphinx == 3.2.1 and check if it was fixed ?

**Comment by trsvchn** [comment]
Nope all new versions after `2.4.4` do not produce the right results, same problem. I've also find this [Pin Sphinx to 2.4.4 ](https://github.com/pytorch/pytorch/pull/36065), they also pinned to `2.4.4` version, looks like pytorch theme has some troubles with newer sphinx.

**Comment by vfdev-5** [comment]
@trsvchn thanks for details, seems like we have no choice here. However, we wanted to update to 3.1 due to https://github.com/pytorch/ignite/issues/1273 . 
I think we have to downgrade to 2.4.4 and try to autogenerate toc tree somehow differently.

cc @theodumont for visibility

**Comment by trsvchn** [comment]
@vfdev-5  I agree with you, we need to downgrade, since for "autotoc" there is alternative solution from SO + we can do it manually (as always :) But I didn't find any solution for that weird header layout.

**Comment by trsvchn** [comment]
With #1374 (from netlify preview):
![doc1](https://user-images.githubusercontent.com/30748114/95367014-e56ec000-08dc-11eb-975a-5b6febf52384.png)
![doc2](https://user-images.githubusercontent.com/30748114/95367018-e7388380-08dc-11eb-95c7-9726814dca85.png)

**Comment by vfdev-5** [comment]
@trsvchn awesome, thanks a lot !
