### ISSUE TITLE
Add materials on how to setup dev env in CONTRIBUTING guide

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1395]
## 🚀 Feature

It would be helpful for the beginners to understand how to setup its development environment and start working on issues. For example, we can base on installing miniconda and setting up a new conda environment.

Idea is to add a small guide [here](https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md#developing-ignite) (before Installation section) and provide a link on a complete guide.

Let's also add links to : 
- https://docs.conda.io/projects/continuumio-conda/en/latest/user-guide/install/index.html
- https://github.com/firstcontributions/first-contributions

Another point to add is a sentence to prevent modifications of `.gitignore` as it was decided from the beginning to use locally `.git/info/exclude` to exclude custom files like: `.idea`, `.vscode` etc.

For Hacktoberfest contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at CONTRIBUTING guide.

**Comment by vfdev-5** [comment]
@BanzaiTokyo would you like to tackle this one :)

**Comment by BanzaiTokyo** [comment]
@vfdev-5 This is definitely doable, but looks time consuming. At the moment I have some other urgent things I need to finish. So it looks like something I could look into in a month or so.

**Comment by vfdev-5** [comment]
@BanzaiTokyo OK, I see. Let's see if it is still open then you can give it a go as soon as it is possible for you. Otherwise, I can assign it to anyone else :)

**Comment by BanzaiTokyo** [comment]
sure @vfdev-5 !

**Comment by fco-dv** [comment]
@vfdev-5 I can give it a try!
