### ISSUE TITLE
Remove all deprecated args, kwargs for v0.5.0

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1396]
## 🚀 Feature

We would like to find and remove all deprecated args/kwargs and associated docstrings in the codebase if it is mentioned that they will be removed in v0.5.0. For example, 
https://github.com/pytorch/ignite/blob/acd2982dfc6ecbea347d1ff88d893f8acdd87a56/ignite/engine/engine.py#L657-L658

For Hacktoberfest contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at CONTRIBUTING guide.

**Comment by ibotdotout** [comment]
I would like to give a go.

**Comment by vfdev-5** [comment]
@ibotdotout sure!
