### ISSUE TITLE
Use @actions/cache in GH actions

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/ignite#1403]
## 🚀 Feature

Use [`@actions/cache`](https://github.com/actions/cache) for caching dependencies to speed up CI

@vfdev-5

**Comment by trsvchn** [comment]
Are there the same feature for produced artifacts, e.g. built Docker images?

**Comment by ydcjeff** [comment]
@trsvchn Yes, there is https://github.com/docker/build-push-action#leverage-github-cache

**Comment by trsvchn** [comment]
@ydcjeff Thanks! I will try!

**Comment by ydcjeff** [comment]
@vfdev-5 what do you think?

**Comment by vfdev-5** [comment]
@ydcjeff yes, makes sense to cache conda deps and reset the cache every week or so.
