### ISSUE TITLE
Fix incorrect design for RunningAverage, Frequency, ModelCheckpoint, ...

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1405]
## 🐛 Bug description

Thanks to PRs on mypy annotation by @gruebel we discovered few classes where we have to redesign methods in order to keep consistency with their base classes.

- Frequency: https://github.com/pytorch/ignite/pull/1391#discussion_r511651133
- RunningAverage: https://github.com/pytorch/ignite/pull/1391#discussion_r511651876
- Checkpoint: `to_save` should not be `Optional` but it is due to `ModelCheckpoint` and current implementation.
https://github.com/pytorch/ignite/blob/ddcce01eb7f64efa274ce25703d8f28245715319/ignite/handlers/checkpoint.py#L241

@gruebel please comment here if you think about other classes/methods we did a type relaxation.

cc @sdesrozis @fco-dv

**Comment by gruebel** [comment]
Similar to `Frequency` also `GpuInfo` inherits from `Metric`, so the `attach` method should have the same signature
https://github.com/pytorch/ignite/blob/ddcce01eb7f64efa274ce25703d8f28245715319/ignite/contrib/metrics/gpu_info.py#L107-L108

**Comment by vfdev-5** [comment]
Closing as solved
