### ISSUE TITLE
MyPy: improve ignite.contrib module

### ISSUE THREAD

**Issue by gruebel** [pytorch/ignite#1406]
## 🚀 Feature

The `ignite.contrib` module is the last one, which is ignored by the `mypy` config 💪 For anyone, who wants to do it, I would recommend to split it in 3-4 PRs

- `ignite.contrib.engines`
- `ignite.contrib.handlers`
- `ignite.contrib.metrics`
- (Optional separate PR) `ignite.contrib.metrics.regression`

After that we could also enable more stricter `mypy` configuration to further improve the typing of the project.

So, feel free to ask any questions here or in your PRs, I will try my best to give proper guidance and @vfdev-5 will do the same for sure, like he did with my previous PRs 👍

**Comment by zhxxn** [comment]
Hi, I would like to give it a try!

**Comment by vfdev-5** [comment]
@gruebel thanks a lot for opening the issue ! 
@zhxxn let me assign it to you. 
As this issue is large, we can assign more than one person to the issue.

**Comment by zhxxn** [comment]
Hi! I would then start with `ignite.contrib.metrics` module 😄

**Comment by zhxxn** [comment]
I just finished my work on `ignite.contrib.metrics`. 
Next I would like to try `ignite.contrib.handlers` 😄

**Comment by vfdev-5** [comment]
> Next I would like to try `ignite.contrib.handlers`

@zhxxn how's going your attempt on `ignite.contrib.handlers` ?

**Comment by zhxxn** [comment]
Hi, I am still working on this and it will take some time.. 😅
Is it urgent for you?

**Comment by vfdev-5** [comment]
Hi @zhxxn, no problems, take your time. I just wanted to check if it is not abandoned :)

**Comment by zhxxn** [comment]
@gruebel Hi, would you be interested in taking over my part `ignite.contrib.handlers`? 
Sadly, timewise I cannot finish it 😥😢

**Comment by gruebel** [comment]
@zhxxn sure, no problem 👍 
@vfdev-5 can you assign me to this issue? I will start working on it this weekend 💪

**Comment by vfdev-5** [comment]
@gruebel thanks !
