### ISSUE TITLE
Replace type hint numbers.Number with float

### ISSUE THREAD

**Issue by gruebel** [pytorch/ignite#1407]
## 🚀 Feature

Due to limitations in `mypy` or to be precise in `typeshed`, `int` and `float` are no `numbers.Number`. (For some extra details https://github.com/pytorch/ignite/pull/1391#discussion_r511656836) 

Therefore it would be helpful to change the typing from `number.Number` to `float` and remove several `# type: ignore`, where applicable.

**Comment by gruebel** [comment]
@vfdev-5 you can directly assign me 😄 I want to see, if it is that easy, how I imagined it or if we get new problems with it.

**Comment by vfdev-5** [comment]
@gruebel sure! Thanks for opening the issue !
