### ISSUE TITLE
Need to automatically reset _saved in Checkpoint handler

### ISSUE THREAD

**Issue by Nic-Ma** [pytorch/ignite#1422]
## 🚀 Feature

Hi @vfdev-5 ,

there is a problem with the Checkpoint handler: if we normally call engine.run() several times, every time it will run from the beginning because it has _is_done() to reset all the state, but Checkpoint handler doesn't reset the self._saved in it.

**Comment by vfdev-5** [comment]
Thanks for the FR @Nic-Ma ! 
In this issue we can think about better and safe API for Checkpoint and provide it also to all other handlers that accumulate state like that.
