### ISSUE TITLE
Provide notebook showing example usage of HandlersTimeProfiler

### ISSUE THREAD

**Issue by harsh8398** [pytorch/ignite#1427]
## 🚀 Provide notebook showing example usage of HandlersTimeProfiler

`ignite.contrib.handlers.time_profilers.HandlersTimeProfiler` can be used to profile handlers attached to any events during engine run. It would be nice if we provide some example notebook with a basic example usage of this profiler.

@vfdev-5 Can you please provide details where this notebook will reside in the repo?

**Comment by vfdev-5** [comment]
@harsh8398 typically, the notebooks we put here : https://github.com/pytorch/ignite/tree/master/examples/notebooks
As an example, you can refer  to FastaiLRFinder_MNIST.ipynb.

Once it is ready, please also update the README.md: https://github.com/pytorch/ignite#tutorials

**Comment by vfdev-5** [comment]
Closed by #1474
