### ISSUE TITLE
Improvements of "Getting started" docs

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1438]
## 🚀 Feature

Currently, [we propose](https://github.com/pytorch/ignite#getting-started) to our users the following documents to getting started: 
- https://pytorch.org/ignite/quickstart.html
- https://pytorch.org/ignite/concepts.html 

The idea is to review and improve these documents by
1) fixing typos, 
2) adding missing links
2) rewording sentences to simplify the understanding,

Any other constructive suggestions on how to simplify the learning curve for the tool are very welcome !

For PyDataGlobal contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at CONTRIBUTING guide.

**Comment by Afzal-Ind** [comment]
As I am one of the participants of this event _PyData_ _Global_ _Summit_, I want to be part of your project. I am looking forward to contributing here. It's my first time though.

**Comment by vfdev-5** [comment]
@Afzal-Ind sure ! Please, read this issue description and follow the guidelines. Feel free to ask questions for other details here or reach out to me on mattermost if needed: @vfdev-5
For global info, please see https://github.com/pytorch/ignite/issues/1437

**Comment by Afzal-Ind** [comment]
@vfdev-5 Thank you, Sir. I went through the guidelines. I want to connect with you. Would you tell me your username on Mattermost?

**Comment by vfdev-5** [comment]
> Would you tell me your username on Mattermost?

Sure, please use "vfdev-5".
