### ISSUE TITLE
Migrate from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1442]
## 🚀 Feature

The idea is to migrate 3 following stages from Travis CI to GitHub Actions:
  - [x] Docs: https://github.com/pytorch/ignite/blob/master/.travis.yml#L64-L95
  - [x] Deploy: https://github.com/pytorch/ignite/blob/master/.travis.yml#L97-L145
  - [x] Nightly: https://github.com/pytorch/ignite/blob/master/.travis.yml#L147-L175 (done by https://github.com/pytorch/ignite/pull/1450)

Each stage can be a separate action: e.g. Docs -> `.github/workflows/docs.yml`, Deploy -> `.github/workflows/binaries-release.yml`, Nightly -> `.github/workflows/binaries-nightly-release.yml`

For PyDataGlobal contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at CONTRIBUTING guide.

**Comment by ydcjeff** [comment]
@vfdev-5 docs and deploy left to done?
can i take this?

**Comment by vfdev-5** [comment]
@ydcjeff yes, docs and deploy are still open. 
You can take a look at how to migrate docs, if you like. This task is also overlaps a little with this https://github.com/pytorch/ignite/pull/1350 in the sense that I'd like to have ["Nice to have" part](https://github.com/pytorch/ignite/issues/1270#issuecomment-703180980) for this issue.

**Comment by ydcjeff** [comment]
Okay, I will start working if that PR get closed.

**Comment by vfdev-5** [comment]
@ydcjeff #1350 does not solve the same problem. It will be closed once we migrated from Travis.

**Comment by ydcjeff** [comment]
Alright then I will draft a PR

**Comment by vfdev-5** [comment]
Thanks @ydcjeff !

**Comment by vfdev-5** [comment]
Done via #1458 #1457 and #1450
