### ISSUE TITLE
Update conda recipe

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1443]
## 🚀 Feature

Currently, we are using the following conda recipe for building conda binaries : https://github.com/pytorch/ignite/tree/master/conda.recipe

The idea is to try to build "universal" package (like with pip) 
```
build:
  noarch: python
```
and thus remove https://github.com/pytorch/ignite/blob/master/conda.recipe/conda_build_config.yaml . I'm not sure if this will give the same result as we have, but it worth to check.

For PyDataGlobal contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at CONTRIBUTING guide.

**Comment by Afzal-Ind** [comment]
@vfdev-5 Hi, How to start off with this? Any prerequisites?

**Comment by vfdev-5** [comment]
@Afzal-Ind i'd suggest to start with conda build: https://docs.conda.io/projects/conda-build/en/latest/index.html
and understand how it works. We build conda binaries here : https://github.com/pytorch/ignite/blob/master/conda.recipe/build_and_upload.sh#L26 so this step is important to run locally while modifying https://github.com/pytorch/ignite/blob/master/conda.recipe/meta.yaml
