### ISSUE TITLE
Fix mypy issue with pytorch nightly

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1446]
## 🐛 Bug description

Currently, there is an issue with running mypy on ignite when using pytorch-nightly : 
```
 ignite/distributed/comp_models/native.py:334: error: Incompatible types in
assignment (expression has type "ReduceOp", variable has type "str") 
[assignment]
                op = self._reduce_op_map[op]
                     ^
Found 1 error in 1 file (checked 84 source files)
```

https://github.com/pytorch/ignite/runs/1373059337#step:5:17

@gruebel could you please take a look if we can fix it ? Thanks

**Comment by gruebel** [comment]
Sure, I can take a look today

**Comment by vfdev-5** [comment]
Thanks @gruebel ! And couldy you please also remove `namedtuple` import (https://github.com/pytorch/ignite/pull/1433#discussion_r516991700). I merged too fast that PR :)

**Comment by gruebel** [comment]
yeah, good point. Already forgot about it 🙈
