### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/ignite#1453]
## ❓ Questions/Help/Support

Why there is no pytorch in requirements-dev.txt?
Also is it okay to add environment.yml for conda users?

cc: @vfdev-5

**Comment by vfdev-5** [comment]
@ydcjeff torch is a hard requirement (see [setup.py](https://github.com/pytorch/ignite/blob/master/setup.py#L26)) vs those from `requirements-dev.txt` which a sort of optional. 

> Also is it okay to add environment.yml for conda users?

I was thinking about that previously and I'm not sure what to add there. If we install ignite from conda
```
conda install ignite -c pytorch
```
we already have a minimum deps working library. What do you think ?

**Comment by ydcjeff** [comment]
I see! so contributors feel free to create their own env as the only req is torch...
we can add `pytorch`, `python` and `-r requirements-dev.txt` in environement.yml

**Comment by vfdev-5** [comment]
> we can add pytorch, python and -r requirements-dev.txt in environement.yml

Well, yes, we can similarly provide a `environement-dev.yml` file and update contributing guide to say how to use it with conda...

Could you also please check if we missed torchvision dependency ? I mean to install pytorch + requirements-dev.txt, see if torchvision was not installed and run tests. Probably it should fail as torchvision is missing...

**Comment by ydcjeff** [comment]
@vfdev-5 do you mean examples? I install pytorch + requirements-dev.txt and tests are passing.

**Comment by vfdev-5** [comment]
@ydcjeff oh, yes, that's true, I though we used torchvision somewhere as test dependency... Not yet. Thanks for checking that !

**Comment by ydcjeff** [comment]
@vfdev-5 how about we put torch in requirements-dev.txt? and add `-r requirements-dev.txt` in environment.yml if we want.
 (we don't need it anymore, I think) I found we are installing torch torchvision separately with conda and follow up with `-r requirements-dev.txt` with pip.
so if we add torch in requirements-dev.txt, we can install all deps with `pip install -r requirements-dev.txt -f https://download.pytorch.org/whl/cpu/torch_stable.html` all in one command. no need for conda and caching can also be done in one step both stable and nightly replacing the url

**Comment by vfdev-5** [comment]
Thanks for the idea, however i'm hesitating to remove conda for now. Let's keep it like that. 
As for caching, can't we put multiple paths to actions/cache ?

**Comment by ydcjeff** [comment]
Yes we can but caching one step is just a suggestion

**Comment by vfdev-5** [comment]
@ydcjeff I think we can close this issue as solved. Let me close it and feel free to reopen if needed.
