### ISSUE TITLE
from ignite.trainer import Trainer ImportError: No module named trainer

### ISSUE THREAD

**Issue by monajalal** [pytorch/ignite#146]
I get this error:

```
[jalal@goku pytorch-sentiment-analysis]$ python run.py --model_config config/cnn_rnn.yml --epochs 50 --model_dir sentiment-analysis.pt --dataset data/sentiment
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    from ignite.trainer import Trainer
ImportError: No module named trainer
```

for the piece of code:
`from ignite.trainer import Trainer`

Issue further explained here:
https://github.com/akurniawan/pytorch-sentiment-analysis/issues/6

```
$ python -V
Python 2.7.14 :: Anaconda custom (64-bit)

```

**Comment by alykhantejani** [comment]
Hi @monajalal,

Sorry about this. As @vfdev-5 mentioned, the API changed a bit since your last pull, we've mostly stabilized this now and will be releasing 0.1 soon.
