### ISSUE TITLE
Parametrize metric tests

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/ignite#1469]
## 🚀 Feature

Use `pytest.mark.parametrize` for metric testing

**Comment by Moh-Yakoub** [comment]
I'd like to work on this.

Are you referring to the tests in `tests\ignite\metrics` ?

**Comment by vfdev-5** [comment]
@Moh-Yakoub thanks for asking, currently we haven't defined exact scope for this issue, so it is more or less exploration and a nice to have in order to simpify our metrics tests: tests/ignite/metrics

**Comment by Moh-Yakoub** [comment]
@vfdev-5 Thanks a lot for the reply. That makes sense. I think I will start experimenting with adding some tests for some of the metrics and we can incrementally adopt the test characterization.
