### ISSUE TITLE
Error with SSIM calculation?

### ISSUE THREAD

**Issue by kacperkan** [pytorch/ignite#1472]
## ❓ Questions/Help/Support

Hi!

Thank you for creating such a great library. I wanted to use SSIM metric calculation implemented in `ignite`. However, at first glance, the implementation lacks the `s` term calculation that can be found in [the original paper](http://www.cns.nyu.edu/pub/eero/wang03-r\eprint.pdf). At this moment, `l` and `c` terms are used only. Can you clarify whether the implementation is wrong or if am I missing something?

Best regards
Kacper

**Comment by vfdev-5** [comment]
@ydcjeff could you please take a look ?

**Comment by kacperkan** [comment]
@vfdev-5 @ydcjeff My bad, there's a derivation in Eq. 13 in the paper that simplifies some terms and leads to the already implemented equation. Sorry for raising the alarm unnecessarily.
