### ISSUE TITLE
Breaking change in metrics behaviour

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1476]
## 🐛 Bug description

Following https://github.com/pytorch/ignite/pull/968 (and associated issue ) metric's output is flatten if it returns a mapping/dict. In details, with ignite v0.4.2, for a 
custom metric's we have the following:
```python
class PerformanceIndicators(Metric):

    def compute(self):
        # ...
        return {
            'a': 12,
            'b': 23
        }

PerformanceIndicators().attach(evaluator, name="indicators")

assert "a" in evaluator.state.metrics
assert "b" in evaluator.state.metrics

# This is a breaking change introduced by the PR
assert not "indicators" in evaluator.state.metrics

print(evaluator.state.metrics)
> {'a': 12, 'b': 23}
```

The questions we would like to address in this issue:
- Should we fix the breaking change by readding the dict into `evaluator.state.metrics` such that we'll have:
```
print(evaluator.state.metrics)
> {'a': 12, 'b': 23, 'indicators': {'a': 12, 'b': 23}}
```
 
- `name` parameter (e.g. "indicators") is never used. Should we append it to the flatten names (e.g. `indicators/a`, `indicators/b`) or we can accept that it is never used ?

Thanks @lidq92 for reporting this.

## Environment

 - PyTorch Version (e.g., 1.4): 1.6.0
 - Ignite Version (e.g., 0.3.0): 0.4.2
 - OS (e.g., Linux): 
 - How you installed Ignite (`conda`, `pip`, source):
 - Python version:
 - Any other relevant information:

cc @sdesrozis @liebkne

**Comment by sdesrozis** [comment]
I really appreciate this idea to have flat values and dict in metrics data 
```
print(evaluator.state.metrics)
> {'a': 12, 'b': 23, 'indicators': {'a': 12, 'b': 23}}
```

It does fix the use of `name` parameter too. 

A point is that doubles stored values but atm these values in dict are numbers.

**Comment by Yevgnen** [comment]
As the original nested value is kept in the metrics dict, some logger will also flatten dict value for plot like `wandb` which results in duplicate (double) plots. Is there any suggestion on this? Thank you.

**Comment by vfdev-5** [comment]
@Yevgnen thanks for pointing out about that !
To avoid duplicated plots, for now it is possible to specify which metrics to plot instead of using "all" :  
```ptyhon
wandb_logger.attach_output_handler(
    ...
    metric_names=["nll", "accuracy"],
)
```
- https://pytorch.org/ignite/contrib/handlers.html#ignite.contrib.handlers.wandb_logger.WandBLogger

Seeing the Wandb logger's code, we log everything:
https://github.com/pytorch/ignite/blob/9230a7319047b37ce19d956e024fa1b86030c30a/ignite/contrib/handlers/wandb_logger.py#L271-L275

however, we check the data type for others (Visdom, MLflow, Polyaxon, ClearML, ...), e.g. Neptune
https://github.com/pytorch/ignite/blob/9230a7319047b37ce19d956e024fa1b86030c30a/ignite/contrib/handlers/neptune_logger.py#L344-L351

Probably, we would like to make that uniform for all loggers ...

**Comment by Yevgnen** [comment]
Thanks for the information about `metric_names`. I'm currently using something like `setup_wandb_logging` (another wrapper over it) which encapsulates the `logger.attach_output_handler` part itself. I might duplicate that code for now. Thanks!

I have lots metrics (E entity types + R relation types + overall) x micro/macro/precision, recall, f1 tracked over iterations). It would be nice to have uniform usage and behavior for all loggers.

**Comment by vfdev-5** [comment]
>  It would be nice to have uniform usage and behavior for all loggers.

@Yevgnen I agree.

Meanwhile, maybe, we add custom filtering of `state.metrics` without changing your code and copying ignite methods:
```python

trainer = ...
evaluator = ...

@trainer.on(...)
def run_validation():
    evaluator.run(val_loader)


@evaluator.on(Events.COMPLETED)
def filter_metrics(engine):
    engine.state.metrics = {
        k: v for k, v in engine.state.metrics.items() if isinstance(v, dict)
    }

setup_wandb_logging(trainer, evaluators=evaluator)
``` 

What do you think ?

**Comment by Yevgnen** [comment]
Looks good! All I should do is to ensure the filter is processed after the metrics computation, right?

**Comment by vfdev-5** [comment]
Exactly, after they are computed by something like `evaluator.run(val_loader)` and before they are logged by wandb.

**Comment by vfdev-5** [comment]
I'll create new issue for uniform approach between loggers.
