### ISSUE TITLE
Drop support of python 3.5

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1495]
## 🚀 Feature

> Python 3.5 has reached end-of-life. Python 3.5.10 is the final release of 3.5.

https://www.python.org/downloads/release/python-3510/

Let's drop python 3.5 in the CI:
- https://github.com/pytorch/ignite/blob/6b263220d9b1ae1ed6d13444d8085ab1878690ee/.github/workflows/pytorch-version-tests.yml#L16
- https://github.com/pytorch/ignite/blob/6b263220d9b1ae1ed6d13444d8085ab1878690ee/.github/workflows/unit-tests.yml#L26

If interested in helping with the issue, please comment here and send a PR according to our contributing guide.
Feel free to ask questions for details if needed.

**Comment by trsvchn** [comment]
Looks like 2020 was a hard year for the python 3.5 :D

Can I work on this issue?

**Comment by vfdev-5** [comment]
@trsvchn sure ! Yes, seems like python 3.5 is no more supported :(

**Comment by trsvchn** [comment]
@vfdev-5 we can remove these lines as well, am I right?

https://github.com/pytorch/ignite/blob/6b263220d9b1ae1ed6d13444d8085ab1878690ee/.github/workflows/pytorch-version-tests.yml#L21-L24

https://github.com/pytorch/ignite/blob/6b263220d9b1ae1ed6d13444d8085ab1878690ee/.github/workflows/unit-tests.yml#L28-L31

**Comment by vfdev-5** [comment]
I think, yes. They already exclude 3.5 for newer pytorch versions...

**Comment by trsvchn** [comment]
Thanks for the help, @vfdev-5 And this line

https://github.com/pytorch/ignite/blob/6b263220d9b1ae1ed6d13444d8085ab1878690ee/.github/workflows/unit-tests.yml#L85

will be just

```python
if: ${{ matrix.os == 'ubuntu-latest' }}
```

**Comment by vfdev-5** [comment]
Yes, you get it right :)

**Comment by trsvchn** [comment]
Thanks!
