### ISSUE TITLE
rename ignite.engines -> ignite.engine

### ISSUE THREAD

**Issue by alykhantejani** [pytorch/ignite#152]
@jasonkriss @vfdev-5  was there a reason we didn't do this when we merged the engines into one?

**Comment by vfdev-5** [comment]
@alykhantejani see [this](https://github.com/pytorch/ignite/issues/108#issuecomment-377291568) and [this](https://github.com/pytorch/ignite/issues/108#issuecomment-377563226):

> The file engineS.rst probably become engine.rst ...

> engines.rst should still be engines because of how we have structured the code.

**Comment by alykhantejani** [comment]
hmm ok, @jasonkriss can you talk a bit about why `engineS.rst` should remain `engines` and not `engine`? 

And do you have any objections for the package `ignite.engines` to be renamed `ignite.engine`?

**Comment by vfdev-5** [comment]
no objections

**Comment by jasonkriss** [comment]
The only real objection I can think of is if we want to guard against breaking backwards compatibility in the event that we introduce other engines in the future. It will also require that current ignite users to update their code (albeit in a very minor way). I'm ok with switching it though and this is the time to do it if so. Whatever you think is best!

**Comment by alykhantejani** [comment]
Yeah, I think it makes sense to switch now if we are going to. Backwards compatibility can be handled in semi-graceful ways with deprecation warnings later down the line. 

Ok I'll try and get to this soon. Trying to close out the small things to ship 0.1 :)

**Comment by jasonkriss** [comment]
sounds good! Excited to see we're close to a 0.1.0 release!
