### ISSUE TITLE
Issue in logging info in jupyter lab notebook

### ISSUE THREAD

**Issue by saruarlive** [pytorch/ignite#1530]
Hi @vfdev-5 et al,
Hope you are doing great. 
I use commands like, 
logging.basicConfig(stream=sys.stdout, level=logging.INFO)     
trainer.run()

It continues to increase notebook length.  The notebook goes down and down. 
![image](https://user-images.githubusercontent.com/24542592/103107010-b265de00-463a-11eb-8057-d74851e9216a.png)

Shall I get logging info in the sub-scrollbar in a notebook?
If so, how to achieve it? I am looking forward to hearing from you.

**Comment by vfdev-5** [comment]
Hi @saruarlive , I think this is expected behaviour with logging that every logged line will be present in the notebook.
You can try as alternative, to use the ProgressBar like the following:
```python
from ignite.engine import Engine
from ignite.contrib.handlers import ProgressBar

def train_step(e, b):
    time.sleep(0.1)
    loss = (10 - b) * 0.01
    return loss

trainer = Engine(train_step)

pbar = ProgressBar(persist=True)
pbar.attach(trainer, output_transform=lambda output: {"train_loss": output})

trainer.run(range(10), max_epochs=2)
```
What do you think ?

**Comment by vfdev-5** [comment]
@saruarlive let me close the issue as answered. If you need more help on this topic, feel free to reopen this issue.
