### ISSUE TITLE
How to check metric output by giving random inputs

### ISSUE THREAD

**Issue by saruarlive** [pytorch/ignite#1538]
Dear @vfdev-5 et al, 

I want to check/investigate metric outputs by giving random inputs. I have tried, but it is not working that way. 
![image](https://user-images.githubusercontent.com/24542592/103411536-dbbdc700-4b70-11eb-83da-8a464ee081dc.png)

Could you kindly suggest how to do that?

**Comment by sdesrozis** [comment]
Hi @saruarlive ! Thank you for this question.

You should use methods `update` and `compute` that are used by engines. 

You can find examples here https://github.com/pytorch/ignite/blob/master/tests/ignite/metrics/test_accuracy.py

```python
acc.update((y_pred, y))
print(acc.compute())
```

HTH

**Comment by sdesrozis** [comment]
@saruarlive The doc has been improved to show how to use metrics without `Engine`.

I close this issue, feel free to reopen if needed.
