### ISSUE TITLE
[Feature] PyTorch 0.4.0 Migration 

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#154]
👍 🎉  [PyTorch 0.4.0](https://github.com/pytorch/pytorch/releases/tag/v0.4.0) is arrived ! 🎉 👍 
and we will need to clean-up the code according to 

**Major Changes and Potentially Breaking Changes:**

- Tensors and Variables have merged
- Some operations now return 0-dimensional (scalar) Tensors
- Deprecation of the volatile flag

Can we do this after the very first release 0.1 ?

**Comment by vfdev-5** [comment]
And incompatibilities already come to the party :) 
```
>       assert model.weight.data[0, 0] == approx(0.0)
E       TypeError: eq() received an invalid combination of arguments - got (ApproxScalar), but expected one of:
E        * (Tensor other)
E             didn't match because some of the arguments have invalid types: (!ApproxScalar!)
E        * (float other)
E             didn't match because some of the arguments have invalid types: (!ApproxScalar!)
```
and 
```
>   ???
E   AssertionError: `loss_fn` did not return the average loss
```
See [here](https://travis-ci.org/pytorch/ignite/jobs/370846036) for example

**Comment by alykhantejani** [comment]
hmm - perhaps we should do this before 0.1 especially if it has breaking changes
