### ISSUE TITLE
Improve metrics docs: 2 types of API

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1540]
## 🚀 Feature

Following https://github.com/pytorch/ignite/issues/1538 it would be nice to explicitly mention [here](https://pytorch.org/ignite/master/metrics.html#ignite-metrics) that there are 2 types of API : 
- using metric with Engine
- using metric's reset/update/compute

and give examples.

**Comment by ydcjeff** [comment]
@vfdev-5 I am familiar with `.attach()` method. For reset/update/compute, the correct way is like this (computing epoch-wise)?
```py
precision = Precision()
precision.attach(engine, 'precision')
@engine.on(Events.EPOCH_STARTED)
def reset():
    precision.reset()

def process_fn(e, b):
    ...
    precision.update((pred, target))

@engine.on(Events.EPOCH_COMPLETED)
def compute():
    precision.compute()
```

**Comment by sdesrozis** [comment]
We have introduced `MetricUsage` to do this. See https://github.com/pytorch/ignite/blob/5ceacbb3ccea433317df2776556bd4a08d0a923d/ignite/metrics/metric.py#L52

The relevant PR is #979

HTH

**Comment by vfdev-5** [comment]
@ydcjeff yes, the idea is to show how to use reset/update/compute API without relation to the engine:
```python
precision = Precision()

precision.update((pred1, target1))
precision.update((pred2, target2))
precision.update((pred3, target3))

print("Precision: ", precision.compute())

precision.reset()
precision.update((pred1, target1))
precision.update((pred2, target2))
precision.update((pred3, target3))
print("Precision: ", precision.compute())
```

**Comment by vfdev-5** [comment]
@ydcjeff would you like to send a PR to fix this issue ?

**Comment by ydcjeff** [comment]
I can only send in next weeks
