### ISSUE TITLE
Pass kwargs to idist.auto_model

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1545]
## 🚀 Feature

It would be nice to have a possibility to pass kwargs to `idist.auto_model`.
For example, a use-case if using multi-gpu DDP model training, I'd like to pass `find_unused_parameters=True` to 
`torch.nn.parallel.DistributedDataParallel`. 
```python
    # model = idist.auto_model(model, find_unused_parameters=True)

    import torch
    lrank = idist.get_local_rank()
    model = model.to(idist.device())
    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[lrank,], find_unused_parameters=True)
```

**Comment by vfdev-5** [comment]
@ryanwongsa here I'd like to pass a kwargs to `auto_*` method, namely to pass a parameter like `find_unused_parameters` which makes sense only for DDP GPUs... Do you think that this is similarly misleading as for the case with `barrier` for `auto_optim` in the other issue ?

**Comment by ryanwongsa** [comment]
I think to me adding the above type of parameter (`find_unused_parameters`) is fine as in this case I don't think it requires other additional code. In the the barrier case in `auto_optim`, you would need to add `xm.mark_step()` if you set `barrier=False` so it could be misleading. Hopefully that makes sense.

**Comment by vfdev-5** [comment]
@ryanwongsa thanks for the feedback. Just in case, if you are interested in helping with this issue, do not hesitate to send a PR with the fix :)
