### ISSUE TITLE
Any difference between these two?

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/ignite#1566]
## ❓ Questions/Help/Support
Is there any difference between this docstring
https://github.com/pytorch/ignite/blob/7280b531e764f6c98970d3bdafa95fd056bf1eda/ignite/contrib/engines/common.py#L592-L593

and this docstring
https://github.com/pytorch/ignite/blob/7280b531e764f6c98970d3bdafa95fd056bf1eda/ignite/contrib/engines/common.py#L645

As far as I see, no difference since we can still use `dict` type in `model` arg of `save_best_model_by_val_score` function

Should I update the docstring?

**Comment by vfdev-5** [comment]
Yes, `model` arg for `save_best_model_by_val_score` can be also a dict of nn.Modules as `gen_save_best_models_by_val_score` can accept it and we do not check the type. As docs of `save_best_model_by_val_score` states it is not intended to pass a dict...

**Comment by ydcjeff** [comment]
So, what's difference between those two functions in terms of usage?

**Comment by vfdev-5** [comment]
The way to store the models. One is always to disk and another with any kind of savers (e.g. cloud etc)

**Comment by ydcjeff** [comment]
I see! Thanks
