### ISSUE TITLE
[metrics] add PSNR

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/ignite#1568]
## 🚀 Feature
I would like to add PSNR metric which is used in super resolution applications.
Implementation will be based from:

https://github.com/pytorch/examples/blob/792d336019a28a679e29cf174e10cee80ead8722/super_resolution/main.py#L69-L70

Though it's relatively easy to implement on our own, having in `ignite` will benefit everyone else.

**Comment by vfdev-5** [comment]
Thanks for the idea, @ydcjeff ! Please, go ahead with a PR :+1:
