### ISSUE TITLE
Possible typo in concepts.rst

### ISSUE THREAD

**Issue by Devanshu24** [pytorch/ignite#1572]
## 🐛 Bug description

On the `concepts` page, in the docs, it says "complexity training". I think it is a typo and was supposed to be "complex training".

The actual line for reference:
https://github.com/pytorch/ignite/blob/7280b531e764f6c98970d3bdafa95fd056bf1eda/docs/source/concepts.rst#L62

I am sorry if it is an intentional phrasing style, I just felt I should convey it once just in case if it isn't intentional :)

**Comment by vfdev-5** [comment]
@Devanshu24 thanks for asking ! I agree that this sentence can be better reworded as "Training logic of any complexity can be coded with ``train_step`` method ...". If you'd like to fix it, please send a PR.
