### ISSUE TITLE
[docs] use `versionadded`, `versionchanged` and `deprecated` directive

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/ignite#1575]
## 🚀 Feature
Use `.. versionadded::`, `.. versionchanged::` and `.. deprecated::` directive, so that user knows which features are added / changed / deprecated in which version and they can navigate the docs easily without changing the docs from version to version.

Ref: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded

**Comment by vfdev-5** [comment]
Thanks for the idea @ydcjeff ! It would be very nice to have that.

**Comment by ydcjeff** [comment]
@vfdev-5 we can start adding for features to be added in 0.5.0.

Where should we begin?

**Comment by vfdev-5** [comment]
Yes, starting from v0.5.0

**Comment by vfdev-5** [comment]
@ydcjeff could you please mention those `versionadded`, `versionchanged` in the CONTRIBUTING in the docs section. Thanks !

**Comment by ydcjeff** [comment]
This is already in use, so closing
