### ISSUE TITLE
[docs] use katex instead of mathjax

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/ignite#1576]
## 🚀 Feature
Currently, math equation in the `contrib.metrics` are so small that we have to zoom to look at.
I want to suggest for using `katex` instead of `mathjax` and also `pytorch_sphinx_theme` has preloaded with `katex` font.

What's need to change here is
- install `sphinxcontrib-katex`
- add `sphinxcontrib.katex` in `extensions` of `conf.py`
- add the below code block in head tag of `layout.html`
```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css" integrity="sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X" crossorigin="anonymous">

    <!-- The loading of KaTeX is deferred to speed up page rendering -->
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js" integrity="sha384-g7c+Jr9ZivxKLnZTDUhnkOnsh30B4H0rpLUpJ4jAIKs4fnJI+sEnkvrMWph2EDg4" crossorigin="anonymous"></script>

    <!-- To automatically render math in text elements, include the auto-render extension: -->
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/contrib/auto-render.min.js" integrity="sha384-mll67QQFJfxn0IYznZYonOWZ644AWYC+Pt2cHqMaRhXVrursRwvLnLaebdGIlYNa" crossorigin="anonymous"
        onload="renderMathInElement(document.body);"></script>
```
Katex: https://katex.org/docs/browser.html

**Comment by vfdev-5** [comment]
Yes, I agree, that if using katex docs rendering could be improved, it is something to do. Thanks @ydcjeff !

cc @trsvchn

**Comment by ydcjeff** [comment]
I have tried locally when implementing #1570 and it works!

**Comment by trsvchn** [comment]
> Yes, I agree, that if using katex docs rendering could be improved, it is something to do. Thanks @ydcjeff !
> 
> cc @trsvchn

Yes! I like it and it looks great! :)
