### ISSUE TITLE
Nightly releases are failing

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1580]
Currently, nightly releases are not upload due to issue from pytorch side:
- https://github.com/pytorch/ignite/runs/1775345299?check_suite_focus=true

```
conda install -y pytorch torchvision cpuonly -c pytorch-nightly
...
The following NEW packages will be INSTALLED:
pytorch            pytorch-nightly/linux-64::pytorch-1.8.0.dev20210124-py3.7_cuda11.0.221_cudnn8.0.5_0
...
Error with archive /opt/conda/pkgs/pytorch-1.8.0.dev20210124-py3.7_cuda11.0.221_cudnn8.0.5_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nSeek failed
```

We can either wait until they fix it for python 3.7 or we can also update conda python to 3.8:
- https://github.com/pytorch/ignite/blob/master/.github/workflows/binaries-nightly-release.yml
- https://github.com/pytorch/ignite/blob/master/.github/workflows/binaries-release.yml

=> I think we can update

**Comment by ydcjeff** [comment]
@vfdev-5 I think the main issue is from https://github.com/pytorch/pytorch/issues/49375
The PR I sent can't fix it, I think.
But we are installing with cpu version, why gpu version got downloaded? Any clue?

**Comment by vfdev-5** [comment]
yes, that's true. I was pointed out also to that link but as far as I understood it is related to 

> so you're running into that conda bug, but there's an issue with feature selection. Packaging is so much fun:)

Manually, I checked that I could install nightly version for py3.8 and py3.6, so probably it is enough for now.

**Comment by ydcjeff** [comment]
Thanks for confirming!
