### ISSUE TITLE
`to_onehot` can't be torchscripted

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/ignite#1584]
## 🐛 Bug description

I need to do one hot conversion and I use `ignite.utils.to_onehot`, but when I try to torchscript the model, it occurs a `RuntimeError`. Stacktrace:
```py
RuntimeError: 
cannot statically infer the expected size of a list in this context:
  File "/usr/local/lib/python3.6/dist-packages/ignite/utils.py", line 59
    input's device`.
    """
    onehot = torch.zeros(indices.shape[0], num_classes, *indices.shape[1:], dtype=torch.uint8, device=indices.device)
                                                        ~~~~~~~~~~~~~~~~~ <--- HERE
    return onehot.scatter_(1, indices.unsqueeze(1), 1)
'to_onehot' is being compiled since it was called from 'SLP.forward'
  File "<ipython-input-3-0f76d1651906>", line 12
    def forward(self, x):
        x = to_onehot(x, 10)
        ~~~~~~~~~~~~~~~~~~~ <--- HERE
        return self.l1(x)
```

## Environment
Colab

## Reproducible Link
https://colab.research.google.com/drive/13mWdz9sGXvAHgKd3vtp5I6Y-gZDRlNAd?usp=sharing

**Comment by vfdev-5** [comment]
Thanks for reporting @ydcjeff ! Let's what can be done in this case...

**Comment by vfdev-5** [comment]
Here is how it can be implemented.
```python
def to_onehot(indices: torch.Tensor, num_classes: int) -> torch.Tensor:
    new_shape = (indices.shape[0], num_classes) + indices.shape[1:]
    onehot = torch.zeros(new_shape, dtype=torch.uint8, device=indices.device)
    return onehot.scatter_(1, indices.unsqueeze(1), 1)
```
@ydcjeff if you'd like to fix it, please send a PR :)

**Comment by ydcjeff** [comment]
If anyone want to fix it, please go ahead
If not, I can send a PR later.

**Comment by ydcjeff** [comment]
@vfdev-5 we should start add tests for the functions or classes that could be used inside a nn.Module.
What do you think?

**Comment by vfdev-5** [comment]
We can start also doing that. Thanks for the suggestion! I'm wondering if there is a lot of functions like that which could be used inside nn.Module ?

**Comment by vfdev-5** [comment]
@Devanshu24 would you like to fix this issue according to the discussion ?

**Comment by ydcjeff** [comment]
Currently, I am seeing only certain functions from `ignite.utils` which input is tensor.

**Comment by Devanshu24** [comment]
> @Devanshu24 would you like to fix this issue according to the discussion ?

I would love to, I will go through your conversion in a little more detail (have gone through once). I think I will be able to work on it
