### ISSUE TITLE
pre-commit failing due to python version

### ISSUE THREAD

**Issue by Devanshu24** [pytorch/ignite#1590]
## 🐛 Bug description
The `CONTRIBUTING.md` file suggests creating a `conda` environment using the following line
https://github.com/pytorch/ignite/blob/7a872123ae607c5a05bf4e717fbb21ff52f9b8c0/CONTRIBUTING.md#L41
which defaults to version `3.9.1` as of now

However, the `pre-commit-config.yaml` file has a flag in the `black` configuration to set the python version to `3.7` (see below)
https://github.com/pytorch/ignite/blob/7a872123ae607c5a05bf4e717fbb21ff52f9b8c0/.pre-commit-config.yaml#L31

This is causing pre-commit to fail when trying to commit with the following error
```sh
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/python', '-mvirtualenv', '/home/think__tech/.cache/pre-commit/repom8oih2jb/py_env-python3.7', '-p', 'python3.7')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7'
    
stderr: (none)
```
I am not very familiar with black. However, changing the `pre-commit-config.yaml` config file to show `language_version: python3`  does work.

**Comment by vfdev-5** [comment]
Thanks for pointing out this @Devanshu24 ! Let's update CONTRIBUTING guide with `python=3.8` and pre-commit file as well.

**Comment by Devanshu24** [comment]
Okay, on it!
