### ISSUE TITLE
[Feature] validate_every_epoch may take integer

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#16]
Hi, 
A feature proposition to change a little bit the behaviour of `validate_every_epoch` [here](https://github.com/pytorch/ignite/blob/master/ignite/trainer.py#L180) and accept an integer and run validation every k epoch. What do you think about this ?

HTH

**Comment by alykhantejani** [comment]
This behaviour could also be achieved by handlers, as well as for running every x iterations although  I'm not opposed to changing this

**Comment by alykhantejani** [comment]
After discussions in #35 and #27 I think there is some consensus on removing this parameter altogether and providing a convenient handler that calls `validate` and wraps the logic for doing this every x epochs/iterations (see #42). 

Closing this issue for now, let's redirect the conversation to #42
