### ISSUE TITLE
Defining trainers and evaluators

### ISSUE THREAD

**Issue by etetteh** [pytorch/ignite#1608]
If I have a training step that takes a different form from the inferencing step, and I have defined these functions separately, 
```
def train_step(e, b):
    ...
    ...
    return batch_loss
trainer = Engine(train_step)
```
and
```
def infer_step(e, b):
    ...
    return batch_loss
evaluator = Engine(infer_step)
```
do I still need to define `create_supervised_trainer` and `create_supervised_evaluator`?
 If yes, do I need to define
```
def run_traiin(engine):
    train_evaluator.run(train_loader)
```
```
def run_validation(engine):
    infer_evaluator.run(valid_loader) 
```
Do I need to do
`trainer.add_event_handler(Events.EPOCH_STARTED(every=1), run_train)`
`evaluator.add_event_handler(Events.EPOCH_STARTED(every=1), run_validation)`

I am a bit confused here.

Or I can do
`@trainer.on(Events...)`
add the evaluation execution here

**Comment by vfdev-5** [comment]
Both ways work :)

**Comment by etetteh** [comment]
Just quick question, instead of opening a new question. Apart from distributed training, is there a way to make ignite train faster?

**Comment by vfdev-5** [comment]
In general case, it is better to profile the training to understand where is the bottleneck. If the model is small, I/O can be a bottleneck, then increasing number of workers could prepare faster the batch... Maybe, caching of read datapoints before dataaug could also help with slow reading from disk. Using SSD is somehow suggested to improve I/O....
In practice, please try to use https://pytorch.org/ignite/master/contrib/handlers.html#ignite.contrib.handlers.time_profilers.HandlersTimeProfiler (currently available with in nightly version: `pip install --upgrade --pre pytorch-ignite` and in the stable v0.4.3 coming this week) and see where trainer engine passes most of the time.

**Comment by etetteh** [comment]
Thanks, and you've been of great help. Wish I could contact you for a discussion via email.
I will check the profiling. My images are 224X224, and I guess that's also a reason
I installed from the repo.

**Comment by vfdev-5** [comment]
@etetteh you can reach out to me at discord: vfdev-5 #4458 or via the email (avoiding basics bots, to get the email, please, run `git log -1` on the cloned repository).

**Comment by etetteh** [comment]
Sure I will and I understand. Thanks
