### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1615]
## 🐛 Bug description

Using pytorchignite/hvd-apex-vision

```
python -c "import cv2"
> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

Same for vision and apex-vision images:
```
docker run --rm -it pytorchignite/apex-vision python -c "import cv2"
docker run --rm -it pytorchignite/vision python -c "import cv2"
```

## Environment

 - PyTorch Version (e.g., 1.4):
 - Ignite Version (e.g., 0.3.0):
 - OS (e.g., Linux):
 - How you installed Ignite (`conda`, `pip`, source):
 - Python version:
 - Any other relevant information:

cc @fco-dv

**Comment by vfdev-5** [comment]
A fix could be to install `opencv-python-headless` and not `opencv-python`. It would be nice to add a test after building the image: `python -c "import cv"`.

**Comment by fco-dv** [comment]
Thanks for the hints @vfdev-5 !

**Comment by net777oz** [comment]
> A fix could be to install `opencv-python-headless` and not `opencv-python`. It would be nice to add a test after building the image: `python -c "import cv"`.

Got damn good person, U saved me.
