### ISSUE TITLE
VOC example is broken

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1616]
## 🐛 Bug description

This PR https://github.com/pytorch/ignite/pull/1605 breakes Pascal VOC example due to bad import:

```python
import torch
from apex import amp
from dataflow.datasets import VOCSegmentationOpencv  # <---- imported before sys.path.insert
from py_config_runner.config_utils import TRAINVAL_CONFIG, assert_config, get_params
from py_config_runner.utils import set_seed
from utils import exp_tracking  # <---- imported before sys.path.insert
from utils.handlers import predictions_gt_images_handler  # <---- imported before sys.path.insert

...

# Adds "code" folder to python path
sys.path.insert(0, Path(__file__).parent.parent.as_posix())
```

## Environment

 - PyTorch Version (e.g., 1.4):
 - Ignite Version (e.g., 0.3.0):
 - OS (e.g., Linux):
 - How you installed Ignite (`conda`, `pip`, source):
 - Python version:
 - Any other relevant information:

**Comment by sparkingdark** [comment]
is this up @vfdev-5

**Comment by vfdev-5** [comment]
@sparkingdark unfortunately this one is for myself as it is a bit situation we have with this ref example.

**Comment by sparkingdark** [comment]
I see it causing from previous pull req.

**Comment by vfdev-5** [comment]
@sparkingdark I answered you there, please see https://github.com/pytorch/ignite/discussions/1603#discussioncomment-344799

Currently, we do not have any "good first issue", but you can check the list of "help wanted" issues like : 
- https://github.com/pytorch/ignite/issues/829
- https://github.com/pytorch/ignite/issues/1415
Others could be more bit tricky.

Maybe, you can try even fixing this issue by inspecting https://github.com/pytorch/ignite/issues/1616 PR and try to check if this is an issue with `isort` and could be fixed by reordering the imports...

Let me know about your choice.

**Comment by sparkingdark** [comment]
@vfdev-5 I see that there is different apex project exists like nvidea one,i used this to install `apex` library 

```
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --disable-pip-version-check --no-cache-dir ./
```
But after that I got this error can you tell me which specific package need to install regarding dataflow

```
╰─ python3 voc.py         
Traceback (most recent call last):
  File "voc.py", line 3, in <module>
    from dataflow.datasets import VOCSegmentationOpencv  # <---- imported before sys.path.insert
ModuleNotFoundError: No module named 'dataflow'
```

**Comment by vfdev-5** [comment]
@sparkingdark here `dataflow` is a local module which was wrongly placed before `sys.path.insert` line. As I said [before](https://github.com/pytorch/ignite/issues/1616#issuecomment-774495099) the issue with isort and reordering.

**Comment by sparkingdark** [comment]
Okay so you are saying that just need to test proper ordering and import can solve this issue.

**Comment by vfdev-5** [comment]
If you ask where this `dataflow` module, it is here : https://github.com/pytorch/ignite/tree/master/examples/references/segmentation/pascal_voc2012/code/dataflow

**Comment by sparkingdark** [comment]
Thanks I will try to reproduce it.

**Comment by sparkingdark** [comment]
I try to reproduce the issue install the miniconda for this purpose,after that created a file containing the following code 

```python3
import torch
from apex import amp
from code.dataflow.datasets import VOCSegmentationOpencv  # <---- imported before sys.path.insert
from py_config_runner.config_utils import TRAINVAL_CONFIG, assert_config, get_params
from py_config_runner.utils import set_seed
from code.utils import exp_tracking  # <---- imported before sys.path.insert
from code.utils.handlers import predictions_gt_images_handler  # <---- imported before sys.path.insert

# Adds "code" folder to python path
sys.path.insert(0, Path(__file__).parent.parent.as_posix())
```
This is error I got...
```
╰─ /home/debo/miniconda3/bin/python /home/debo/ignite/examples/references/segmentation/pascal_voc2012/vcc.py
Traceback (most recent call last):
  File "/home/debo/ignite/examples/references/segmentation/pascal_voc2012/vcc.py", line 6, in <module>
    from code.utils import exp_tracking  # <---- imported before sys.path.insert
  File "/home/debo/ignite/examples/references/segmentation/pascal_voc2012/code/utils/exp_tracking.py", line 9, in <module>
    import ignite.distributed as idist
ModuleNotFoundError: No module named 'ignite.distributed'
╭─   debo@pop-os    ~/ignite     testing                              1 ↵  3.94G    2.35    14:26:21   
╰─ 
```

**Comment by vfdev-5** [comment]
Looks like you have installed an old version. Try to install the latest one: 0.4.3

**Comment by sparkingdark** [comment]
which module?

**Comment by vfdev-5** [comment]
This is strange. Probably, something odd with your env setup. Try simply: `python -c "import ignite; print(ignite.__version__); import ignite.distributed"`

**Comment by sparkingdark** [comment]
I checkout the branch 0.4.3 and installed that.after that I got the setup error for pascal voc data 

```
Traceback (most recent call last):
  File "vcc.py", line 7, in <module>
    from code.utils import exp_tracking  # <---- imported before sys.path.insert
  File "/home/debo/ignite/examples/references/segmentation/pascal_voc2012/code/utils/exp_tracking.py", line 144, in <module>
    raise RuntimeError(
RuntimeError: No experiment tracking system is setup. Please, setup either MLflow, Polyaxon or ClearML. For more details see NOTES_*.md
```
probably error solved with bad import.I am doenloading the data.

**Comment by sparkingdark** [comment]
```python
from pathlib import  Path
import sys
import torch
from apex import amp
from code.dataflow.datasets import VOCSegmentationOpencv  # <---- imported before sys.path.insert
from py_config_runner.config_utils import TRAINVAL_CONFIG, assert_config, get_params
from py_config_runner.utils import set_seed
from code.utils import exp_tracking  # <---- imported before sys.path.insert
from code.utils.handlers import predictions_gt_images_handler  # <---- imported before sys.path.insert

# Adds "code" folder to python path
sys.path.insert(0, Path(__file__).parent.parent.as_posix())
```

run succesfully.

**Comment by vfdev-5** [comment]
I'm not sure if preprending `code.` is the correct solution. To ensure that you have to run the training as it is described in for example in `NOTES_MLflow.md` where `mlflow run` cmd line tool is used. Same for `NOTES_ClearML.md`...

**Comment by sparkingdark** [comment]
I don't imported code in path ,how can I do that export what to put = codes path, i don't understand that's why used clearml as per notes.

**Comment by vfdev-5** [comment]
@sparkingdark if you'd like to help with a fix for this issue, please follow the guideline above. Thanks.

**Comment by sparkingdark** [comment]
Okay
