### ISSUE TITLE
[docs] Make it clear in CONTRIBUTION.MD that distributed tests should be skipped on windows

### ISSUE THREAD

**Issue by ahmedo42** [pytorch/ignite#1619]
## 🚀 Feature

While running tests on windows I realized that the terminal freezes upon running distributed tests , until I found #1426 .
 should this be made clear in the docs ?

**Comment by vfdev-5** [comment]
@ahmedo42 thanks ! Yes, it would be nice to mention that !

Btw, if you are on Windows, would you be interested in working on this issue : https://github.com/pytorch/ignite/issues/1432
This could enable ignite distributed automatic setup and those tests, I think.

**Comment by ahmedo42** [comment]
I'll make a PR
regarding #1432 , I'm interested in making it work but I'll have to do some digging first , I'll let you know if I'm going to take it.
