### ISSUE TITLE
Got TypeError while running cifar10 example in google colab

### ISSUE THREAD

**Issue by sparkingdark** [pytorch/ignite#1623]
## 🐛 Bug description
While running the cifar10 example in google collab I got this error, can you tell me why I am getting this error?
```
2021-02-07 13:50:34,164 ignite.distributed.launcher.Parallel INFO: Initialized distributed launcher with backend: 'xla-tpu'
2021-02-07 13:50:34,165 ignite.distributed.launcher.Parallel INFO: - Parameters to spawn processes: 
	nproc_per_node: 8
	nnodes: 1
	node_rank: 0
	with_trains: True
2021-02-07 13:50:34,166 ignite.distributed.launcher.Parallel INFO: Spawn function '<function training at 0x7f4c104e5f28>' in 8 processes
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-45b7651d6263> in <module>()
----> 1 run(backend="xla-tpu", num_workers=12, nproc_per_node=8, with_trains=True)

3 frames
/usr/local/lib/python3.6/dist-packages/ignite/distributed/comp_models/xla.py in spawn(fn, args, kwargs_dict, nproc_per_node, nnodes, node_rank, backend, **kwargs)
    126                 args=(backend, fn, args, kwargs_dict),
    127                 nprocs=nproc_per_node,
--> 128                 **kwargs,
    129             )
    130 

TypeError: spawn() got an unexpected keyword argument 'with_trains'
```

link to the cell of the [collab](https://colab.research.google.com/drive/1E9zJrptnLJ_PKhmaP5Vhb6DTVRvyrKHx#scrollTo=vZxFcLZE9Xml&line=1&uniqifier=1)

One thing that can be improved more in [here](https://github.com/pytorch/ignite/tree/master/examples/contrib/cifar10#requirements) the all pip install can be written in one line instead of multiple lines or adding a requirements.txt would work in cifar10 example I think that will be great. 

## Environment

 - PyTorch Version (e.g., 1.4): 1.7+
 - Ignite Version (e.g., 0.3.0): current
 - OS (e.g., Linux):ubuntu google colab
 - How you installed Ignite (`conda`, `pip`, source): `pip`
 - Python version: 3.6
 - Any other relevant information: It's related to the example documentation cifar10.

tagging @vfdev-5  for better visibility

**Comment by vfdev-5** [comment]
Thank again for reporting @sparkingdark , yes I already fixed the notebook. If you'd like to check it again.

**Comment by sparkingdark** [comment]
Great I will recheck it.

**Comment by vfdev-5** [comment]
Closed the issue as solved

**Comment by sparkingdark** [comment]
Running the collab and it's totally fine with no error.
