### ISSUE TITLE
Images not rendered on PyPI

### ISSUE THREAD

**Issue by Devanshu24** [pytorch/ignite#1626]
## 📚 Documentation
The logo and other assets on the project README.md are not rendered on the PyPI page of [pytorch-ignite](https://pypi.org/project/pytorch-ignite/)
This is because PyPI does not read the repo for the images, and we'll have to use external links for the image. (reference [here](https://stackoverflow.com/questions/41983209/how-do-i-add-images-to-a-pypi-readme-that-works-on-github))
We could use the `https://raw.githubusercontent.com/*`  counterparts for the assets instead of specifying the path

By specifying the path, I mean the following
https://github.com/pytorch/ignite/blob/6753b19b74fd8d128188dd0a75b405d19aa515b5/README.md#L5

Just a suggestion, please ignore if it is unnecessary :)

**Comment by vfdev-5** [comment]
Thanks for the suggestion @Devanshu24 ! We kept it relative as fork modifications of these things can be seen directly in the fork and the PR.
There is also url for "assets/tldr/pytorch-ignite-teaser.gif" which is also relative.

Maybe, we could add "https://raw.githubusercontent.com/*" prefix here
https://github.com/pytorch/ignite/blob/6753b19b74fd8d128188dd0a75b405d19aa515b5/setup.py#L21

**Comment by Devanshu24** [comment]
To confirm if I understand it correctly, we could parse the contents of README and replace the relative paths to the URLs using python?

**Comment by vfdev-5** [comment]
Yes, it's an idea on how to try to have both features...
