### ISSUE TITLE
Use one_rank_only in ProgressBar and HandlersTimeProfiler

### ISSUE THREAD

**Issue by sdesrozis** [pytorch/ignite#1648]
## 🚀 Feature

The idea is to use the decorator `@one_rank_only` on attachment of `ProgressBar` and `HandlersTimeProfiler` 
```python
if idist.get_rank() == 0:
    ProgressBar(persist=False).attach(trainer, metric_names="all")
    HandlersTimeProfiler().attach(trainer)
```
could become
```python
ProgressBar(persist=False).attach(trainer, metric_names="all")
HandlersTimeProfiler().attach(trainer)
```

Methods `ProgressBar.log_message()`, `HandlersTimeProfiler.get_results()`, and `HandlersTimeProfiler.write_results()` should be compatible. I think it is already done by user who calls these methods only on the master rank. 

@vfdev-5 what do you think ?

**Comment by vfdev-5** [comment]
@sdesrozis this point is always bothering me as well. The problem why we didn't do that yet is due 
- to public methods inside loggers like ProgressBar (pbar), TensorboardLogger (writer) which could be potentially used to do things and should be also mocked somehow to do nothing and return other mocks for other procs > 0.
- mixing handlers that should be used with ``if idist.get_rank() == 0` and those that are distrib friendly can lead to a bad user experience.

**Comment by sdesrozis** [comment]
Ok I understand. I have suggested only for some specific handlers. I will handle this on my side.

I close this issue 😉
