### ISSUE TITLE
Create a footer on main docs site

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1649]
## 📚 Documentation

It would be helpful to enable a footer on the docs site: https://pytorch.org/ignite/ where we can keep current mentions like 
-  © Copyright 2021, PyTorch-Ignite Contributors.
- Built with Sphinx using a theme provided by Read the Docs. 

and should place a badge from https://www.netlify.com/press/#badges . For example, this one : 

  <a href="https://www.netlify.com">
    <img src="https://www.netlify.com/img/global/badges/netlify-light.svg" alt="Deploys by Netlify" />
  </a>

I assume that we can tweak footer part from https://github.com/pytorch/ignite/blob/master/docs/source/_templates/layout.html#L304

@trsvchn could you please help us with this improvement ?

**Comment by trsvchn** [comment]
@vfdev-5 Absolutely! I would love to do that!

**Comment by vfdev-5** [comment]
Thanks a lot @trsvchn !
