### ISSUE TITLE
 No module named 'ax' in Cifar10_ax_hyperparma_tuning notebook

### ISSUE THREAD

**Issue by sparkingdark** [pytorch/ignite#1651]
## 🐛 Bug description

While Execute this [notebook](https://github.com/pytorch/ignite/blob/master/examples/notebooks/Cifar10_Ax_hyperparam_tuning.ipynb) in google colab I got the following error:

```
ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-20-038803be34bd> in <module>()
      1 from matplotlib import axes as ax
----> 2 from ax.plot.contour import plot_contour
      3 from ax.plot.trace import optimization_trace_single_method
      4 from ax.service.managed_loop import optimize
      5 from ax.utils.notebook.plotting import render, init_notebook_plotting

ModuleNotFoundError: No module named 'ax'
```
Link to the cell is [here](https://colab.research.google.com/drive/1-y9NZbpa96Ps8BDzeqJsxNCyhKMjOjUn#scrollTo=Yt3W860Hfaqw&line=1&uniqifier=1)

Tagging @vfdev-5 

## Environment

- PyTorch Version (e.g., 1.4):`1.7.0+cu101`
- Ignite Version (e.g., 0.3.0): `0.4.3`
- OS (e.g., Linux): Ubuntu
- How you installed Ignite (`conda`, `pip`, source):pip
- Python version:3.6
- Any other relevant information: Google colab

**Comment by vfdev-5** [comment]
Yes, looks like the first cell is missing `ax` to be installed. Maybe, like that:
```bash
!pip install pytorch-ignite tensorboardX ax-platform
```

**Comment by sparkingdark** [comment]
Yes I added that and now works fine.
