### ISSUE TITLE
Automatically create an issue if cron jobs fail

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/ignite#1659]
## 🚀 Feature
We currently have two cron jobs, `pytorch-version-tests` and `binaries-nightly-release`.
While doing #1589 , if I fail to skip some tests, that would fail in `pytorch-version-tests`, but not on master.
And, the failed cron jobs notifications will only be pushed to repo maintainers, not PR authors.
Since maintainers are usually track issue/pr via labels/milestones/projects, only a few look at github notifications.

Past example: #1580 

So why not create an issue automatically if cron jobs (2 currently) fail?
And, we can mention PR authors directly on that issues, less burden on maintainers and we should automate what can be automated, I think.

Inspires by : https://github.com/pytorch/vision/blob/master/.github/workflows/tests-schedule.yml

Relate actions:
- https://github.com/marketplace/actions/create-issue-from-file
- https://github.com/marketplace/actions/create-an-issue

**Comment by vfdev-5** [comment]
Yes, makes sense! We can try that. Maybe a tricky part is to cc PR authors in case they really break the builds. Like now failure is PR unrelated...

**Comment by ydcjeff** [comment]
Sometimes PR authors break the tests, sometimes new pytorch version does.
So, I think it's ok not to cc PR authors (leave as it is) and pining authors can also be hard.
But, such an issue can be a good first issue for new contributors.
