### ISSUE TITLE
Fix code formatting github action

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1660]
## 🐛 Bug description

Currently, auto code formatting GA: https://github.com/pytorch/ignite/actions/workflows/code-style.yml
does not on forks and fails while try to commit/push the fix to the fork. This gives a misleading error to the user without helping how to solve it. Currently this action is disabled.

The idea is to find out what is the cause of the failure and fix it if possible.

## Environment

- PyTorch Version (e.g., 1.4):
- Ignite Version (e.g., 0.3.0):
- OS (e.g., Linux):
- How you installed Ignite (`conda`, `pip`, source):
- Python version:
- Any other relevant information:

**Comment by Devanshu24** [comment]
Hi @vfdev-5 !
I could try fixing this, the problem is the user has to enable GitHub actions on their fork (which GitHub disables by default)
We could add a line in CONTRIBUTING.md suggesting if you want to use auto formating please enable GitHub actions on your fork. :)

**Comment by vfdev-5** [comment]
@Devanshu24 thanks for the info! Do you know if still there is a way to use/skip this action if user disabled actions ?

**Comment by Devanshu24** [comment]
I do not at this moment, but I'll look it up! :)

**Comment by trsvchn** [comment]
@vfdev-5 

Actions are disabled by default for forked repos (as @Devanshu24 already mentioned). When you're creating a PR to upstream repo (`pytorch/ignite`) it triggers worklfow from that repo (`pytorch/ignite`).

If you want to use GH Actions you need to toggle them manually for your fork. Then, if you're creating PR or pushing to the fork repo (`user/ignite`) it triggers local workflow (workflow file from the fork repo will be used).

So, I want to clarified, what kind of fail do we have 

> while try to commit/push the fix to the fork

do we assume that actions already activated for that fork?

**Comment by trsvchn** [comment]
I've made some tests. Here #1663 you can see a PR with autopep8 fix made for a dummy python file in a fork w/failure. so, it works as expected.

But the most interesting thing happens when you're trying to add new commits to that branch, it triggers 2 same workflows simultaneously: one for push and one for pr:

![Screenshot from 2021-02-21 15-58-01](https://user-images.githubusercontent.com/30748114/108627359-cfae0180-745d-11eb-9f7e-596d5a26ac06.png)

**Comment by trsvchn** [comment]
so we have double triggering here, and there is no way to fix it:

> I’m afraid that you cannot do this directly.  However, you can trigger only on pushes to master, or pull requests to master.  This will prevent builds from happening twice when somebody opens a pull request against master and then pushes updates to their branch.  For example: ...

Full: https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662

**Comment by trsvchn** [comment]
well, setting this really triggers only one workflow:

```yml
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
```

But, again it will work against master branch

**Comment by trsvchn** [comment]
I think the possible solution might be to create two separate workflows file:
main code-style with:
```yml
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
```

and another for local/forks events, only for push events

```yml
on:
  push:
    branches:
    - "!master"
```

But we need to discuss it (and verify it)

**Comment by vfdev-5** [comment]
@trsvchn thanks for inspecting that ! 

> What kind of error do we have? I am going to reproduce it in my fork.

Here is a log where GA has failed : 
- https://github.com/pytorch/ignite/runs/1936462365?check_suite_focus=true
- https://github.com/pytorch/ignite/actions/workflows/code-style.yml

It is `stefanzweifel/git-auto-commit-action@v4` which fails if there are files to format the code.

**Comment by trsvchn** [comment]
@vfdev-5 ok, I see, it's different. Thanks, I will try to play that dummy PR to reproduce exactly that error. But, auto-formatting for forked repo with enabled actions works fine.

**Comment by trsvchn** [comment]
After quick view at the `stefanzweifel/git-auto-commit-action@v4` I found this recomendation:

You must use action/checkout@v2 or later versions to checkout the repository. In non-push events, such as pull_request, make sure to specify the ref to checkout:

```yml
- uses: actions/checkout@v2
  with:
    ref: ${{ github.head_ref }}
```

**Comment by vfdev-5** [comment]
Thanks for the info and the link. Shouldn't we do like in the example: https://github.com/stefanzweifel/git-auto-commit-action#example-2 but adapted for us:
- add pull_request_target

We can inspect what happens in both cases: 
a) GitHub Action is enabled on the forked repository. 
b) GitHub Action is disabled on the forked repository.

**Comment by trsvchn** [comment]
@vfdev-5 yes, I think we can start from that

**Comment by vfdev-5** [comment]
Let's close this issue as solved.

Current state of the thing is:
- it is unsafe to use `pull_request_target` and bash script to run formatting

A solution could be to add specific label condition to run unsafe pipeline.
