### ISSUE TITLE
add automatic mixed precision in create_supervised_evaluator

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/ignite#1670]
## 🚀 Feature

Like #1235, add automatic mixed precision (both torch.cuda.amp) in `create_supervised_evaluator`.
PR that can reference: #1589 
Related issue: #1666

**Comment by ydcjeff** [comment]
How shall we call them? `supervised_evaluation_step_*` or `supervised_validation_step_*`?

**Comment by vfdev-5** [comment]
`supervised_evaluation_step_*` is good, IMO

**Comment by Moh-Yakoub** [comment]
@ydcjeff  Are you currently working on this one? If not I'd like to give it a shot

**Comment by ydcjeff** [comment]
@Moh-Yakoub I amnot working on this.
Feel free to go ahead
