### ISSUE TITLE
add cohen kappa in contrib.metrics module

### ISSUE THREAD

**Issue by KickItLikeShika** [pytorch/ignite#1673]
## 🚀 Feature
cohen's kappa is widely used in kaggle competitions, i think it would be great to add it in `ignite.contrib.metrics`

**Comment by vfdev-5** [comment]
@KickItLikeShika thanks for a FR, can you provide few links on where it is used etc.

Few links from our issues tracker : 
- https://github.com/pytorch/ignite/issues/551
- https://github.com/pytorch/ignite/pull/924
    - https://github.com/Minyus/pipelinex/blob/master/src/pipelinex/extras/ops/ignite/metrics/cohen_kappa_score.py

**Comment by KickItLikeShika** [comment]
Competitions that use cohen's kappa for evaluation:
- https://www.kaggle.com/c/aptos2019-blindness-detection/overview/evaluation
- https://www.kaggle.com/c/petfinder-adoption-prediction/overview/evaluation

For more details about the Cohen's Kappa and Weighted Cohen's Kappa:
- https://www.real-statistics.com/reliability/interrater-reliability/weighted-cohens-kappa

**Comment by KickItLikeShika** [comment]
@vfdev-5 so what do you think? should i start working on it?

**Comment by vfdev-5** [comment]
@KickItLikeShika thanks for the links!  How would you like to implement it ?

**Comment by KickItLikeShika** [comment]
I think just like [average precision](https://github.com/pytorch/ignite/blob/master/ignite/contrib/metrics/average_precision.py) is implemented would be good, what do you think?

**Comment by vfdev-5** [comment]
OK, let's do like that
