### ISSUE TITLE
Adding Jaccard index for metrics

### ISSUE THREAD

**Issue by Moh-Yakoub** [pytorch/ignite#1680]
## 🚀 Feature

I propose implementing Jaccard index (https://en.wikipedia.org/wiki/Jaccard_index) for ignite metrics. I believe it should be doable given we already support confusion matrices.

**Comment by vfdev-5** [comment]
@Moh-Yakoub thanks for FR! We already provide [IoU](https://pytorch.org/ignite/v0.4.3/metrics.html#ignite.metrics.IoU) which is the same as Jaccard Index, right ?

I agree that we can add a shortcut for IoU as JaccardIndex for those who search it like that and not as IoU ...

**Comment by Moh-Yakoub** [comment]
I agree most likely people will start looking for Jaccard.
I will add a shortcut for it now then.
