### ISSUE TITLE
Remove 1024 limit for str on collective ops

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1697]
## 🚀 Feature

Currently, if we have a limitation of 1024 chars for str input on collective ops:

https://github.com/pytorch/ignite/blob/314b87f490eeb812bca8b0b4911a4a60a847c010/ignite/distributed/comp_models/base.py#L92-L95

The idea is to remove this limitation. We can do that as following:
- for all inputs as str, we can first gather all lenghts
- find the max lengths
- pad the input to the max lenghts + add input length value (as it is done currently)
- perform collective op

Bug ref:  https://github.com/Project-MONAI/MONAI/issues/1633

**Comment by sdesrozis** [comment]
https://github.com/pytorch/ignite/blob/314b87f490eeb812bca8b0b4911a4a60a847c010/ignite/distributed/comp_models/base.py#L185

Maybe a fix has to be done here.
