### ISSUE TITLE
Adding Classification report utility function

### ISSUE THREAD

**Issue by Moh-Yakoub** [pytorch/ignite#1715]
## 🚀 Feature

I'd like to add the classification report utility to ignite. Similar to the same functionality in scikit-learn https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html#sklearn.metrics.classification_report

**Comment by vfdev-5** [comment]
@Moh-Yakoub thanks for a FR! May be helpful. I think this can be done as a helper method with attaching precision, recall, f1 and returning a dictionary with [MetricsLambda](https://pytorch.org/ignite/metrics.html#ignite.metrics.MetricsLambda).

**Comment by Moh-Yakoub** [comment]
Great, I will start doing that!
