### ISSUE TITLE
[flake8] remove F401 in `ignite`

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/ignite#1725]
# Improvement
Update the code base by removing unused imports in ignite. This can be easily found by removing `F401` in `setup.cfg`.
Previous PRs are done for `examples` in #1703 and `tests` in #1707 
Only `ignite` package left now. Modules TBD:
- [x] `ignite.base`
- [x] `ignite.contrib.engines`
- [x] `ignite.contrib.handlers`
- [x] `ignite.contrib.metrics`
- [x] `ignite.distributed`
- [x] `ignite.engine`
- [x] `ignite.handlers`
- [x] `ignite.metrics`
- [x] `ignite._utils`
- [x] `ignite.utils`

How to proceed (thanks to @Moh-Yakoub for the details):

- removed F401 from setup.cfg
- run flake8 on ignite/metrics
- remove unused imports
- revert setup.cfg

**Comment by Moh-Yakoub** [comment]
@ydcjeff  are you currently working on this?

**Comment by vfdev-5** [comment]
@Moh-Yakoub this isssue can be tackled by multiple persons. Just say which part you'd like to work on and go ahead. Thanks for asking!

**Comment by Moh-Yakoub** [comment]
> @Moh-Yakoub this isssue can be tackled by multiple persons. Just say which part you'd like to work on and go ahead. Thanks for asking!

Thanks a lot @vfdev-5 for the reply. I can start with metrics ` ignite.metrics`

**Comment by trsvchn** [comment]
What about `_utils.py`, we need that imports for compatibility, right?
