### ISSUE TITLE
[bug] Adding exception handler results in errors

### ISSUE THREAD

**Issue by elanmart** [pytorch/ignite#175]
This code [here](https://github.com/pytorch/ignite/blob/master/ignite/engine/engine.py#L178-L180) means, that if user chooses to ignore the exception, `_run_once_on_dataset` will return `None`. This will result in an error [here](https://github.com/pytorch/ignite/blob/master/ignite/engine/engine.py#L207)

**Comment by alykhantejani** [comment]
hmm, what would be the preferred result here `None, None, None`?

**Comment by elanmart** [comment]
Oh, I forgot to tag this issue in the PR (https://github.com/pytorch/ignite/pull/176) I decided to return the time, even if exception occurred.

**Comment by alykhantejani** [comment]
Nice - fixed in #176
