### ISSUE TITLE
Implementation of ReduceLROnPlateau scheduler 

### ISSUE THREAD

**Issue by ahmedo42** [pytorch/ignite#1754]
## 🚀 Feature

While there might be some workarounds in using `ReduceLROnPlateau` with ignite's optimizer , it would be nicer to have a standalone feature like other schedulers in contrib.

[Relevant issue and code sample](https://github.com/pytorch/ignite/issues/462#issuecomment-771907302).

**Comment by sadra-barikbin** [comment]
Hi there, 
I make this feature's PR. Is it OK? What else should I do?

**Comment by sdesrozis** [comment]
@ahmedo42 It exists the class `LRScheduler` to wrap PyTorch schedulers. Out of curiosity, have you tried it? And if so, why doesn't it work on this case? Thanks a lot for the feedback!

**Comment by sadra-barikbin** [comment]
@sdesrozis `LRScheduler` does not support `param_group_index` and also It's not sufficient to just wrap a PyTorch's `ReduceOnPlateau`, but one should also feed its `step` function with a metric value.
