### ISSUE TITLE
improve documentation search results

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/ignite#1766]
## 📚 Documentation
Currently searching docs on duckduckgo and google results in poor search results.
DuckDuckGo: search precision metrics show source code result first while third one is a correct page.

![Screen Shot 2021-03-10 at 22 57 27](https://user-images.githubusercontent.com/32727188/110663247-a7135f00-81f4-11eb-90ce-ef262a412b7c.png)

Google: nearly same to google as well tho 2nd one is correct page.

![Screen Shot 2021-03-10 at 22 58 08](https://user-images.githubusercontent.com/32727188/110663285-ac70a980-81f4-11eb-9aac-663f747a11bb.png)

For Algolia Docsearch: source code are shown first then correct ones.

![Screen Shot 2021-03-10 at 23 04 31](https://user-images.githubusercontent.com/32727188/110663700-125d3100-81f5-11eb-9d8e-0a21feaa7faf.png)

---

This might be due to title of the page generated by `_modules` folder.
To improve this, we have the following options
1. use `autosummary` and generate the docs for only classes or functions or both just like [nn.Module](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module)
2. put heading 2 to every classes and functions before `autoclass`, `autofunction`
3. make `_modules` not to be indexed by search engines and algolia

Here's my suggestions:
- For search engine results, I think 1 > 2 > 3. IMO generating long docstring classes and functions to separate page would result better search result by search engines and docs readability (sometimes I got lost in long docstrings and methods). **generating such pages have a downside, we can't specify `:members:` in `.. autoclass` manually** since it will be already included in template. See [pytorch template](https://github.com/pytorch/pytorch/blob/master/docs/source/_templates/classtemplate.rst).
- For algolia docsearch, 1 == 2 > 3. Algolia docsearch searches h1-h6, so adding heading to every classes and functions can result better in-docs search.

What do you think ? @vfdev-5 @sdesrozis

**Comment by vfdev-5** [comment]
@ydcjeff thanks for pointing out this! Very interesting topic to think about. I think your suggestions make a lot of sense. Would you like to draft a PR for that ?
