### ISSUE TITLE
Attribute errors in TextCNN.ipynb

### ISSUE THREAD

**Issue by cozek** [pytorch/ignite#1777]
## 🐛 Bug description
I was trying to learn how to use ignite so I tried running one of the example notebooks.
While running the notebook [TextCNN.ipynb] (https://github.com/pytorch/ignite/blob/master/examples/notebooks/TextCNN.ipynb) in google colab,
the following code results in error.

```python
from torchtext import data
TEXT = data.Field(lower=True, batch_first=True)
LABEL = data.LabelField(dtype=torch.float)
```

```python
AttributeError                            Traceback (most recent call last)
<ipython-input-43-b883b5f642a4> in <module>()
      1 device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
      2 
----> 3 TEXT = data.Field(lower=True, batch_first=True)
      4 LABEL = data.LabelField(dtype=torch.float)
      5 

AttributeError: module 'torchtext.data' has no attribute 'Field'
```

I think, this is because the `Field` and `LabelField` have been move to `legacy` in torchtext==0.9.0

This also causes the following to error out.
```python
train_iterator, valid_iterator, test_iterator = data.BucketIterator.splits((train_data, valid_data, test_data), 
                                                                           batch_size=32,
                                                                           device=device)
```
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-46-b1d7e1f60f0d> in <module>()
----> 1 train_iterator, valid_iterator, test_iterator = data.BucketIterator.splits((train_data, valid_data, test_data), 
      2                                                                            batch_size=32,
      3                                                                            device=device)

AttributeError: module 'torchtext.data' has no attribute 'BucketIterator'
```

Can be easily reproduced by running the said notebook in Colab.

## Environment

- PyTorch Version (e.g., 1.4): 1.8.0+cu101
- Ignite Version (e.g., 0.3.0): 0.4.4
- OS (e.g., Linux): Google Colab
- How you installed Ignite (`conda`, `pip`, source):
- Python version: Python 3.7.10
- Any other relevant information: 
 
Can be easily fixed by importing the `legacy` module. This allows minimal changes to the tutorial.
I successful ran the entire notebook using the `legacy` module.
Or rewrite the code that uses legacy code using latest API (if any) and probably rewrite some parts of the tutorial.

```
from torchtext import data,legacy

TEXT = legacy.data.Field(lower=True, batch_first=True)
LABEL = legacy.data.LabelField(dtype=torch.float)

train_data, test_data = legacy.datasets.IMDB.splits(TEXT, LABEL, root='/tmp/imdb/')
train_data, valid_data = train_data.split(split_ratio=0.8, random_state=random.seed(SEED))
```

I am willing to make a PR to work on this. Just let me know how to proceed.

**Comment by vfdev-5** [comment]
Thanks for reporting this bug @cozek !

> I am willing to make a PR to work on this. Just let me know how to proceed.

Sounds great ! If you can also update the example to use the latest torchtext API, it would be perfect.

Please, take a look at our [CONTRIBUTING guide](https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md).
Here, the fix is about changing the notebook, so, there is no need to run unit tests etc... Just modify the notebook and rerun on the Colab. Let us know if something is unclear there.

**Comment by trsvchn** [comment]
@vfdev-5 what do you think about a kind of "smoke tests" for our examples? E.g. we can create a workflow that runs/tests our examples vs latest stable versions of third party dependencies. We can run it weekly or smth.
I don't know how to do it right now, but I can check.

**Comment by vfdev-5** [comment]
@trsvchn I think this would be awesome !

**Comment by trsvchn** [comment]
Great! I'll check this idea!
