### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by KickItLikeShika** [pytorch/ignite#1786]
We have improved most of our tests in `ignite.contrib.metrics`, and some other tests in `ignite.metrics`,  `ignite.contrib.metrics.regression`. But there more tests to update. We need to remove duplicate code, generalize tests and add distributed tests if they are not existed. These tests have been updated recently, making something similar to them would be good: [AveragePrecsision](https://github.com/pytorch/ignite/blob/master/tests/ignite/contrib/metrics/test_average_precision.py), [CohenKappa](https://github.com/pytorch/ignite/blob/master/tests/ignite/contrib/metrics/test_cohen_kappa.py), [RocAUC](https://github.com/pytorch/ignite/blob/master/tests/ignite/contrib/metrics/test_roc_auc.py).

**Comment by KickItLikeShika** [comment]
I think we can close this now, right? @vfdev-5

**Comment by vfdev-5** [comment]
@KickItLikeShika I think we can close it once we solved the issue with AP revealed here: 
- https://github.com/pytorch/ignite/pull/1808
- https://github.com/pytorch/ignite/pull/1808/checks?check_run_id=2289971532#step:10:935

**Comment by vfdev-5** [comment]
We can close this issue as required PR and the failing test were done.
