### ISSUE TITLE
Support for max/min ops for `sync_all_reduce`

### ISSUE THREAD

**Issue by KickItLikeShika** [pytorch/ignite#1813]
Running the distributed tests while `world_size > 1` makes the tests fail. I was trying to make the metric compatible with DDP with doing the same thing we have done with the other metrics but the results are different!
I tried to print out some things for a better understanding, everything seemed to be working fine (calculating the metric is very simple) but after doing `metric.compute()` returns a strange result! (even printing the values computed in `_update()` function seems fine!).

[Code snippet](https://gist.github.com/KickItLikeShika/fcd6a671cddbbfc7f787403c32fc792f)

**Comment by sdesrozis** [comment]
That is because your reduction must be a maximum and not a summation.

**Comment by KickItLikeShika** [comment]
@sdesrozis is that can be done the same decorator `sync_all_reduce`?

**Comment by sdesrozis** [comment]
The reduction used is a sum 
https://github.com/pytorch/ignite/blob/8fe6086456a9b81fc9db5840121796a3ed951eba/ignite/distributed/utils.py#L327

We have to extend the api

**Comment by KickItLikeShika** [comment]
@sdesrozis well, that can be done in a separate PR, i will work on it, Thanks!

**Comment by sdesrozis** [comment]
@KickItLikeShika Thank you.

**Comment by sdesrozis** [comment]
Otherwise, you can create a zero tensor of size world_size. Each process writes in the rank position. You reduce this tensor and compute the max.
