### ISSUE TITLE
GitHub Actions Workflow Improvements 

### ISSUE THREAD

**Issue by trsvchn** [pytorch/ignite#1836]
There are some elements in our CI that can be improved:

For example, `code-style.yml` starts very often in non-code updates. The same for `docs.yml` for non-docs.

`pytorch-version-tests.yml` fails to open the issue because of access problem:
https://github.com/pytorch/ignite/runs/2157534748?check_suite_focus=true#step:9:8

- [x] code-style
- [x] docs
- [x] unit-tests: https://github.com/pytorch/ignite/pull/1838#issuecomment-804796165

**Comment by vfdev-5** [comment]
@trsvchn why there was a message for the first contribution here ?

**Comment by trsvchn** [comment]
@vfdev-5 Yeah, I think its a bug and removed it.

**Comment by trsvchn** [comment]
But honestly, it worries me now

**Comment by trsvchn** [comment]
@vfdev-5 Because, It was my second issue, but the first issue is closed so there was no open issue by me, is this what action call "first contribution"?

**Comment by vfdev-5** [comment]
Can you try that on a separate repo to see what it works exactly. For me "first contribution" is the first and only the first issue issue (same for PR).

**Comment by trsvchn** [comment]
Yes, exactly I'll try that!

**Comment by trsvchn** [comment]
@vfdev-5 I think I got it, I know what is happening.

According to action source code first contribution is:
you have no issues at all
```ts
        if (issues.length === 0) {
            return true;
        }
```
or current issue number less or equal to any of issue numbers (I am not familiar with TS): 
```ts
        for (const issue of issues) {
            if (issue.number < curIssueNumber && !issue.pull_request) {
                return false;
            }
        }
        return true;
```
I've checked the actions logs, and turned out that it added comment not on `issue: opened`, but on `issue: edited`.
In our case on issue: edit it was kind of `issue.number === curIssueNumber` (I hope I used right amount of "=" to express "equality" :) ) since issues already contains edited issue but it returns that `true` after the for-loop:

https://github.com/actions/first-interaction/blob/bd33205aa5c96838e10fd65df0d01efd613677c1/lib/main.js#L111

And that's why it treats it as first-time contrib.

But in updated version our workflow (#1835) is going to start only on issue:opened, so we expect this branch:
```ts
        if (issues.length === 0) {
            return true;
        }
```

**Comment by vfdev-5** [comment]
>  The same for docs.yml for non-docs.

@trsvchn this is misleading. We would like to rebuild the docs on master for example if a docstring in the code has been changed. We also update the docs on each commit to update master version...

**Comment by vfdev-5** [comment]
Let me know if I'm missing something in your description on what remains to do with docs.yml otherwise I think we can close this issue.

**Comment by trsvchn** [comment]
@vfdev-5 
Absolutely, docs is very tricky, docs is tightly connected with the repo code, its hard to find non-docs related parts, I was thinking about reducing the number of docs "dry runs" on pull_request by excluding `docker`, some GHA workflows, `tests` but I think its minor changes
