### ISSUE TITLE
Windows GPU test is skipping

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/ignite#1843]
## 🐛 Bug description

[Windows GPU tests are currently not running on master](https://app.circleci.com/pipelines/github/pytorch/ignite/1661/workflows/7cffc0a3-ac7b-4305-a291-f0de3b3c6978/jobs/4851/parallel-runs/0/steps/0-104)

**Comment by vfdev-5** [comment]
Thanks for reporting @ydcjeff !

**Comment by vfdev-5** [comment]
I think this is related to machine we are using on Circle CI: https://circleci.com/docs/2.0/configuration-reference/#available-windows-gpu-image which has CUDA 10.1 but we install pytorch with CUDA 11.1 support.

**Comment by vfdev-5** [comment]
I think we should do something like vision does here: https://github.com/seemethere/vision/blob/master/packaging/windows/internal/cuda_install.bat
- install cuda 11.1
