### ISSUE TITLE
AttributeError: module 'neptune' has no attribute 'OfflineBackend'

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1862]
## 🐛 Bug description

New release of neptune (`neptune_client-0.5.3` vs `neptune-client-0.5.2`) breaks compatibility with our CI and `NeptuneLogger`:

https://github.com/pytorch/ignite/pull/1834/checks?check_run_id=2174048638
```
AttributeError: module 'neptune' has no attribute 'OfflineBackend'
```

cc @jakubczakon

**Comment by jakubczakon** [comment]
Thanks for pointing it out @vfdev-5!

@pitercl can you take a look?

**Comment by aniezurawski** [comment]
Hi. Do not worry. `OfflineBackend` is still there. It just not imported in main `__init__.py` file. We will restore this import in future release this week because it was not intentional. Maybe even today.

**Comment by vfdev-5** [comment]
@aniezurawski @jakubczakon thanks for the update. Please remove [this version freeze](https://github.com/pytorch/ignite/pull/1863/files) once you have fixed the import. Thanks!
