### ISSUE TITLE
Improve Accumulation metric on tensors to work with Apex

### ISSUE THREAD

**Issue by youshaox** [pytorch/ignite#1872]
## 🚀 Feature Request
It seems that the ignite is not compatible with apex. When i am trying to use the (automatic mixed precision)amp from the Apex for the GPU Acceleration, I have encountered the following error. Look around the Ignite source code and I find that it uses the original torch.Tensor. Is there any timeline for Ignite to be compatible with Apex?
```
m.update(loss)
--
File "/usr/local/lib/python3.6/site-packages/ignite/metrics/metric.py", line 575, in wrapper
func(self, *args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/ignite/metrics/accumulation.py", line 73, in update
self.accumulator = self._op(self.accumulator, output)
File "/usr/local/lib/python3.6/site-packages/ignite/metrics/accumulation.py", line 130, in _mean_op
return a + x
File "/usr/local/lib64/python3.6/site-packages/apex/amp/wrap.py", line 62, in wrapper
.format(types))
NotImplementedError: Do not know how to handle these types to promote: {'FloatTensor', 'DoubleTensor'}
```
Apex: https://github.com/NVIDIA/apex

## Environment

- PyTorch Version (1.4.0):
- Ignite Version (0.4.4):
- OS (Linux):
- Python version:  python 3.6
- Apex Version (0.1)

**Comment by vfdev-5** [comment]
Thanks for reporting @youshaox! Normally, Ignite is compatible with Apex, please take a look at this notebook: https://github.com/pytorch/ignite/blob/master/examples/notebooks/Cifar100_bench_amp.ipynb
in older versions we also provided image segmentation example with Apex: https://github.com/pytorch/ignite/blob/0.4.4/examples/references/segmentation/pascal_voc2012/code/scripts/training.py

However, let me still investigate what happens with accumulation metric. Meanwhile, could you please provide a reproducible small code snippet ? Thanks

**Comment by vfdev-5** [comment]
@youshaox I could reproduce the issue you reported. A workaround in this case can be:
```diff
- m.update(loss)
+ m.update(loss.item())
```

**Comment by fco-dv** [comment]
Could help with this issue, however struggling to reproduce it with autocast, @vfdev-5 would you still have the code snippet ? thanks

**Comment by vfdev-5** [comment]
@fco-dv it is apex only related failure. To reproduce it, try to add two tensors of different types: f32 and f64 once apex is fully initialized (following above discussion).
