### ISSUE TITLE
Fix TPU CI, libmkl_intel_lp64.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1884]
- https://github.com/pytorch/ignite/pull/1880/checks?check_run_id=2205301550

I think this is related to this bad configuration:
https://github.com/pytorch/ignite/blob/05c5e19c839b1ef0138d695613997af1da2aef71/.github/workflows/tpu-tests.yml#L69

while we are using https://github.com/pytorch/ignite/blob/05c5e19c839b1ef0138d695613997af1da2aef71/.github/workflows/tpu-tests.yml#L29

**Comment by trsvchn** [comment]
I'll check that!

**Comment by trsvchn** [comment]
@vfdev-5 Setting:

```yml
           export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/hostedtoolcache/Python/3.7.10/x64/lib 
```
didn't help
https://github.com/trsvchn/ignite/runs/2205429091?check_suite_focus=true#step:8:23

**Comment by vfdev-5** [comment]
@trsvchn we have to find where `pip install mkl` put its library...

**Comment by trsvchn** [comment]
@vfdev-5 I've tried

```bash
$ sudo updatedb
$ locate libmkl_intel_lp64.so

/opt/hostedtoolcache/Python/3.7.10/x64/lib/libmkl_intel_lp64.so.1
```

**Comment by vfdev-5** [comment]
Maybe, we can also set up latest stable xla version instead of nightly. Looks like a linking issue...

**Comment by trsvchn** [comment]
that was in sandbox repo, going try to locate in `tpu-test` workflow

**Comment by trsvchn** [comment]
the same result:
https://github.com/trsvchn/ignite/runs/2205725384?check_suite_focus=true#step:9:8

**Comment by vfdev-5** [comment]
Here is how to repro that locally:
```docker
FROM python:3.7-buster

# - Install gsutil to copy wheels from gcr
# - Install openblas
# - Download torch & xla
# - Setup Python 3.7 env for Torch XLA wheels
# - Install torch & xla
RUN export VERSION="nightly" \
  && curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py \
  && pip install requests gsutil mkl \
  && apt-get update && apt-get install -y libopenblas-dev libomp5 \
  && python pytorch-xla-env-setup.py --version $VERSION

ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:/usr/local/lib/
ENV XRT_DEVICE_MAP "CPU:0;/job:localservice/replica:0/task:0/device:XLA_CPU:0"
ENV XRT_WORKERS "localservice:0;grpc://localhost:40934"

RUN python -c "import torch" && python -c "import torch_xla"
```
and 
```bash
docker build -t xla-cpu:nightly -f Dockerfile.nightly .
```

**Comment by vfdev-5** [comment]
Workaround is 
```
cd <where located libmkl_intel_lp64.so.1>
ln -s libmkl_intel_lp64.so.1 libmkl_intel_lp64.so
ln -s libmkl_intel_thread.so.1 libmkl_intel_thread.so
ln -s libmkl_core.so.1 libmkl_core.so
```

**Comment by trsvchn** [comment]
What about `ldconfig`? I've tried it here: https://github.com/trsvchn/ignite/runs/2205830908?check_suite_focus=true#step:7:1141 but I think it didn't look inside the `/opt/hostedtoolcache/Python/3.7.10/x64/lib` folder

**Comment by vfdev-5** [comment]
That was the purpose of `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/hostedtoolcache/Python/3.7.10/x64/lib`

**Comment by vfdev-5** [comment]
To fix the issue we can also install previous version of mkl:
```
pip install requests gsutil mkl==2021.1.1
```

**Comment by trsvchn** [comment]
Currently trying that workaround
