### ISSUE TITLE
Update docs 

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#189]
Current documention update is needed:
- version : 0.1.0a1 -> 0.1.0
- update [index.rst](https://github.com/pytorch/ignite/blob/master/docs/source/index.rst) in respect to [README.rst](https://github.com/pytorch/ignite/blob/master/README.rst):
    - Add the same description and side-by-side image 
- update pytorch logo :)

Info on documentation regeneration can be found [here](https://github.com/pytorch/ignite/wiki/Maintainer-Notes#how-to-update-documentation)

**Comment by alykhantejani** [comment]
ifxed in #190
