### ISSUE TITLE
Missing `close` method in `WandBLogger` and `PolyaxonLogger` ?

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/ignite#1894]
## 🐛 Bug description

Just found it unexpected. Not sure this is intended. There are `close` method overrides in provided loggers except for `WandBLogger` and `PolyaxonLogger`. [wandb states that wandb process have to close if we are on jupyter or colab env](https://docs.wandb.ai/integrations/huggingface#6-finish-your-w-and-b-run-notebook-only). Not sure about PolyaxonLogger.

We need to have one API to close all loggers even if users want to change using different loggers.

**Comment by vfdev-5** [comment]
@ydcjeff thanks for the report (sorry for the delay) ! Yes, I agree it would make sense to have a unified API. As for PolyaxonLogger I think there is not special need for closing it AFAIK.
