### ISSUE TITLE
CI tests are failing on BLEU

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1910]
CI tests on Master are failing on checking Bleu metric: 

- https://app.circleci.com/pipelines/github/pytorch/ignite/1755/workflows/00c8cfad-8243-4f5f-9e9e-b8eaeee58b17
- https://github.com/pytorch/ignite/actions/runs/725753501

cc @sdesrozis @gucifer

**Comment by gucifer** [comment]
It is failing because of assertion error as nltk corpus bleu is giving different results than ignite's bleu. It was passing those assertions when the original PR was made, I will check what happened since then

**Comment by vfdev-5** [comment]
@gucifer that's true, it is new version of nltk (3.6 vs 3.5) that gives the error: 
- https://github.com/pytorch/ignite/runs/2286735030?check_suite_focus=true#step:7:109
- https://github.com/pytorch/ignite/runs/2278640364#step:7:299

**Comment by sdesrozis** [comment]
Related to https://github.com/nltk/nltk/issues/2571 fix.

**Comment by gucifer** [comment]
Sure It's just a simple fix. I should change according to the new nltk update?

**Comment by gucifer** [comment]
> Related to [nltk/nltk#2571](https://github.com/nltk/nltk/issues/2571) fix (smooth2 method). 1-gram is no longer modified (adding one to numerator / denominator). Let's fix it. @gucifer do you want to contribute on this ?

I checked nltk's new implementation, for the first example they do num/den and (num+1)/(den+1) after that. If we do that it will fail division by zero division test.

**Comment by sdesrozis** [comment]
Ok I will check on my side later.

**Comment by gucifer** [comment]
Added PR https://github.com/pytorch/ignite/pull/1911

**Comment by vfdev-5** [comment]
GPU CI is still failing: 
- https://app.circleci.com/pipelines/github/pytorch/ignite/1759/workflows/8268b94a-b53f-46dd-be89-4a73d5d860fc

**Comment by vfdev-5** [comment]
Sorry, wrong job.
