### ISSUE TITLE
Datasets are downloading only on node 0, rank 0 in Ignite examples.

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/ignite#1922]
## 🐛 Bug description
Datasets are downloading only on node 0, rank 0 in Ignite examples. `idist.get_rank()` should be `idist.get_local_rank()`

https://github.com/pytorch/ignite/blob/13a42b90589112e67bcc6e1780e7c826a5a34199/examples/contrib/cifar10/main.py#L204-L214

---

https://github.com/pytorch/ignite/blob/13a42b90589112e67bcc6e1780e7c826a5a34199/examples/contrib/cifar10_qat/main.py#L189-L199

---

https://github.com/pytorch/ignite/blob/13a42b90589112e67bcc6e1780e7c826a5a34199/examples/contrib/transformers/main.py#L207-L219

cc @vfdev-5 for confirmation

**Comment by ydcjeff** [comment]
> @ydcjeff If you are not going to work on this. I can prepare a PR. the approach looks straightforward to me

@Moh-Yakoub Sure! you can go ahead

**Comment by sdesrozis** [comment]
I think that is correct to download dataset only on rank 0.

Usually, if you have multiple nodes, dataset is downloaded on a shared directory on the file system. We don't want to have multiple datasets on memory.

**Comment by vfdev-5** [comment]
That's true for large datasets which we do not usually download during the training. In case of cifar10 we never stated that we have to use shared filesystem.

**Comment by sdesrozis** [comment]
> That's true for large datasets which we do not usually download during the training. In case of cifar10 we never stated that we have to use shared filesystem. 

Do we really have an issue here ? I'm not sure.

IMO, what is currently done is exactly what should be done. The implementation works on clusters and classical multinode systems. Change that means handle concurrent writes and maybe have different paths per node... 

We should keep current code.

**Comment by vfdev-5** [comment]
@sdesrozis we discovered that in code-generator examples and it was me who asked him to file the issue here as we replaced rank by local rank there.

My point is that doing what is described here: https://github.com/pytorch/ignite/tree/13a42b90589112e67bcc6e1780e7c826a5a34199/examples/contrib/cifar10#multiple-nodes-multiple-gpus as by default it will use `data_path="/tmp/cifar10"` which is not shared. Either we say that explicitly that `data_path` for multi-node should point to a shared fs or use local rank and download on each node...

**Comment by sdesrozis** [comment]
Ok I understand but I would be surprised if this would be relevant in a real scenario. Usually, datasets are not downloaded during training, they are stored in a persistent folder. Other points are the network bandwidth, cost of the downloading, etc.

**Comment by vfdev-5** [comment]
Do you think for cifar10 we should do like for Pascal VOC ?
https://github.com/pytorch/ignite/blob/13a42b90589112e67bcc6e1780e7c826a5a34199/examples/references/segmentation/pascal_voc2012/main.py#L26-L48

**Comment by sdesrozis** [comment]
I'm not sure. Cifar10 is a small dataset, I think that what is currently done is good.
