### ISSUE TITLE
ImportError: cannot import name 'Metric' from 'ignite.metrics'

### ISSUE THREAD

**Issue by bennydayana** [pytorch/ignite#1929]
## 🐛 Bug description

Unable to use Metric for calculating roc_auc_compute 

Code that caused error:

```
from typing import Any, Callable, Tuple

import torch

from ignite.metrics import EpochMetric


def roc_auc_compute_fn(y_preds: torch.Tensor, y_targets: torch.Tensor) -> float:
    try:
        from sklearn.metrics import roc_auc_score
    except ImportError:
        raise RuntimeError("This contrib module requires sklearn to be installed.")

    y_true = y_targets.numpy()
    y_pred = y_preds.numpy()
    return roc_auc_score(y_true, y_pred)
```

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-25-eaec9c574c2d> in <module>
      3 import torch
      4 
----> 5 from ignite.metrics import EpochMetric
      6 
      7 

C:\Users\dayan\AppData\Roaming\Python\Python37\site-packages\ignite\metrics\__init__.py in <module>
----> 1 from ignite.metrics.accumulation import Average, GeometricAverage, VariableAccumulation
      2 from ignite.metrics.accuracy import Accuracy
      3 from ignite.metrics.confusion_matrix import ConfusionMatrix, DiceCoefficient, IoU, mIoU
      4 from ignite.metrics.epoch_metric import EpochMetric
      5 from ignite.metrics.fbeta import Fbeta

C:\Users\dayan\AppData\Roaming\Python\Python37\site-packages\ignite\metrics\accumulation.py in <module>
      5 
      6 from ignite.exceptions import NotComputableError
----> 7 from ignite.metrics.metric import Metric, reinit__is_reduced, sync_all_reduce
      8 
      9 __all__ = ["VariableAccumulation", "GeometricAverage", "Average"]

C:\Users\dayan\AppData\Roaming\Python\Python37\site-packages\ignite\metrics\metric.py in <module>
      8 
      9 import ignite.distributed as idist
---> 10 from ignite.engine import CallableEventWithFilter, Engine, Events
     11 
     12 if TYPE_CHECKING:

C:\Users\dayan\AppData\Roaming\Python\Python37\site-packages\ignite\engine\__init__.py in <module>
      8 from ignite.engine.engine import Engine
      9 from ignite.engine.events import CallableEventWithFilter, EventEnum, Events, EventsList, RemovableEventHandle, State
---> 10 from ignite.metrics import Metric
     11 from ignite.utils import convert_tensor
     12 

ImportError: cannot import name 'Metric' from 'ignite.metrics' (C:\Users\dayan\AppData\Roaming\Python\Python37\site-packages\ignite\metrics\__init__.py)

I am trying to compute AUC ROC score. But error is occurring ...

## Environment

- PyTorch Version : 1.8.1
- Ignite Version : 0.4.4
- OS : Windows
- How you installed Ignite : pip
- Python version: 3.7.7
- Any other relevant information:

**Comment by vfdev-5** [comment]
@bennydayana thanks for reporting, we'll take a look. 

Meanwhile, could you please install [nightly version](https://github.com/pytorch/ignite#nightly-releases) to see if it was fixed in between ? Thanks

**Comment by bennydayana** [comment]
Yes.. in nightly version it is solved.. Thanks

**Comment by vfdev-5** [comment]
@bennydayana could you please provide minimal code snippet to reproduce the issue with the stable version ?
As your first message shows ignite's code, I'd like to understand the origins of the issue... Thanks

**Comment by bennydayana** [comment]
This import line caused the error
from ignite.metrics import EpochMetric

**Comment by vfdev-5** [comment]
@bennydayana could you please detail which Windows version you are using ?

**Comment by vfdev-5** [comment]
@bennydayana tried to reproduce the issue on windows 10 VM with conda environment and there is no issue:
```
(pytorch-ignite-dev) C:\Users\IEUser>python
Python 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ignite.metrics import EpochMetric
>>> import ignite
>>> ignite.__version__
'0.4.4'
>>> import torch
>>> torch.__version__
'1.8.1+cpu'
```

Can you provide more details on your env and how cand we replicate it to reproduce the issue. Thanks

**Comment by bennydayana** [comment]
The error occurred in stable version ('0.4.4') when I tried in jupyter notebook of WinPython.

**Comment by vfdev-5** [comment]
@bennydayana I tried with [Winpython64-3.8.8.0dot.exe](https://github.com/winpython/winpython/releases/tag/4.0.20210307), installed manually pytorch-ignite and jupyter notebook, called `﻿﻿from ignite.metrics import EpochMetric` inside a notebook and still can not reproduce your issue.
I suppose that you should something strange with your python environment.

**Comment by bennydayana** [comment]
I tried it in another system and the stable version is working there.. So no issues now.. Thanks!
