### ISSUE TITLE
[Feature Request] Custom user variables in engine.state 

### ISSUE THREAD

**Issue by system123** [pytorch/ignite#193]
I have come across a situation where I need to set variables in the on_iteration_complete callback and access them in the on_epoch_complete callback. Currently, I have done this by creating a metric but the variables are not actually metrics, so I feel it would be better to have a separate API for users to specify custom states which they can modify in the callback.

I was thinking about something along the lines of:

```
evaluator = Engine(some_update_function, state={'my_var': ['SomeDefaultValue']})

@evalutor.on(Events.ITERATION_COMPLETED)
def accumulate_testing_measure(engine):
     y_pred, y_true = engine.state.output
     updated_state = update_this_state(engine.state.custom['my_var'], y_pred)
     return {'my_var': updated_state}
     

@evalutor.on(Events.EPOCH_COMPLETED)
def save_testing_results(engine):
    some_var = compute(engine.state.my_var)
    save(some_var)
    return {'my_var': []}
```

Perhaps there is another way to achieve this easily, but I think something along these lines should provide a lot of flexibility.

**Comment by vfdev-5** [comment]
@system123 idea is to use `state` as a holder:
```python
# Optional initialization
@evalutor.on(Events.STARTED)
def init_all_custom_var(engine):
     engine.state.my_var = []

@evalutor.on(Events.ITERATION_COMPLETED)
def accumulate_testing_measure(engine):
     y_pred, y_true = engine.state.output
     engine.state.my_var = update_this_state(engine.state.my_var, y_pred)
     
@evalutor.on(Events.EPOCH_COMPLETED)
def save_testing_results(engine):
    some_var = compute(engine.state.my_var)
    save(some_var)
    engine.state.my_var = []
```

See [here](https://pytorch.org/ignite/concepts.html#state) and [here](https://github.com/pytorch/ignite/pull/142#issuecomment-380171722) for more info.

HTH
