### ISSUE TITLE
What's the usage of `event_to_attr`

### ISSUE THREAD

**Issue by Nic-Ma** [pytorch/ignite#1934]
## ❓ Questions/Help/Support

Hi @vfdev-5 ,

I see there is a dict property `event_to_attr` in `State`:
https://github.com/pytorch/ignite/blob/master/ignite/engine/events.py#L374
And users can register new event-to-attr "mapping" in engines.
But I didn't find the usage of this property, may I know why you defined this dict and what the usage case it is for?

In my simple mind, maybe "register events" and "register attributes" can be 2 independent features of `State`?
I didn't see the relationship between "event names" and "attributes" of `State`.
I am enabling it in MONAI and Clara workflows, users use custom events and attributes to share data between handlers.
 
Thanks in advance.

**Comment by vfdev-5** [comment]
Hi @Nic-Ma ,

it is, for example, used internally to resolve events filtering:
```python
@trainer.on(Events.EPOCH_COMPLETED(every=5))
def do_something():
    # do something
```
it adds a `if-else` clause: `trainer.state.epoch % 5 == 0`  and we have to connect `Events.EPOCH_COMPLETED` <-> `State.epoch`. 
Please, keep in mind that some parts of this design is subject to change in future release as we'd like to have more splitting between `Engine` and `State`.

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 ,

Thanks for your example, makes sense.
As Clara users usually use JSON config to develop DL pipeline, we highlight "event-handlers" as the main approach to bring their own python code.
So "register events", "register attrs", "end-to-end context dict data" would 3 most important features to construct a flexible program based on ignite handlers.

Thanks.

**Comment by vfdev-5** [comment]
> As Clara users usually use JSON config to develop DL pipeline, we highlight "event-handlers" as the main approach to bring their own python code.

@Nic-Ma, I had a side thought about DL pipeline development. What do you think about providing an app similar to this one: http://pytorch-ignite-code-generator-dev.eu-west-3.elasticbeanstalk.com/  where the main goal is to "generate your training scripts" ?

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 ,

Thanks for your sharing, a very cool online tool.
NVIDIA Clara is based on MMAR standard archive and JSON configs, many users are not programmers.
https://docs.nvidia.com/clara/tlt-mi/nvmidl/model.html#
The new version that is based on MONAI & ignite is not released yet.
Maybe we can leverage your application in the future.

Thanks.

**Comment by vfdev-5** [comment]
Let me close this issue as answered. We can reopen it if needed.
