### ISSUE TITLE
Make sure that all exp tracking system loggers handle metric types in the same way

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1965]
## 🚀 Feature

Related to the discussion from here: https://github.com/pytorch/ignite/issues/1476#issuecomment-826314243

We would like to ensure that all our supported experiment tracking loggers handle metric types in the same way as here:

For Neptune (correct):
https://github.com/pytorch/ignite/blob/9230a7319047b37ce19d956e024fa1b86030c30a/ignite/contrib/handlers/neptune_logger.py#L344-L351

In a previous issue we found that the code for WandB is different (incorrect):
https://github.com/pytorch/ignite/blob/9230a7319047b37ce19d956e024fa1b86030c30a/ignite/contrib/handlers/wandb_logger.py#L271-L275

ToDo:
- check `OutputHandler` implementation for all supported loggers: tensorboard_logger.py, clearml_logger.py, mlflow_logger.py, neptune_logger.py, polyaxon_logger.py, tqdm_logger.py, visdom_logger.py, wandb_logger.py
and find those where it is not done as in the "correct" example of Neptune.
- reimplement those loggers using above "correct" example of Neptune.

If interested in working on this issue, please comment out in here such that it could be assigned to you.

**Comment by Muktan** [comment]
I would like to work on this issue and would like to start with `wandb_logger`

**Comment by vfdev-5** [comment]
@Muktan thanks for proposing your help! Actually, this is not a per-logger generic issue but 1 PR to fix everything. You can draft a PR with `wandb_logger` and then update it with others if found other loggers with issues.

Please, check our contributing guide and ask questions here or on our discord server.

**Comment by Muktan** [comment]
Okay, I will work on all the loggers and will try my best to complete it by june 2nd.

**Comment by vfdev-5** [comment]
Thanks a lot !
