### ISSUE TITLE
Can't get `Parallel.run`  with NCCL in SLURM environment to work

### ISSUE THREAD

**Issue by djberenberg** [pytorch/ignite#1968]
## 🐛 Bug description
Dispatching a distributed multi-node/multi-gpu script via SLURM `sbatch` raises a `RuntimeError` 

#### Slurm invocation: 
```bash
 OMP_NUM_THREADS=1 sbatch -N1 -n2 -p gpu --gres=gpu:v100-32gb:02 --wrap "python -u test_dist.py run --nnodes=1 --nproc_per_node=2"
```
### `test_dist.py`
Python script
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os

import fire

import torch
import ignite
import ignite.distributed as idist

def run_diagnostic(local_rank):
    prefix = f"{local_rank}) "
    print(f"{prefix}Rank={idist.get_rank()}")
    print(f"{prefix}torch version: {torch.version.__version__}")
    print(f"{prefix}torch git version: {torch.version.git_version}")
    
    if torch.cuda.is_available():
        print(f"{prefix}torch version cuda: {torch.version.cuda}")
        print(f"{prefix}number of cuda devices: {torch.cuda.device_count()}")

        for i in range(torch.cuda.device_count()):
            print(f"{prefix}\t- device {i}: {torch.cuda.get_device_properties(i)}")
    else:
        print("{prefix}no cuda available")


    if "SLURM_JOBID" in os.environ:
        for k in ["SLURM_PROCID", "SLURM_LOCALID", "SLURM_NTASKS", "SLURM_JOB_NODELIST"]:
            print(f"{k}: {os.environ[k]}")
        
        if local_rank == 0:
            hostnames = subprocess.check_output(["scontrol", "show", "hostnames", os.environ["SLURM_JOB_NODELIST"]])
            print(f"hostnames: {hostnames}")


def run(**spawn_kwargs):
    with idist.Parallel(backend='nccl', **spawn_kwargs) as parallel:
        parallel.run(run_diagnostic)

if __name__ == '__main__':
    fire.Fire({'run': run})

```
### Error message (and logged output):
```
2021-04-25 19:06:35,565 ignite.distributed.launcher.Parallel INFO: Initialized distributed launcher with backend: 'nccl'
2021-04-25 19:06:35,566 ignite.distributed.launcher.Parallel INFO: - Parameters to spawn processes: 
	nproc_per_node: 2
	nnodes: 1
	node_rank: 0
2021-04-25 19:06:35,566 ignite.distributed.launcher.Parallel INFO: Spawn function '<function run_diagnostic at 0x1555554741e0>' in 2 processes
Traceback (most recent call last):
  File "test_dist.py", line 45, in <module>
    fire.Fire({'run': run})
  File "path_to_python_env/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "path_to_python_env/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "path_to_python_env/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "test_dist.py", line 42, in run
    parallel.run(run_diagnostic)
  File "path_to_python_env/lib/python3.7/site-packages/ignite/distributed/launcher.py", line 309, in run
    idist.spawn(self.backend, func, args=args, kwargs_dict=kwargs, **self._spawn_params)
  File "path_to_python_env/lib/python3.7/site-packages/ignite/distributed/utils.py", line 324, in spawn
    fn, args=args, kwargs_dict=kwargs_dict, nproc_per_node=nproc_per_node, backend=backend, **kwargs
  File "path_to_python_env/lib/python3.7/site-packages/ignite/distributed/comp_models/native.py", line 380, in spawn
    **spawn_kwargs,
  File "path_to_python_env/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "path_to_python_env/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "path_to_python_env/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "path_to_python_env/lib/python3.7/site-packages/ignite/distributed/comp_models/native.py", line 323, in _dist_worker_task_fn
    backend, init_method=init_method, world_size=arg_world_size, rank=arg_rank, **kw
  File "path_to_python_env/lib/python3.7/site-packages/ignite/distributed/comp_models/native.py", line 72, in create_from_backend
    backend=backend, init_method=init_method, world_size=world_size, rank=rank, **kwargs
  File "path_to_python_env/lib/python3.7/site-packages/ignite/distributed/comp_models/native.py", line 93, in __init__
    backend, timeout=timeout, init_method=init_method, world_size=world_size, rank=rank, **kwargs
  File "path_to_python_env/lib/python3.7/site-packages/ignite/distributed/comp_models/native.py", line 124, in _create_from_backend
    dist.init_process_group(backend, init_method=init_method, **init_pg_kwargs)
  File "path_to_python_env/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 500, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "path_to_python_env/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 190, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
RuntimeError: Address already in use

```
## Expected behavior
I would like the code to run `run_diagnostic` for each `local_rank` in the allocation. Right now it does not reach that point, it seems to complete parallel configuration on the master process but fails in the auxiliary processes.

## Environment

- PyTorch Version (e.g., 1.4): `1.8.1+cu102`
- Ignite Version: was using `0.4.4`, also tried on `0.5.0.dev20210423` 
- OS: Linux (CentOS)
- How you installed Ignite (`conda`, `pip`, source): `pip`
- Python version:  `3.7.3` 
- Any other relevant information:
1. I've checked that this isn't a problem of zombie processes lingering on the compute nodes from previous failed runs.
2. there is an `dist.barrier()` after `init_process_group()` in `ignite/distributed/comp_models/native.py` (`Parallel._create_from_backend`). Clearly the `init_process_group` completes for at least one process, but in syncing via `barrier()`, the other auxiliary processes fail.
3. Not sure if this is handled elsewhere (pretty sure not) or even relevant, but in `ignite.distributed.comp_models.native.Parallel.setup_env_vars`, upon discovering that the environment is a SLURM environment, the system makes a call to `self._setup_env_in_slurm` and returns without setting `self._local_rank`, `self._master_addr`, and `self._master_port` (as it would otherwise).
4. Thanks!

**Comment by sdesrozis** [comment]
@djberenberg Thank you for this report.

When using SLURM, arguments for parallel distribution are automatically handled from the configuration (`srun` environment). Therefore, no need to specify in the python cmd line.

Could you try the following command
```comandline
 OMP_NUM_THREADS=1 sbatch -N1 -n2 -p gpu --gres=gpu:v100-32gb:02 --wrap "python -u test_dist.py run"
```
and tell me if it solves your issue ?

**Comment by vfdev-5** [comment]
@sdesrozis do you think we should handle the case like that by showing a warning or runtime error ?
Same question about the issue in MONAI ...

**Comment by sdesrozis** [comment]
@vfdev-5 I think we should do something in that case.

**Comment by djberenberg** [comment]
@sdesrozis Thank you for the reply! Unfortunately, your suggestion did not work for me. Rather than even throwing an error the script hangs indefinitely.

Interestingly, if I allocate:
```
salloc -N1 -p gpu --gres=gpu:v100-32gb:02
```
and then `srun`:
```
srun python test_dist.py run
```
I get a different error: 
```
Traceback (most recent call last):
  File "test_dist.py", line 44, in <module>
    fire.Fire({'run': run})
  File "path_to_python_envlib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "path_to_python_env/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "path_to_python_env/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "test_dist.py", line 40, in run
    with idist.Parallel(backend='nccl', **spawn_kwargs) as parallel:
  File "path_to_python_env/nard-meta/lib/python3.7/site-packages/ignite/distributed/launcher.py", line 319, in __enter__
    idist.initialize(self.backend, init_method=self.init_method)
  File "path_to_python_env/lib/python3.7/site-packages/ignite/distributed/utils.py", line 539, in initialize
    _set_model(comp_model_cls(backend, **kwargs))
  File "/path_to_python_env/lib/python3.7/site-packages/ignite/distributed/comp_models/native.py", line 93, in __init__
    backend, timeout=timeout, init_method=init_method, world_size=world_size, rank=rank, **kwargs
  File "path_to_python_env/lib/python3.7/site-packages/ignite/distributed/comp_models/native.py", line 130, in _create_from_backend
    torch.cuda.set_device(self._local_rank)
AttributeError: '_NativeDistModel' object has no attribute '_local_rank'
srun: error: workergpu16: task 0: Exited with exit code 1
```
which seems related to point 3 in the relevant information I provided above.

That being said, https://github.com/sdesrozis/why-ignite did work! (that is, `salloc ...` followed by `srun python check_config.py`) *That* being said, it doesn't look like `check_config.py` makes use of `Parallel.run` so it's not clear how to use it in my own workflow. 

Really what I would like is to be able to `sbatch` my launch script, set some environment variables in the launch script, and finally `srun` my python script to dispatch the work to every worker in my allocation. 

Thanks again!

**Comment by vfdev-5** [comment]
@djberenberg thanks a lot for the bug report, we'll work on it in high priority!

**Comment by djberenberg** [comment]
@vfdev-5  Awesome! Thank you so much

**Comment by sdesrozis** [comment]
@djberenberg I will run the script on a cluster as soon as possible.

However, it should be tomorrow afternoon or on Wednesday.

**Comment by sdesrozis** [comment]
@djberenberg Please have a look here https://github.com/sdesrozis/why-ignite/blob/main/basics/3_ignite/README.md to see how an example using `Parallel` is launched. Maybe it could help.

**Comment by djberenberg** [comment]
@sdesrozis Whoops, I didn't even see that directory in the repo. Yes, it's quite helpful. (Naive) question - does `master_port` have to be unique for each worker?

**Comment by sdesrozis** [comment]
> @sdesrozis Whoops, I didn't even see that directory in the repo. Yes, it's quite helpful. 

Good ! Currently we are writing a blog post to explain how ignite can help to use multiple launching methods with the same code. I hope we will release this post soon.

> (Naive) question - does `master_port` have to be unique for each worker?

yes it does. Each workers have to sync using master_addr:master_port.

**Comment by djberenberg** [comment]
@sdesrozis  This is very helpful, thank you. Isn't `SLURM_JOB_ID` the same for every node in the allocation though? Will there be collisions when physically different nodes connect to master?

**Comment by vfdev-5** [comment]
> Will there be collisions when physically different nodes connect to master?

@djberenberg all nodes should connect to master with the same port independently of SLURM, see for example here:
 - https://github.com/pytorch/examples/tree/master/imagenet#multiple-nodes
 - https://github.com/pytorch/ignite/tree/master/examples/contrib/cifar10#multiple-nodes-multiple-gpus

**Comment by sdesrozis** [comment]
> @sdesrozis  This is very helpful, thank you. Isn't `SLURM_JOB_ID` the same for every node in the allocation though? Will there be collisions when physically different nodes connect to master?

I think it could have collision. We extract the last 4 digits of the slurm jobid, so 2 runs could have the same port. Therefore, if these runs are located on same nodes (suppose you decided to split the nodes with 4 GPUs in 2x2 GPUs), it will conflit.

However, I suppose we are talking about hypothetical scenarios. The best practice is to use full nodes as possible to avoid communication costs.

**Comment by vfdev-5** [comment]
@sdesrozis when you say we extract 4 last digits of jobid, do they pad the id with zeros for newly created clusters ? I mean, can't we have a situation when id is smaller then 1000 and thus parsing the id would fail ?

**Comment by sdesrozis** [comment]
> @sdesrozis when you say we extract 4 last digits of jobid, do they pad the id with zeros for newly created clusters ? I mean, can't we have a situation when id is smaller then 1000 and thus parsing the id would fail ?

Precisely we do `15000 + jobid[-4:]` but it is the same issue. 

https://github.com/pytorch/ignite/blob/d90a2efded4ddaf5265f9d346be8f1ee2b94d12a/ignite/distributed/comp_models/native.py#L245

Anyway, we could let user gives a port number if it would be necessary.

**Comment by vfdev-5** [comment]
> Precisely we do 15000 + jobid[-4:] but it is the same issue.

Yes, I know that, but `jobid[-4:]` is always a number ?

**Comment by sdesrozis** [comment]
I would say yes but I don't find this info in the doc. Although it's very common to cast the job id in an integer.

**Comment by sdesrozis** [comment]
@djberenberg from my side, the following command works 
```
OMP_NUM_THREADS=1 srun  --nodes 1 --ntasks-per-node 2 -p gpu --gres=gpu:v100-32gb:02 python -u test_dist.py run 
```
It means `torch.distributed.launch` is replaced by `srun`. However this is the commandline approach. To submit a batch job, the following command works
```
OMP_NUM_THREADS=1 sbatch -N1 -n2 -p gpu --gres=gpu:v100-32gb:02 --wrap "srun python -u test_dist.py run"
```

**Comment by djberenberg** [comment]
@sdesrozis thank you for looking into this! I will test it on my end.

**Comment by sdesrozis** [comment]
@djberenberg I was thinking about the most coherent and robust solution possible. The usage of `slurm` I suggest is to use `srun` to spawn process. It works perfectly with `sbatch` for the submission of jobs to the scheduler. If we mix `torch.distributed.spawn` or `torch.distributed.launch` with `slurm`, we have to consider 2 parallel configurations (`sbatch` and the python script). First, I think it's bug prone approach. Second, it is less straighforward. Lastly, the implementation is less robust because a plenty of scenariis are opened...

By the way, I think that the doc should be improved to clearly explain how slurm should be use with ignite. What do you think ?

**Comment by djberenberg** [comment]
@sdesrozis  re: docs - Personally I would have benefited greatly from a clear explanation of the interaction between slurm and ignite and how to dispatch jobs on such a system. . I'm awaiting in excitement the upcoming blog post you mentioned a few days ago. Thanks again for working on this so much for the last few days it really has helped a lot. The why-ignite package was also very helpful!

I also think the usage you suggested is good because it is has the least deviation from any other slurm script meaning there is a low barrier to entry and doesn't require acute understanding of the initialization process of distributed jobs as much as `torch.distributed.[launch|spawn]`.

**Comment by sdesrozis** [comment]
@fco-dv we definitely need the blog post about `idist` 😉
