### ISSUE TITLE
Set `seed` for xla in `manual_seed`

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/ignite#1969]
### 🚀 Feature
While reading HF's accelerate source, just found that we don't set seed for xla in `manual_seed`. We do need to set seed in xla environment right?

Ref: [XLA set seed docs](https://pytorch.org/xla/release/1.8/index.html#torch_xla.core.xla_model.set_rng_state), [HF set seed source](https://github.com/huggingface/accelerate/blob/e0a420f7cb32124cadeeae690b56e463f8fc598f/src/accelerate/utils.py#L45)

**Comment by sdesrozis** [comment]
@ydcjeff Thank you for pointing this out ! I think it should be added in `manual_seed`.

**Comment by vfdev-5** [comment]
@ydcjeff can you send a PR for that please ?
