### ISSUE TITLE
Is it possible to have access to outputs?

### ISSUE THREAD

**Issue by versatran01** [pytorch/ignite#20]
I want the training_update_function to return the output of a network in addition to loss so that I could visualize it.
The output is a one-time thing for viz only, but it seems like it will be appended to the history, which is a waste of memory?
Engine saves the output and releases it immediately afterward. Is there a way to do this in Trainer?

**Comment by alykhantejani** [comment]
Hi @versatran01,

For the moment no - you can access them via the history (with the event `TRAINING_ITERATION_COMPLETE`) and you can also remove it from the history. 

We are also discussing the API internally to try and solve these kind of issues, so stay tuned.

**Comment by alykhantejani** [comment]
@versatran01 You could also do the visualisation inside your update function and not return the value as you don't want it to persist. 

Let me know if this answers your question

**Comment by versatran01** [comment]
Thanks for the answer.
That's what I'm doing now. But it would be nice to do it in the training_iteration_complete event.

**Comment by alykhantejani** [comment]
@versatran01 you can also do it in the event handler and then remove it from history. 

Closing this issue now as a wont-fix, but let me know if you have further issues or ideas around changes that could be made
