### ISSUE TITLE
Precision raises an NonComputableError for all zeros model predictions

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2007]
## 🐛 Bug description

Following https://github.com/pytorch/ignite/issues/1991#issuecomment-844860265

```python
from ignite.metrics import Precision
p = Precision()
p.update((torch.zeros(4), torch.randint(0, 2, (4,))))
p.compute()
> NotComputableError: Precision must have at least one example before it can be computed.
```
which is wrong as we do call `update`.

This is related to the check
```
/opt/conda/lib/python3.8/site-packages/ignite/metrics/precision.py in compute(self)
     51         is_scalar = not isinstance(self._positives, torch.Tensor) or self._positives.ndim == 0
     52         if is_scalar and self._positives == 0:
---> 53             raise NotComputableError(
     54                 f"{self.__class__.__name__} must have at least one example before it can be computed."
     55             )
```
where `self._positives` is 0 for all zeros predictions but is thought as uninitialized.

I think this should be related to a change in pytorch that previously had `torch.tensor([0, 0, 0]).sum()` as 1d tensor and now is 0d tensor.

## Environment

- PyTorch Version (e.g., 1.4): 1.8
- Ignite Version (e.g., 0.3.0): 0.4.4
- OS (e.g., Linux):
- How you installed Ignite (`conda`, `pip`, source):
- Python version:
- Any other relevant information:

cc @liebkne

**Comment by trsvchn** [comment]
yes, it's true

`torch.sum` with default `keepdim=False` will squeeze the dim, 1 to 0 dim in our case.

Thus in a corner case withg zeros:

```python
prec.update((torch.zeros(4), ...))
```
will produce `self._positives` equals `tensor(0)` with size of `torch.Size([])`, `ndim=0`

and later when checking `self._positives == 0` will produce True and raise Error, since

```python
>>> torch.tensor(0) == 0
tensor(True)
```

**Comment by trsvchn** [comment]
After reading discussion #335 and some experiments I'd like to propose another solution. It is based on the code proposed in that discussion, but the approach is slightly different. I uses the  `__new__` magics, so we wraps the methods on instance creation, so no need to call `super()` and user cannot break it by overriding `__init__`, `reset`, `update` etc.

```python
class Metric(metaclass=ABCMeta):
...
    def __new__(cls, *args, **kwargs):
        """Prevents metric from being computed before updated.
        """
        metric = super(Metric, cls).__new__(cls, *args, **kwargs)

        _reset = metric.reset
        _update = metric.update
        _compute = metric.compute

        def wrapped_reset():
            _reset()
            metric._updated = False

        metric.reset = wraps(metric.reset)(wrapped_reset)

        def wrapped_update(output):
            _update(output)
            metric._updated = True

        metric.update = wraps(metric.update)(wrapped_update)

        def wrapped_compute():
            if not metric._updated:
                raise NotComputableError(
                    f"{metric.__class__.__name__} not updated before compute."
                )
            return _compute()

        metric.compute = wraps(metric.compute)(wrapped_compute)

        return metric
...
        def __init__(...):
            ...
```

What do you think?

**Comment by sdesrozis** [comment]
This solution is smart but IMO it should be a temporary fix. We have a `Metric` interface that could be adapted to handle this flag. However, that would mean 2 method levels : logic (defined by user) and API (the wrappers, used to compute). To be discussed in next version ?

**Comment by vfdev-5** [comment]
@sdesrozis I'm not sure that we would like just patch the problem as it can be recurrent for other metrics once pytorch has changed some other behaviour on which we rely on (but should not) to assert `reset -> (update)+ -> compute` logic.
As proposed change reside in `Metric` there is no change for extended classes. 

> To be discussed in next version ?

Can you detail what you would like to discuss ?

**Comment by trsvchn** [comment]
@sdesrozis Thanks for the review, I have another idea, let's encapsulate `reset-comp-update` in a separate MetaClass, it looks similar to @zasdfgbnm proposed in #336 But here we put the code into metaclass `__call__`, to customize instance creation when "calling a class", like this:

```python
class MetaMetric(ABCMeta):

    def __call__(cls, *args, **kwargs):
        """Prevents metric from being computed before updated.
        """

        metric = super(MetaMetric, cls).__call__(*args, **kwargs)

        metric._updated = False

        _reset = metric.reset
        _update = metric.update
        _compute = metric.compute

        def wrapped_reset():
            _reset()
            metric._updated = False

        metric.reset = wraps(metric.reset)(wrapped_reset)

        def wrapped_update(output):
            _update(output)
            metric._updated = True

        metric.update = wraps(metric.update)(wrapped_update)

        def wrapped_compute():
            if not metric._updated:
                raise NotComputableError(
                    f"{metric.__class__.__name__} not updated before compute."
                )
            return _compute()

        metric.compute = wraps(metric.compute)(wrapped_compute)

        return metric


# No changes for the Metric class
class Metric(metaclass=ABCMeta):
    ...
```

Then, If we want to activate it in Custom Metric we can do:

```python
class Precision(_BasePrecisionRecall, metaclass=MetaMetric):
    ...
```

Thus precision instance will be created using `MetMetric`'s `__call__`  method with wrappers, if omitted - works as usual.

**Comment by vfdev-5** [comment]
> class Precision(_BasePrecisionRecall, metaclass=MetaMetric):

@trsvchn I think we should not expose that for the user. It is also a breaking change to avoid for now.

**Comment by trsvchn** [comment]
Oh, ok, I see. in such case we can:

```python
class Metric(metaclass=MetaMetric):
    ...

```

**Comment by sdesrozis** [comment]
@trsvchn your first solution based on `__new__` is perfect regarding to BC concerns.

> Can you detail what you would like to discuss ?

If we hadn't the BC constraint, we would have change how to define, and use a metric (I suppose). User would have to define the computing methods (not API methods) `reset-update-compute` as today but the usage would have been different using API methods, because of the internal logic added (counter for instance). This is the template method design pattern. Having same computing methods and API methods is blocking here.

Btw, I understand that it could be considered low interest regarding to the impact for existing codes.
