### ISSUE TITLE
[docs] Mistake in note about engine.state.output

### ISSUE THREAD

**Issue by 01-vyom** [pytorch/ignite#2022]
## 📚 Documentation

For the note in `engine.create_supervised_evaluator` about `engine.state.output`, there is a spelling mistake in `defined`.

[Link to Doc](https://pytorch.org/ignite/engine.html#ignite.engine.create_supervised_evaluator)

**Comment by ydcjeff** [comment]
Thanks @01-vyom Can you check does this still exist on [master docs](https://pytorch.org/ignite/master)?

**Comment by 01-vyom** [comment]
Yes, it exists in master docs.

[Master Docs Link](https://pytorch.org/ignite/master/generated/ignite.engine.create_supervised_evaluator.html#create-supervised-evaluator)

Code:
https://github.com/pytorch/ignite/blob/be2bff832b88cfbc0a21828a38c664930f297409/ignite/engine/__init__.py#L548-L551

Also, found 2 other function notes with the same mistake:

https://github.com/pytorch/ignite/blob/be2bff832b88cfbc0a21828a38c664930f297409/ignite/engine/__init__.py#L490-L493

https://github.com/pytorch/ignite/blob/be2bff832b88cfbc0a21828a38c664930f297409/ignite/engine/__init__.py#L442-L445

**Comment by ydcjeff** [comment]
Thanks @01-vyom Would you like to send a PR to fix?

**Comment by 01-vyom** [comment]
Sure, I will make a PR.
