### ISSUE TITLE
Extending sync_all_reduce decorator's functionality to collect function results

### ISSUE THREAD

**Issue by gucifer** [pytorch/ignite#2036]
## 🚀 Feature
When performing tasks involving costly calculations, it is highly possible that we wish to do lazy calculations of the costly bits and such costly functions are only called once at the end to get the final result. In such a scenario we need sync_all_reduce like functionality except to collect data from function outputs. 
Example Usecase:
FID Metric has two sets of calculations. First is calculation of covariance and mean which are linear time operations and can be done quickly whereas calculating FID score from mean and covariance is cubic time operation and takes a lot of time. In such a case we might not want to calculate FID score every time update() function is called and lazily calculate it when compute() function is called. In such a scenario, we might need to collect function output in a distributed environment when calculating final FID score.

**Comment by gucifer** [comment]
https://github.com/pytorch/ignite/blob/d16d15efbbbfc476702e91f3ab2bc757b839be26/ignite/metrics/metric.py#L550
I think adding an if condition to check if attribute is a function and running said function in that case might solve work.

**Comment by gucifer** [comment]
```
if callable(t):
    setattr(self, "sync_all_reduce_function_result", t())
    t = getattr(self, "sync_all_reduce_function_result", None)
```
Something like this

**Comment by sdesrozis** [comment]
Let's try to explain concretely the motivation of this PR.

Consider the following pseudo approximate FID metric. The point is to call a function `fid_score` when the epoch is completed and sync the result. This result can't be computed online.
```python
class FIDMetric1(Metric):

    @reinit__is_reduced
    def reset(self):
        self.mu = ...
        self.sigma = ...
        self.num_examples = ...

    # this method is explicitly called in compute()
    def fid_score(self):
        # compute a local fid score using mu, sigma and num_examples
        return ...

    @sync_all_reduce()
    def compute(self):
        # we dont want to reduce mu, sigma and num_examples but fid
        # first, we compute fid
        fid = self.fid_score()
        # second, we reduce
        return idist.all_reduce(fid)

    @reinit__is_reduced
    def update(self, output):
        self.num_examples += 1
        # online update from output
        self.sigma = ...
        self.mu = ...
```

An alternative is to attach the function `fid_score` before the method `compute` and sync a variable `fid`. To do such a strategy, one must override the `attach` method of the `Metric` class.
```python
class FIDMetric2(Metric):

    # same reset() and update() than above

    # override the attach to set fid_score before compute
    def attach(self, engine, name, usage):
        # fid_score() will be called first
        engine.add_event_handler(usage.COMPLETED, self.fid_score, name)
        # then others attached methods should be called
        super(FIDMetric2, self).attach(engine, name, usage)

    # fid_score is now implicitly called by engine before compute()
    def fid_score(self):
        # compute a local fid score using mu, sigma and num_examples
        self.fid = ...

    @sync_all_reduce("fid")
    def compute(self):
        return self.fid
```

The idea in this PR is to sync the result of a function. It means that the function should return a float or a tensor. The result must be stored somewhere, in the snippet below, the result is an attribute of the method. It could be another idea. I was thinking about an argument `fid_score_result` automatically set to the method `compute` but it can't work. Any idea and suggestion is welcome.
```python
class FIDMetric3(Metric):

    # same reset() and update() than above

    # fid_score is now implicitly called by sync_all_reduce()
    def fid_score(self):
        # compute a local fid score using mu, sigma and num_examples
        return ...

    @sync_all_reduce("fid_score")
    def compute(self):
        # computed value is stored in the method
        return self.fid_score.result
```

What do you think ?

**Comment by sdesrozis** [comment]
I think the return of a method to sync could provide a dict. Therefore, a variable could be created from the key of the dict rather than store in the method. 

We could imagine something like 
```python
def func(self):
    ...
    return {"a:MIN": ...}
```

**Comment by vfdev-5** [comment]
If you need to reduce values manually, you can just skip `sync_all_reduce` and call `idist.all_reduce` on what you need to reduce. We are doing similar things for EpochMetric where we need to do `all_gather`.

However, are we sure that all procs mean of fid scores is equal to fid score computed of all procs ?

**Comment by sdesrozis** [comment]
> If you need to reduce values manually, you can just skip `sync_all_reduce` and call `idist.all_reduce` on what you need to reduce. We are doing similar things for EpochMetric where we need to do `all_gather`.

Sure, we can do manually things, it's my first example. However, maybe we could do better. 

> However, are we sure that all procs mean of fid scores is equal to fid score computed of all procs ?

No that is not equivalent. FID is a very bad distributed algorithm. In fact, only the feature extraction over batches can be done in parallel. After that, features would be broadcasted. We will provide this mode (expensive but correct) and a cheaper but approximate.

**Comment by vfdev-5** [comment]
Can we close this issue ?
