### ISSUE TITLE
Alternative to the command scontrol

### ISSUE THREAD

**Issue by sdesrozis** [pytorch/ignite#2051]
## 🚀 Feature

Using `idist` on a slurm cluster relies on the command `scontrol` for selecting an hostname as `MASTER_ADDR`.

https://github.com/pytorch/ignite/blob/86cec1165441a945c93c938c23544ac52a17a170/ignite/distributed/comp_models/native.py#L258

As discussed in #2048, we should provide another way whether the command missing, for instance, using container launcher as `pyxis`.

**Comment by vfdev-5** [comment]
@sdesrozis any ideas how quickly we could support that ?

**Comment by sdesrozis** [comment]
https://sphinx-python.readthedocs.io/en/latest/source/hostlist.html ?
