### ISSUE TITLE
Wrong docstrings for Metric `update` method's input type

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2054]
## 📚 Documentation

For example, [accuracy documentation](https://pytorch.org/ignite/metrics.html#ignite.metrics.Accuracy) says that 

> update must receive output of the form `(y_pred, y)` or `{'y_pred': y_pred, 'y': y}`.

which is incorrect as it can only takes `(y_pred, y)` but `iteration_completed` can handle both types.

**Comment by afzal442** [comment]
Want to take up this.

**Comment by vfdev-5** [comment]
@afzal442 thanks for proposing help with this issue, I'm not sure what should be done here. Either code improvement or removing this from docs...

**Comment by afzal442** [comment]
As per the issue fallback, we need to fix docs, I believe.

Also after quick overview I found, `updates internal variables and accumulators with provided batch output (y_pred, y)`.
```python 
def update(self, output: Sequence[torch.Tensor]) -> None:
```

**Comment by sallycaoyu** [comment]
> @afzal442 thanks for proposing help with this issue, I'm not sure what should be done here. Either code improvement or removing this from docs...

Hi @vfdev-5 @afzal442, may I take up this issue? And since this issue has been raised for a while, may I know if you currently have a preference between these two options or not, if regarding the overall design of pytorch-ignite? Thanks in advance!

**Comment by vfdev-5** [comment]
@sallycaoyu yes, sure, you can try to tackle this one. I think it would be better to update the docs only, right now.

**Comment by sallycaoyu** [comment]
> @sallycaoyu yes, sure, you can try to tackle this one. I think it would be better to update the docs only, right now.

Thanks for the suggestion! I will try to update the docs then.
