### ISSUE TITLE
Update circle CI pytorch images 1.8.1 -> 1.9

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2065]
## 🚀 Feature

Update : https://github.com/pytorch/ignite/blob/4ead17cf4cf96022d77704b39045feffc6e0f2b8/.circleci/config.yml#L3-L29

https://hub.docker.com/layers/pytorch/pytorch/1.9.0-cuda11.1-cudnn8-runtime/images/sha256-e04020e1b6cc744659c70f5afdc0ab602486f24d74f9ba44929c14b7442dca31?context=explore

**Comment by afzal442** [comment]
Is it like refactoring the version from 1.8.1 to 1.9? T!
e.g.
`default: "pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime" `

**Comment by ydcjeff** [comment]
> Is it like refactoring the version from 1.8.1 to 1.9? T!
> e.g.
> `default: "pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime" `

Yes @afzal442
