### ISSUE TITLE
`linkcheck` job fails on release event

### ISSUE THREAD

**Issue by trsvchn** [pytorch/ignite#2066]
## 🐛 Bug description

ci docs `linkcheck` job fails on release event.

https://github.com/pytorch/ignite/runs/2861705532?check_suite_focus=true#step:6:480

---

Possible Solution to prevent this in a future:
Turn on docs workflow triggering for dev branches.
Perfect solution:
Trigger only for release-like branches: x.x.x

## Environment

GH Actions runtime
- Any other relevant information:

**Comment by ydcjeff** [comment]
I think this is due to this revert commit: 57b1d200e7ca56e39b1b8456749cc1a3fecb3681 which is not on master, so the check failed.

**Comment by vfdev-5** [comment]
Yes, certainly due to that, I think there are two points to address here:
- workflow should run on origin branches (let's say any branch)
- fix the issue on 0.4.5 branch

Would you like to tackle this issue, @ydcjeff ?

**Comment by ydcjeff** [comment]
If we have a release branch naming (like `v.x.x.x` or `x.x.x`), we could run on any other branch

**Comment by vfdev-5** [comment]
To avoid collisions:
- release branches: x.x.x
- tags created from release branches: vx.x.x

**Comment by ydcjeff** [comment]
Ohh! We could run the action only on push and pull, no need to filter with branches
