### ISSUE TITLE
Bug Definition MBConv Class - EfficientNet_Cifar100_finetuning.ipynb

### ISSUE THREAD

**Issue by log-layer** [pytorch/ignite#2072]
Hi, I think a found a bug in one of the PyTorch examples:

## 🐛 Bug description

In the iPython notebook "EfficientNet_Cifar100_finetuning.ipynb", there is a bug in the definition of the MBConv class:

In the third line after the sub-section `# Add identity skip`, the function `_drop_connect` is called without assigning the returned values to x. The code simply says `self._drop_connect(x)` instead of `x = self._drop_connect(x)`. The final operation performed inside `_drop_connect` does not occur in-place :)

**Comment by sdesrozis** [comment]
@log-layer Thank you for pointing out this !!

What do you think about submitting a PR to correct this error ? It would be a great help.

**Comment by log-layer** [comment]
@sdesrozis Thank you for the feedback, I just created a pull request. I hope that everything is ok, this is my first time performing a contribution.
