### ISSUE TITLE
[Examples] RL example implementation

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#208]
I'm trying to port [actor-critic example](https://github.com/pytorch/examples/blob/master/reinforcement_learning/actor_critic.py) to ignite. Here is ported [code](https://github.com/vfdev-5/ignite/blob/rl_example/examples/actor_critic.py). The logic is not that straight forward but if user understands how `ignite.engine` works it can be implemented without problems. 

Some term correspondences:
```
episode <-> epoch
timestep <-> iteration
```
However, ignite lacks of an option that maybe typical for RL, that when episode is finished when agent is failed for example, we need to stop our "batch" iterations, execute handlers and go on the next epoch. On the other hand `ignite.engine` provides `should_terminate` flag that can stops the training and it is not what we would like to do.

Any thoughts?

**Comment by alykhantejani** [comment]
I'm not quite clear about what you mean by "stop our batch iterations", does that mean just kill a batch mid processing? 

I'm not familiar with RL at all so this is new to me, but can it be handled by adding a new event to engine?

**Comment by vfdev-5** [comment]
Yes, just stop a batch iterations in a middle. Take a look [here](https://github.com/pytorch/examples/blob/master/reinforcement_learning/actor_critic.py#L98):
```python
        for t in range(10000):  # Don't infinite loop while learning
            action = select_action(state)
            state, reward, done, _ = env.step(action)
            if args.render:
                env.render()
            model.rewards.append(reward)
            if done:
                  break
```

An episode is started and there is an iteration over timesteps (batches in our terminology). Given a state an action is proposed `action = select_action(state)` and then environment reaction on the action `state, reward, done, _ = env.step(action)`. Then they store the reward for the action and see if the episode is finished or not. This makes sense to check if the system is failed to stabilize the Cart-Pole model and so no need to continue anymore (-> restart).

> can it be handled by adding a new event to engine?

Maybe it is possible but in any case we should exit earlier the [batch loop](https://github.com/pytorch/ignite/blob/master/ignite/engine/engine.py#L166). With the actual ignite code I'm not sure if it is possible...

**Comment by alykhantejani** [comment]
We should be able to do this with a normal handler attached to the `ITERATION_COMPLETE` event. we just need another `terminate` flag that terminates the epoch but not the whole trainer. 

Now I understand your original message :)

**Comment by alykhantejani** [comment]
If this is basically all that is blocking RL applications, that's great news as its easy to fix without breaking any API 🎉

**Comment by vfdev-5** [comment]
> we just need another terminate flag that terminates the epoch but not the whole trainer.

Yes, I agree this can a solution for that :)

**Comment by alykhantejani** [comment]
@vfdev-5 is this now unblocked since #210 was merged?
