### ISSUE TITLE
Incomplete section in documentation

### ISSUE THREAD

**Issue by thistlillo** [pytorch/ignite#2089]
## 📚 Documentation

Please have a look at section 2 in:
https://pytorch-lightning.readthedocs.io/en/latest/starter/converting.html#converting

The title is `2. Move the optimizer(s) and schedulers`, but there is only one example for the optimizers. I think that at least the name of the corresponding method for the schedulers would be very helpful for those starting to use the library.

Cheers

**Comment by KickItLikeShika** [comment]
Hi @thistlillo, I think you opened the issue in the wrong repository

**Comment by vfdev-5** [comment]
@thistlillo check out our docs and examples : https://pytorch.org/ignite/ instead

**Comment by thistlillo** [comment]
I think you are absolutely right and I beg your pardon. Sorry.
