### ISSUE TITLE
Add missing distributed tests to core handlers

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2101]
## 🚀 Feature

- Early stopping:

Currently, early stopping tests does not run any distributed tests with horovod:
https://github.com/pytorch/ignite/blob/a75d228ddae9558f925384bf3a199832c78de8c3/tests/ignite/handlers/test_early_stopping.py#L336-L352

ToDo:
- [x] add hvd distributed test similarly to 
https://github.com/pytorch/ignite/blob/a75d228ddae9558f925384bf3a199832c78de8c3/tests/ignite/metrics/test_accuracy.py#L576-L588

- [x] add xla tests similarly to 
https://github.com/pytorch/ignite/blob/a75d228ddae9558f925384bf3a199832c78de8c3/tests/ignite/metrics/test_accuracy.py#L591-L617

- Checkpoint:

Same for Checkpoint tests
https://github.com/pytorch/ignite/blob/a75d228ddae9558f925384bf3a199832c78de8c3/tests/ignite/handlers/test_checkpoint.py#L1190-L1212

ToDo:
- [ ] add hvd distributed test similarly to 
https://github.com/pytorch/ignite/blob/a75d228ddae9558f925384bf3a199832c78de8c3/tests/ignite/metrics/test_accuracy.py#L576-L588

If you would like work on this issue, please comment out and say which part you would like to cover.
A PR should contain new code, tests and documentation updates. Please see our contributing guide: https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md
A draft PR can be sent and maintainers can help to iterate over the remaining tasks.

**Comment by Ishan-Kumar2** [comment]
Interested in this, will raise a PR soon!

**Comment by vfdev-5** [comment]
@Ishan-Kumar2 it remains adding hvd tests to Checkpoint. Would you like to help with that as well to finalize this issue ?

**Comment by Ishan-Kumar2** [comment]
@vfdev-5 sure, I will raise a PR soon.
