### ISSUE TITLE
NVIDIA/APEX installation errors on Colab

### ISSUE THREAD

**Issue by sdesrozis** [pytorch/ignite#2113]
## 🐛 Bug description

#2112 

Due to a mismatch on PyTorch binaries and compilation tools installed on colab, NVIDIA/APEX installation doesn't work.

See the discussion 
https://github.com/pytorch/ignite/issues/2112#issuecomment-881316895

## Environment

- PyTorch Version (e.g., 1.4): Colab
- Ignite Version (e.g., 0.3.0):
- OS (e.g., Linux): Colab
- How you installed Ignite (`conda`, `pip`, source): Colab
- Python version: Colab
- Any other relevant information:

**Comment by vfdev-5** [comment]
@sdesrozis we can put the following into the cells where we are installing nvidia/apex:
```
# If torch cuda version and nvcc version match:
!pip install --upgrade --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" git+https://github.com/NVIDIA/apex/
# if above command is failing, please install apex without c++/cuda extensions:
# !pip install --upgrade --no-cache-dir git+https://github.com/NVIDIA/apex/
```

**Comment by 01-vyom** [comment]
Seems pretty simple, just have to add the above line in all of the `.ipynb` files. Can I work on this issue?

**Comment by vfdev-5** [comment]
@01-vyom yes, please
