### ISSUE TITLE
Improve doc examples rendering

### ISSUE THREAD

**Issue by KickItLikeShika** [pytorch/ignite#2114]
Currently we are rendering our examples in the docs like this https://pytorch.org/ignite/generated/ignite.engine.engine.Engine.html#ignite.engine.engine.Engine which is not very neat.
What we want to do is to find a better way to make it more good looking, and update our docs examples

![image](https://user-images.githubusercontent.com/2459423/129027565-5363ac3b-03ec-4f72-a41e-c3d1441cc7f5.png)

- Replace "Examples" with some sphinx tag or something else, for example, like scikit-image does:

![image](https://user-images.githubusercontent.com/2459423/129027830-7c9a8295-78db-41f7-9f72-5dd71bce72d6.png)

**Comment by Ketan-Kapse** [comment]
Hi @KickItLikeShika, I'm interested in working on this issue! It would be my very first contribution.

**Comment by KickItLikeShika** [comment]
Hi @Ketan-Kapse, thanks a lot for showing interest! You're welcome to send PRs to tackle this

**Comment by FarehaNousheen** [comment]
Hi, I'm not clear about the suggested ways of improving the doc. Kindly guide me on this so that I can proceed ahead in improvising this.

**Comment by KickItLikeShika** [comment]
Hi @FarehaNousheen, you can see here how we render examples https://github.com/pytorch/ignite/issues/2114, if you're familiar with Sphinx, we are using Sphinx to create our docs: https://www.sphinx-doc.org/en/master/. We would like to change the way we render our examples, we left a suggestions in the description of the issue, if you have another idea to render our docs we can discuss it here. 
For the idea in the description you can check how scikit-learn does that in their codebase, and replicate it here.
