### ISSUE TITLE
Do not wrap existing DistributedSampler in DistributedProxySampler in auto_dataloader()

### ISSUE THREAD

**Issue by aschuh-hf** [pytorch/ignite#2118]
## 🚀 Feature

I've looked at the implementation of ``ignite.distributed.auto_dataloader()`` and found that when the data loader has a sampler set, it will always wrap this sampler in a `DistributedProxySampler`. This works fine when the data loader sampler is of type `Sampler` and does itself not handle distribution of samples across processes. However, in my case I want to distribute samples differently across processes to minimize cache misses with my custom map-style dataset which buffers chunks of data. This places some constraints on how indices should be grouped based on rank, i.e., which indices should be assigned to the same process. Currently, the only work-around is to use an iterable dataset instead.

However, I would think that the lines:
https://github.com/pytorch/ignite/blob/0f7819a5d2f5c17697eaf4f01848a54ed43e6e53/ignite/distributed/auto.py#L86-L89

could be changed to keep the user provided instance (of a subclass) of `DistributedSampler` if set.

**Comment by sdesrozis** [comment]
@aschuh-hf Thank you for this request !!

Maybe you could try providing the `batch_sampler` rather than the `sampler` ? Anyway, we will have a look !

**Comment by vfdev-5** [comment]
@aschuh-hf thanks for FR and giving the context, it helps to understand !

> However, I would think that the lines: ... could be changed to keep the user provided instance (of a subclass) of DistributedSampler if set.

Yes, I agree that we can think about adding this possiblity to skip wraping `sampler` as `DistributedSampler` with `DistributedProxySampler`.

**Comment by aschuh-hf** [comment]
@sdesrozis I see, providing a `BatchSampler` that wraps my distributed sampler is a better option indeed than using a proxy `IterableDataset` that wraps the map-style dataset and custom sampler.

Still, having a distributed sampler wrapped by another distributed sampler doesn't seem quite right. I think it should at least trigger a warning or error if not supported by Ignite? But passing on the users distributed sampler to the data loader should be an easy enough change, possibly checking only that the `rank` and `num_replicas` attributes of the existing sampler matches with `ignite.distributed.get_rank()` and `ignite.distributed.get_world_size()`.

I can provide a PR for this.

**Comment by vfdev-5** [comment]
> Still, having a distributed sampler wrapped by another distributed sampler doesn't seem quite right. I think it should at least trigger a warning or error if not supported by Ignite? But passing on the users distributed sampler to the data loader should be an easy enough change, possibly checking only that the rank and num_replicas attributes of the existing sampler matches with ignite.distributed.get_rank() and ignite.distributed.get_world_size().

Yes, I agree.

>  I can provide a PR for this.

Sounds great ! Let me assign it to you.

**Comment by schuhschuh** [comment]
Ok, I've submitted two separate PRs. One that just raises an error in `DistributedProxySampler` to avoid wrapping a `DistributedSampler` and the other that modifies `auto_dataloader()` to allow users to provide their own distributed sampler.

**Comment by vfdev-5** [comment]
@schuhschuh thanks! Sounds good !
