### ISSUE TITLE
[Feature Request] Neural Style example

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#212]
Following #202 idea is to port fast neural style example from official [pytorch examples](https://github.com/pytorch/examples/tree/master/fast_neural_style).

**Comment by anmolsjoshi** [comment]
@vfdev-5 , I'm interested in helping out with this issue. 

I've been wanting to contribute to open source for a while, and this would be a good start.

**Comment by vfdev-5** [comment]
@anmolsjoshi sounds good! Feel free to post any questions here, e.g if you have problems with implementation or encounter some limits of the API.
You can inspire from other examples on how to port examples from official pytorch examples to ignite.
We have smoke tests for the examples, so once your code is locally running and gives similar results as the original official one, then you will need to integrate it into `.travis.yaml`.
When you are done with the code in your fork in a branch (e.g. named neural_style_example), then please submit a PR, we will review it and if everything is OK, CI passes, then it will merged into the master and it will be your first contribution to Ignite :)

**Comment by anmolsjoshi** [comment]
@vfdev-5 Thanks for the input! I've already gotten started on this project.

**Comment by alykhantejani** [comment]
@anmolsjoshi thanks for taking this up, and welcome to open source!

**Comment by anmolsjoshi** [comment]
@alykhantejani thanks! 

@vfdev-5 I have been able to reproduce results of the original example, it is working locally. I am unfamiliar integrating the code with .travis.yaml. Any guidance on that?

**Comment by vfdev-5** [comment]
@anmolsjoshi good news! So, about `.travis.yaml`. We are just providing a sort of smoke tests for examples = run example in a tiny configuration and check that returned code is 0. For example,
https://github.com/pytorch/ignite/blob/c4563ddc67bee03fc616e87b84abd9b5e17e21cc/.travis.yml#L36
In your case you can add after the line with RL examples a command to run your example: (smth like that)
```
- python examples/fast_neural_style/neural_style.py --epochs 1
```

When you send a PR, it will be executed with travis and it will give you the result of the run.
While in the PR you can make any number of modifications of the code you want, so if it does not work from the first time you can fix it with another commit. When PR is accepted we will squash all in a single commit, no problems.

**Comment by anmolsjoshi** [comment]
@vfdev-5  thanks for the help! this code requires MSCOCO dataset and a few images downloaded before, to run correctly. Am I supposed to incorporate that into the .travis.yaml file? Sorry if this is a dumb question.

**Comment by vfdev-5** [comment]
@anmolsjoshi 
> this code requires MSCOCO dataset and a few images downloaded before, to run correctly. 

If it possible to run training on Cifar10 instead of MSCOCO would be better. I mean if `--dataset` option could recieve a path and a str `cifar10` and then configure the [dataloader](https://github.com/pytorch/examples/blob/master/fast_neural_style/neural_style/neural_style.py#L43) with CIfar10 dataset. What do you think ?

Could you please also send a PR, we will consider it as Work-in-progress to take a look on your code and iterate on what can be done.

**Comment by anmolsjoshi** [comment]
@vfdev-5 Can this be closed?
