### ISSUE TITLE
"Accuracy must have at least one example before it can be computed."

### ISSUE THREAD

**Issue by riyaj8888** [pytorch/ignite#2124]
NotComputableError "Accuracy must have at least one example before it can be computed."

may i know why its coming

**Comment by trsvchn** [comment]
@riyaj8888 Thanks you for your question and interest in PyTorch-Ignite!
To compute accuracy we need two tensors: y_pred and y. Every iteration Accuracy (in attached form) accumulates value via calling update method: .update(y_pred, y).
At the end of each epoch engine invokes another Accuracy method update, responsible for computing average value of the accuracy.

Thus, if you try to run compute method with out priors update you will receive this error.

**Comment by vfdev-5** [comment]
Close as stale
