### ISSUE TITLE
[Docs] Improve output_transform description

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#213]
I think current [description of `output_transform`](https://github.com/pytorch/ignite/blob/master/ignite/metrics/metric.py#L16) is not very clear:
```
output_transform (callable): a callable that is used to transform the
            model's output into the form expected by the metric. This can be
            useful if, for example, you have a multi-output model and you want to
            compute the metric with respect to one of the outputs.
```
Probably, we need to a small example to show that `output_transform` is applied on `engine.state.output` that is eventually is the output of update function and not model's output as it could be understood from the doc string.

Any thoughts?

**Comment by jasonkriss** [comment]
I agree that this is not very clear. I think a small tweak in the wording along with a minimal example would be great. Perhaps just have an update function that returns a dict and then have the output_transform access a member of the dict. I think that'd be enough to illustrate what this can be used for.
