### ISSUE TITLE
[CI] Fix "Trigger Build and Push Docker images to Docker Hub"

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2131]
- https://github.com/pytorch/ignite/runs/3223083163?check_suite_focus=true#step:4:1

I have to renew the access token. It can not be org one but user's one.

**Comment by trsvchn** [comment]
For the future we can try to split this workflow of 2 jobs into 2 workflows:
pip build workflow -> trigger docker workflow


https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run

**Comment by vfdev-5** [comment]
Updated CIRCLE_TOKEN and rebuilt new images:
- https://hub.docker.com/u/pytorchignite
- https://app.circleci.com/pipelines/github/pytorch/ignite/2071/workflows/e3521eac-2365-4463-8b85-a518571367eb/jobs/6341

Closing as solved
