### ISSUE TITLE
Update versionadded/versionchanged in master accordning to the latest releases

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2133]
Currently, we are manually updating versionadded/versionchanged for each v0.4.X release:
- https://github.com/pytorch/ignite/commit/eee8dc5159eaec741d677c8a6db9f7ba00d50afa
- https://github.com/pytorch/ignite/commit/84e51c3b4987c16f6dd27a6abd2f9ff95da3dc6c
- https://github.com/pytorch/ignite/commit/84e51c3b4987c16f6dd27a6abd2f9ff95da3dc6c

Tasks to do to fix this issue:
- [ ] Let's update versionadded/versionchanged in the master according to v0.4.6 release: https://github.com/pytorch/ignite/tree/0.4.6 . We need to find all mentions of `0.4.5` and `0.4.6` in v0.4.6 and port them to the master.
- [ ] Add `.. versionadded:: 0.4.6` as [here](https://github.com/pytorch/ignite/blob/84e51c3b4987c16f6dd27a6abd2f9ff95da3dc6c/ignite/handlers/stores.py#L37) to `FastaiLRFinder` here: https://github.com/pytorch/ignite/blob/3ef85e1b7af58cfbcf2033d62085a759aa722cc1/ignite/handlers/lr_finder.py#L73

**Comment by Chandan-h-509** [comment]
Hi @vfdev-5 . I am new to PyTorch Ignite and would like to work on this issue to gain some experience.

**Comment by Chandan-h-509** [comment]
Sure.. I'll start working on it. Thank you @vfdev-5

**Comment by Chandan-h-509** [comment]
Hey @vfdev-5 .
I have found all the mentions of 0.4.5 and 0.4.6 in v0.4.6.
Can you kindly help me in proceeding further.

**Comment by vfdev-5** [comment]
Please submit a draft PR. Here is a guideline on how to fork and create a PR : https://github.com/firstcontributions/first-contributions
Make sure to accomplish both tasks from this issue description. Thanks
