### ISSUE TITLE
`ignite.contrib.metrics.roc_auc` does not invoke `output_transform`? Is it by design?

### ISSUE THREAD

**Issue by lyhyl** [pytorch/ignite#2159]
## ❓ Questions/Help/Support

`ignite.contrib.metrics.roc_auc` does not invoke `output_transform`?
Is it by design?

ignite==0.4.6

```
def ToConfidence(output) -> tuple:
    pred, y = output
    pred = pred[:,1]
    return pred, y

aucmeter = roc_auc.ROC_AUC(ToConfidence) # it will not invoke `ToConfidence`
aucmeter.update((pred, y))
aucmeter.compute() # raise Exception here
```
So, I have to do it manually
```
def ToConfidence(output) -> tuple:
    pred, y = output
    pred = pred[:,1]
    return pred, y

aucmeter = roc_auc.ROC_AUC()
aucmeter.update(ToConfidence((pred, y))) # do it manually
aucmeter.compute() # works fine
```

**Comment by vfdev-5** [comment]
@lyhyl yes, you are right, output transform is not called if using reset/update/compute API and should be called manually. However, it is automatically called if metric is attached to Engine.

**Comment by lyhyl** [comment]
> @lyhyl yes, you are right, output transform is not called if using reset/update/compute API and should be called manually. However, it is automatically called if metric is attached to Engine.

OK. But it is strange to me that metric takes `output_transform` to construct but does not use it. Why not make `output_transform` as parameter of Engine?

**Comment by vfdev-5** [comment]
yes, that's right Engine can be used with different metrics with different output_transforms.

>  Or let metric calls it automatically?

output_transform is applied automatically in `iteration_completed` method. For custom metrics, `update` method is implemented by user and in the current design we didn't ask user to call output_transform there.
I agree that it would be nice to fix this design issue.

**Comment by Abdullahaml1** [comment]
The Issue is still exists why is it closed ?
