### ISSUE TITLE
[Feature Request] Class handles

### ISSUE THREAD

**Issue by AntoinePrv** [pytorch/ignite#216]
I came across some cases (for Visdom callbacks but this is not limited to this) where I found it useful to add a whole object as a handle.

There are examples such as the [early stopping](https://github.com/pytorch/ignite/blob/0cd7c9b57174947b6a1428b7897f641522145e44/ignite/handlers/early_stopping.py) implementing the `__call__` function but this is **not** what I mean.

One could write a class with methods such as `handle_epoch_started(self, engine)` and `handle_iteration_completed`. When adding the whole object, every method starting with `handle_` (in this example) will be added to the relevant callback.

I wrote some code for myself (where the method can add multiple objects at once):

```python
def ignite_auto_add(engine, *handle_objects):
    """Add handle objects.

    For every object given, loop over the methods of the object looking for
    methods matching `handle_{name}`and adds it using the mathcing
    `add_handle_name`.
    This comes handy when wanting to do an object to abstact interactions
    between multiple handles.

    Parameters
    ----------
    *handle_objects : sequence of objects
        In every object, we look for specific handle method to add to the engine.
        Handle method should take one parameter which will be given the
        current instance.

    """
    # Loop over every handle object given
    for handle in handle_objects:
        # Loop over all methods of the current handle
        for func_name in dir(handle):
            # Look for mehtod starting with "handle_"
            if func_name.startswith("handle_"):
                # Loop over events looking for a match
                for event in Events:
                    if event.value in func_name:
                        # Add function to engine
                        func = getattr(handle, func_name)
                        engine.add_event_handler(event, func)
```

This helps writing more encapsulated handles.

**Comment by vfdev-5** [comment]
@AntoinePrv correct me if I misunderstood your proposition, but you would like to introduce a sort of callback class being interpretable by event handling system ? [Here](https://github.com/pytorch/ignite/issues/37) is a discussion on pros/cons of callbacks and why we adopted event handlers.

Could you please I concrete example of such class with multiple event handlers implemented ?

**Comment by AntoinePrv** [comment]
Yes, sorry, I'll leave my comment there for the record #37
