### ISSUE TITLE
Using Bleu for batch input

### ISSUE THREAD

**Issue by Ishan-Kumar2** [pytorch/ignite#2178]
The example provided in docs for Bleu is for Single input. In that case the output from the engine should be in this format
```python

def evaluate_step():
  ...
  predictions = "Predicted Sentence 1".split()
  references = ["Reference Sentence 1".split(), "Reference Sentence 1.2".split()]
  return (predictions, references)

```

When calculating Bleu score for a Batch what is the format for output from the engine?
It should be something like
```python
#For a batch of size 2
predictions = ["Predicted Sentence 1".split(), "Predicted Sentence 2".split()]
references = [["Reference Sentence 1.1".split(), "Reference Sentence 1.2".split()], ["Reference Sentence 2.1".split(), "Reference Sentence 2.2".split()]]
```
Doing this gives an error. 
```python
TypeError: unhashable type: 'list'
```
The typing for `update` requires predictions to be a `Sequence[Any]` and References to be `Sequence[Sequence[Any]]]`. Does this mean the batch input is not possible?

**Comment by vfdev-5** [comment]
Cc @sdesrozis @gucifer

**Comment by sdesrozis** [comment]
@Ishan-Kumar2 Thanks for this question.

You are right, we didn't expose a batchwise api. Note that the internal function to compute the bleu score could be use in that sense. However, it will compute a bleu score per batch which would be different to a batch bleu score.

https://github.com/pytorch/ignite/blob/cc2c1aa9e31c297f8eb8fe14f3301dd201be8e48/ignite/metrics/nlp/bleu.py#L190

Would you like to help on this ? It would be a great improvement to fix the batch usage.

**Comment by Ishan-Kumar2** [comment]
@sdesrozis thanks for the update, I am interested in contributing to this.
I agree we should implement the micro avg version also. Then the `corpus_bleu` can be renamed to `sentence_bleu` and the new `corpus_bleu` should be used for corpus/batch level calculations.

**Comment by sdesrozis** [comment]
Firstly, the `_corpus_bleu` should be split in 2 parts : (1) the accumulation of ngrams counter (maybe the lenghts of cand/hyp too) and (2) the computation of bp, smoothing and geometric mean. The sentence bleu score (ie macro avg) is (1) + (2) for each sentence and (3) average. The corpus bleu score (ie micro avg) is (1) for each sentence then (2). 

For batch version, the macro avg means apply the sentence score to each sentence of the batch. We must add a loop over the batch, it is quite straighforward. The micro avg is natively fine with batch version (apply (1) on batch then (2)).

For DDP, the work is fine for the actual macro avg. Concerning the micro avg version, a synchronization is needed to sum the different counters and lenghts. 

HTH

**Comment by Ishan-Kumar2** [comment]
Hey @sdesrozis 
Since the `_corpus_bleu` already has a loop to iterate over a batch, what if instead of splitting it into 2 seperate functions, we call it once for micro-avg case and multiple times(for each hypothesis in batch) for macro avg.
Like this

```python
def update(self, output: Tuple[Sequence[Sequence[Any]], Sequence[Sequence[Sequence[Any]]]], macro_averaging=False) -> None:
        y_pred, y = output
        
        if macro_averaging:
            #Calculate bleu score for each hypothesis indiviually and then average
            for refs, hyp in zip(y, y_pred):
                self._sum_of_bleu += self._corpus_bleu(references=[refs], candidates=[hyp])
                self._num_sentences += 1

        else:
            #Calculate bleu for entire corpus
            self._sum_of_bleu += self._corpus_bleu(references=y, candidates=y_pred)
            self._num_sentences += 1
```
