### ISSUE TITLE
CI XLA failing test: test_ema_final_weight_distrib_single_device_xla

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2181]
tests/ignite/handlers/test_ema_handler.py::test_ema_final_weight_distrib_single_device_xla

- https://github.com/pytorch/ignite/pull/2180/checks?check_run_id=3471518836#step:9:147

```
_test_ema_final_weight(get_dummy_model(), device=device, ddp=True)

...

actual = tensor([[4.0625, 4.0625]], device='xla:0', dtype=torch.float64)
expected = tensor([[4.0625, 4.0625]], device='xla:0', dtype=torch.float64)

> Operator __and__ is only supported for integer or boolean type tensors, got: f64[1,2]{1,0}
```

cc @sandylaker

**Comment by sandylaker** [comment]
@vfdev-5 Thanks for the cc. I will create a PR to fix it as soon as possible.

**Comment by vfdev-5** [comment]
Thanks @sandylaker , I think we can cast it tensors to f32 for xla without any harm...

**Comment by sandylaker** [comment]
@vfdev-5 I have a question. It would be nice if you could help me. 

Why is this test only failed on XLA devices? 

We first intialize a dummy model (nn.Linear). By default the `dtype` of `weight.data` is `torch.float32`. So why is the `dtype` of the actual tensor is `torch.float64` as shown in the log message above?

**Comment by vfdev-5** [comment]
@sandylaker good question. Seems like the cast happens inside `torch.testing.assert_allclose`:
https://github.com/pytorch/ignite/pull/2182/checks?check_run_id=3473653855#step:9:206

**Comment by sandylaker** [comment]
> @sandylaker good question. Seems like the cast happens inside `torch.testing.assert_allclose`:
> https://github.com/pytorch/ignite/pull/2182/checks?check_run_id=3473653855#step:9:206

@vfdev-5 So a floating point will casted to `torch.float64` anyway, according to [torch.testing](https://github.com/pytorch/pytorch/blob/0ef8760bf6b3e8098ef42df60f1e451234151f32/torch/testing/_asserts.py#L396). But I think the problem might be caused by `torch_xla`. Please have a look at my comments in the PR #2182 .
