### ISSUE TITLE
Automatic jupyter environment detection

### ISSUE THREAD

**Issue by sdesrozis** [pytorch/ignite#2187]
## 🚀 Feature

Running code from jupyter (Colab or whatever), one have to add the argument `start_method="fork"` in order to launch a parallel run.

https://github.com/pytorch/ignite/blob/4a243a1b1045ddd1ca8c70afe153b1b208777213/ignite/distributed/launcher.py#L114

An idea would be to detect if a jupyter environment is used and automatically add the `start_method` value if necessary.

EDIT:
this is already done for XLA : 
https://github.com/pytorch/ignite/blob/4a243a1b1045ddd1ca8c70afe153b1b208777213/ignite/distributed/comp_models/xla.py#L121-L122

The idea is to override "start_method" here:
https://github.com/pytorch/ignite/blob/4a243a1b1045ddd1ca8c70afe153b1b208777213/ignite/distributed/comp_models/native.py#L375 
if we can detect Jupyter related environment variables.

**Comment by Chandan-h-509** [comment]
Hey @sdesrozis . I would like to work on this issue.

**Comment by sdesrozis** [comment]
@Chandan-h-509 Thank you for the help !
