### ISSUE TITLE
Compatibility with `torch.distributed.elastic`?

### ISSUE THREAD

**Issue by tadejsv** [pytorch/ignite#2191]
Is ignite compatible with [`torch.distributed.elastic`](https://pytorch.org/docs/stable/distributed.elastic.html)? Namely, do `auto_model` and other utils work if the script is launched using `torch.distributed.run`, instead of `torch.distributed.elastic`?

**Comment by vfdev-5** [comment]
@tadejsv thanks for the question. I'd say no changes required in ignite code for using torch distributed elastic.
[cifar10 example](https://github.com/pytorch/ignite/tree/master/examples/contrib/cifar10) with a single node can be run without issues:
```
python -u -m torch.distributed.run --nnodes=1:1 --nproc_per_node=2 --rdzv_id=0 --rdzv_backend=c10d --rdzv_endpoint=localhost --use_env main.py run --backend="nccl"
```

**Comment by tadejsv** [comment]
That's great, thanks for confirming
