### ISSUE TITLE
Automatically detect `DiskSaver` as `save_handler` in `Checkpoint`

### ISSUE THREAD

**Issue by Priyansi** [pytorch/ignite#2194]
## 🚀 Feature

Currently, when we use `Checkpoint`, we have to specify a `save_handler` even when we want to store the checkpoints on disk:
```python
handler = Checkpoint(
        to_save, DiskSaver('/tmp/models', create_dir=True), n_saved=2
   )
```
An enhancement can be to automatically detect the `save_handler` as `DiskSaver` if a path is passed, like this:
```python
handler = Checkpoint(
        to_save, create_dir=True, dir_name='/tmp/models', n_saved=2
   )
```
Internally, 
```python
if dir_name is not None:
    save_handler = DiskSaver(path, create_dir = create_dir)
```

**Comment by vfdev-5** [comment]
@Priyansi thanks for FR. Actually I was thinking about the following:
```python
handler = Checkpoint(to_save, "/tmp/models", n_saved)
```
where 2nd arg is `save_handler: Union[Callable, BaseSaveHandler],` which be updated to 
`save_handler: Union[str, Callable, BaseSaveHandler],` and internally interpreted as you suggested:
```python
if isinstance(save_handler, str):
    save_handler = DiskSaver(path, create_dir=True)
```

What do you think ?

**Comment by Priyansi** [comment]
Yeah sounds good. Should I send a PR for this?

**Comment by vfdev-5** [comment]
@Priyansi yes, please
