### ISSUE TITLE
Improve GHA CI when old pytorch nightly version is installed

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2199]
From time to time we have tests failing when using pytorch nightly because of old version is installed.
For example: https://github.com/pytorch/ignite/runs/3620746086

Failing tests:
```
FAILED tests/ignite/distributed/test_auto.py::test_auto_methods_gloo - Assert...
FAILED tests/ignite/distributed/test_auto.py::test_auto_methods_gloo - Assert...
```
because of at "Install dependencies" step, conda installed 
```
pytorch-1.9.0.dev20210415  |py3.7_cuda10.1_cudnn7.6.3_0       676.5 MB  pytorch-nightly
```
which dates on April 2021 and not September (today).

Let's add an option to skip all other tests if we detect that pytorch nightly version date is 2 months old.

This issue is open for everyone to tackle if interested in working with CI and Github Actions.

**Comment by ydcjeff** [comment]
I suggest to use `pip` instead of miniconda.

**Comment by vfdev-5** [comment]
Why it would solve the problem of installing old package ?

**Comment by ydcjeff** [comment]
We can define the PyTorch S3 URL for installation.
https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html doesn't have 1.9.0 binaries.

**Comment by vfdev-5** [comment]
In this case we have to generate the name of wheel we need by today, yesterday date + python version etc... I think it may be more complex than just verify conda installed package date from version and stop further tests if date is 2-3 months old.

**Comment by ydcjeff** [comment]
I think we don't need to generate date. This nightly command is shown on pytorch.org.
```sh
pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
```

**Comment by vfdev-5** [comment]
Technically, if pip would behave as conda for some reason, it could also install an old version, thus we have to check version date as well. Similarly, you can see the files on anaconda : https://anaconda.org/pytorch-nightly/pytorch/files
We can try to replace conda by pip if this implicitly solve the problem...

**Comment by ydcjeff** [comment]
Yes, pip can also behave like conda. But it would be great if pytorch team can remove old binaries from nightly channel.
