### ISSUE TITLE
Bug with `_expand_nodelist`

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2203]
## 🐛 Bug description

```
_expand_hostlist('gpu-compute-on-demand-dy-g4dnxlarge-[1-4]')
> 
['g4dnxlarge-1', 'g4dnxlarge-2', 'g4dnxlarge-3', 'g4dnxlarge-4']
```
but should be
```
scontrol show hostnames 'gpu-compute-on-demand-dy-g4dnxlarge-[1-4]'
>
gpu-compute-on-demand-dy-g4dnxlarge-1
gpu-compute-on-demand-dy-g4dnxlarge-2
gpu-compute-on-demand-dy-g4dnxlarge-3
gpu-compute-on-demand-dy-g4dnxlarge-4
```

## Environment

- PyTorch Version (e.g., 1.4):
- Ignite Version (e.g., 0.3.0): 0.4.6
- OS (e.g., Linux):
- How you installed Ignite (`conda`, `pip`, source):
- Python version:
- Any other relevant information:

cc @sdesrozis

**Comment by sdesrozis** [comment]
Two wrong results
* `c1009a-s17,c1010a-s11`
* `compute-b24-[1-3,5-9], compute-b25-[1,4,8],compute-b25-[2-9,13]`
