### ISSUE TITLE
CI is failing with Visdom tests on macosx

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2229]
## 🐛 Bug description

```
 tests/ignite/contrib/handlers/test_visdom_logger.py::test_logger_init_hostname_port ERROR [ 21%]
tests/ignite/contrib/handlers/test_visdom_logger.py::test_logger_init_env_vars FAILED [ 21%]
tests/ignite/contrib/handlers/test_visdom_logger.py::test_integration_no_executor FAILED [ 21%]
tests/ignite/contrib/handlers/test_visdom_logger.py::test_integration_with_executor FAILED [ 21%]
```

Let's temporarily disable these tests on macosx and fix them later.

- https://github.com/pytorch/ignite/pull/2201/checks?check_run_id=3730936423#step:15:201

## Environment

- PyTorch Version (e.g., 1.4):
- Ignite Version (e.g., 0.3.0):
- OS (e.g., Linux):
- How you installed Ignite (`conda`, `pip`, source):
- Python version:
- Any other relevant information:

**Comment by ydcjeff** [comment]
It's failing on macos, not windows.

**Comment by avats-dev** [comment]
Hey @vfdev-5 , I want to take up this issue and contribute. Can you guide me further on how to implement this?

**Comment by vfdev-5** [comment]
@avats-dev sounds good about helping us with this issue. It is not about implementing things but using pytest skip feature to skip above mentioned tests in order to make CI happy on macosx.

**Comment by avats-dev** [comment]
Ok, I'm working on resolving this. Would let you know if need help somewhere. Thanks!

**Comment by vfdev-5** [comment]
@avats-dev any updates on this issue ?

**Comment by theory-in-progress** [comment]
Hey @vfdev-5! I think I can resolve this issue... Those tests are already being skipped on Windows, I just need to add a statement to make the tests skip on Macos too right?

**Comment by vfdev-5** [comment]
@theory-in-progress if no signs from @avats-dev in 5h, we can accept your PR on this issue as well

**Comment by theory-in-progress** [comment]
Sure! I'll get right on to it.

**Comment by vfdev-5** [comment]
@theory-in-progress you can either check that by setting up the same GH actions on your fork or sending a PR to this repository and we'll see

**Comment by avats-dev** [comment]
Sorry @vfdev-5, I was busy somewhere else so couldn't do this. Good work @theory-in-progress ! 🎉
