### ISSUE TITLE
`pack_sequence` capability

### ISSUE THREAD

**Issue by kl2792** [pytorch/ignite#224]
Is it possible for this to be implemented in Ignite, or should we just call pack_sequence in our LSTM nn.Modules?

Any help appreciated!

**Comment by vfdev-5** [comment]
@kl2792 unfortunately, we have not yet worked on use-cases with RNN/LSTM. So I would say we can call pack_sequence in your model.

I'm not expert in RNNs but if word embeddings are not trainable, so probably this can be done in a custom [`_prepare_batch`](https://github.com/pytorch/ignite/blob/master/ignite/engine/__init__.py#L7) for example if one wants to use [`create_supervised_trainer`](https://github.com/pytorch/ignite/blob/master/ignite/engine/__init__.py#L12).

Anyway, we can discuss here your use-case and see if we can improve Ignite to cover more RNN/LSTM use-cases. 

And as always PR are very welcome :)

**Comment by kl2792** [comment]
Let me know how my PR's code style/content looks! I think this could help resolve this issue with an extra argument:

``` python3
create_supervised_trainer(..., prepare_batch=lambda batch: pack_padded_sequence(batch[0]), batch[1])
```

**Comment by alykhantejani** [comment]
In this case I would also recommend rolling your own version of `create_supervised_trainer` as the current one is meant to serve as a minimalist example (which fits many use cases). 

I would however be interested to know if this was the only change you needed.

Also a RNN example would be great if you want to send a PR :)

**Comment by kl2792** [comment]
Sounds good. I thought about it it a bit more too and realized that I can use the `collate_fn` argument in DataLoader to do this:

``` python3
def collate_fn(batch):
    l, i, t = zip(*sorted((len(x), i, (x, y)) for i, (x, y) in enumerate(batch)), reverse=True))
    x, y = zip(*t)
    return (torch.LongTensor(np.array(l)), pack_sequence(x)), y

DataLoader(..., collate_fn=collate_fn)
```

Thanks for your help!
