### ISSUE TITLE
Update the `black` version and format the strings

### ISSUE THREAD

**Issue by sdesrozis** [pytorch/ignite#2249]
## 🚀 Feature

We currently use `black` version `19.10b0`. The idea is to upgrade to the version `21.9b0` and use the following option 
```
black . --experimental-string-processing
```
to format strings.

This should be included in the script `run_code_style.sh`
```
bash ./tests/run_code_style.sh fmt
```

A point is to check and report the impact of the upgrade.

**Comment by vfdev-5** [comment]
@sdesrozis can you try locally that ? The last time I tried that and black reformatted a lot of code into ugly things like:
```
a = [
    func(
       a,
       b,
       12,
    ) 
]
```

That was principal blocker to update. If the newest version does not produce weird result and our codebase remains practially the same I'd agree to update.

**Comment by vfdev-5** [comment]
in case of 
```python
# original
train_loader = idist.auto_dataloader(
    train_dataset, batch_size=config["batch_size"], num_workers=config["num_workers"], shuffle=True, drop_last=True,
)

# black
train_loader = idist.auto_dataloader(
    train_dataset,
    batch_size=config["batch_size"],
    num_workers=config["num_workers"],
    shuffle=True,
    drop_last=True,
)
```
the last comma after `drop_last=True,` makes it line by line. If you remove it, it should be unexpanded.

**Comment by sdesrozis** [comment]
The option `--skip-magic-trailing-comma` would have helped, it removes last comma. Otherwise, the default is to add a comma at the end of a pack and put one argument per line (can't avoid just the line breaking).
```python
# original
train_loader = idist.auto_dataloader(
    train_dataset, batch_size=config["batch_size"], num_workers=config["num_workers"], shuffle=True, drop_last=True,
)

# black => remove comma
train_loader = idist.auto_dataloader(
    train_dataset, batch_size=config["batch_size"], num_workers=config["num_workers"], shuffle=True, drop_last=True
)
```

```python
# original
return {
    "batch loss": loss.item(),
}

# black => pack on one line (and no comma)
return {"batch loss": loss.item()}
```

**Comment by vfdev-5** [comment]
We are using `--skip-magic-trailing-comma` once, right ? If yes, then ok
