### ISSUE TITLE
[docs] Add doctests for metrics

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/ignite#2265]
### 📚 Documentation

Following #2230 , I listed the metrics places (suggested by @sdesrozis) where doctests can be added.

#### Metrics

- [x] Average (#2332)
- [x] GeometricAverage (#2332)
- [x] VariableAccumulation (This class is an helper, no test needed)
- [x] Accuracy (#2345)
- [x] ConfusionMatrix (#2336)
- [x] ClassificationReport (#2346)
- [x] DiceCoefficient (#2336)
- [x] JaccardIndex (#2336)
- [x] IoU (#2336)
- [x] mIoU (#2336)
- [x] EpochMetric (#2351)
- [x] Fbeta (#2340)
- [x] Loss (#2335)
- [x] MeanAbsoluteError (#2280)
- [x] MeanPairwiseDistance (#2307)
- [x] MeanSquaredError (#2280)
- [x] MetricsLambda (#2352)
- [x] MultiLabelConfusionMatrix (#2347)
- [x] Precision (#2340)
- [x] PSNR (#2311)
- [x] Recall (#2340)
- [x] RootMeanSquaredError (#2307)
- [x] RunningAverage (#2348)
- [x] SSIM (#2241)
- [x] TopKCategoricalAccuracy (#2284)
- [x] Bleu (#2317)
- [x] Rouge (#2317)
- [x] RougeL (#2317)
- [x] RougeN (#2317)
- [x] InceptionScore (#2349)
- [x] FID (#2349)

#### Contrib Metrics

- [x] AveragePrecision (#2341)
- [x] CohenKappa (#2321)
- [x] PrecisionRecallCurve (#2341)
- [x] ROC_AUC (#2341)
- [x] RocCurve (#2341)
- [x] CanberraMetric (#2323)
- [x] FractionalAbsoluteError (#2323)
- [x] FractionalBias (#2323)
- [x] GeometricMeanAbsoluteError (#2323)
- [x] GeometricMeanRelativeAbsoluteError (#2324)
- [x] ManhattanDistance (#2324)
- [x] MaximumAbsoluteError (#2324)
- [x] MeanAbsoluteRelativeError (#2324)
- [x] MeanError (#2324)
- [x] MeanNormalizedBias (#2324)
- [x] MedianAbsoluteError (#2324)
- [x] MedianAbsolutePercentageError (#2324) 
- [x] MedianRelativeAbsoluteError (#2324)
- [x] R2Score (#2324)
- [x] WaveHedgesDistance (#2324) 

This is a great issue for first comers and those who want to learn more about Sphinx. This issue is the community effort.
If you want to contribute, please comment on this issue with the metric you want to add doctest (one by one).

Example on how to add doctest, see #2241 

Thanks!

**Comment by vfdev-5** [comment]
Sure @wanjuntham , go for it

**Comment by Eunjnnn** [comment]
Hello 
This is my first contribution :-)

can I work on `Loss` ?

**Comment by sdesrozis** [comment]
> Hello 
> 
> This is my first contribution :-)
> 
> 
> 
> can I work on `Loss` ?

@Eunjnnn thank you ! Yes you can 😉

**Comment by wanjuntham** [comment]
@vfdev-5 Hey, I actually didnt have time to work on this. Could you unassign me?

**Comment by sdesrozis** [comment]
@Eunjnnn Are you still working on `Loss` ? Or do you need help ?

**Comment by Eunjnnn** [comment]
@sdesrozis Hi I'm trying to work on it, but actually i'm not sure where to start,,

**Comment by sdesrozis** [comment]
> @sdesrozis Hi I'm trying to work on it, but actually i'm not sure where to start,,

First, take a look to our [contribution guide](https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md). Then, you will have to set up your environment (testing, building the doc).

And finally, you will find [here](https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md#writing-documentation) what is needed to write the doc and doctests according to our guidelines :)

**Comment by Ishan-Kumar2** [comment]
I'll add some of the contrib regression metrics ``FractionalBias``, ``FractionalAbsoluteError``, ``CanberraMetric``, ``GeometricMeanAbsoluteError``

**Comment by Ishan-Kumar2** [comment]
I'll add the remaining contrib metrics ``AveragePrecision``, ``PrecisionRecallCurve``, ``ROC_AUC`` and ``RocCurve``
