### ISSUE TITLE
Release program in standard pipeline

### ISSUE THREAD

**Issue by Nic-Ma** [pytorch/ignite#2267]
## ❓ Questions/Help/Support

Hi @vfdev-5 ,

I remember you shared with me a project to set up some ignite training pipeline with standard config, could you please help share it again? We want to compare it with our NVIDIA Clara solution in details.

Thanks in advance.

**Comment by vfdev-5** [comment]
Hi @Nic-Ma ,

We have sort of references here: https://github.com/pytorch/ignite/tree/master/examples/references
where configuration is not that standard (python config) but brings a lot of flexibility in terms of configuration and avoid any meta-languages.

**Comment by Nic-Ma** [comment]
Cool, thanks for your sharing!
Let me try to investigate them.

Thanks.

**Comment by vfdev-5** [comment]
Let me close this issue as answered, please feel free to reopen if needed
