### ISSUE TITLE
Update `common.setup_common_training_handlers` ProgressBar to work in distributed

### ISSUE THREAD

**Issue by Ishan-Kumar2** [pytorch/ignite#2271]
## 🐛 Bug description
Currently the `common.setup_common_training_handlers` has the same step for setting up the `ProgressBar` [here](https://github.com/pytorch/ignite/blob/a967d872209b9bf71a8371c8f1f3eb64df1da2f7/ignite/contrib/engines/common.py#L215-L223) for both single device and distributed training. 

In case of Distributed Training (>1 GPUs) this doesnt take into account whether the `rank` of current device is 0 or not and it will attach on all processes thus resulting in wrong logging. 

A simple solution would be to add a check if `idist.get_world_size() > 1` we should only attach progress bar to `rank` 0 process only.

**Comment by vfdev-5** [comment]
> In case of Distributed Training (>1 GPUs) this doesnt take into account whether the rank of current device is 0 or not and it will attach on all processes thus resulting in wrong logging.

@Ishan-Kumar2 I'm not sure to follow you here. Here is a line that does what you suggest: 
https://github.com/pytorch/ignite/blob/a967d872209b9bf71a8371c8f1f3eb64df1da2f7/ignite/contrib/engines/common.py#L252

Am I missing something ?

**Comment by Ishan-Kumar2** [comment]
@vfdev-5 yes you are right, I missed this part. It should work, I'll investigate in my code.
Thanks for the help, closing this.
