### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/ignite#2274]
Tracking for Python 3.10 support:

- https://github.com/pytorch/pytorch/issues/66424 (probably in PyTorch 1.11)
- https://github.com/pytorch/pytorch/pull/66530

**Comment by vfdev-5** [comment]
Nightlies are shipping 3.10 python binaries.
For example, see https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html

**Comment by vfdev-5** [comment]
Supported -> closing
