### ISSUE TITLE
Out of box PyTorch style datasets for standard tasks

### ISSUE THREAD

**Issue by Atharva-Phatak** [pytorch/ignite#2281]
## 🚀 Feature

Ignite is amazing :heart: . I like the concepts of event handlers very much. I was looking at the roadmap for the library there is a reference to improving ignite.data. 
To talk about the feature, I think if we have PyTorch style datasets already implemented for standard tasks like image classification,etc will be really helpful since it could be a start to something much bigger(maybe later down the line we can have pipelines like sklearn which wrap data and training together😃 ).

What I am basically proposing is something similar to what they have in fast.ai like [datablock API](https://docs.fast.ai/data.block.html). 
Since Ignite abstracts away all the boiler plate code, I think it would be nice to abstract away all the hassle of writing PyTorch style 
datasets/data-classes. 

Ofcourse, this is a big-task and we will need to discuss how to design and implement everything. 
This goes without saying but I would very much like to work on a PR for this  🚀

**Comment by sdesrozis** [comment]
@Atharva-Phatak Thank you for your support and nice words.

The roadmap for `ignite.data` is much less ambitious than what you proposed. An idea was to provide a way in order to manage multiple data sources.

Anyway, this FR requires discussions and a good motivation. Today, we let the definition of native PyTorch objects such the datasets, models, etc. to the user.

**Comment by Atharva-Phatak** [comment]
@vfdev-5 Awesome. When is the ETA for release of data-pipes. By datatransforms do you mean torchvision transforms or is it a new module ? Can you provide a link to the repo ?
I am very open to ideas and willing to invest my time to develop this integral part in Ignite. 
I understand this is a big change and we need a lot of discussions. But yeah I am very open to guidance from you guys and would love to code this ❤️

**Comment by Atharva-Phatak** [comment]
@vfdev-5 sure I will try to create a google colab which uses fastai and ignite. And share the same here. Will that work for you guys ?

**Comment by vfdev-5** [comment]
Sounds good, thanks @Atharva-Phatak !

**Comment by Atharva-Phatak** [comment]
I am sorry I am really busy with my college and assignments as my exams are going on. But I will work on a colab notebook by the end of this week. Sorry for the delay guys 😭
