### ISSUE TITLE
Update for `timeline_and_event` image

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/ignite#2282]
### 📚 Documentation

When I first read about [timeline and events in PyTorch-Ignite concepts](https://pytorch.org/ignite/master/concepts.html#timeline-and-events), I noticed I had to rotate my head around 30 degree to read [`timeline_and_event` image](https://pytorch.org/ignite/master/_static/img/concepts/timeline_and_events.png).

Should we update the image so that it will be easier to read?

**Comment by pacificdragon** [comment]
@vfdev-5, Can we use svg format for this image? 

Let me know if this looks good or needs some changes.

![timeline_and_events](https://user-images.githubusercontent.com/12509045/218300562-41d3abab-d311-4391-b510-6e96cd98bbc5.svg)

**Comment by vfdev-5** [comment]
@pacificdragon thanks for working on that !
Actually, vertical text layout was associated with horizontal time line showing time order of the events.
If we want to put text horizontally then we may need to put the time line vertically ?

**Comment by pacificdragon** [comment]
@vfdev-5  Is it better now?

![timeline](https://user-images.githubusercontent.com/12509045/218507897-3864fb27-f336-4f47-a4b3-5d838a01cfd1.png)

**Comment by vfdev-5** [comment]
@pacificdragon thanks, yes, I like it more. @ydcjeff any comments from your side or we can directly proceed with docs update ?

**Comment by ydcjeff** [comment]
Yea, it looks better now.
