### ISSUE TITLE
[Feature] Possibility to pass `non_blocking` attribute to `convert_tensor`

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#231]
Following torch docs on [CUDA memory management](https://pytorch.org/docs/stable/notes/cuda.html#use-pinned-memory-buffers) if user configures DataLoader with `pin_memory=True` then
he/she can use asynchronous GPU copies, just passing an additional `non_blocking=True` argument to a `cuda()` call or tensor method [`.to()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.to).

In ignite this can be done with utils method `convert_tensor` that accepts `device` argument: `cpu`, `cuda` or `cuda:N`. It would be great to have a possibility to pass `non_blocking` as kwargs.

In addition, this should be also propaged until `create_supervised_trainer` and `_prepare_batch`.

PS: it is okay to call `x.to('cpu', non_blocking=True)`, no error raised.

**Comment by vfdev-5** [comment]
@anmolsjoshi could you please take a look on this one, once #220 is merged ?

**Comment by anmolsjoshi** [comment]
@vfdev-5 sure!

**Comment by alykhantejani** [comment]
Fixed in #239

**Comment by vfdev-5** [comment]
Forgot to say that `create_supervised_evaluator` needed this option too. Will add by myself
