### ISSUE TITLE
ignite.distributed.Parallel: master_port seems always to be 2222 when using env:// init_method

### ISSUE THREAD

**Issue by kong13661** [pytorch/ignite#2312]
I want to use another master_port in my machine. My code is below:

```python
def run(
    backend='nccl',
    resume=True,
    nproc_per_node=4,
    with_clearml=False,
    with_amp=False,
    **spawn_kwargs
):
    config = locals()
    config.update(config["spawn_kwargs"])
    del config["spawn_kwargs"]
    spawn_kwargs["nproc_per_node"] = nproc_per_node
    if backend == "xla-tpu" and with_amp:
        raise RuntimeError("The value of with_amp should be False if backend is xla")

    os.environ['CUDA_VISIBLE_DEVICES']   = "0,1,2,3"

    with ignite.distributed.Parallel(backend=backend, **spawn_kwargs) as parallel:

        parallel.run(training, config)


if __name__ == '__main__':
    fire.Fire(run)
```

I use the command to run this:

`python normal_train_ddp.py  --matser-port 50001`

I found it always use master port 2222.

I found this code.  It seems ignore my master_port setting when init_method is None or env://. 

https://github.com/pytorch/ignite/blob/8a1de70e2152936ffcb051f3bd618138130626ec/ignite/distributed/comp_models/native.py#L385-L388

## Environment

- PyTorch Version (e.g., 1.4): 1.8
- Ignite Version (e.g., 0.3.0): 0.4.7
- OS (e.g., Linux): Linux
- How you installed Ignite (`conda`, `pip`, source): conda
- Python version: 3.8

**Comment by vfdev-5** [comment]
@kong13661 thanks a lot for the report! It looks like it is a bug propagated since https://github.com/pytorch/ignite/pull/1767

Meanwhile you can do the following: you can use `init_method` as tcp where you can specify master address and port:
```python
import os
import time
import ignite.distributed as idist
import torch.distributed as dist
import torch.distributed.distributed_c10d as c10d


def training(lrank):    
    time.sleep(idist.get_rank() * 0.05)
    print(idist.get_rank(), " - used init method: ", c10d._default_pg_init_method)

if __name__ == "__main__":
    
    spawn_kwargs = {
        "nproc_per_node": 4,
        "init_method": "tcp://0.0.0.0:50001"
    }
    
    os.environ["CUDA_VISIBLE_DEVICES"] = ""

    with idist.Parallel(backend="gloo", **spawn_kwargs) as parallel:
        parallel.run(training)

```

**Comment by kong13661** [comment]
> @kong13661 thanks a lot for the report! It looks like it is a bug propagated since #1767
> 
> Meanwhile you can do the following: you can use `init_method` as tcp where you can specify master address and port:
> 
> ```python
> import os
> import time
> import ignite.distributed as idist
> import torch.distributed as dist
> import torch.distributed.distributed_c10d as c10d
> 
> 
> def training(lrank):    
>     time.sleep(idist.get_rank() * 0.05)
>     print(idist.get_rank(), " - used init method: ", c10d._default_pg_init_method)
> 
> if __name__ == "__main__":
>     
>     spawn_kwargs = {
>         "nproc_per_node": 4,
>         "init_method": "tcp://0.0.0.0:50001"
>     }
>     
>     os.environ["CUDA_VISIBLE_DEVICES"] = ""
> 
>     with idist.Parallel(backend="gloo", **spawn_kwargs) as parallel:
>         parallel.run(training)
> ```
> 
> > 
> 
> ```
> 2021-11-09 06:49:50,807 ignite.distributed.launcher.Parallel INFO: Initialized distributed launcher with backend: 'gloo'
> 2021-11-09 06:49:50,807 ignite.distributed.launcher.Parallel INFO: - Parameters to spawn processes: 
>         nproc_per_node: 4
>         nnodes: 1
>         node_rank: 0
>         init_method: tcp://0.0.0.0:50001
> 2021-11-09 06:49:50,807 ignite.distributed.launcher.Parallel INFO: Spawn function '<function training at 0x7fc14dadb280>' in 4 processes
> 0  - used init method:  tcp://0.0.0.0:50001
> 1  - used init method:  tcp://0.0.0.0:50001
> 2  - used init method:  tcp://0.0.0.0:50001
> 3  - used init method:  tcp://0.0.0.0:50001
> 2021-11-09 06:49:53,402 ignite.distributed.launcher.Parallel INFO: End of run
> ```

It works. Thanks.
