### ISSUE TITLE
Making a conda-forge pytorch-ignite package

### ISSUE THREAD

**Issue by knc6** [pytorch/ignite#2318]
## 🚀 Feature
Hi,

I would like to make a [`conda-forge`](https://github.com/conda-forge/) package for [ALIGNN network](https://github.com/usnistgov/alignn) which uses pytorch-ignite. As ignite is only available on pytorch conda channel and not on conda-forge, I submitted a PR for making a conda-forge pytorch-ignite implementation [here](https://github.com/conda-forge/staged-recipes/pull/16795).

I just wanted to check if ignite team is ok with this strategy, or please suggest an alternative.

**Comment by vfdev-5** [comment]
Hi @knc6 thanks a lot for creating a conda package on conda-forge for pytorch ignite.
Happy to know that it works as few time ago it was a problem to install pytorch, cudatoolkit etc using conda-forge channel.
From our side everything is ok.

**Comment by knc6** [comment]
Perfect, sounds good!

**Comment by vfdev-5** [comment]
@knc6 looks like your PR for the recipe is merged, maybe we can update our readme and other places with additional new instructions on how to install ignite using conda-forge channel ?

I'm also wondering about how this recipe will be sync with new releases ? 

I also checked which pytorch version is installed using only conda-forge channel and it looks like it proposes only old 1.9.0 cpu version:
```
(test) user:/# conda install pytorch-ignite -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda/envs/test

  added / updated specs:
    - pytorch-ignite


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2021.10.8  |       ha878542_0         139 KB  conda-forge
    certifi-2021.10.8          |   py37h89c1867_1         145 KB  conda-forge
    cffi-1.14.5                |   py37h261ae71_0         224 KB
    future-0.18.2              |   py37h89c1867_4         713 KB  conda-forge
    libblas-3.9.0              |   12_linux64_mkl          12 KB  conda-forge
    libcblas-3.9.0             |   12_linux64_mkl          12 KB  conda-forge
    liblapack-3.9.0            |   12_linux64_mkl          12 KB  conda-forge
    libprotobuf-3.16.0         |       h780b84a_0         2.5 MB  conda-forge
    numpy-1.20.3               |   py37h038b26d_1         5.7 MB  conda-forge
    pycparser-2.21             |     pyhd8ed1ab_0         100 KB  conda-forge
    python_abi-3.7             |          2_cp37m           4 KB  conda-forge
    pytorch-1.9.0              |cpu_py37hb06efa0_2        46.8 MB  conda-forge
    pytorch-ignite-0.4.7       |     pyhd8ed1ab_0         137 KB  conda-forge
    sleef-3.5.1                |       h7f98852_1         1.5 MB  conda-forge
    typing_extensions-3.10.0.2 |     pyha770c72_0          28 KB  conda-forge
```
I do not know if pytorch team is supposed to maintain conda-forge recipe and update it somehow, but I think later this can be a problem using outdated pytorch...
