### ISSUE TITLE
Update pytorch.org/ignite site and reference pytorch-ignite.ai

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2325]
## 📚 Documentation

Our project new website is online and available. We need to update pytorch.org/ignite to reflect only API and provide links to pytorch-ignite.ai as source for examples/tutorials/how-to guides etc.

### Redirections:

Quickstart -> https://pytorch-ignite.ai/tutorials/beginner/01-getting-started/
FAQ -> https://pytorch-ignite.ai/how-to-guides/
Concepts -> TBD
Examples -> TBD
Github -> Github (no change)
About us -> https://pytorch-ignite.ai/about/community/

### Index page (https://pytorch.org/ignite/)

Remove almost all the content and add the logo and the link to https://pytorch-ignite.ai. Like below (but better aligned):

<div>
  <img width=200 src=https://pytorch-ignite.ai/_images/ignite_logo.svg />
  <p>https://pytorch-ignite.ai</p>
</div>

### Add another explicit link to https://pytorch-ignite.ai from the header ?

The idea is to have something like: 
```
Quickstart    Concepts    Examples     FAQ     GitHub     About us    https://pytorch-ignite.ai
```
Any thoughts ?

**Comment by iamhardikat11** [comment]
Is this issue open to be taken up?

**Comment by vfdev-5** [comment]
Hi @iamhardikat11 , this issue is a bit critical for the project, but yes, you can help with a part of it, for example, replacing the links for: about us, FAQ, Quickstart (as suggested in the description) and remove those .rst files.

**Comment by iamhardikat11** [comment]
Yup, I can work on that. I will Submit my PR By today Night.

**Comment by Moh-Yakoub** [comment]
> Hi @iamhardikat11 , this issue is a bit critical for the project, but yes, you can help with a part of it, for example, replacing the links for: about us, FAQ, Quickstart (as suggested in the description) and remove those .rst files. What do you think ?

@vfdev-5 Any other parts that I can help with at the moment?

**Comment by vfdev-5** [comment]
@Moh-Yakoub yes, you can help. Nothing is done at the moment. You can submit a PR with docs updates for the redirections (see the description). What do you think ?

**Comment by Moh-Yakoub** [comment]
> @Moh-Yakoub yes, you can help. Nothing is done at the moment. You can submit a PR with docs updates for the redirections (see the description). What do you think ?

Great, I will start doing that. Thanks a lot!

**Comment by Moh-Yakoub** [comment]
@vfdev-5 I just checked the updated task description. 

I agree with your suggested approach, but maybe add some description to explain the missing documentation i.e. something like "All our documentation moved to https://pytorch-ignite.ai." or something similar.

**Comment by vfdev-5** [comment]
Yes, I agree, thanks for the suggestion!
