### ISSUE TITLE
Make event handler dict ordered to respect handling order.

### ISSUE THREAD

**Issue by veugene** [pytorch/ignite#233]
Currently the dictionary of event handlers in Engine is defined thus:
```python
self._event_handlers = defaultdict(list)
```
The `defaultdict` stores items in unpredictable order. It would be better for the dictionary to store handlers in the order in which they are added to the `Engine`.

**Here's a use case:**
A checkpoint is defined with a `score_function` that tracks a metric. However, the metric in `engine.state.metrics` may not yet be recorded or updated by the time that the `score_function` accesses it.
```python
ModelCheckpoint(dirname="tmp_dir",
                filename_prefix="best_state",
                score_function=lambda engine: -engine.state.metrics['loss'])
```
A `Metric` object updates the `engine.state.metrics` dictionary when `Events.EPOCH_COMPLETED` is fired. A `ModelCheckpoint` typically fires with the same event. Because the order in which handlers are stored is unpredictable, the checkpoint and its `score_function` may be run before the `Metric`. In that case, 'loss' may either be missing in `engine.state.metrics` (resulting in a `KeyError`) or it may be stale.

**Suggested change:**
I propose changing `self._event_handlers` from a `defaultdict(list)` to an `OrderedDict()`, thus also changing
```python
self._event_handlers[event_name].append((handler, args, kwargs))
```
to
```python
if event_name not in self._event_handlers.keys():
    self._event_handlers[event_name] = []
self._event_handlers[event_name].append((handler, args, kwargs))
```
in `Engine`, thereby retaining the initialization that `defaultdict` performs.

**Comment by alykhantejani** [comment]
I agree with @veugene on this one, `defaultdict` gives no guarantee of order, whereas its a simple change to guarantee this without producing hard to track down bugs.

**Comment by alykhantejani** [comment]
Here's a reference, where order was implemented in in normal dicts in 3.6 but should not be relied upon

https://docs.python.org/3.6/whatsnew/3.6.html#whatsnew36-pep520

> The order-preserving aspect of this new implementation is considered an implementation detail and should not be relied upon (this may change in the future, but it is desired to have this new dict implementation in the language for a few releases before changing the language spec to mandate order-preserving semantics for all current and future Python implementations; this also helps preserve backwards-compatibility with older versions of the language where random iteration order is still in effect, e.g. Python 3.5).

**Comment by alykhantejani** [comment]
Sorry I've mis-read the issue

> Because the order in which handlers are stored is unpredictable,

@veugene the handlers are stored in a list, so the order should be preserved. Can you provide a snipper to reproduce the error you are seeing?

**Comment by veugene** [comment]
@alykhantejani You are right. The event firing order is manually defined in `Engine` and the handlers are organized per event. Although the events are in a dict, the handlers are in a list. I rescind my issue ;) so you may close this.
