### ISSUE TITLE
Engine.run make input data optional

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2354]
## 🚀 Feature

In certain use-cases, for example in RL or multi-data cases, it does not make much sense to call `engine.run` with an artificial data that only defines epoch lenght:
```python
trainer.run(data, max_epochs=100)
```
For example, 
https://github.com/pytorch/ignite/blob/4759e01034f53bb0334f661b8a8d61f76f6be9e4/examples/reinforcement_learning/reinforce.py#L70

https://github.com/pytorch/ignite/blob/4759e01034f53bb0334f661b8a8d61f76f6be9e4/examples/reinforcement_learning/reinforce.py#L118

The idea is to make `data` argument optional. Proposed API
```python
trainer.run(max_epochs=100, epoch_length=10_000)
```
In this case, `training_step(engine, batch)` will receive `None` as batch value.

cc @sdesrozis

**Comment by sdesrozis** [comment]
Yes I understand the idea and agree that it would be great to have such a feature !

**Comment by fco-dv** [comment]
This API would seem clearer in such uses-cases, yes!
