### ISSUE TITLE
Fix warning in the test for SSIM metric

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2358]
## 🚀 Feature

We can see on the CI that we are using a deprecated arg.
```
tests/ignite/metrics/test_ssim.py::test_ssim
  /home/runner/work/ignite/ignite/tests/ignite/metrics/test_ssim.py:79: FutureWarning: `multichannel` is a deprecated argument name for `structural_similarity`. It will be removed in version 1.0.Please use `channel_axis` instead.
    skimg_ssim = ski_ssim(
```

The idea is to fix that as suggested by skimage doc and the message.

**Comment by bibhabasumohapatra** [comment]
hey @vfdev-5  I have changed the multichannel = True to channel_axis = 3,       This is my first pull request, 
Let me know if I miss something.
#2360

**Comment by bibhabasumohapatra** [comment]
https://github.com/scikit-image/scikit-image/issues/4294

**Comment by bibhabasumohapatra** [comment]
**my pull request fixes the warnings**
first one is the master branch
and second is my new branch1 changes
![image](https://user-images.githubusercontent.com/68384968/146353796-6ee635d9-da2d-49d5-92e9-b741c03f251f.png)
