### ISSUE TITLE
Fix mypy issues with mypy==0.920

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2361]
## 🐛 Bug description

Our code base mypy check is failing:
```
ignite/handlers/time_profilers.py:638: error: Incompatible return value type
(got
"List[List[Union[Any, str, float, Tuple[Union[str, float], Union[str, float]]]]]",
expected "List[List[Union[str, float]]]")  [return-value]
            return event_handler_stats
                   ^
ignite/handlers/param_scheduler.py:829: error: unused "type: ignore" comment
                scheduler = cls(save_history=False, lr_scheduler=lr_schedu...
                ^
ignite/handlers/checkpoint.py:721: error: unused "type: ignore" comment
                    tmp_file = tmp.file  # type: ignore
                    ^
ignite/contrib/handlers/neptune_logger.py:588: error: unused "type: ignore"
comment
                torch.save(checkpoint, tmp.file)  # type: ignore[attr-defi...
                ^
Found 4 errors in 4 files (checked 103 source files)
```
for mypy==0.920

Let's make our codebase compatible.

## Environment

- PyTorch Version (e.g., 1.4):
- Ignite Version (e.g., 0.3.0):
- OS (e.g., Linux):
- How you installed Ignite (`conda`, `pip`, source):
- Python version:
- Any other relevant information:

**Comment by Moh-Yakoub** [comment]
@vfdev-5 Is the issue fixed by the above mentioned PR, or is anything else is required to close this task

**Comment by bibhabasumohapatra** [comment]
IG @vfdev-5  forgot to close the issue, #fixed

**Comment by vfdev-5** [comment]
@Moh-Yakoub yes, the issue is still open. We need to fix above mentioned mypy error on the master with mypy>=0.920.

@bibhabasumohapatra No, the issue is not fixed. Above PR just pins mypy version to 0.910 but we would like to have the codebase compliant with >=0.920

**Comment by sayantan1410** [comment]
@vfdev-5 I would like to contribute to this issue, if this is not assigned to someone else.
