### ISSUE TITLE
Remove python 3.6 support due to EOL, 2021-12-23

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2363]
Let's remove python 3.6 from our CI from due to EOL, 2021-12-23 (https://www.python.org/downloads/)

**Comment by bibhabasumohapatra** [comment]
hey @vfdev-5 ,
 to remove python-version 3.6 and py36 support from
IG I can remove that the following way from these paths ,right? 

1. **.github/workflows/unit-tests.yml**

2. **.github/workflows/pytorch-version-tests.yml**

 `python-version: [3.6, 3.7, 3.8, 3.9]`    ->   `python-version: [3.7, 3.8, 3.9] `

3. **pyproject.toml**
 `target-version = ['py36', 'py37', 'py38']`  -> `target-version = [ 'py37', 'py38']`

**Comment by vfdev-5** [comment]
@bibhabasumohapatra yes probably removing python 3.6 from these paths can be enough.
