### ISSUE TITLE
Replace all `os.path` in ignite and tests by `pathlib.Path`

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2418]
Let's update the codebase and tests:
1) replace all `os.path.exists(folder)` usage by `Path(folder).exists()`
2) replace all `os.path.join(a, b)` by `Path(a) / b`
3) replace `os.makedirs(folder)` by `Path.mkdir(folder, parents=True)`
4) update all folder/files being `str` to `Union[str, Path]` and make all folder/file-like attributes as `Path` objects.
  - https://github.com/pytorch/ignite/blob/0666b407f7cdba81842014c6026e33b66113bb94/ignite/handlers/checkpoint.py#L649
  -

**Comment by parthvaidya** [comment]
Can you specify which file to work on? I am new to open source but am interested in working on it.

**Comment by vfdev-5** [comment]
@parthvaidya thanks for you interest in working on this issue ! Actually, there are plenty of files where we would like to make this changes. I'd suggest to do a "seach in files" with your IDE and you can find them. If using GitHub:
- https://github.com/pytorch/ignite/search?q=%22os.path%22

**Comment by parthvaidya** [comment]
Sure I got the files. Will work on it and update soon.

**Comment by vfdev-5** [comment]
Feel free to send a draft PR to iterate over. If you got stuck please ask questions here or on discord : https://pytorch-ignite.ai/chat
Meanwhile, please also take a look as contributing guide: https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md

**Comment by yash-0501** [comment]
Hey @vfdev-5 If this issue is still open, I would love to contribute in this.

**Comment by vfdev-5** [comment]
@yash-0501 we can divide the work between you and @parthvaidya. I let you propose which part you can work on such that there is no overlap between you two. I relabelled the tasks by numbers.

**Comment by parthvaidya** [comment]
No let Yash work as I actually got caught up in something else

**Comment by nishithshowri006** [comment]
Is anyone still working on this? If not can I work on it?

**Comment by vfdev-5** [comment]
@nishithshowri006 there is #2422 PR covering a part of it.

**Comment by rishav-karanjit** [comment]
Can I work on this. If no one else is working on it?

**Comment by snnipetr** [comment]
Is this issue open for contribution?

**Comment by vfdev-5** [comment]
Yes, it is open for contributions
