### ISSUE TITLE
Add an explanation on how metrics work with engine

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2437]
## 📚 Documentation

It is unclear for newcomers what does the code below from docs (for example, Accuracy)
```python
metric = Accuracy()
metric.attach(default_evaluator, "accuracy")
y_true = torch.Tensor([1, 0, 1, 1, 0, 1])
y_pred = torch.Tensor([1, 0, 1, 0, 1, 1])
state = default_evaluator.run([[y_pred, y_true]])
print(state.metrics["accuracy"])
```
More precisely, it is unclear that the metric is computed online and at each iteration some internal variables are updated and on epoch completed metric value is computed.

For each metric docs, let's add a link on the explanation that we can add explicitly to https://pytorch.org/ignite/metrics.html

**Comment by sadra-barikbin** [comment]
Hi,
You mean to add a thorough explanation at the beginning of the [this page](https://pytorch.org/ignite/metrics.html) and include a link to it in every metric page?

**Comment by vfdev-5** [comment]
> Hi, You mean to add a thorough explanation at the beginning of [this page](https://pytorch.org/ignite/metrics.html) and include a link to it in every metric page?

Yes, exactly !

**Comment by sayantan1410** [comment]
@vfdev-5 Can I work on this issue ?
