### ISSUE TITLE
Seemingly unnecessary dictionary comprehension in contrib's BaseOutputHandler

### ISSUE THREAD

**Issue by sadra-barikbin** [pytorch/ignite#2438]
Hi,
`output_dict` is made sure to be a dictionary just above the line below. 

https://github.com/pytorch/ignite/blob/21a2ccc25dd7ff0aec5f1538387597cb093fe36e/ignite/contrib/handlers/base_logger.py#L108

So this line could be replaced with:

```python
metrics_state_attrs.update(output_dict) 
```

**Comment by vfdev-5** [comment]
Thanks for pointing out that, @sadra-barikbin !
Would you like to send a PR to fix that ?

**Comment by sadra-barikbin** [comment]
Yes, sure!
