### ISSUE TITLE
Fix DeprecationWarning: distutils Version classes are deprecated

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2472]
We need to fix `DeprecationWarning: distutils`:

```
  /home/docker/actions-runner/_work/ignite/ignite/tests/ignite/engine/test_create_supervised.py:587: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    @pytest.mark.skipif(LooseVersion(torch.__version__) < LooseVersion("1.6.0"), reason="Skip if < 1.6.0")
```
- In the CI and in the code

In addition to the code change we have to figure out if we need to add `packaging` as a dependency.
It is most probably brought with some other packages but we have to ensure that on a clean environment it is (or not) installed together with for example pytorch.

---

`packaging` is not installed with torch cpu on Ubuntu, checked ubuntu:latest docker container.
```
apt-get install -y python3 python3-pip
python3 --version
Python 3.8.10

pip3 install torch -f https://download.pytorch.org/whl/cpu/torch_stable.html
pip3 list | grep torch
torch             1.10.2+cp

python3 -c "import packaging"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'packaging'
```

**Comment by DevPranjal** [comment]
Hello! I would like to fix this.
I am looking if `packaging` is a dependency in any other required package.

**Comment by vfdev-5** [comment]
@DevPranjal thanks !
The only dependency ignite has is pytorch: https://github.com/pytorch/ignite/blob/750719f01585b068bb86cdbcc6c618439f555016/setup.py#L27-L29

So, if pytorch requires `packaging` it would be good.

**Comment by DevPranjal** [comment]
@vfdev-5 Just a few facts I found:
- [This](https://github.com/pytorch/pytorch/pull/69823) approved PR in `pytorch` would include `packaging` to the requirements.
- Any system with `pip` installed would have the `packaging` module (from this [comment](https://github.com/pytorch/pytorch/pull/69823#pullrequestreview-831808434))

**Comment by vfdev-5** [comment]
Yes, let's add it now and remove once torch included it
