### ISSUE TITLE
Allow filename_pattern to be passed to ModelCheckpoint

### ISSUE THREAD

**Issue by KevinMusgrave** [pytorch/ignite#2475]
[Checkpoint](https://pytorch.org/ignite/v0.4.8/generated/ignite.handlers.checkpoint.Checkpoint.html#ignite.handlers.checkpoint.Checkpoint) accepts ```filename_pattern``` as an argument, but [ModelCheckpoint](https://pytorch.org/ignite/v0.4.8/generated/ignite.handlers.checkpoint.ModelCheckpoint.html#ignite.handlers.checkpoint.ModelCheckpoint) doesn't.

**Comment by vfdev-5** [comment]
Thanks for reporting @KevinMusgrave ! It shouldn't be difficult to pass it through, i think.
