### ISSUE TITLE
Checkpoint loading doesn't work if object doesn't contain a torch.nn.Module

### ISSUE THREAD

**Issue by KevinMusgrave** [pytorch/ignite#2479]
## 🐛 Bug description

Running the following code:
```python
from ignite.handlers import Checkpoint
Checkpoint.load_objects(to_load=to_load, checkpoint=checkpoint)
```

results in the following error:
```
load_state_dict() got an unexpected keyword argument 'strict'
```

if ```to_load``` doesn't contain a ```torch.nn.Module```. 

For example, ```{"optimizer": optimizer}``` fails, but ```{"model": torch.nn.Linear(10, 10)}``` succeeds.

## Notebook to reproduce
https://colab.research.google.com/drive/1G-iVC-ixMQrw90AEp5mDuSjxUAPyO8YF?usp=sharing

## Environment
Run on google colab with:
torch version 1.10.0+cu111
ignite version 0.4.8

**Comment by vfdev-5** [comment]
@KevinMusgrave thanks for the report. I tried your colab and it fails elsewhere.

However, you should be able to save model, optimizer, lr_scheduler, trainer etc
Here is a working code (tested in your colab)
```python
!rm -rf /tmp/models

import torch
from ignite.engine import Engine, Events
from ignite.handlers import ModelCheckpoint, Checkpoint
trainer = Engine(lambda engine, batch: None)
handler = ModelCheckpoint('/tmp/models', 'myprefix', n_saved=None, create_dir=True)
model = torch.nn.Linear(3, 3)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
to_save = {"weights": model, "optimizer": optimizer, "trainer": trainer}
trainer.add_event_handler(Events.EPOCH_COMPLETED(every=2), handler, to_save)
trainer.run(torch.randn(10, 1), 5)

to_load = to_save
checkpoint_fp = "/tmp/models/myprefix_checkpoint_40.pt"
checkpoint = torch.load(checkpoint_fp)
Checkpoint.load_objects(to_load=to_load, checkpoint=checkpoint)

# or using a string for checkpoint filepath

to_load = to_save
checkpoint_fp = "/tmp/models/myprefix_checkpoint_40.pt"
Checkpoint.load_objects(to_load=to_load, checkpoint=checkpoint_fp)
```

Meanwhile I'll try to figure out what is the issue that give you reported error: "load_state_dict() got an unexpected keyword argument 'strict'".
