### ISSUE TITLE
test_distrib_cpu from test_inception_score.py is failing. 

### ISSUE THREAD

**Issue by sayantan1410** [pytorch/ignite#2484]
## 🐛 Bug description
I ran the test_inception_score.py locally and `test_distrib_cpu` test failed with the error:
`fixture 'worker_id' not found`.

Function `test_distrib_cpu` calls another function `distributed_context_single_node_gloo` from conftest.py which takes in `local_rank` as parameter. `local_rank` is another function in conftest.py which takes in `worker_id` as parameter. But the worker_id is not passed earlier.

**Comment by vfdev-5** [comment]
To run these test you have use xdist : https://github.com/pytorch/ignite/blob/master/tests/run_cpu_tests.sh#L19
