### ISSUE TITLE
Add StepParamScheduler feature

### ISSUE THREAD

**Issue by sadra-barikbin** [pytorch/ignite#2488]
## 🚀 Feature

I propose to add `StepParamScheduler` to `ignite.handlers.param_scheduler`. It is basically used to multiply a parameter
by a fixed factor every `step_size` steps. This can be done by subclassing `ParamScheduler` and implementing its simple logic.

This class is commonly used, so it's good to have it in the Ignite.

**Comment by vfdev-5** [comment]
Thanks for the feature request. I'm not sure that we need to wrap all built-in torch lr schedulers. Today user can use LRSheduler to wrap torch schedulers : https://pytorch.org/ignite/v0.4.8/generated/ignite.handlers.param_scheduler.LRScheduler.html#lrscheduler

What would be an added value by explicitly providing StepParamScheduler ?

**Comment by sadra-barikbin** [comment]
Yes, you're right. I had written it for a project, so I attempted for a PR.

**Comment by sadra-barikbin** [comment]
@vfdev-5 This class is also useful in the case where user wants to apply such scheduling on a parameter other than LR or a specific parameter group.

**Comment by vfdev-5** [comment]
Yes, you are right about other then LR parameter scheduling. Do you have a use case for that ?

**Comment by vfdev-5** [comment]
LRScheduler is a wrapper over torch lr scheduler. I think if torch lr scheduler already works on a single group then LRScheduler can work on a group...

**Comment by sadra-barikbin** [comment]
It could work, but only by separating their optimizers. That gets difficult. PyTorch's `_LRSchduler` does not accept a `param_group_index`-like parameter.
