### ISSUE TITLE
Using auto_dataloader with a custom sampler

### ISSUE THREAD

**Issue by kkarrancsu** [pytorch/ignite#2500]
The [docs](https://pytorch.org/ignite/generated/ignite.distributed.auto.auto_dataloader.html) for auto_dataloader are confusing to me, with respect to whether providing alternate samplers work in the DistributedDataParallel mode.  

One of the bullet points indicates:"if another sampler is provided, it is wrapped by [DistributedProxySampler](https://pytorch.org/ignite/generated/ignite.distributed.auto.DistributedProxySampler.html#ignite.distributed.auto.DistributedProxySampler)."

Additionally, a warning is provided below:
**_Custom batch sampler is not adapted for distributed configuration. Please, make sure that provided batch sampler is compatible with distributed configuration._**

Is there a difference between these scenarios that I'm missing?

**Comment by vfdev-5** [comment]
@kkarrancsu originally a dataloader can accept a sampler or a batch sampler, check out : https://pytorch.org/docs/stable/data.html?highlight=dataloader#torch.utils.data.DataLoader
Let me know if it becomes clear now ?

**Comment by kkarrancsu** [comment]
That is clear - thanks! I never used the batch_sampler functionality before.
