### ISSUE TITLE
Windows binaries not available on anaconda

### ISSUE THREAD

**Issue by MrinalJain17** [pytorch/ignite#251]
As of now, only linux and osx binaries are available on [pytorch/ignite](https://anaconda.org/pytorch/ignite) on anaconda.

**Please add the windows binaries too.**

**Comment by vfdev-5** [comment]
@MrinalJain17 thanks for the feedback ! Yes, we will add windows binaries in the next release.

At the moment, I think installation via pip should work too.

**Comment by MrinalJain17** [comment]
That sounds great @vfdev-5  👍 

Thanks for the prompt reply.

**Comment by adityabalu** [comment]
I think the pip install is not updated yet, I got an error while running the example code (somehow the Accuracy metric was not imported).  Installing from source worked fine

**Comment by vfdev-5** [comment]
Close it as the release v0.1.1 on conda contains binaries for Linux, OSX, Windows: https://anaconda.org/pytorch/ignite

If problem remains, feel free to reopen it.
