### ISSUE TITLE
SSIM update does not work for the last batch (if batch size is different)

### ISSUE THREAD

**Issue by vinayak015** [pytorch/ignite#2532]
## 🐛 Bug description
![Screenshot 2022-03-28 at 4 27 36 PM](https://user-images.githubusercontent.com/13629918/160447093-d5c0980e-4951-4eaa-930b-6dd9ea7992a4.png)

## Environment

- PyTorch Version :1.10.1
- Ignite Version ():0.4.8
- OS : Ubuntu
- How you installed Ignite (`conda`, `pip`, source): 
- Python version: 3.9
- Any other relevant information:

If the previous batch and the current batch are different then it throws the error. Attaching the screen shot of error. 

Screenshot of the basic code is also attached.
![Screenshot 2022-03-28 at 7 04 08 PM](https://user-images.githubusercontent.com/13629918/160450347-141131ed-ef66-4532-a36a-a21c27028b0e.png)

**Comment by vfdev-5** [comment]
Thanks for reporting @vinayak015 ! Looks like a bug

**Comment by vinayak015** [comment]
Thanks for accepting it. I am happy to work on it, if that's alright.

**Comment by sdesrozis** [comment]
@vinayak015 Thank you for your help !

**Comment by vfdev-5** [comment]
@vinayak015 yes, thanks for proposing to help.
Let me expose here how I would tackle the issue.
1) Create a test that would reproduce the issue and fail with the current codebase
2) Fix the implementation of SSIM

Please, take a look of our contributing guide for info : https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md

**Comment by vinayak015** [comment]
I will work on it after 11th April, as I do not have bandwidth left right now. In the mean time the temporary workaround is to drop the last batch!

**Comment by vfdev-5** [comment]
@vinayak015 any chance you could work on this issue ?

**Comment by vinayak015** [comment]
Hey @vfdev-5, I am on holiday for the next 15 days. (It was a sudden plan). Please feel free to unassign me if its priority has been increased.
