### ISSUE TITLE
Bar format is `str` but should be  `Optional[str]` in ignite.contrib.handlers.tqdm_logger.ProgressBar

### ISSUE THREAD

**Issue by yohan-pg** [pytorch/ignite#2540]
## 🐛 Bug description

`ignite.contrib.handlers.tqdm_logger.ProgressBar` can accept `None` in the `bar_format` initialization argument (as documented), but this is not reflected in the type annotation.

https://github.com/pytorch/ignite/blob/82a929d3e452ccaba8c7767148231e741b6335e5/ignite/contrib/handlers/tqdm_logger.py#L120

**Comment by vfdev-5** [comment]
Thanks for catching that @yohan-pg , would you like to send a fix ?
So, it should be 
```
bar_format: Union[str, None] = "{desc}[{n_fmt}/{total_fmt}] {percentage:3.0f}%|{bar}{postfix} [{elapsed}<{remaining}]"
```

**Comment by Davidportlouis** [comment]
I would like to work on this fix

**Comment by vfdev-5** [comment]
Thanks @Davidportlouis , assigned it to you
