### ISSUE TITLE
Add whitelist parameter to some contrib.tensorboard_logger & contrib.clearml_logger handlers

### ISSUE THREAD

**Issue by sadra-barikbin** [pytorch/ignite#2548]
## 🚀 Feature

Following issue #2328 , we could add `whitelist` parameter to these classes in `contrib.tensorboard_logger` and `contrib.clearml_logger` to be able to log only desired weights or gradients.

1. GradsHistHandler
2. GradsScalarHandler
3. WeightsScalarHandler
4. WeightsHistHandler

**Comment by sadra-barikbin** [comment]
@vfdev-5, assign it to me if you will.

**Comment by vfdev-5** [comment]
Thanks for opening the issue @sadra-barikbin ! I assigned it to you

**Comment by sadra-barikbin** [comment]
@vfdev-5 ,
As `clearml_logger` is also able to have this parameter, how is to do it for that as well? I would rename the issue. if you agreed.

**Comment by vfdev-5** [comment]
@sadra-barikbin yes, let's rename it and add the arg for clearml as well
