### ISSUE TITLE
Error in tbptt

### ISSUE THREAD

**Issue by AntoinePrv** [pytorch/ignite#255]
Hello,
I left a typo in [create_supervised_tbptt_trainer](https://github.com/pytorch/ignite/blob/8adab93849194d8ca0fe4d152a34f4269efbbc0f/ignite/contrib/engines.py#L43), sorry about it. On [this line](https://github.com/pytorch/ignite/blob/8adab93849194d8ca0fe4d152a34f4269efbbc0f/ignite/contrib/engines.py#L99) it should of course be 
```python
y_pred_t, hidden = model(x_t, hidden)
```

I'll do a PR to fix it, but of course I need to improve the tests for that function because this was not detected.

**Comment by vfdev-5** [comment]
@AntoinePrv thanks! Yes, definitely we need to improve the test part.
