### ISSUE TITLE
Wrong event -- EarlyStopping Example

### ISSUE THREAD

**Issue by rave78** [pytorch/ignite#258]
This is the example in the Ignite documentation about EarlyStopping
```
from ignite.engine import Engine, Events
from ignite.handlers import EarlyStopping

def score_function(engine):
    val_loss = engine.state.metrics['nll']
    return -val_loss

handler = EarlyStopping(patience=10, score_function=score_function, trainer=trainer)
evaluator.add_event_handler(Events.COMPLETED, handler)
```
I was wondering if `Events.COMPLETED` is wrong. I think the evaluator should be fired either `Events.EPOCH_COMPLETED` or `Events.ITERATION_COMPLETED`

**Comment by vfdev-5** [comment]
@rave78 this is a correct event in the docentation. Actually this handler is attached to an evaluator that runs a single epoch on a validation dataset. Once it is done, run completed we get results and check for early stopping.

**Comment by rave78** [comment]
I see.  thank you for your reply
