### ISSUE TITLE
Regarding calculating metrics

### ISSUE THREAD

**Issue by anmolsjoshi** [pytorch/ignite#259]
I know that metrics can be attached to any engine and they are calculated with torch.no_grad, so there is no limitation to where to calculate them. In the mnist example, it seems that the metrics related to training are calculated at the end of each epoch instead of during the training process. Is this standard practice?

I am working on a TensorBoard Handler and was hoping to understand what is standard so I can tweak my approach. 

Would appreciate any help!

**Comment by vfdev-5** [comment]
@anmolsjoshi @rave78 it seems that you both are working (or plan to work) on TensorBoard logger. Please create an issue for that and let's exchange for details there. Thanks

**Comment by anmolsjoshi** [comment]
Done
