### ISSUE TITLE
Problems with binary classifier & metrics

### ISSUE THREAD

**Issue by joelrich** [pytorch/ignite#262]
Hi,

I am new to PyTorch and am trying to get started with Ignite. I want to train a simple binary classifier:

```
class NeuralNet(nn.Module):
  def __init__(self, input_size, hidden_size, num_classes):
    super(NeuralNet, self).__init__()
    self.fc1 = nn.Linear(input_size, hidden_size)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(hidden_size, num_classes)
    self.out_act = nn.Sigmoid()

  def forward(self, x):
    out = self.fc1(x)
    out = self.relu(out)
    out = self.fc2(out)
    out = self.out_act(out)
    return out
```

First I had (plus some events):

```
trainer = create_supervised_trainer(model, optimizer, nn.BCELoss(), device=device)

evaluator = create_supervised_evaluator(
    model, metrics={'precision': Precision(),
                    'recall': Recall(),
                    'accuracy': BinaryAccuracy()}, device=device)
```

This failed with:

```
~/.local/share/virtualenvs/bot2-Z_RSwUyv/lib/python3.6/site-packages/ignite/metrics/precision.py in update(self, output)
     29         num_classes = y_pred.size(1)
     30         indices = torch.max(y_pred, 1)[1]
---> 31         correct = torch.eq(indices, y)
     32         pred_onehot = to_onehot(indices, num_classes)
     33         all_positives = pred_onehot.sum(dim=0)

RuntimeError: Expected object of type torch.LongTensor but found type torch.FloatTensor for argument #2 'other'
```

Then I found the `output_transform` parameter and changed it to:

```
def output_transform(output):
  y_pred, y = output
  return y_pred.gt(0.5).long(), y.long()

evaluator = create_supervised_evaluator(
    model, metrics={'precision': Precision(output_transform=output_transform),
                    'recall': Recall(output_transform=output_transform),
                    'accuracy': BinaryAccuracy(output_transform=output_transform)}, device=device)
```

Even if this worked, I do not think it was a good solution. In my opinion, it should be possible to do the transformation in just one place instead of having to pass it to each metric. Is this somehow possible? Anyway, this fails with:

```
~/.local/share/virtualenvs/bot2-Z_RSwUyv/lib/python3.6/site-packages/ignite/metrics/precision.py in update(self, output)
     35             true_positives = torch.zeros_like(all_positives)
     36         else:
---> 37             correct_onehot = to_onehot(indices[correct], num_classes)
     38             true_positives = correct_onehot.sum(dim=0)
     39         if self._all_positives is None:

IndexError: too many indices for tensor of dimension 1
```

Am I on the right track?

**Comment by vfdev-5** [comment]
Hi @joelrich thanks for the feedback. 
Concerning the first fail, could you please provide more detail on what is your data and targets especially.
The error states that your targets are float instead of being integer indices like (0, 1)

Concerning the possibility to setup output transform once for all metrics, let me think about this whether this is not too specific. As all metrics are independent it is OK to setup them separately.

**Comment by joelrich** [comment]
I fear that I have already deleted the code (without committing it first) because I decided to do everything from scratch. Anyway, this is what I remember:

It was a simple binary classifcation. Y_train/Y_test was an array like `[[0], [1], ...]`, Y_pred `[[0.453], [0.876], ...]`. The long/float problem happened because I first did not convert the floats to zeros and ones manually. By now, I agree that every metric should have its own output_transform. However, I still find it a bit strange that I had to write my own "rounding code" with the callbacks. An alternative threshold parameter for the classifier metrics might be useful. Something like `Precision(threshold=0.5)`.

Here is some code which reproduces the last problem:

```
from ignite.metrics import Precision

p = Precision()
p.update((torch.tensor([[1], [1]]), torch.tensor([[1], [0]])))
```

This results in:

```
IndexError: too many indices for tensor of dimension 1
```

**Comment by vfdev-5** [comment]
@joelrich 
> It was a simple binary classifcation. Y_train/Y_test was an array like `[[0], [1], ...]`, Y_pred `[[0.453], [0.876], ...]`

Simple binary classification can be done in two ways: 
- final activation is softmax with `y_train` is `[0, 1, 0, ...]` and `y_pred` is `[[0.9, 0.1], ...]`
- final activation is sigmoid with `y_train` is `[0, 1, 0, ...]` and `y_pred` is `[0.1, 0.9, 0.2,...]`

`Precision` metric is intended to work with multi-class classification (including 2 classes), first case. 

HTH

PS.: I'm not sure whether we would like to cover the second case...
cc @jasonkriss

**Comment by jasonkriss** [comment]
@vfdev-5 Sorry I think I'm still a lil confused. I agree with your two options for binary classification. With the first option, you can calculate accuracy with CategoricalAccuracy. With the second option, you can calculate accuracy with BinaryAccuracy. Are you asking if we should have some sort of `BinaryPrecision` and `BinaryRecall` metrics?

**Comment by vfdev-5** [comment]
@jasonkriss yes, I was asking whether we need to introduce BinaryPrecision and BinaryRecall metrics.

**Comment by vfdev-5** [comment]
@jasonkriss yes, completely agree with your proposition to improve `Precision`/`Recall` and merge `BinaryAccuracy` and `CategoricalAccuracy`. Maybe we should leave for the next next release the compatibility between`BinaryAccuracy` and `CategoricalAccuracy` and new `Accuracy`.

**Comment by alykhantejani** [comment]
If `BinaryAccuracy` and `CategoricalAccuracy` were introduced after `0.1` then we can just merge them here before `0.1.1` as we wont be breaking the API. If not, then we should still merge and provide deprecation warnings. i.e. merge the classes into `Accuracy` and still keep `BinaryAccuracy` and `CategoricalAccuracy` and have their constructors just create the appropriate instance of `Accuracy` and throw a warning that these will be removed in `0.1.2`

btw - we should freeze the things for 0.1.1 soon, finish them and cut a release

**Comment by anmolsjoshi** [comment]
Is someone working on this? Can I help out?

**Comment by vfdev-5** [comment]
@anmolsjoshi please go ahead. I think nobody has yet taken this one.

**Comment by anmolsjoshi** [comment]
Question regarding testing of metrics. For [test_compute_batch_image](https://github.com/pytorch/ignite/blob/master/tests/ignite/metrics/test_categorical_accuracy.py#L30)
Below is how y_pred is prepared and categorical accuracy is calculated

```python
    y_pred = torch.zeros(2, 3, 2, 2)
    y_pred[0, 1, :] = 1
    y_pred[0, 2, :] = 1

   indices = torch.max(y_pred, 1)[1] 
```
Given the above setup, y_pred[0, :, 0, 0] is [0, 1, 1]. I'm not sure if that is the correct intent of this test, shouldn't each pixel be a one-hot vector like [0, 0, 1].

Similar question for the binary accuracy test which uses an image of (2, 2, 2) where the first 2 is number of classes, but binary accuracy should only try to handle (N, 1, H, W) given the way indices are calculated for binary accuracy as in the test y is of shape (1, 2, 2). 

I know we're updating both, I just want to clarify these questions about these tests before rewriting them with the new Accuracy metric. 

Thoughts?
