### ISSUE TITLE
Cannot find ModelCheckpoint score name notes 

### ISSUE THREAD

**Issue by haochunchang** [pytorch/ignite#2622]
## 📚 Documentation

In the [ModelCheckpoint](https://pytorch.org/ignite/generated/ignite.handlers.checkpoint.ModelCheckpoint.html) documentation `score_name` parameter, it says: 
> if `score_function` not None, it is possible to store its value using _score_name_. See Notes for more details.

However, I cannot find any Notes for this detail.

I suggests adding examples about using `score_name` and `score_function` like [here](https://github.com/pytorch/ignite/issues/677#issuecomment-559786455)

I would love to open a PR for this if that is ok. Or if there are already examples exists, perhaps the links can be added to the documentation.

**Comment by vfdev-5** [comment]
@haochunchang thanks for the feedback, basically the examples were mostly written for [Checkpoint](https://pytorch.org/ignite/generated/ignite.handlers.checkpoint.Checkpoint.html#ignite.handlers.checkpoint.Checkpoint).
I agree it would be nice to improve the docs of `ModelCheckpoint` as well. Yes, please, send a PR with the improvements you think of and we can iterate over that.

**Comment by haochunchang** [comment]
take
