### ISSUE TITLE
Code formatting issue with latest flake8

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2638]
https://github.com/pytorch/ignite/runs/7781175697?check_suite_focus=true#step:11:84

```
Collecting flake8
  Downloading flake8-5.0.4-py2.py3-none-any.whl (61 kB)

+ flake8 ignite tests examples --config setup.cfg
ignite/metrics/psnr.py:12:121: E501 line too long (121 > 120 characters)
```

**Comment by trsvchn** [comment]
this https://github.com/psf/black/issues/1632looks similar

But why does flake complain right now?

**Comment by trsvchn** [comment]
Looks like the very first line of the docstring has to respect the line length convention.
