### ISSUE TITLE
Fix a few bugs in engine interrupt/resume feature

### ISSUE THREAD

**Issue by sadra-barikbin** [pytorch/ignite#2689]
## 🐛 Bug description

- [ ] A typo in [docstrings](https://github.com/pytorch/ignite/blob/c12ad57e26aa8ec2b191ff4bc0e01e97ef24f8f7/ignite/engine/engine.py#L34). 0.4.10 or 0.5.0?
- [ ] ~~`_run_once_on_dataset_as_gen` is restarted (because it is called) whenever we get into `_internal_run_as_gen`~~
- [ ] ~~Some statements before `_run_once_on_dataset_as_gen` should be skipped on resume and some other after that should be skipped on interrupt~~
- [ ] ~~Once running after a terminated state, `_run_once_on_dataset_as_gen` should be set to None before entering `_internal_run`.~~
- [ ] ~~If engine was interrupted in the middle of the last epoch, `is_done` incorrectly returns True on resume thus preventing it.~~
- [ ] ~~`_run_once_on_dataset_as_gen` yields the state on interrupt, not the time, so [this](https://github.com/pytorch/ignite/blob/c12ad57e26aa8ec2b191ff4bc0e01e97ef24f8f7/ignite/engine/engine.py#L965) shoud be changed.~~
- [ ] Since `_run_once_on_dataset_as_gen` has both return value and yield value with different types, its annotation could be updated to reflect this e.g. become `Generator[State, None, float]`

**Comment by vfdev-5** [comment]
> A typo in [docstrings](https://github.com/pytorch/ignite/blob/c12ad57e26aa8ec2b191ff4bc0e01e97ef24f8f7/ignite/engine/engine.py#L34). 0.4.10 or 0.5.0?

v0.5.0 is correct.

@sadra-barikbin for other points can you provide a repro for each statement to see exactly how it is failing ? Thanks!
