### ISSUE TITLE
Prepare CI for PyTorch 1.0

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#270]
Idea is to check CI against PyTorch 1.0:
```
conda install pytorch-nightly -c pytorch
```
and replace the hard-coded PyTorch version when documentation is built, see [here](https://github.com/pytorch/ignite/blob/master/.travis.yml#L84).

**Comment by Sayan98** [comment]
Hey, I would like to take up this issue.

**Comment by vfdev-5** [comment]
@Sayan98 thanks for the proposition ! 
I think it would be better to start assuming that [this PR](https://github.com/pytorch/ignite/pull/279) is accepted and check if everything passes when we using `pytorch-nightly`.

**Comment by vfdev-5** [comment]
Close this one in favor of #306
