### ISSUE TITLE
Handlers should print verbose and helpful messages

### ISSUE THREAD

**Issue by pbamotra** [pytorch/ignite#274]
Hi contributors,

I believe that handlers like model checkpoint and early stopping should print helpful messages like if the performance improved in the current iteration and the counter was reset.

Pankesh

**Comment by vfdev-5** [comment]
@pbamotra yes, for example early stopping uses logging to print messages, see [here](https://github.com/pytorch/ignite/blob/master/ignite/handlers/early_stopping.py#L43). 
I think model checkpoint can be quiet. What do you think about to print with model checkpoint ?

**Comment by vfdev-5** [comment]
I close this one as it seems to be answered.
@pbamotra feel free to reopen if you have more questions on that
