### ISSUE TITLE
Drop TrainsLogger and TrainsSaver

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2740]
I suggest to drop all ClearML/Trains backward compatibility as ClearML is v1.X since 1.5 year and no one should be using trains v0.16 (the last version of trains).

Let's do the following:
- [ ] remove TrainsLogger, TrainsSaver code and tests
- [ ] remove all trains package backward compatility. For example, https://github.com/pytorch/ignite/blob/4bdf243dca5fb35134c7f7db551f7fac43f639f8/ignite/contrib/handlers/clearml_logger.py#L118-L121

**Comment by louis-she** [comment]
I'd like to do it if no one else wants.

**Comment by soma2000-lang** [comment]
@vfdev-5  I would like to take this.

**Comment by vfdev-5** [comment]
@soma2000-lang any blockers from your side to send a PR to solve this issue ?

**Comment by soma2000-lang** [comment]
I haven't  starred working on it yet ,will start soon

**Comment by harry7337** [comment]
@vfdev-5 Hi! I would like to contribute to this issue asap, just wanted to clarify one thing. Do we need to drop TrainsSaver and Logger completely or is there an alternative we need to use(maybe something like clearml)?

**Comment by soma2000-lang** [comment]
@harry7337  I am working on it already

**Comment by harry7337** [comment]
> @harry7337  I am working on it already

@soma2000-lang I'll let you carry on then, good luck!

**Comment by vfdev-5** [comment]
@soma2000-lang please send a PR in following days.

@harry7337 we have other help wanted issues, please take another one 👍

**Comment by vfdev-5** [comment]
@soma2000-lang please communicate when you will be able to send a draft PR with a fix for this issue ?

**Comment by soma2000-lang** [comment]
@vfdev-5  I could not find any Trainslogger and TrainsSaver test file here.Also I am unable to find the TrainsSaver  file which  needs to be removed.

**Comment by vfdev-5** [comment]
Try to search for TrainsLogger: https://github.com/pytorch/ignite/search?q=TrainsLogger

May I ask whether you understand what we need to do to fix this issue ?

**Comment by soma2000-lang** [comment]
@vfdev-5  If I could understand the issue correctly  the I need to
1.completely remove the TrainsLogger.py[https://github.com/pytorch/ignite/blob/9230a7319047b37ce19d956e024fa1b86030c30a/ignite/contrib/handlers/trains_logger.py] file

**Comment by soma2000-lang** [comment]
If I have understood the issue correctly then I  have to


1.Completely remove the TrainsLogger.py file(ignite/contrib/handlers/trains_logger.py](https://github.com/pytorch/ignite/blob/9230a7319047b37ce19d956e024fa1b86030c30a/ignite/contrib/handlers/trains_logger.py)
and all  the places where the code of TrainsLogger and TrainsSaver has been used

2.Remove the backward comaptibility  code for the trains package.

**Comment by vfdev-5** [comment]
Seems correct, please go ahead with this plan
