### ISSUE TITLE
DeterministicEngine improvement

### ISSUE THREAD

**Issue by louis-she** [pytorch/ignite#2754]
* remove `torch.cuda.manual_seed_all(seed)` [here](https://github.com/pytorch/ignite/blob/1800feec9b4f70b2a6cd8f409ac76da06015efb1/ignite/utils.py#L237
) as `torch.manual_seed(seed)` will seed CUDA if it has CUDA enabled.
* try to use `torch.use_deterministic_algorithms(True)` if torch has it instead of `torch.backends.cudnn.deterministic = True`, as the later only makes convolutional deterministic.

**Comment by vfdev-5** [comment]
Solved by #2756
