### ISSUE TITLE
Update NeptuneLogger and handlers implementations to new API

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2758]
## 🚀 Feature

According to the docs : https://docs.neptune.ai/about/legacy/#initialization and https://docs.neptune.ai/about/legacy/#scores-and-metrics current [`NeptuneLogger` implementation](https://github.com/pytorch/ignite/blob/master/ignite/contrib/handlers/neptune_logger.py) is legacy and may fail with new neptune versions.

cc @Blaizzy

**Comment by Blaizzy** [comment]
@vfdev-5 

That is correct, and thanks for bringing this up!

FYI the updated integration is in the `development` stage 👍  but there is no ETA yet.

Here are a few alternatives I can think of:
- Add a warning about the version support and skip neptune tests
- Temporarily patch the current integration with the updates 
- Wait a bit longer for the update.

I will talk to the team and see if there are any updates on the development of the integration.

What are your thoughts?

**Comment by vfdev-5** [comment]
@Blaizzy thanks for the updates. How stable the new version ? I'm a bit surprized that new API is in the docs and previous is marked as legacy, but you say that new API is in dev stage...

By the way, there were another issue spotted by @louis-she on `importlib-metadata` being a common dep with the latest `gym`:
https://github.com/pytorch/ignite/pull/2757#issuecomment-1295868089
Can you bring it as well to neptune team. Thanks!

**Comment by Blaizzy** [comment]
Most welcome!

The new API is stable.

I was actually referring to the Neptune + PyTorch Ignite integration using the new API that is in the dev stage, not the API itself.

**Comment by Blaizzy** [comment]
Sure thing, I have informed the team, and we will look into it.

Thanks for letting me know!

**Comment by vfdev-5** [comment]
> I was actually referring to the Neptune + PyTorch Ignite integration using the new API that is in the dev stage

Is it from Neptune side or pytorch-ignite code ?
Anyway, can you update our code to the newer API ?

**Comment by Blaizzy** [comment]
> Is it from Neptune side or pytorch-ignite code ?

Neptune side, and we'll send a PR to your repo once it's done. :)

> Anyway, can you update our code to the newer API?

We have completed the specification of the update, and now it's marked `for development`, but there is no ETA for it.

**Comment by Blaizzy** [comment]
Great news on the dependency conflict with `gym`

The team had already noticed and fixed it [here](https://github.com/neptune-ai/neptune-client/blob/095c5f4fd5fb4d15bee587321ae8cdd67518bdcb/pyproject.toml#L15) and will be a part of a next release.

**Comment by vfdev-5** [comment]
Hey @Blaizzy, @jakubczakon  can we advance on this issue ?

**Comment by Blaizzy** [comment]
Hey @vfdev-5 

Unfortunately, there is still no ETA on the issue yet. It's waiting for development.

**Comment by vfdev-5** [comment]
Fixed in #2881
