### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Chucy2020** [pytorch/ignite#2762]
## Environment

- PyTorch Version (1.7):
- Ignite Version (e.g., 0.4.2):
- OS (Linux):
- How you installed Ignite (pip):
- Python version: 3.7
- Any other relevant information:

运行下面代码print(word_logits.shape)时正常可以得到结果，但是print(word_logits)时报错
![image](https://user-images.githubusercontent.com/73978694/200279258-fb287af8-169e-402f-9bb8-3bdb5eaf49aa.png)
错误如下：

![image](https://user-images.githubusercontent.com/73978694/200279532-30a591b9-a5ff-4b30-9c16-6c83ccf85d8c.png)
请问如下错误是什么问题？改如何解决？

**Comment by vfdev-5** [comment]
@Chucy2020 thanks for posting an issue but please write in english as our team can't read chineese.
On the other hand, is it related to pytorch-ignite somehow ?

**Comment by Chucy2020** [comment]
> @Chucy2020 thanks for posting an issue but please write in english as our team can't read chineese. On the other hand, is it related to pytorch-ignite somehow ?
Thank you for your reply and sorry for the trouble,
I used pytorch-ignite for this code，but the error may not be due to the pytorch-ignite. Now I haven't solved this problem, do you know how to solve this problem?

Running the following code print(word_logits.shape) normally yields the result, but print(word_logits) times the error

**Comment by vfdev-5** [comment]
To debug "CUDA error: device-side assert triggered" if you can reproduce the error on a given batch, I would recommend to switch on CPU and it can give you a more understandable error message (maybe some indices are going out of bounds)...

It could be helpful if you could provide a small repro code, such we could help.

**Comment by Chucy2020** [comment]
The following is the code, but the data is troublesome. I don't know how to send it to you.



 with torch.no_grad():
    # batch = tuple(convert_tensor(input_tensor, device=args.device, non_blocking=True) for input_tensor in batch)
    batch = tuple(input_tensor.to(args.device) for input_tensor in batch)
    graph, input_ids, decode_input, segment_id, input_masks, lm_labels, ans_idxs, ans_from = batch
    outputs = model(graph=graph, input_ids=input_ids, decoder_input_ids=decode_input, token_type_ids=None, labels=lm_labels, attention_mask=input_masks, decoder_ans_idxs=ans_idxs, decoder_ans_from=ans_from, return_dict=True)

    lm_logits = outputs.logits
    word_logits = lm_logits.gather(dim=2, index=labels.unsqueeze(-1)).squeeze() # (bsz, sumlen)
    print(word_logits )

**Comment by vfdev-5** [comment]
@Chucy2020 just try to run this batch and the model and all above code on cpu to see if it works or fails with a more comprehensive error

**Comment by Chucy2020** [comment]
> @Chucy2020 great! I think we can close the issue as unrelated to pytorch-ignite

Haha, thank you so much!
pytorch-ignite is very great
