### ISSUE TITLE
TypeError: Checkpoint.__init__() got an unexpected keyword argument 'require_empty'

### ISSUE THREAD

**Issue by aliwaqas333** [pytorch/ignite#2771]
## 🐛 can't save to checkpoint with files.

` handler = Checkpoint(to_save, DiskSaver('./checkpoints', create_dir=True), require_empty=False) `

when  `require_empty=False` not passed, the following error is thrown:
` '.pt' are already present in the directory checkpoints. If you want to use this directory anyway, pass 'require_empty=False'. `

is there any work around? 

thank you all.

## Environment ubuntu 22 cuda conda 

- PyTorch Version (e.g., 1.4): 1.11
- Ignite Version (e.g., 0.3.0): 0.3
- OS (e.g., Linux): Linux
- How you installed Ignite (`conda`, `pip`, source): pip
- Python version: 3.8

**Comment by vfdev-5** [comment]
@aliwaqas333 you need to put `require_empty` to [`DiskSaver`](https://pytorch.org/ignite/generated/ignite.handlers.DiskSaver.html#ignite.handlers.DiskSaver): 
```python
handler = Checkpoint(to_save, DiskSaver('./checkpoints', create_dir=True, require_empty=False))
```

**Comment by vfdev-5** [comment]
@aliwaqas333 I close the issue as solved. Feel free to reopen if needed.
