### ISSUE TITLE
Does ignite save checkpoint take up video memory?

### ISSUE THREAD

**Issue by Chucy2020** [pytorch/ignite#2779]
## Environment

- PyTorch Version (e.g., 1.4):1.7
- Ignite Version (e.g., 0.3.0):0.4.1
- OS (e.g., Linux):Linux
- How you installed Ignite (`conda`, `pip`, source):pip
- Python version:3.7
- Any other relevant information:

```
for i in range(n):
    common.setup_common_training_handlers()
    common.gen_save_best_models_by_val_score()
    trainer.run()   
```

During training, there will be a gradual increase in video memory, and eventually lead to cuda memory explosion
![image](https://user-images.githubusercontent.com/73978694/202171674-4d54c090-0035-458c-9b9c-c4ab61cd4958.png)
Please, Is this a problem caused by saving checkpoint or something else?

**Comment by vfdev-5** [comment]
@Chucy2020 thanks for reporting ! 

Do you create new trainer in the loop or append training handlers on each iteration ? I imagine your code looks like:
```python
trainer = ...

for i in range(n):
    common.setup_common_training_handlers()  # <---- here you add the same handlers multiple times in the loop
    common.gen_save_best_models_by_val_score()   # <---- same here
    trainer.run() 
```

Maybe, you have to setup trainer outside the loop ?
```python
trainer = ...
common.setup_common_training_handlers(...)
common.gen_save_best_models_by_val_score(...)

for i in range(n):
    trainer.run() 
```

**Comment by Chucy2020** [comment]
> @Chucy2020 thanks for reporting !
> 
> Do you create new trainer in the loop or append training handlers on each iteration ? I imagine your code looks like:
> 
> ```python
> trainer = ...
> 
> for i in range(n):
>     common.setup_common_training_handlers()  # <---- here you add the same handlers multiple times in the loop
>     common.gen_save_best_models_by_val_score()   # <---- same here
>     trainer.run() 
> ```
> 
> Maybe, you have to setup trainer outside the loop ?
> 
> ```python
> trainer = ...
> common.setup_common_training_handlers(...)
> common.gen_save_best_models_by_val_score(...)
> 
> for i in range(n):
>     trainer.run() 
> ```


Since I will train the model with different data in each cycle, my purpose is to load the model with the data training in the first cycle in the second cycle until the end of the cycle and the training ends. So, i have to setup trainer outside the loop ?

**Comment by Chucy2020** [comment]
> @Chucy2020 thanks for reporting !
> 
> Do you create new trainer in the loop or append training handlers on each iteration ? I imagine your code looks like:
> 
> ```python
> trainer = ...
> 
> for i in range(n):
>     common.setup_common_training_handlers()  # <---- here you add the same handlers multiple times in the loop
>     common.gen_save_best_models_by_val_score()   # <---- same here
>     trainer.run() 
> ```
> 
> Maybe, you have to setup trainer outside the loop ?
> 
> ```python
> trainer = ...
> common.setup_common_training_handlers(...)
> common.gen_save_best_models_by_val_score(...)
> 
> for i in range(n):
>     trainer.run() 
> ```

The way I am using it is as follows
for i in range(n):
    trainer = ...
    common.setup_common_training_handlers()  # <---- here you add the same handlers multiple times in the loop
    common.gen_save_best_models_by_val_score()   # <---- same here
    trainer.run()

**Comment by vfdev-5** [comment]
@Chucy2020 if you could share runnable code if would be more simple to help with the issue.

Where do you create the model and move it to cuda ?

**Comment by Chucy2020** [comment]
> if you could share runnable code if would be more simple to help with the issue.
> 
> Where do you create the model and move it to cuda ?



I really want to provide it to you and solve this problem as soon as possible, but it is difficult for the code to be transmitted from the Intranet.

The way I am using it is as follows:
```python
model = AutoModel.from_pretrained(model_path)
model = model.to(device)
for i in range(n):
    train_dataloder = Dataloader(train_data_i)
    trainer = ...
    common.setup_common_training_handlers()  # <---- here you add the same handlers multiple times in the loop
    resume_from(checkpoint_path)
    common.gen_save_best_models_by_val_score()   # <---- same here
    trainer.run() 
```

**Comment by Chucy2020** [comment]
> @Chucy2020 if you could share runnable code if would be more simple to help with the issue.
> 
> Where do you create the model and move it to cuda ?

Hello, is this code correct? How do I implement the code to make sense? Is the reason for the above memory increase because of the way I am coding? What should I do about it?

**Comment by vfdev-5** [comment]
Hello, above code does not look wrong from the first glance. Let me try that with a simple resnet and cifar10 config to check.

Can you put the following into your code to check memory consumption:
```
print(f"GPU memory: {torch.cuda.memory_allocated() / 1024 / 1024} MB")
```
to see at which steps you have the growth. Is it related to the loop iterations ?

**Comment by Chucy2020** [comment]
> 

Okay, I'll try it, thank you very much!  ~~~

**Comment by Chucy2020** [comment]
> Hello, above code does not look wrong from the first glance. Let me try that with a simple resnet and cifar10 config to check.
> 
> Can you put the following into your code to check memory consumption:
> 
> ```
> print(f"GPU memory: {torch.cuda.memory_allocated() / 1024 / 1024} MB")
> ```
> 
> to see at which steps you have the growth. Is it related to the loop iterations ?

I also want to know at this point is the model loading the trained model with the data in the loop or the untrained model outside the loop? thanks。
![image](https://user-images.githubusercontent.com/73978694/202379971-a14e6dcd-bff5-4025-91ca-653d3bcb1ded.png)

**Comment by vfdev-5** [comment]
@Chucy2020 Actually I do not quite understand why do you need to create a new trainer, dataloader etc for a chunk of training data ? 
Can't we do something like:
```python
model = ...
optimizer = ...

trainer = Engine(update)
to_save = {"trainer": trainer, "model": model, "optimizer": optimizer}
common.setup_common_training_handlers(to_save, ...)
common.gen_save_best_models_by_val_score(...)

lines = ...

for iter in range(n):
    for i in range(0, len(lines), data_onetime_train_lines):
        val_result = eval(model, val_loader)
        train_dataloader = DataLoader(lines[i:i + data_onetime_train_lines])

        resume_from(checkpoint_train_data_(i-1)

        trainer.run(train_dataloader, epochs)
```

As for your question, on the first iteration model will be `AutoModel.from_pretrained` and then it will be trained with `trainer.run` and this updated model will be evaluated..

**Comment by Chucy2020** [comment]
> @Chucy2020 Actually I do not quite understand why do you need to create a new trainer, dataloader etc for a chunk of training data ? Can't we do something like:
> 
> ```python
> model = ...
> optimizer = ...
> 
> trainer = Engine(update)
> to_save = {"trainer": trainer, "model": model, "optimizer": optimizer}
> common.setup_common_training_handlers(to_save, ...)
> common.gen_save_best_models_by_val_score(...)
> 
> lines = ...
> 
> for iter in range(n):
>     for i in range(0, len(lines), data_onetime_train_lines):
>         val_result = eval(model, val_loader)
>         train_dataloader = DataLoader(lines[i:i + data_onetime_train_lines])
> 
>         resume_from(checkpoint_train_data_(i-1)
> 
>         trainer.run(train_dataloader, epochs)
> ```
> 
> As for your question, on the first iteration model will be `AutoModel.from_pretrained` and then it will be trained with `trainer.run` and this updated model will be evaluated..

Thank you very much for your reply and patience.
I used the data in common.setup_common_training_handlers, so I put it inside the loop.
Putting it outside has no effect?

> ```python
> model = ...
> optimizer = ...
> 
> trainer = Engine(update)
> to_save = {"trainer": trainer, "model": model, "optimizer": optimizer}
> #common.setup_common_training_handlers(to_save, ...)
> common.gen_save_best_models_by_val_score(...)
> 
> lines = ...
> 
> for iter in range(n):
>     for i in range(0, len(lines), data_onetime_train_lines):
>         val_result = eval(model, val_loader)
>         train_dataloader = DataLoader(lines[i:i + data_onetime_train_lines])
>         common.setup_common_training_handlers(to_save, train_sampler=train_loder.sampler,...)
>         resume_from(checkpoint_train_data_(i-1)
> 
>         trainer.run(train_dataloader, epochs)
> ```

**Comment by vfdev-5** [comment]
@Chucy2020 I think we can rewrite this code to get `setup_common_training_handlers` out of the loop.

Are you doing distributed training ?

```
model = ...
optimizer = ...

trainer = Engine(update)
trainer.state.train_sampler = None
to_save = {"trainer": trainer, "model": model, "optimizer": optimizer}
common.setup_common_training_handlers(to_save, train_sampler=None, ...)
common.gen_save_best_models_by_val_score(...)

@trainer.on(Events.EPOCH_STARTED)
def distrib_set_epoch(engine: Engine) -> None:
     assert trainer.state.train_sampler is not None
     trainer.state.train_sampler.set_epoch(engine.state.epoch - 1)

lines = ...

for iter in range(n):
    for i in range(0, len(lines), data_onetime_train_lines):
        val_result = eval(model, val_loader)
        train_dataloader = DataLoader(lines[i:i + data_onetime_train_lines])
        # Let's set sampler into trainer state:
        trainer.state.train_sampler = train_dataloader.sampler
        resume_from(checkpoint_train_data_(i-1)

        trainer.run(train_dataloader, epochs)
```

**Comment by Chucy2020** [comment]
> @Chucy2020 I think we can rewrite this code to get `setup_common_training_handlers` out of the loop.
> 
> Are you doing distributed training ?
> 
> Here is the code with `setup_common_training_handlers` outside of the loop:
> 
> ```python
> model = ...
> optimizer = ...
> 
> trainer = Engine(update)
> trainer.state.train_sampler = None
> to_save = {"trainer": trainer, "model": model, "optimizer": optimizer}
> common.setup_common_training_handlers(to_save, train_sampler=None, ...)
> common.gen_save_best_models_by_val_score(...)
> 
> @trainer.on(Events.EPOCH_STARTED)
> def distrib_set_epoch(engine: Engine) -> None:
>      assert trainer.state.train_sampler is not None
>      trainer.state.train_sampler.set_epoch(engine.state.epoch - 1)
> 
> lines = ...
> 
> for iter in range(n):
>     for i in range(0, len(lines), data_onetime_train_lines):
>         val_result = eval(model, val_loader)
>         train_dataloader = DataLoader(lines[i:i + data_onetime_train_lines])
>         # Let's set sampler into trainer state:
>         trainer.state.train_sampler = train_dataloader.sampler
>         resume_from(checkpoint_train_data_(i-1)
> 
>         trainer.run(train_dataloader, epochs)
> ```

Thank you very much.
Not yet, I will use distributed next because there is too much data and single card training is too slow.

**Comment by vfdev-5** [comment]
> Not yet, I will use distributed next because there is too much data and single card training is too slow.

in this case you do not need to put train_sampler into `setup_common_training_handlers` as it is only for DDP

**Comment by Chucy2020** [comment]
> in this case you do not need to put train_sampler into `setup_common_training_handlers` as it is only for DDP

Okay, I get it, thank you very much. 
Thank you for being professional, responsible, patient, powerful, etc. Thank you!

**Comment by vfdev-5** [comment]
@Chucy2020 did you solve the issue ?

**Comment by Chucy2020** [comment]
> did you solve the issue ?

![image](https://user-images.githubusercontent.com/73978694/202936295-f6d40783-5ec5-4ac6-99fb-06221e172c1d.png)

No, I don't know what the problem is with that one, maybe it's not a problem brought on by models being placed inside loops or constantly saving models, now this video memory doesn't seem to be increasing.
