### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Liumengqiu01** [pytorch/ignite#2781]
def _check_shape(self, output: Sequence[torch.Tensor]) -> None:
        y_pred, y = output

if not (y.ndimension() == y_pred.ndimension() or y.ndimension() + 1 == y_pred.ndimension()):

it said type of y_pred is tuple

**Comment by vfdev-5** [comment]
@Liumengqiu01 can you provide some code that gives you this error. 
Without the context, everything seems fine. Predictions should be a tensor and not tuple

**Comment by Liumengqiu01** [comment]
> @Liumengqiu01 can you provide some code that gives you this error. Without the context, everything seems fine. Predictions should be a tensor and not tuple

@vfdev-5 Thanks for your help, I think I've figured this out myself. I made a careless mistake because I was missing a variable to receive the output of the model. Sorry to trouble you.

**Comment by vfdev-5** [comment]
Sounds good. I close the issue as solved then.
