### ISSUE TITLE
[CI] update set-output usage

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2784]
Use
```
- name: Set output
  run: echo "{name}={value}" >> $GITHUB_OUTPUT
```
instead of
```
- name: Set output
  run: echo "::set-output name={name}::{value}"
```
in our GHA yml files.

- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

What to do:
- comment here to be assigned to the issue
- find all files where we use "::set-output"
- replace set-output by what GH suggests (see above)
- send a PR

**Comment by guptaaryan16** [comment]
Hey @vfdev-5, please assign me to this issue
