### ISSUE TITLE
CI GH Actions updates

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2789]
According to recent warnings on unit tests:
```
cpu-tests (ubuntu-latest, 3.9, pytorch)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/setup-python@v2, codecov/codecov-action@v1
```
we need to update versions for `actions/setup-python@v2` and `codecov/codecov-action@v1`.

What to do:
- Find the latest version for `actions/setup-python@v2` and `codecov/codecov-action@v1`
- Update the version for all our GH actions workflows by searching in the codebase
- Please send a PR

**Comment by vfdev-5** [comment]
@guptaaryan16 would you like to tackle this one ?

**Comment by guptaaryan16** [comment]
yes ok I will take this

**Comment by RishiKumarRay** [comment]
@vfdev-5 @guptaaryan16  can i go for this ?

**Comment by guptaaryan16** [comment]
yeah you can take this
