### ISSUE TITLE
WandBLogger and TensorboardLogger have different APIs for logging audio

### ISSUE THREAD

**Issue by turian** [pytorch/ignite#2791]
## 🚀 Feature

The following code doesn't work:

```
logger = WandBLogger()
logger.writer
```

This is how you would typically add audio with a tensorboard logger:
```
logger.writer.add_audio('mixture', x.t(), engine.state.epoch)
```

The workaround (similar to discussed in https://github.com/Lightning-AI/lightning/issues/7028) would be to use the underlying _wandb object:
```
logger._wandb.log({"validation": [wandb.Audio(x.t(), caption="mixture", sample_rate=44100)]})
logger._wandb.log({"validation": [wandb.Audio(x.t(), caption="vocals", sample_rate=44100)]})
```

Is there a proposal for a standardized media logging API?

**Comment by vfdev-5** [comment]
@turian thanks for reporting.

I think you do not need such workaround as we propagate automatically attributes to `_wandb`:
https://github.com/pytorch/ignite/blob/a36e62dbc6f88e186c3ea183f0b498fc2bf5e14b/ignite/contrib/handlers/wandb_logger.py#L137-L138

So, I think the following should work (haven't explicitly checked)
```python
logger.log({"validation": [wandb.Audio(x.t(), caption="mixture", sample_rate=44100)]})
logger.log({"validation": [wandb.Audio(x.t(), caption="vocals", sample_rate=44100)]})
```

> WandBLogger and TensorboardLogger have different APIs for logging audio

I agree that in case of TensorboardLogger, user can access `logger.writer` object and use directly tensorboard API as in your example. Maybe, it would make sense to propagate attributes to `writer` similarly to what we are doing for WandBLogger. What do you think ?

**Comment by guptaaryan16** [comment]
Hey @vfdev-5 I want to contribute to this issue, can you please give me a general idea what should I do to make the APIs consistent

**Comment by vfdev-5** [comment]
@guptaaryan16 as it is described in https://github.com/pytorch/ignite/issues/2791#issuecomment-1336521118 we can add `__getattr__` to `TensorboardLogger` to propagate call to `writer` such that user does not need to call it:
```diff
- logger.writer.add_audio('mixture', x.t(), engine.state.epoch)
+ logger.add_audio('mixture', x.t(), engine.state.epoch)
```
Is it more clear now ?

**Comment by guptaaryan16** [comment]
thanks for the guidance , I will try to complete it as fast as possible
