### ISSUE TITLE
Requirements document

### ISSUE THREAD

**Issue by PaulDaratzis** [pytorch/ignite#2804]
Hello I would like to make the document of requirements for the project. Could you give me some information about the project?

**Comment by vfdev-5** [comment]
@PaulDaratzis thanks for asking and the interest to the project. What do you mean by document of requirements ?
As for the project info please check the readme and our website: pytorch-ignite.ai

**Comment by PaulDaratzis** [comment]
Thank you for the information. I would like to write them about the software specifications like resources, security, connectivity,stability etc

**Comment by vfdev-5** [comment]
Closing as solved
