### ISSUE TITLE
[CI] distributed gpu tests are failing on pytorch-nightly

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2841]
- https://github.com/pytorch/ignite/actions/runs/4064422346/jobs/6997839795

```
[gw1] [ 34%] FAILED tests/ignite/distributed/comp_models/test_native.py::test__native_dist_model_warning_index_less_localrank 
```

**Comment by guptaaryan16** [comment]
Hey @vfdev-5 I want to start working on this issue as well so can you provide some explanation about the same

**Comment by vfdev-5** [comment]
@guptaaryan16 this is a CI issue and seems like now GPU tests on pytorch-nightly are passing. Close the ticket
