### ISSUE TITLE
tqm_logger: metric_names is currently not optional 

### ISSUE THREAD

**Issue by rlebret** [pytorch/ignite#285]
Hi,

https://github.com/pytorch/ignite/blob/master/ignite/contrib/handlers/tqdm_logger.py#L75
This line should be modified to make `metric_names` optional. Here is a suggestion:
```
if metric_names is not None and not isinstance(metric_names, list):
    raise TypeError("metric_names should be a list, got {} instead".format(type(metric_names)))
```

Thanks

**Comment by miguelvr** [comment]
thanks for pointing it out! I'll fix that ASAP
