### ISSUE TITLE
[Feature Request]  tqdm_logger update on every epoch instead of every iteration

### ISSUE THREAD

**Issue by PsiPhire** [pytorch/ignite#289]
Currently `tqdm_logger` creates a progress bar for every epoch and updates it on every iteration. I would like to have a single progress bar for the entire run that updates every epoch instead.

**Comment by miguelvr** [comment]
@vfdev-5 I could add back the `mode` argument to support this. Should be relatively straightforward

**Comment by vfdev-5** [comment]
@miguelvr yes, go ahead.

**Comment by alykhantejani** [comment]
Thanks @miguelvr

**Comment by vfdev-5** [comment]
@miguelvr any updates on this :)

**Comment by miguelvr** [comment]
I started it already, but I have been quite busy with work. Will work on it soon, sorry for the delay

**Comment by vfdev-5** [comment]
@miguelvr no problem, take your take :) I had a doubt whether it was already done in a PR on tqdm

**Comment by vfdev-5** [comment]
@miguelvr any updates on this ?

**Comment by vfdev-5** [comment]
@miguelvr I tried to implement this one by myself. Seems to be not a trivial one without changing the API and keeping all simple

**Comment by vfdev-5** [comment]
I was also thought about how to itegrate this one with [this feature](https://github.com/pytorch/ignite/pull/351): to support custom events
