### ISSUE TITLE
Dependencies issue on CI with pytest and codecov

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2917]
All CI jobs are failing due to dependencies issue: 
```
Requirement already satisfied: numpy in /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages (from -r requirements-dev.txt (line 2)) (1.24.2)
Collecting pytest
  Using cached pytest-7.3.0-py3-none-any.whl (320 kB)
ERROR: Could not find a version that satisfies the requirement codecov (from versions: none)
ERROR: No matching distribution found for codecov
```

- https://github.com/pytorch/ignite/actions/runs/4685041039/jobs/8303411754?pr=2907

~~Hypothesis: pytest has released a new version that is incompatible with `pytest-cov` plug-in.~~
This a wrong hypothesis. Another one: Issue is related to https://github.com/codecov/python-standard/issues/31

TODO:
- figure out (and confirm above hypothesis) why there is this issue and report the conclusion here
- Send a PR with a fix

**Comment by AlexanderChaptykov** [comment]
Why to not use Poetry?

**Comment by vfdev-5** [comment]
I'm not very familiar with poetry. What would be benefits of using it vs requirements list for pip ?

**Comment by AlexanderChaptykov** [comment]
Poetry automatically find compatible version, and should solve this type of issue. I hope

**Comment by vfdev-5** [comment]
From what I remember from poetry is that they may be fixing deps versions, so yes then the resolver can find compatible versions. In our case in https://github.com/pytorch/ignite/blob/master/requirements-dev.txt we left everything unfixed to take the latest versions and such issues can happen from time to time when one version is temporarily is incompatible with another one.

**Comment by AlexanderChaptykov** [comment]
`codecov` - is it correct name of the package? `pytest-codecov` maybe this right name?

**Comment by vfdev-5** [comment]
Seems like they just removed recently `codecov` package from pypy: https://github.com/codecov/python-standard/issues/31 
We have to follow their migration guidelines...
