### ISSUE TITLE
[Feature request] class MaximumAbsoluteError(Metric)

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/ignite#292]
`error = (y_pred - y).abs().max()`

Would this be a good thing to add?

**Comment by zasdfgbnm** [comment]
@vfdev-5 This is for regression problem, it characterizes how far the worst point are deviated from ground truth.

**Comment by alykhantejani** [comment]
I echo @jasonkriss sentiment, that more metrics are welcom. MAE is often used in recommender systems, and other regression tasks to measure performance. 

I say go for it, might as well just put it in core as it's pretty simple to implement and I don't envisage much support being needed going forward

@zasdfgbnm can you send a PR?
