### ISSUE TITLE
Set custom state variables at engine creation

### ISSUE THREAD

**Issue by milesial** [pytorch/ignite#297]
Hello <sup>(again)</sup>, currently the `engine.state` object is created on the first run of the engine. I would like to assign custom data before the engine runs, just after its creation:

```python
trainer = engine.create_supervised_trainer(model, optimizer, loss)
trainer.state.my_var = 42
```
> AttributeError: 'NoneType' object has no attribute 'progress_bar'

I could assign my_var directly to `engine`, but I and the docs think that it is good practice to store user data in the state. (Specifically, I want to assign a `ProgressBar` instance.)

**Solution:**

We could assign `engine.state` to a default `State` in the constructor, instead of setting it to None.

Then, on `run`, we assign the dataloader, we set the epoch and max_epoch.

so in the contructor we can call
```python
self.state = State()
```

and on `run`:
```python
self.state.dataloader = data
self.state.epoch = 0
self.state.max_epochs = max_epochs
self.state.metrics = {}
```

Should I open a PR for this ?

**Comment by vfdev-5** [comment]
@milesial take a look at #193 
Internal state I think should be reinitialised at each run. More on this you can find in #182.

**Comment by milesial** [comment]
Thanks, so as I understand it the `engine.state` is more of a run-state that an engine-state. For my issue I will stick to assigning it directly to the engine I think. However if I wanted to checkpoint / resume the engine it wouldn't have saved my custom variable : what about checkpointing accross-runs custom variables ?

There is another solution:
```python
trainer = engine.create_supervised_trainer(model, optimizer, loss)
pbar = ProgressBar()
pbar.attach(trainer)

@trainer.on(Events.STARTED)
def assign_var(engine):
    engine.state.progress_bar = pbar
```

but it involves an out-of-scope variable, it would be cleaner to be able to do:

```python
trainer = engine.create_supervised_trainer(model, optimizer, loss)
pbar = ProgressBar()
pbar.attach(trainer)
trainer.state.progress_bar = pbar
```

**Comment by vfdev-5** [comment]
> what about checkpointing accross-runs custom variables ?
@milesial i'm not quite sure to understand your question.

Anyway, to initialize a variable at start can be done as said [here](https://github.com/pytorch/ignite/issues/193#issuecomment-398054103):
```
@evalutor.on(Events.STARTED)
def init_all_custom_var(engine):
     engine.state.my_var = []
```

But seeing the example you are providing with `engine.state.progress_bar = pbar`, what is the purpose to add progress bar to the state? You can call it directly from any handler:
```
pbar = ProgressBar()

@trainer.on(Events.*)
def event_handler(engine, *args, **kwargs):
    pbar.log_message("....")
```

**Comment by milesial** [comment]
@vfdev-5 I was thinking about someone that might use `engine.state` to store global info about the engine, variables that do not depend on the run and the run parameters (maybe to use in the process function, or in a handler). If the state is erased for each run, those variables would be erased at the start of each run.
I have no concrete example, I was just thinking about it.


In my case, I wanted to export the engine to other modules and notebooks, and allow these modules to add handlers that use the progress bar instance, without actually passing them both the engine and the progress bar, for each engine.

**Comment by vfdev-5** [comment]
@milesial in this case you can just add this stuff to the engine directly:
```
engine.global_info = ...
```

**Comment by milesial** [comment]
Yeah that's what I did :) I'll close the issue thanks.
