### ISSUE TITLE
Link is broken for Getting Started

### ISSUE THREAD

**Issue by puhuk** [pytorch/ignite#2995]
## 📚 Documentation

In markdown (https://github.com/pytorch/ignite#getting-started),
there are two links for `[Quick Start Guide: Essentials of getting a project up and running](https://pytorch.org/ignite/quickstart.html)` and `[Concepts of the library: Engine, Events & Handlers, State, Metrics](https://pytorch.org/ignite/concepts.html)`

I raise this issue cause both links are broken :)

**Comment by vfdev-5** [comment]
@puhuk thanks for reporting the issue !
