### ISSUE TITLE
How to pass arguments to the process function of the engine?

### ISSUE THREAD

**Issue by onnyyonn** [pytorch/ignite#3000]
## ❓ Questions/Help/Support

I am creating a class with the step and train functions inside, which looks something like this:
```python
class MyModel(torch.nn.Module):

    def __init__(self, arg1):
        super().__init__()
        self.arg1 = arg1

    def step(self, engine, batch, arg2):
        ...
        ...
        return someFunction(batch, self.arg1, arg2)

    def train(arg2):
        trainer = Engine(self.step)
        ...
```

Now `self.step` is expecting 3 arguments. But in the Pytorch Ignite documentation, `engine` and `batch` are usually not explicitly passed to this function. What would be the write way to pass the arguments in my case?

**Comment by sadra-barikbin** [comment]
@onnyyonn , thank you for the question. Both `engine` and `batch` are passed to the `step` function. So you could use them. Could you please tell where in the documents there's no explicitness?
Regarding `arg2`, if it's a constant argument like a hyper parameter, you could use `functools.partial` to feed it to `self.step` on creating `trainer`:

```python
import functools
trainer = Engine(functools.partial(self.step, arg2=arg2))
```
I Hope that helps.

**Comment by onnyyonn** [comment]
@sadra-barikbin Thanks for the `functools.partial` suggestion. It solves my problem.

Regarding my comment on explicitness, I think I should have expressed it more clearly. What I meant is, `engine` and `batch` are passed to the function, without us having to declare it explicitly. So I was confused what to do about the other arguments. Your suggestion solves the problem.

**Comment by vfdev-5** [comment]
In addition to Sadra's answer, we can in general save params in `trainer.state` and get them in the step function:
```python
def training_step(engine, batch):
    arg2 = engine.state.arg2
    ...


trainer = Engine(training_step)
trainer.state.arg2 = ...
```

We can also update params in handlers if they need to be non-static.

**Comment by onnyyonn** [comment]
@vfdev-5 thank you. I was planning on submitting another question on changing the training step function based on the epoch. Your suggestion can help me with that as well.

**Comment by vfdev-5** [comment]
You can also get a prompt reply on our discord server: https://pytorch-ignite.ai/chat
