### ISSUE TITLE
Discussion about Metrics plotting

### ISSUE THREAD

**Issue by amitibo** [pytorch/ignite#301]
Hello, I would like to discuss the automation the metric plotting.

## Motivation

Currently a big part of (my?) ignite scripts go into the boiler plate of logging the training and testing results, be it a set of **visdom** windows, **mlflow** experiments, logging files or any combination of these. Each time a metric is added or removed, all the logging mechanism needs to be updated accordingly.

## Solution

A possible solution is to have a mechanism similar to the `ProgressBar` (#296), where you create a `Plotting` object (e.g. a wrapper to a **visdom** window or **mlflow** server) and `attach` metrics to it. This object will take care of plotting the metric in the correct context.

An example use case is to have a **visdom** window that plots loss values every iteration or metric values every epoch. Another use case is to log the metrics to an **mlflow** experiment. 

The benefit of this idea is that it will reduce much of the plotting boiler plate that currently has to be "manually" added to event handlers.

## Implementation Discussion

The problem that I see with the `attach` approach (used in the `ProgressBar`) is that it is not clear whether the `EPOCH_COMPLETED` will trigger first the `self.completed` method of the metric, or the plotting callback of the `Plotting` object. In the second case, the metric value will not be ready for plotting.

In my opinion a better method is to add a callback mechanism to the `Metric` class that enables calling arbitrary callbacks (**visdom** plot etc) at the end of the `completed` method.

Another option is to add a wrapper metric (like `RunningAverage`) that will add the callback functionality.

Will appreciate any ideas.

**Comment by miguelvr** [comment]
There's currently an ongoing PR for a TensorBoard handler (#265). A Visdom handler would be welcome as well, I think.

**Comment by jasonkriss** [comment]
@amitibo I am totally in agreement here. This logging/plotting of metrics is the only real significant source of boilerplate in my projects these days.

I'm not sure on the implementation yet. I definitely see your point on the confusion around ordering of metric computation and logging. @alykhantejani @vfdev-5 What are your thoughts on this? How are you currently handling this?

**Comment by amitibo** [comment]
A possible solution to the confusion around ordering of metric computation is to have more fine grained `Events` enum, e.g. add `Events.EPOCH_FINALIZED` and `Events.ITERATION_FINALIZED` which are fired after the corresponging `..._COMPLETED` events. Logging handlers can attach to these events knowing that the metrics were already calculated.

**Comment by amitibo** [comment]
BTW, I just noticed that there might already be an implicit assumption in the code, that the metrics handlers are called first (being attached to the evaluator `Engine` on its creation). If I am correct this assumption, for example, allows using the `ModelCheckpoint` with a `score_function` that uses the engine metrics. Note that both the `ModelCheckpoint` object and the `Metric.completed` method are attached to the `EPOCH_COMPLETED` event.

**Comment by vfdev-5** [comment]
@amitibo yes, you are correct about implicit assumption about metrics, especially with `create_supervised_*`. Maybe we need to underline the logic that user need to setup metrics computation before setting up any handler using info from `engine.state.metrics`.

**Comment by vfdev-5** [comment]
@amitibo yes, you are correct about implicit assumption about metrics, especially with `create_supervised_*`. Maybe we need to underline the logic that user need to setup metrics computation before setting up any handler using info from `engine.state.metrics`.

**Comment by vfdev-5** [comment]
I think we can close this one. If there are any other suggestions to plot metrics, please open another issue.
