### ISSUE TITLE
Is it good to Add Feature "cosine annealing with warmup restart each cycle"?

### ISSUE THREAD

**Issue by sihyeong671** [pytorch/ignite#3036]
## ❓ Questions/Help/Support

I asked [this question](https://discord.com/channels/831462531327328276/831463420272312330/1139572172122247218) on discord channel

Do you think it is good to add "cosine annealing with warmup restart each cycle" feature?
If you have plan to add this feature, can I contribute this?

**Comment by vfdev-5** [comment]
@sihyeong671 thanks for opening this issue, indeed we discussed about this feature and eventually a possibility to add it to ignite.

> Do you think it is good to add "cosine annealing with warmup restart each cycle" feature?

Yes, let's add it.

> If you have plan to add this feature, can I contribute this?

RIght now we haven't thought about how exactly provide such lr scheduler:
- as an option to some existing class
- write a new class with the code inspired from https://github.com/katsura-jp/pytorch-cosine-annealing-with-warmup/blob/master/cosine_annealing_warmup/scheduler.py

If you have a suggestion we would be happy to try to elaborate it and you can definitely contribute it

**Comment by vfdev-5** [comment]
Fixed in #https://github.com/pytorch/ignite/pull/3064
