### ISSUE TITLE
Version selector on gh-pages like in pytorch docs

### ISSUE THREAD

**Issue by igormq** [pytorch/ignite#308]
I think that many of us are installing the ignite using the master branch.

It would be nice if the ignite documentation also contains the master docs like https://pytorch.org/docs/versions.html. 

What do you think?

Best,
Igor.

**Comment by vfdev-5** [comment]
@igormq today the documentation reflects the master version and not the stable 0.1.0. 
I agree that it would be nice to add such selector between versions.

**Comment by miguelvr** [comment]
I think the easiest way is to host the documentation on readthedocs.org

**Comment by vfdev-5** [comment]
@miguelvr yes, it is pretty easy to deal with that in `readthedocs.org`, but today our docs are at `pytorch.org/ignite` and not all projects have this opportunity :)

**Comment by miguelvr** [comment]
yeah, but `pytorch.org` has the version selector, so I guess we can still do it.

Since you brought that up: 

It is a shame that this project does not appear on https://pytorch.org/ecosystem, or is linked in the main page in some way.

**Comment by vfdev-5** [comment]
> It is a shame that this project does not appear on https://pytorch.org/ecosystem, or is linked in the main page in some way.

@miguelvr yes, we talked about that with @soumith, he told that he will work on it, to highlight ignite and skorch, and we are still waiting :)

**Comment by anmolsjoshi** [comment]
* Up to date fork that works with Sphinx==1.8.5 - https://github.com/sphinxcontrib-versioning-ng/sphinxcontrib-versioning
* working link here - https://anmolsjoshi.github.io/ignite_sphinx_try/

**Comment by vfdev-5** [comment]
@anmolsjoshi, your working prototype looks great and seems like doing what we need ...
