### ISSUE TITLE
Allow the settings of require_empty flag when constructing the checkpoint object

### ISSUE THREAD

**Issue by ggbioing** [pytorch/ignite#3137]
When instantiating the checkpoint object it would be useful to be able to set the "require_empty" flag of DiskSaver to values other than the default (True) one.

https://github.com/pytorch/ignite/blob/4dc4e04b901c682e3e6f0b193a18c50c56eb3c41/ignite/handlers/checkpoint.py#L326C64-L326C64

**Comment by vfdev-5** [comment]
@ggbioing thanks for the feedback! In case if we would like to customize DiskSaver options we can pass its instance to the Checkpoint as following:
```python
save_handler = DiskSaver('/tmp/models', create_dir=False, require_empty=False)
handler = Checkpoint(to_save, save_handler, ...)
```

What do you think ?

**Comment by ggbioing** [comment]
excellent!
