### ISSUE TITLE
Arithmetic of metrics?

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/ignite#321]
Is it good to support arithmetics of metrics?

For example, `metric1 + metric2` gives a new metric whose update function is updating metric1 and metric2, and compute function is the sum of the compute of metric1 and metric2.

The idea comes from wiki: https://en.wikipedia.org/wiki/Sensitivity_and_specificity

There are many things to do with confusion matrix, see the table in https://en.wikipedia.org/wiki/Sensitivity_and_specificity#Definitions

It might be nice to add a metric for counting positive, true positive, negative, true negative, and allow users to combine these values using arithmetics to form their own metric.

**Comment by vfdev-5** [comment]
@zasdfgbnm excelent idea, thanks ! I was thinking about a similar stuff previously in a very simple case of `accuracy` -> `error = 1.0 - accuracy`. 
The API I was thinking of is something like:
```
precision = Precision()
recall = Recall()


def compute_f1(p, r):
    return 2 * p * r / (p + r)

f1= MetricsLambda(compute_f1, precision, recall) 
f1.attach(evaluator, "f1")
```

> It might be nice to add a metric for counting positive, true positive, negative, true negative, and allow users to combine these values using arithmetics to form their own metric.

👍

**Comment by amitibo** [comment]
I am already using a reduction metric:
```
class ReductionMetric(Metric):
    """
    Apply reduction to a list of metrics.

    Args:
        metrics (list of metrics): The metrics to apply reduction to.
        reduction (callable): The reduction operation to apply to the metrics.
        output_transform (callable): a callable that is used to transform the
            model's output into the form expected by the metric. This can be
            useful if, for example, you have a multi-output model and you want to
            compute the metric with respect to one of the outputs.
    """
    def __init__(self, metrics: Union[Tuple, List], reduction=mean, output_transform=lambda x: x):

        self.metrics = metrics
        self.reduction = reduction
        super(ReductionMetric, self).__init__(output_transform=output_transform)

    def reset(self):
        for metric in self.metrics:
            metric.reset()

    def update(self, output):
        for metric in self.metrics:
            o = metric._output_transform(output)
            metric.update(o)

    def compute(self):
        return self.reduction([m.compute() for m in self.metrics])
```
I can create a PR, let me know about the API.

**Comment by jasonkriss** [comment]
Love this idea!

**Comment by zasdfgbnm** [comment]
done
