### ISSUE TITLE
Too much memory was cost for eval and train 

### ISSUE THREAD

**Issue by niuliling123** [pytorch/ignite#3211]
## 🐛 Bug description
Problem:
when  I set persistent_worker = True in datalaoder, The memory cost of model will increase 2 times
eg: 
   the model is training 344G CPU memory was token, after one epoch, use _run_once_on_dataset for eval, 630G memory of CPU was costed, and the memory will never released after eval. so it'll be OOM when memory size of GPU is very small

![image](https://github.com/pytorch/ignite/assets/51102941/bdac9332-ae29-459d-8aad-e18ac75d0423)

## Environment
- PyTorch Version :1.11
- ignite Version: 0.4.8
- OS : Linux
- How you installed Ignite (`conda`, `pip`, source):pip
- Python version: 3.8
- Any other relevant information:

**Comment by vfdev-5** [comment]
@niuliling123 thanks for reporting this issue!
Do you think it could be possible to get a minimal repro code for that?
At first glance, persistent_worker is related to pytorch dataloader and it may be possible that ignite has little impact on that.
I would like to figure out whether it is pytorch or ignite problem.

**Comment by niuliling123** [comment]
I got it , thanks
