### ISSUE TITLE
Confused about Batch_size

### ISSUE THREAD

**Issue by niuliling123** [pytorch/ignite#3233]
## 🐛 Bug description

<img width="530" alt="image" src="https://github.com/pytorch/ignite/assets/51102941/78d92aa4-c482-4b74-969d-c60925257dc3">
HI, when I use the auto_dataloder, I really confused about  the code in the image, 
If I update my batch_size from 1 to 16, and world_size still is 8,  Need I set batch_size = batch_size * world_size. eg:  auto_dataloder( batch_size = batch_size * world_size ... ?
thanks

**Comment by vfdev-5** [comment]
Closing this one as a duplicate of https://github.com/pytorch/ignite/issues/3234. Let's keep discussions in another ticket
