### ISSUE TITLE
Initialization of WandBLogger with `init=True` fails

### ISSUE THREAD

**Issue by zubatyuk** [pytorch/ignite#3272]
`wandb.init` function does not have 'init' keyword argument.
Therefore, [this code](https://github.com/pytorch/ignite/blob/4c93282385353b585b4536c4553589af7dd58af0/ignite/handlers/wandb_logger.py#L136-L137) fails:
```
        if kwargs.get("init", True):
            wandb.init(*args, **kwargs)
```
Solution is to pop 'init' key from kwargs.

**Comment by vfdev-5** [comment]
@zubatyuk Thanks for reporting the issue and sending a PR. Seems like `init` arg never existed for [`wandb.init` function](https://github.com/wandb/wandb/blob/fdb04cc9c48e0f62500614caf48982b448eb7891/wandb/__init__.py#L459).

In pytorch-ignite code looks like it worked as no one previously tried to pass `init` as kwargs and by default it calls `wandb.init`. 
In your use case are you passing it explicitly and which value do you pass?

**Comment by zubatyuk** [comment]
There are two usage patterns.
1.
```
import wandb
from ignite.handlers import WandBLogger

wandb_logger = WandBLogger()
wandb.init(**wandb_kwargs)
wandb_log_dir = wandb.log.dir
```
2.
```
import wandb
from ignite.handlers import WandBLogger

wandb_logger = WandBLogger(init=True, **wandb_kwargs)
wandb_log_dir = wandb_logger.log.dir 
```
Apparently, everyone was using first pattern, even though proper `__getattr__` implemented in `WandBLogger`.
