### ISSUE TITLE
Update v0.1.1 to Pypi and Conda

### ISSUE THREAD

**Issue by fer-git** [pytorch/ignite#328]
Hi,

Could you please update ignite on Pypi / conda? I am excited to try the updated version. Thanks.

**Comment by vfdev-5** [comment]
@fer-git yes, I'm working on it :) This should be done soon

**Comment by vfdev-5** [comment]
@fer-git close it as the release is done:
- Conda: https://anaconda.org/pytorch/ignite
- PyPI: https://pypi.org/project/pytorch-ignite/
