### ISSUE TITLE
Replace `torch.cuda.amp.autocast` with `torch.amp.autocast('cuda',...)`

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#3304]
Fix the warning:
```
 FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
```
by replacing everywhere in the codebase:
```diff
- torch.cuda.amp.autocast(...
+ torch.amp.autocast("cuda", ...
```

**Comment by Gulin7** [comment]
Hi, @vfdev-5 , could you please assign me to this issue?

**Comment by vfdev-5** [comment]
@Gulin7 you can start working on it

**Comment by Gulin7** [comment]
@vfdev-5 I searched for the use of torch.cuda.amp.autocat(... and found nothing, except a reference in some mock tests.

**Comment by vfdev-5** [comment]
You should search for `autocast`, for example:
 https://github.com/pytorch/ignite/blob/master/ignite/engine/__init__.py#L188

**Comment by Gulin7** [comment]
@vfdev-5 I made a PR, I'm waiting for feedback.
