### ISSUE TITLE
Add flag to `Engine.terminate(skip_complete_event: bool = False)`

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#3308]
## 🚀 Feature

Add flag to `Engine.terminate(skip_complete_event: bool = False)` to optionally skip `Events.COMPLETE` when terminate was called.

Context:
- https://discuss.pytorch.org/t/average-time-per-epoch-calculation-on-pytorch-ignite/82506/10?u=vfdev-5

**Comment by bonassifabio** [comment]
Hi, I tried to implement this in the pull request #3309!

**Comment by vfdev-5** [comment]
This issue can be closed as completed by #3309 PR
