### ISSUE TITLE
TypeError: 'no_grad' object is not callable with pytorch version 0.4

### ISSUE THREAD

**Issue by sjzcv** [pytorch/ignite#345]
please help, error below occurred when I try to import ignite

> TypeError                                 Traceback (most recent call last)
> <ipython-input-1-1598b5d1429d> in <module>()
> ----> 1 import ignite
> 
> /opt/conda/lib/python3.6/site-packages/ignite/__init__.py in <module>()
>       1 import ignite.engine
>       2 import ignite.handlers
> ----> 3 import ignite.metrics
>       4 import ignite.exceptions
>       5 import ignite.contrib
> 
> /opt/conda/lib/python3.6/site-packages/ignite/metrics/__init__.py in <module>()
> ----> 1 from ignite.metrics.binary_accuracy import BinaryAccuracy
>       2 from ignite.metrics.categorical_accuracy import CategoricalAccuracy
>       3 from ignite.metrics.accuracy import Accuracy
>       4 from ignite.metrics.loss import Loss
>       5 from ignite.metrics.mean_absolute_error import MeanAbsoluteError
> 
> /opt/conda/lib/python3.6/site-packages/ignite/metrics/binary_accuracy.py in <module>()
>       2 import warnings
>       3 
> ----> 4 from ignite.metrics.accuracy import Accuracy
>       5 
>       6 
> 
> /opt/conda/lib/python3.6/site-packages/ignite/metrics/accuracy.py in <module>()
>       3 import torch
>       4 
> ----> 5 from ignite.metrics.metric import Metric
>       6 from ignite.exceptions import NotComputableError
>       7 
> 
> /opt/conda/lib/python3.6/site-packages/ignite/metrics/metric.py in <module>()
>       6 
>       7 
> ----> 8 class Metric(object):
>       9     """
>      10     Base class for all Metrics.
> 
> /opt/conda/lib/python3.6/site-packages/ignite/metrics/metric.py in Metric()
>      62         self.reset()
>      63 
> ---> 64     @torch.no_grad()
>      65     def iteration_completed(self, engine):
>      66         output = self._output_transform(engine.state.output)
> 
> TypeError: 'no_grad' object is not callable

**Comment by vfdev-5** [comment]
@sjzcv which version of pytorch you are using ?

**Comment by vfdev-5** [comment]
@sjzcv close this issue. Feel free to reopen if any you encounter other problems related to import ignite.

**Comment by anniezhi** [comment]
Hi. I'm using pytorch 0.5.0 and encounters the issue again. Would downgrading possibly solve the problem?

**Comment by vfdev-5** [comment]
@anniezhi please use more recent pytorch. Ignite>=0.4.0 supports only  pytorch>=1.3.0. Thanks !
