### ISSUE TITLE
Use collections.abc in ProgressBar instead of checking isinstance() against list or dict

### ISSUE THREAD

**Issue by willfrey** [pytorch/ignite#355]
Expecting a `list` or `dict` is overly restrictive when we really just need a sequence or mapping. I have a patch that checks against `collections.abc.Sequence` instead of `list` and `collections.abc.Mapping` instead of `dict`. This will work for both Python 3 and 2.7.

If you're cool with this change, I'll submit a PR for the patch.

Thanks.

**Comment by jasonkriss** [comment]
@willfrey 👍PR would be great!

**Comment by vfdev-5** [comment]
@willfrey @jasonkriss could you please explain me with an example why this is important to use sequence and mapping ?

**Comment by alykhantejani** [comment]
@willfrey do you have a use case where you would use a collection other than dict or list here?

I've left a comment in the PR, but the current implementation of using Sequence is too loose

**Comment by willfrey** [comment]
I found myself passing sequences such as `dict_keys` or tuples and got to thinking that the precondition requiring that `metric_names` be a `list` was too strong. I sought to make this a little more Pythonic by loosening the preconditions to only require the sequence or mapping protocols, but I see now that those protocols are too weak as preconditions.

An alternative approach would be to just do this:

```python
def attach(...):
    metric_names = list(metric_names)
    ...
```

which would just consume any iterator or cast any sequence to a list.

It's just a convenience/design thing, so feel free to swat me away. No offense will be taken!

**Comment by vfdev-5** [comment]
@willfrey maybe instead of calling `d.keys()` you can use `list(d)` or `list(d.keys())` as `d.keys()` is an iterator. As argument of `metric_names` we need something more "determinist" :)
But I agree that we need to change the check if list by check if list/tuple.

**Comment by willfrey** [comment]
That's exactly what I've been doing. I was just seeking to hide a little more of the information inside the implementation rather than having to always cast everything to a list.

Sounds like this isn't too popular or isn't the right time to make this sort of change, so feel free to close this. Otherwise I'm open to more discussion!

**Comment by vfdev-5** [comment]
@willfrey personnally I'm not against such change if it makes code more simple and it covers some cases. 

**PS:**
```
# python 3.7
from collections.abc import Sequence
d = {'a': 0, 'b': 1}
isinstance(d.keys(), Sequence)
> False
```

**Comment by willfrey** [comment]
My mistake! Objects of type `dict_keys` should be an `Iterable`.

```python
>>> from collections.abc import Iterable
>>> d = {'a': 0, 'b': 1}
>>> isinstance(d.keys(), Iterable)
True
```
I think for `metric_names` we want `Iterable[str]` but we have the problem of the fact that just ` str` would be valid for this. Do we want to have some convention for accepting strings? The convention used for `collections.namedtuple` and `enum.Enum` is to accept strings that are whitespace/comma-delimited. I think `pytest` also accepts this convention for their fixtures.

I'm not a fan of using strings for everything but this at least is consistent with the behavior of some of the Python standard library and at least one popular testing framework.

But like I said, I feel like I'm bikeshedding and creating a whole lot of extra work over one call to `list()`!
