### ISSUE TITLE
Add some notebooks in examples

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#367]
> Putting tutorials like the basic mnist into Jupyter notebooks would be helpful for new users to get started quicker

**Comment by vfdev-5** [comment]
@anmolsjoshi I think the idea is to provide some basics of ignite in notebook such that user understands how to play with. If your implementation is not too heavy with translation part vs ignite part this can be interesting.

**Comment by NeelMishra** [comment]
Hey, I would love to work on this issue. I can make some jupyter notebook examples.

**Comment by vfdev-5** [comment]
@NeelMishra yes please go ahead and send a PR. I think everybody can contribute on this issue.

Something like [this](https://www.kaggle.com/vfdev5/pytorch-and-ignite-on-fruits-360) can be a good start.

**Comment by NeelMishra** [comment]
So sorry for the delay, I will start working on it right on.

**Comment by anmolsjoshi** [comment]
@vfdev-5 this might be a dumb question. do we need smoke tests for jupyter notebooks?

**Comment by vfdev-5** [comment]
@anmolsjoshi I think no. If we would like to do this more neat we could insert the notebooks into the doc as it is done for pytorch tutorials: https://github.com/pytorch/tutorials 
but it is necessary.

**Comment by vfdev-5** [comment]
@anmolsjoshi @NeelMishra any advances on this ?

**Comment by anmolsjoshi** [comment]
@vfdev-5 just finished two notebooks, working on one more, will push tonight.

**Comment by vfdev-5** [comment]
@anmolsjoshi maybe we could split this into several PRs to simplify the review ?

**Comment by anmolsjoshi** [comment]
@vfdev-5 yes that was the plan, i'll send in a PR shortly.

**Comment by NeelMishra** [comment]
Hi, I have a similar approach, but it will be slower due to final exams next week. I am working on that fashion MNIST in ignite, and simpler stuffs like basic NN. I want to follow the trickle approach for pull request's, and I don't want to delay the development. So if urgent, please feel free to assign someone else as I will submit a PR after next week. 

Also, I will be referring the above notebook created by Anmol for creation of notebooks.

**Comment by anmolsjoshi** [comment]
@NeelMishra any updates on Fashion MNIST example?

**Comment by chitralverma** [comment]
@anmolsjoshi @NeelMishra 
I was doing my own learning using the FashionMNIST dataset and have a notebook mostly ready for the same.

If it's ok, maybe I can adopt the notebook template used for other examples and raise a PR for this?

**Comment by vfdev-5** [comment]
@chitralverma you van take a look at thé current notebooks: https://github.com/pytorch/ignite/tree/master/examples/notebooks. Actually no template or style to follow, juste it should explain everything for beginners. And yes, please send a PR for this.

**Comment by vfdev-5** [comment]
@chitralverma you can take a look at the current notebooks: https://github.com/pytorch/ignite/tree/master/examples/notebooks. Actually no template or style to follow, juste it should explain everything for beginners. And yes, please send a PR for this.

**Comment by anmolsjoshi** [comment]
@chitralverma any updates on the FashionMNIST notebook?

**Comment by ANUBHAVNATANI** [comment]
@anmolsjoshi  I am interested in working on FashionMNIST notebook or other such basic neural network notebooks. I want to contribute to open source. I think this would be a good start. Please suggest any other good first issues if this is not available.

**Comment by anmolsjoshi** [comment]
@ANUBHAVNATANI please go ahead and work on FashionMNIST, and send in a PR. Let us know if you have any questions

**Comment by ANUBHAVNATANI** [comment]
Thanks for the response, I have started working on the project.

**Comment by ANUBHAVNATANI** [comment]
@anmolsjoshi  I had completed the notebook can I directly make a pull request to master or I have to do something else.

**Comment by vfdev-5** [comment]
@ANUBHAVNATANI yes you can create a PR to master and we'll review it. Thanks

**Comment by ANUBHAVNATANI** [comment]
@vfdev-5 @anmolsjoshi  I had made the pull request #549 for the Fashion MNIST dataset.

**Comment by vfdev-5** [comment]
I'll close this issue as we have already 5 tutorial notebooks with Ignite usage. I think it is OK for this issue.
