### ISSUE TITLE
Adding Dice Coefficient Metric for Image Segmentation

### ISSUE THREAD

**Issue by anmolsjoshi** [pytorch/ignite#368]
I wanted to implement Dice Coefficient as a metric for image segmentation problems. any interest?

**Comment by vfdev-5** [comment]
@anmolsjoshi yes, please send a PR

**Comment by anmolsjoshi** [comment]
@vfdev-5 thanks. i'll add it to ignite.contrib.metrics

**Comment by anmolsjoshi** [comment]
@vfdev-5 were you thinking a binary or categorical implementation for this?

I've mainly seen binary implementations only, but a few blog posts mention categorical.

**Comment by vfdev-5** [comment]
@anmolsjoshi maybe it would be more interesting to implement [Tversky index](https://en.wikipedia.org/wiki/Tversky_index) - generalization of Dice and Jaccard.
Categorial index makes sens too, we can tryout to implement both :)

**Comment by anmolsjoshi** [comment]
@vfdev-5 working on this now, found an implementation here - https://github.com/kevinzakka/pytorch-goodies/blob/master/losses.py#L131-L175

Idea is that we create a general Tversky Index Metric, and then create children Metrics such as Jaccard Index and Dice Coefficient by forcing values of alpha and beta.

**Comment by pldelisle** [comment]
Tversky loss is indeed more interesting and offer more flexibility afterwards with fixed alpha and beta values. 
Does using the Confusion Matrix object is the best way to implement this or inheriting from _BaseClassification is better ?

**Comment by vfdev-5** [comment]
@anmolsjoshi sorry, I haven't notice your link on kevinzakka's repo. His implementation seems like to be image-wise and can not be used in our `update-compute` paradigm.

@pldelisle we think to implement it using a confusion matrix and provide it as `IoU` or `mIoU` methods... @anmolsjoshi should be working on it...

**Comment by pldelisle** [comment]
I have also been working a bit on this (needed to implement Dice coefficient for my own project, then stumbled on this library which proposes a pretty good structure, so I decided to contribute). I've done it for the Dice Coefficient, but I struggle a bit for the Tversky Index and the relative complement.

As I can understand, the relative complement is the position N_xy in the diagonal where x=y minus everything else, for each position in the diagonal.

I just don't know how to implement this.

**Comment by PyExtreme** [comment]
Hi @vfdev-5 , I am looking to contribute to ignite.
Could you please help me by detailing out this issue please? I have gone through the conversation but couldn't understand it exactly. Would be of great help to me.

Thank you

**Comment by vfdev-5** [comment]
Hi @PyExtreme thanks for the proposition.
Idea here is to provide precoded Dice Coefficient metric. It is more simple to start from [Confusion Matrix](https://github.com/pytorch/ignite/blob/master/ignite/metrics/confusion_matrix.py) and implement Dice Coefficient as it is done for [IoU](https://github.com/pytorch/ignite/blob/master/ignite/metrics/confusion_matrix.py#L118).
Please, take a look at our [contributing rules](https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md) and feel free to ask if you have a question.

**Comment by pldelisle** [comment]
@PyExtreme See https://github.com/banctilrobitaille/kerosene/blob/3c27cdfefcb3624e0a0de9590108d40c36a1810e/kerosene/metrics/metrics.py#L76 for my implementation.

**Comment by vfdev-5** [comment]
@pldelisle thanks for the link, looks good !

Btw, I wonder what is the purpose of this kerosene more higher level API framework ?
Would not be better to enhance contrib module with such higher level abstractions ?

**Comment by pldelisle** [comment]
The goal of Kerosene was to support the multi-GPU and mixed precision features of Pytorch Lightning while keeping the flexibility of ignite (No strict interface for user defined models). The template method in the trainer let the user only focus on the model and makes it very simple to train new model architecture with multi-gpu, mixed-precision and automatic Visdom logging (only a model and a config file is required). We use the library at our research lab, and it's still under development.
