### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#369]
I think we need to update our README.rst for 0.2.0 release in order to better present `contrib` module (e.g. `contrib.metrics.regression` module)

**Comment by anmolsjoshi** [comment]
@vfdev-5 the picture in README should be updated. Currently shows BinaryAccuracy.

**Comment by vfdev-5** [comment]
There is also a typo with event name `Events.ITERATION_COMPLETE` :)
To generate the image we can use follow the info from [here](https://github.com/pytorch/ignite/wiki/Maintainer-Notes#side-by-side-code-compare)

**Comment by anmolsjoshi** [comment]
I can work on that later today. What exactly did you want added for the regression module?

**Comment by vfdev-5** [comment]
Idea is to make README more friendly to start with and understand the package.
Some propositions:
- Add a section between Documentation and Examples and tell more about global structure:
  - core package `ignite`
  - contrib package with more features
     - regression module with more than ten various metrics

- Remove "How does this compare to Torchnet?" or put somewhere in wiki.

cc @alykhantejani
