### ISSUE TITLE
Improve Quickstart

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#371]
We need to improve official [Quickstart](https://pytorch.org/ignite/quickstart.html) documentation:

- Empty link on ignite modules that are empty, for example: 
  - create_supervised_trainer()
  - create_supervised_evaluator()
  - Engine
  - add_event_handler()
  - on()
- Typos

**Comment by furkan-kucuk** [comment]
I would be glad to help as soon as I gain some more insight about the library.
