### ISSUE TITLE
Issue with traced models

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#373]
If user passes a traced model into `create_supervised*` methods and specifies a device, there will be the following error:
```python
traced_model = torch.jit.trace(model, z)

evaluator = create_supervised_evaluator(traced_model, metrics, device='cuda')
> RuntimeError: to is not supported on TracedModules
```

We need to check if model have the method `.to`...

**Comment by vfdev-5** [comment]
Probably, we should wait until [this PR](https://github.com/pytorch/pytorch/issues/6008) is done.

**Comment by TheCodez** [comment]
> the test should pass for pytorch-nightly build (can be check with torch.__version__)

Do you mean only executing the test if on the nightly, or check if it throws a `RuntimeError` if not on the nightly?

**Comment by vfdev-5** [comment]
@TheCodez yes something like this.

**Comment by TheCodez** [comment]
@vfdev-5 which `torch.__version__` to check for nightly?

**Comment by vfdev-5** [comment]
@TheCodez you can do it like this:
```python
# Check if torch-nightly
if "dev" in torch.__version__:
     ...
else:
    ...
```
