### ISSUE TITLE
Make ignite utils public

### ISSUE THREAD

**Issue by TheCodez** [pytorch/ignite#389]
When using a dataset which returns a tuple of more than 2 values, you have to implement your own `_prepare_batch` function. Let's say we're using this function:

```python
def _prepare_batch(batch, dev=None, non_blocking=False):
    x, instance, boxes = batch

    return (convert_tensor(x, device=dev, non_blocking=non_blocking),
            convert_tensor(instance, device=dev, non_blocking=non_blocking),
            convert_tensor(boxes, device=dev, non_blocking=non_blocking))
```

As in the original `_prepare_batch` function used in `create_supervised_trainer` we're using the `convert_tensor` function. This function is located in `_utils.py` resulting in a protected member access warning. This file has some useful and commonly used methods, so it would be nice if it was public instead.

**Comment by vfdev-5** [comment]
@TheCodez I agree. We need to think how to play with backward compatibility at least for other minor releases (if we do any) and just rename `_utils.py` by `utils.py` since `0.2.0`

@alykhantejani @jasonkriss what do you think ?

**Comment by amitibo** [comment]
I suggest making `_prepare_batch` more general like:
```
def _prepare_batch(batch, device=None):
    return [convert_tensor(x, device=device) for x in batch]
```

**Comment by anmolsjoshi** [comment]
@vfdev-5 any reason #396 was closed?

**Comment by vfdev-5** [comment]
@anmolsjoshi thanks! my bad, I deleted fork's branch and that closed the PR. I thought we've merged it.
