### ISSUE TITLE
Improve State documentation

### ISSUE THREAD

**Issue by EtienneDesticourt** [pytorch/ignite#393]
Hi,

I think the documentation of states and the way they're used by engines is not detailed enough.
Currently the only way to know what attributes are available in the default State object, used by the engines generated by convenience methods such as `create_supervised_trainer`, is to look at the source code.  
Some of them are mentioned in the [Concept](https://pytorch.org/ignite/concepts.html#state) part of the documentation but there is still a lot of room for confusion about the way they work and some are missing.
For example, no information about the `batch` attribute which without documentation some might assume to correspond to the batch index (kinda like `epoch` for the epoch index) which is actually `iteration`. Same thing for `epoch` which is used implicitly in examples but no mention of it in the default `State` documentation, and you might think it's obvious but then someone will try to create a default `State` and assume `epoch` is a built-in attribute set to 0 at instantiation when in fact you'll have to search through the source code to figure out that it's not a default attribute and is only created by the default `Engine` through a kwarg passed to the `State` class.

Additionally this kind of explicit documentation of the state should be done every time a custom `State` is created otherwise the user is left to guess what attributes are available in it, what they mean and what format they're in. For example, is `output` the return from the forward pass of your model? The loss?
You'll have to look at `Engine` then find out it's the output of the process_function argument. Then figure out that in the case of the  `create_supervised_trainer` that function is `_update` which returns `loss.item()` and in the case of `create_supervised_evaluator` returns `(y_pred, y)`.

Thank you, and sorry for the verbosity but without it I was afraid this would be rejected as trivial.

**Comment by vfdev-5** [comment]
@EtienneDesticourt thanks for a great feedback. I agree that the docs on `State` may seem unclear.
If you would like to improve it, please, send a PR. We are really appreciate community contributions !

> You'll have to look at Engine then find out it's the output of the process_function argument. Then figure out that in the case of the create_supervised_trainer that function is _update which returns loss.item() and in the case of create_supervised_evaluator returns (y_pred, y).

Generally, `process_function` is defined by user when it is inserted to `Engine`. Probably, it is unclear that `engine.state.output` will contain the output of `process_function`, see [Concepts](https://pytorch.org/ignite/concepts.html#state). 
And I agree that the docstring of these `create_supervised*` should be improved to clearly indicate what is stored in `engine.state.output`.
