### ISSUE TITLE
Probably a typo in the documentation?

### ISSUE THREAD

**Issue by devforfu** [pytorch/ignite#402]
There is the following fragment in the [docs on `EarlyStopping` handler](https://pytorch.org/ignite/handlers.html#ignite.handlers.EarlyStopping):
```python
from ignite.engine import Engine, Events
from ignite.handlers import EarlyStopping

def score_function(engine):
    val_loss = engine.state.metrics['nll']
    return -val_loss

handler = EarlyStopping(patience=10, score_function=score_function, trainer=trainer)
# Note: the handler is attached to an *Evaluator* (runs one epoch on validation dataset).
evaluator.add_event_handler(Events.COMPLETED, handler)
```
I am not sure why do we attach this handler to the `COMPLETED` event. This event is fired at the end training process, right? So I would expect to perform `EarlyStopping` checks at the end of an _epoch_, not the whole training process. Could it be a typo in the docs?

**Comment by vfdev-5** [comment]
@devforfu no this is not a typo. Actually, similar question was already asked several times previously and we modified the documentation with thr note:
```
# Note: the handler is attached to an *Evaluator* (runs one epoch on validation dataset).
```
Please, read more attentively the example.
Early stopping handler consumes a trainer, but attached to an evaluator.

**Comment by devforfu** [comment]
Oh, ok, makes sense
