### ISSUE TITLE
Remove `activation` argument from AveragePrecision and ROC_AUC

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#404]
I propose to remove `activation` argument from `AveragePrecision` and `ROC_AUC`:
https://github.com/pytorch/ignite/blob/862ab0073e461a32bf5b53fa015f88c143ae9079/ignite/contrib/metrics/roc_auc.py#L23-L28
to be coherent with `Accuracy` et friends and the usage of `output_transform` to apply the binarization/activation :
https://github.com/pytorch/ignite/blob/862ab0073e461a32bf5b53fa015f88c143ae9079/ignite/metrics/accuracy.py#L81-L93

**Comment by anmolsjoshi** [comment]
@vfdev-5 I agree, this would better aligned with the other metrics. Is it ok if I work on this issue?

**Comment by vfdev-5** [comment]
@anmolsjoshi yes go ahead, it is not yet assigned.
