### ISSUE TITLE
ModelCheckpoint parameter `save_as_state_dict` should default to True

### ISSUE THREAD

**Issue by fabianschilling** [pytorch/ignite#406]
Given that the recommended way to save model checkpoints is to only serialize the `state_dict` rather than the whole object (see https://pytorch.org/docs/stable/notes/serialization.html), shouldn't `save_as_state_dict` in `ModelCheckpoint` default to `True`?

Maybe I'm nitpicking but I think this would be a better default.

Here's the line: https://github.com/pytorch/ignite/blob/862ab0073e461a32bf5b53fa015f88c143ae9079/ignite/handlers/checkpoint.py#L84

**Comment by vfdev-5** [comment]
@fabianschilling I agree, thanks for the feedback. We kept it equal False because of backward compatibility to the previous versions. I think since 0.2.0 we can set it to be True by default.
If you would like send a PR with a change, please do no hesitate.
