### ISSUE TITLE
Fix CI : bug with python 2.7 opengym

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#424]
Currently, CI is [broken](https://travis-ci.org/pytorch/ignite/builds/490068197), smoke tests of RL examples fail using opengym. Need to investigate.

**Comment by anmolsjoshi** [comment]
@vfdev-5 looked into this, this is an issue with the super call in discrete.py 

This was recently fixed on the master branch using [this PR](https://github.com/openai/gym/pull/1312). I built gym from the master branch and the tests in travis.yml passed. 

One option is to wait till a new release is cut, or we can just build from master. Thoughts?

**Comment by vfdev-5** [comment]
Thanks @anmolsjoshi, maybe we can set now the version of opengym to the previous stable one and once the bug is fixed, remove the version fix.
