### ISSUE TITLE
Wrong event used in doc example of "ignite.contrib.handlers.LRScheduler"

### ISSUE THREAD

**Issue by Bibonaut** [pytorch/ignite#425]
At first, thanks for this nice project! 

While reading the documentation, I encountered, that in the  little example on how to use `ignite.contrib.handlers.LRScheduler` the `ITERATION_COMPLETED` event is used instead of the `ITERATION_STARTED` event.  From pytorch documentation, the event should be triggered, when the iteration started.

Example from pytorch documentation ([doc link](https://pytorch.org/docs/stable/optim.html#torch.optim.lr_scheduler.StepLR)):

```python
>>> # Assuming optimizer uses lr = 0.05 for all groups
>>> # lr = 0.05     if epoch < 30
>>> # lr = 0.005    if 30 <= epoch < 60
>>> # lr = 0.0005   if 60 <= epoch < 90
>>> # ...
>>> scheduler = StepLR(optimizer, step_size=30, gamma=0.1)
>>> for epoch in range(100):
>>>     scheduler.step()  # is called at iteration start
>>>     train(...)
>>>     validate(...)
```

Example from `ignite.contrib` documentation ([doc link](https://pytorch.org/ignite/contrib/handlers.html#ignite.contrib.handlers.LRScheduler)):
```python
from ignite.contrib.handlers.param_scheduler import LRScheduler
from torch.optim.lr_scheduler import StepLR

step_scheduler = StepLR(optimizer, step_size=3, gamma=0.1)
scheduler = LRScheduler(step_scheduler)
trainer.add_event_handler(Events.ITERATION_COMPLETED, scheduler)  # Should this be Events.ITERATION_STARTED?
```

Minimum pytorch example to show behaviour of pytorch schedulers:
```python
import torch
optimizer = torch.optim.Adam([torch.Tensor([1,2,3])], lr=0.001) # initial learning rate is 0.001
lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer ,30)

lr_scheduler.get_lr() # outputs 0.01 instead of 0.001

lr_scheduler.step()
lr_scheduler.get_lr() # outputs 0.001 after first call of step()
```

**Comment by vfdev-5** [comment]
@Bibonaut yes, you are correct about that, thanks for catching !
If you would like to send a PR, we'll highly appreciate community contributions. 

PS. glad that you like the project !
