### ISSUE TITLE
Make info logs optional

### ISSUE THREAD

**Issue by zippeurfou** [pytorch/ignite#433]
Hi,
It would be nice to be able to remove the info logs (ie. https://github.com/pytorch/ignite/blob/master/ignite/engine/engine.py#L308)
I find it especially cluttering my logs when I run metrics on my epoch.
ie.
<img width="928" alt="image 2019-02-14 at 12 31 08 am" src="https://user-images.githubusercontent.com/4520383/52764917-f3791a00-2fef-11e9-8b9c-54a3e4d8415b.png">
I am not saying I don't appreciate having some timer but it could be integrated as a state rather than a log.
PS:
I believe I can just set it with something like:
```
import logging
logging.getLogger("ignite").setLevel(logging.WARNING)
```
However, it might just be better to not show it by default?

**Comment by vfdev-5** [comment]
@zippeurfou thanks for the feedback, I see what you mean. 
I see that you have messages from [`ignite.engine` logger](https://github.com/pytorch/ignite/blob/master/ignite/engine/engine.py#L62) and a custom messenger/logger ("Training Results - ...").
If you are not interested of engines messenges, you can disable it. And I think it is disabled by default.
Did you activated it explicitly ?

**Comment by zippeurfou** [comment]
Thanks @vfdev-5 for the reply.
This might just be me then.
I did this:
```
import logging
for key in logging.Logger.manager.loggerDict:
    logging.getLogger(key).setLevel(logging.CRITICAL)


logger = logging.getLogger(__name__)
handler = logging.StreamHandler()
formatter = logging.Formatter("%(asctime)s %(name)-12s %(levelname)-8s %(message)s")
handler.setFormatter(formatter)
logger.addHandler(handler)
logger.setLevel(logging.INFO)
```
However, maybe this is wrong.

**Comment by vfdev-5** [comment]
@zippeurfou Ok, I tried to insert this code to `mnist.py` example to see the logs you have, but did not manage to reproduce your output. Anyway, I think if you can disable manually like that `logging.getLogger("ignite.engine.engine.Engine").setLevel(logging.WARNING)` or manually remove all added handlers. By default, we do not add any stream handler to it. 
HTH

**Comment by zippeurfou** [comment]
Closing it since it seems it's not an ignite issue 👍
