### ISSUE TITLE
Ignite vs Tnt vs Torchbearer

### ISSUE THREAD

**Issue by dyngts** [pytorch/ignite#434]
Hi all,

Currently, i'm looking for high level library that can help me to simplify my Pytorch's training code. After some searches, i found these libraries are promising to try: Ignite, TNT, and Torchbearer.

After skimming the contents, i found Ignite and TNT are closely similar each other in terms of usage and the design (based on driven API design) while torchbearer offer different design (such callback etc).

Wondering if anyone have insights about those libraries? The better question would be when to use and not to use Ignite vs TNT vs Torchbearer? Any pros and cons?

Thanks!

**Comment by vfdev-5** [comment]
@dyngts I think the best answer you can get is by testing all these libs by yourself :)

For example, you can checkout [our examples](https://github.com/pytorch/ignite/tree/master/examples), take one and play with it.
Some other points to take into account:
- development activity
- community support on the issues
- github stars :)

PS: IMO such question should be asked at the [pytorch forum](https://discuss.pytorch.org/).
PPS: I saw you've already seen polyaxon. [Here](https://github.com/vfdev-5/cifar10-faster) is another example to play with polyaxon and ignite.

**Comment by dyngts** [comment]
@vfdev-5 I wish someone already did this, hence i don't need go through all the libraries by myself 😛 

I just know that you're the creator of ignite, good to know that.

>PS: IMO such question should be asked at the [pytorch forum](https://discuss.pytorch.org/).

great idea, i'll do that. Thanks!

**Comment by vfdev-5** [comment]
>  I wish someone already did this, hence i don't need go through all the libraries by myself

@dyngts that way you'll get your own experience. All libs mostly do a similar stuff, that it is a matter of taste and community behind the project. Very soon we'll merge some notebook for playing in a more interactive way with ignite, so stay tuned :)

> I just know that you're the creator of ignite, good to know that.

The creator of ignite is @alykhantejani, I'm just a frequent contributor :)

And if you have other concrete questions on the usage or you find unclear our documentation, please do not hesitate to open an issue.

**Comment by williamFalcon** [comment]
@dyngts Check out PyTorch Lightning as well. Comes with a lot of advanced fewtures out of the box while still keeping the research code in pure PyTorch. 

Here’s a useful comparison between the three frameworks (didn’t see torchbearer when the article was written).  

https://towardsdatascience.com/pytorch-lightning-vs-pytorch-ignite-vs-fast-ai-61dc7480ad8a
