### ISSUE TITLE
Doc issue

### ISSUE THREAD

**Issue by drozzy** [pytorch/ignite#439]
Reading the docs here, [the explanation part](https://pytorch.org/ignite/quickstart.html#explanation), I don't understand this sentence:

> update_function: a function which is passed the engine and a batch and it passes data through and updates your model

**Comment by vfdev-5** [comment]
@drozzy thanks for the feedback! 
I agree that this phrase may be unclear. It says that `update_function` being the only requirement to construct an `Engine` has a signature such that an `engine` and `batch` are passed into the function:
```
def update_function(engine, batch):
    # ...
```
and the role of the function is that it receives the input data (i.e. `batch`) and helps to update model's parameters.
Hope this is more clear now :)

And if you have a constructive suggestion on how to improve this part of the docs, we will be happy to accept your PR !
