### ISSUE TITLE
Look inside the "create_supervised_trainer"

### ISSUE THREAD

**Issue by drozzy** [pytorch/ignite#440]
The [explanation](https://pytorch.org/ignite/quickstart.html#explanation) says that if we look inside the "create_supervised_trainer/create_supervised_evaluator" we can observe some pattern... however, we never actually look inside these functions, instead we look inside "create_engine". Is create_engine defined inside create_supervised_trainer?

> However, we could also define trainer and evaluator using Engine. If we look into the code of create_supervised_trainer() and create_supervised_evaluator(), we can observe a pattern:
> 
> def create_engine(*args, **kwargs):
> 
>     def _update(engine, batch):
>         # Update function logic
>         pass
> 
>     return Engine(_update)
>

**Comment by vfdev-5** [comment]
By "we look inside the "create_supervised_trainer/create_supervised_evaluator"" it means if we are curious to see the code-source of the function. Okay, maybe we can replace `look inside` by `look inside their implementations`.

`create_engine` is the pattern that we could observe.
