### ISSUE TITLE
Remove handler feature in Engine

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#451]
I recently encountered the cases where I would like to remove a handler and optionally replace it with another one. The following code is used:
```python
def remove_handler(engine, handler, event_name):
    assert event_name in engine._event_handlers    
    engine._event_handlers[event_name] = [(h, args, kwargs) 
                                          for h, args, kwargs in engine._event_handlers[event_name] 
                                            if h != handler]
```

@alykhantejani @jasonkriss what do you guys think about inserting such method into `Engine` ?
cc @anmolsjoshi

**Comment by jasonkriss** [comment]
@vfdev-5 Do you mind giving an example use case for this?

**Comment by vfdev-5** [comment]
Sure, maybe these examples I have may look a bit particular:
1) engine that logs to the tensorboard on different datasets at different groups:
```python
    tb_logger = TensorboardLogger(log_dir=log_dir)

    tb_handler = tb_output_handler(tag="training", output_transform=lambda x: x)
    tb_logger.attach(stats_collector,
                     log_handler=tb_handler,
                     event_name=Events.ITERATION_COMPLETED)

    stats_collector.run(config.train_loader, max_epochs=1)

    remove_handler(stats_collector, tb_handler, Events.ITERATION_COMPLETED)
    tb_logger.attach(stats_collector,
                     log_handler=tb_output_handler(tag="validation", output_transform=lambda x: x),
                     event_name=Events.ITERATION_COMPLETED)

    stats_collector.run(config.val_loader, max_epochs=1)
```
2) A handler that when attached to the engine adds some internal handlers and when finished cleans out after itself.

**Comment by jasonkriss** [comment]
Thanks @vfdev-5. I'm still trying to understand the motivation...

1. Would it maybe more clear here to use two stats_collectors rather than having to remember to remove the handler?

2. Is there a benefit to cleaning up after it finishes?

**Comment by vfdev-5** [comment]
> Would it maybe more clear here to use two stats_collectors rather than having to remember to remove the handler?

@jasonkriss it means that we need to copy previous code to reinit another `stats_collectors` ... 

> Is there a benefit to cleaning up after it finishes?

More on the context: I wrote a basic time profiler that collect times spent in handlers, batch preparation and process function. To do this the profiler adds manually its handlers in the special order: the first and the last handlers on the events. It adds its handler **once** the `run` is called to avoid the situation when user adds other handlers after `profiler.attach(trainer)` is called.
So, once `trainer.run(train_loader)` is done, profiler computed what it needs and should remove its added handlers. Otherwise, on the second call of  `trainer.run(train_loader)` there will be twice more attached handlers and times collection will be difficult or even faulty.

**Comment by jasonkriss** [comment]
Got it! Thanks for the added context. Helps a lot. Let's go ahead and add it then.
