### ISSUE TITLE
Example with albumentations and dynamic augmentations

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#457]
Idea is to provide an example with data augmentations using [albumentations](https://github.com/albu/albumentations.git) and show a possibility to make data augmentation parameters change on epoch.

**Comment by anmolsjoshi** [comment]
@vfdev-5 apart from changing image sizes during training, what other transformations did you think of changing on epochs?

**Comment by vfdev-5** [comment]
Maybe also check a schema like: less augmentation in the first epochs and more hard augmentations to prevent the overfitting from some epoch...

**Comment by lintangsutawika** [comment]
Hi, @vfdev-5 is this something open to contribute to?

**Comment by vfdev-5** [comment]
@lintangsutawika yes, idea is to provide some cool example Ignite + Albumentations usage. It is rather open and some ideas are described above. So, if you would like to contribute let's discuss a bit of what kind of example you would like to provide and as always PR are welcome :)

**Comment by vfdev-5** [comment]
Close this FR as stale
