### ISSUE TITLE
Add section about metrics to the README

### ISSUE THREAD

**Issue by alykhantejani** [pytorch/ignite#46]

**Comment by vishwakftw** [comment]
What is expected here? Like, is there supposed to description about the functions in `metrics.py`?

**Comment by alykhantejani** [comment]
Sorry for the non-descriptive issue. 

This issue is to add some details to the README about what the metrics are and how to use them. For example [here](https://github.com/pytorch/ignite/issues/37#issuecomment-354101896) is where the ideas stemmed from,  it would be good to have something in the README like that.

(Still not sure what the best way to document this stuff is, but the README will suffice for now I guess).

**Comment by vishwakftw** [comment]
Oh okay. I can probably take it up.

**Comment by alykhantejani** [comment]
@vishwakftw that'd be great. Thanks!
