### ISSUE TITLE
ReduceLROnPlateau LRScheduler error

### ISSUE THREAD

**Issue by sudarshan85** [pytorch/ignite#462]
Hi,

I tried to use the `LRScheduler` handler for `ReduceLROnPlateau` from `torch.optim` and it threw an a `TypeError`:

```
plateau_scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer=optimizer, mode='min', factor=0.5, patience=1)
ignite_plateau_scheduler = LRScheduler(plateau_scheduler)
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-56cb18e5af57> in <module>
      1 plateau_scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer=optimizer, mode='min', factor=0.5, patience=1)
----> 2 ignite_plateau_scheduler = LRScheduler(plateau_scheduler)

/net/vaosl01/opt/NFS/su0/anaconda3/envs/nlpbook/lib/python3.7/site-packages/pytorch_ignite-0.2.0-py3.7.egg/ignite/contrib/handlers/param_scheduler.py in __init__(self, lr_scheduler, save_history, **kwds)
    424         if not isinstance(lr_scheduler, _LRScheduler):
    425             raise TypeError("Argument lr_scheduler should be a subclass of torch.optim.lr_scheduler._LRScheduler, "
--> 426                             "but given {}".format(type(lr_scheduler)))
    427 
    428         if len(lr_scheduler.optimizer.param_groups) > 1:

TypeError: Argument lr_scheduler should be a subclass of torch.optim.lr_scheduler._LRScheduler, but given <class 'torch.optim.lr_scheduler.ReduceLROnPlateau'>
```
The example from the documentation with `StepLR` works without problems. It seems that the objects belong to different base classes. This is indeed true as can be from the source [here](https://pytorch.org/docs/stable/_modules/torch/optim/lr_scheduler.html). `StepLR` inherits from `_LRScheduler`, while `ReduceLROnPlateau` does not have a base class (inherits from `object`). Is there a way to bypass that check for this scheduler?

Thanks.

**Comment by vfdev-5** [comment]
@sudarshan85 thanks for the feedback ! Yes, you are correct about `ReduceLROnPlateau` that is not derived from `_LRScheduler`:
```python
class ReduceLROnPlateau(object):`
```

However, it is possible to use `ReduceLROnPlateau` as it suggested by `pytorch` and just call `step` method in a handler:
```python
optimizer = torch.optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
scheduler = ReduceLROnPlateau(optimizer, 'min')

@evaluator.on(Event.COMPLETED)
def reduct_step(engine):
    # engine is evaluator
    # engine.metrics is a dict with metrics, e.g. {"loss": val_loss_value, "acc": val_acc_value}
    scheduler.step(engine.metrics['loss'])
```

However, mixing a normal pytorch scheduler (e.g. `StepLR`) and `ReduceLROnPlateau` should be checked explicitly whether one does not overwrite another. 

HTH

**Comment by sudarshan85** [comment]
@vfdev-5 Thank you for your prompt reply! Yes, I thought that I could something like that. But shouldn't the event be `EPOCH_COMPLETED`? `COMPLETED` refers to the entire training process completed right?

This might be a bit off-topic, but I'm confused about using the `evaluator.on` decorator vs using `trainer.on` decorator and using the evaluator inside the that function as is shown in the quickstart example here:

```
@trainer.on(Events.EPOCH_COMPLETED)
def log_training_results(trainer):
    evaluator.run(train_loader)
    metrics = evaluator.state.metrics
    print("Training Results - Epoch: {}  Avg accuracy: {:.2f} Avg loss: {:.2f}"
          .format(trainer.state.epoch, metrics['accuracy'], metrics['nll']))
```

**Comment by vfdev-5** [comment]
@sudarshan85 as the handler is attached to the evaluator which goes through validation dataset only once it is correct to set `Events.COMPLETED`.

To answer your off-topic question, it would be better represent the training loop and the events happening during its run. 
![ignite_training_loop](https://user-images.githubusercontent.com/2459423/54835949-7eba8f00-4cc3-11e9-82cf-be352dcb9a4c.png)


The decorator just means at which event the engine should execute decorated function:
```
# trainer should execute `in_training_loop_on_epoch_completed` every time when epoch ends
# to compute validation metrics
@trainer.on(Events.EPOCH_COMPLETED)
def in_training_loop_on_epoch_completed(engine):
    evaluator.run(val_loader) # this starts another loop on validation dataset to compute metrics

# evaluator should execute `when_validation_loop_is_done` when run 
# over validation dataset is over.
@evaluator.on(Events.COMPLETED)
def when_validation_loop_is_done(engine):
    # do something with computed metrics etc
    # -> early stopping or reduce LR
    # or just log them 
```

**Comment by sudarshan85** [comment]
Thanks. The picture does add more clarity on whats going on. The example in the documentation about early stopping shows a non-decorator version, where the score function is declared and passed onto the handler. How would we write the decorator version of it?

**Comment by vfdev-5** [comment]
Decorators are useful with user defined functions. In case of EarlyStoping
handler, as it is a callable class it is more simple to add it as described
in the docs

**Comment by sudarshan85** [comment]
Ok thanks. I just started using ignite today. Thats why I'm having some basic questions. Thanks for your help.

**Comment by ismael-elatifi** [comment]
I wrote a wrapper of **torch.optim.lr_scheduler.ReduceLROnPlateau** so I put it here as it might be useful for others :
```python
from torch.optim.lr_scheduler import ReduceLROnPlateau


class ReduceLROnPlateauScheduler:
    """Wrapper of torch.optim.lr_scheduler.ReduceLROnPlateau"""

    def __init__(
            self,
            optimizer,
            metric_name,
            mode='min', factor=0.1, patience=10,
            threshold=1e-4, threshold_mode='rel', cooldown=0,
            min_lr=0, eps=1e-8, verbose=False,
    ):
        self.metric_name = metric_name
        self.scheduler = ReduceLROnPlateau(optimizer, mode=mode, factor=factor, patience=patience,
                                           threshold=threshold, threshold_mode=threshold_mode, cooldown=cooldown,
                                           min_lr=min_lr, eps=eps, verbose=verbose)

    def __call__(self, engine, name=None):
        self.scheduler.step(engine.state.metrics[self.metric_name])

    def state_dict(self):
        return self.scheduler.state_dict()

            
# usage		
scheduler = ReduceLROnPlateauScheduler(optimizer, "my_metric", mode="max")
evaluator.add_event_handler(Events.COMPLETED, self.scheduler)
```

**Comment by ismael-elatifi** [comment]
I wrote a wrapper of **torch.optim.lr_scheduler.ReduceLROnPlateau** and put it here as it might be useful to others.

```python
from torch.optim.lr_scheduler import ReduceLROnPlateau


class ReduceLROnPlateauScheduler:
    """Wrapper of torch.optim.lr_scheduler.ReduceLROnPlateau"""

    def __init__(
            self,
            optimizer,
            metric_name,
            mode='min', factor=0.1, patience=10,
            threshold=1e-4, threshold_mode='rel', cooldown=0,
            min_lr=0, eps=1e-8, verbose=False,
    ):
        self.metric_name = metric_name
        self.scheduler = ReduceLROnPlateau(optimizer, mode=mode, factor=factor, patience=patience,
                                           threshold=threshold, threshold_mode=threshold_mode, cooldown=cooldown,
                                           min_lr=min_lr, eps=eps, verbose=verbose)

    def __call__(self, engine, name=None):
        self.scheduler.step(engine.state.metrics[self.metric_name])

    def state_dict(self):
        return self.scheduler.state_dict()

# usage 
scheduler = ReduceLROnPlateauScheduler(self.optimizer, metric_name="my_metric", mode="max")
evaluator.add_event_handler(Events.COMPLETED, scheduler)

**Comment by vfdev-5** [comment]
Hey @ismael-elatifi , thanks for sharing ! Looks cool ! If you'd like to see such code in the contrib.handlers module, feel free to send a draft PR and we could guide you in the dev process.
