### ISSUE TITLE
Improve docs with Events timeline image

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#463]
As there is a lot of issues where folks seem not to understand well ignite's event handling, idea is to improve the docs with a visual representation like [this one](https://github.com/pytorch/ignite/issues/462#issuecomment-475677991). Thoughts ?

**Comment by anmolsjoshi** [comment]
@vfdev-5 i think this is a good idea, the more information we provide the better users are able to use ignite

**Comment by anmolsjoshi** [comment]
@vfdev-5 might be worth it to add this in the FAQ
