### ISSUE TITLE
Create FAQ in the docs based on questions in issues

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#469]
Idea is to create a FAQ page in the docs based on answers of questions asked in the past issues. For example:
- https://github.com/pytorch/ignite/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aquestion+
- and other best practices.

Thoughts ?

**Comment by anmolsjoshi** [comment]
@vfdev-5 I think that's a really good idea! A lot of users end up using templates for these best practices.

**Comment by anmolsjoshi** [comment]
Closing in favor of #471
