### ISSUE TITLE
How to resume training with stored statistics? i.e. how to load engine state  in terms of num_epochs etc

### ISSUE THREAD

**Issue by Kyridiculous2** [pytorch/ignite#470]

**Comment by vfdev-5** [comment]
@Kyridiculous2 could you please provide more details on the question ?

To resume training in a basic way, you can do the following. Assuming you previosly saved state dicts of your model, optimizer, lr_scheduler.
```python
model.load_dict(saved_model_dict)
optimizer.load_dict(saved_optimizer_dict)
lr_scheduler.load_dict(saved_lr_scheduler_dict)

# Redefine the trainer as previously
trainer = ...

# Set the initial epoch
@trainer.on(Events.STARTED)
def setup_state(engine):
    engine.state.epoch = start_epoch

trainer.run(data, max_epochs=max_epochs)
```

**Comment by Kyridiculous2** [comment]
Thanks for replying.
One more question, when using checkpoint to save a class instance, I found when I change the value of some attributes of it, it still save the original value.  
`    trainer.add_event_handler(event_name=Events.ITERATION_COMPLETED, handler=checkpoint_handler,
                              to_save={'model': model.state_dict(), 'optimizer': optimizer.state_dict(),
                                       'annealers': sigma_scheme.__repr__()})`
and sigma_scheme is an instance of 
`class Annealer(object):
    def __init__(self, init, delta, steps,s=0):
        self.init = init
        self.delta = delta
        self.steps = steps
        self.s = s
        self.recent = init
    def __repr__(self):
        return {"init": self.init, "delta": self.delta, "steps": self.steps, "s": self.s}`

when i set sigma_scheme.steps to another value in iteration, it still saves the initial value.
How can I get away with that?

**Comment by Kyridiculous2** [comment]
Alternatively how can i save the current iteration steps using the model checkpoint handler?
since engine.state.iteration isn't initialized at first, so can be a parameter to to_save

**Comment by vfdev-5** [comment]
Maybe you can do this like the following:

```python
save_dict = {
    'model': model,
    'optimizer': optimizer,
    'annealers': sigma_scheme.__repr__(),
}
handler = ModelCheckpoint('/tmp/models', 'myprefix', save_interval=2, n_saved=2, create_dir=True)

def save_params(engine, save_dict):
    save_dict['iteration'] = engine.state.iteration
    handler(engine, save_dict)

trainer.add_event_handler(Events.EPOCH_COMPLETED, save_params)
```

**Comment by Kyridiculous2** [comment]
So what's the difference between them ?
It seems the way i saved them before take a copy of the instance at the beginning.
I'll try your suggestions though, Thank u!

**Comment by vfdev-5** [comment]
If you pass `repr(sigma_scheme)` in the begining 
```python
save_dict = {
    # 'model': model.state_dict(), => DO NOT NEED TO PASS state_dict JUST MODEL.
    'model': model,
    # 'optimizer': optimizer.state_dict(),
    'optimizer': optimizer,
    # 'annealers': sigma_scheme.__repr__() => THIS BECOMES FIXED WHICH IS NOT WHAT YOU WANT
}
trainer.add_event_handler(event_name=Events.ITERATION_COMPLETED, handler=checkpoint_handler,
                              to_save=save_dict)
```
it becomes fixed and does not change at iteration.

To overcome this you can augment `save_dict` dynamically in a custom handler as proposed in https://github.com/pytorch/ignite/issues/470#issuecomment-478899010

**Comment by Kyridiculous2** [comment]
Thank u very much! Your suggestions help well!
So model and optimizer (pytorch objects?) are special objects that will be updated every time to be saved,while ordinary python objects will be fixed?

**Comment by vfdev-5** [comment]
Internally we are using `torch.save` on either `object` or `object.state_dict()` if there is one : https://github.com/pytorch/ignite/blob/master/ignite/handlers/checkpoint.py#L139
So if you can save your object `sigma_scheme` with `torch.save` directly it will work for you without the workaround I proposed previously:
```python
save_dict = {
"obj": torch_storable_object
}
```

**Comment by Kyridiculous2** [comment]
Thank you~!

**Comment by Oktai15** [comment]
Can be closed, @vfdev-5?

**Comment by vfdev-5** [comment]
Technically, yes, but I still keep open those related to coming engine refactoring, #640

**Comment by vfdev-5** [comment]
I close the issue as resolved. Please see [here](https://pytorch.org/ignite/master/concepts.html#resume-training) for more details on how to resume a training.
