### ISSUE TITLE
What is the canonical way to log some images to tensorboard?

### ISSUE THREAD

**Issue by philip-bl** [pytorch/ignite#497]
Hello. I would like to know, what is the best way (i.e. least spaghetti code) to log some images via tensorboardx logger? E.g. I am creating a denoising autoencoder. Every time I evaluate the model on validation dataset, I would like to also use its input (noisy image), its output (reconstructed image), and the target (noiseless image) - to extract a few random images from them, put them into `torchvision.utils.make_grid` and send its output to `writer.add_image`. But what's the best way to do that via `TensorboardLogger` class?

**Comment by vfdev-5** [comment]
@philip-bl you can do this by several ways: 
1) `TensorboardLogger` exposes `writer` so you can use it in your custom handlers to do everything you want. 
2) You define a handler and attach it as it shown in the docstring (e.g. `OutputHandler`). Below an example of how to log images generated by a GAN (cycle gan horses):
```python
def log_generated_images(tag, fake_buffer):    
    def wrapper(engine, logger, event_name):
        res = vutils.make_grid(torch.cat(fake_buffer, dim=0), padding=2, normalize=True)
        res = res.detach().cpu()
        state = engine.state
        global_step = state.get_event_attrib_value(event_name)
        logger.writer.add_image(tag=tag, img_tensor=res, global_step=global_step, dataformats='CHW')
    return wrapper
    
tb_logger.attach(trainer,
                 log_handler=log_generated_images('Horses', fake_a_buffer), 
                 event_name=Events.EPOCH_STARTED)
```
HTH
