### ISSUE TITLE
Removing tensorboardX dependency for tensorbord_logger

### ISSUE THREAD

**Issue by aktgpt** [pytorch/ignite#518]
Hi,
As pytorch now supports tensorboard, wouldn't it be a good idea to remove tensorboardX dependency from the contrib module?

**Comment by vfdev-5** [comment]
@aktgpt haven't use it yet, but saw some issues with. Maybe we can wait a bit until torch TB becomes more stable...

**Comment by vfdev-5** [comment]
I'll close this issue in favor of #553
