### ISSUE TITLE
Improve OutputHandler's API

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#519]
Following a dicsussion from the slack:
> trying to set up a regular evaluation (on an evaluation dataset) along the training (every 500 steps for instance) and log that on Tensorboard with the training step number. Not exactly sure if I can do that with 0.2, I've tried:
> - to log metrics after the evaluation (event `EPOCH_COMPLETED` for the evaluation engine) but with the event `ITERACTION_COMPLETED` of the training engine => doesn't seem possible

cc @thomwolf

**Comment by anmolsjoshi** [comment]
@vfdev-5 here is code I mentioned on slack - https://github.com/anmolsjoshi/ignite/blob/tensorboard_fix/ignite/contrib/handlers/base_logger.py#L30-L55

In this branch, I have updated mnsit_with_tensorboard_logger.py to evaluate at CustomPeriodicEvent at every 500 iterations. 

Thoughts?

Edge cases?
