### ISSUE TITLE
Update examples with newer API

### ISSUE THREAD

**Issue by alykhantejani** [pytorch/ignite#53]
As it is in alpha, the code is moving quickly. We should try and keep the examples up to date

**Comment by keon** [comment]
I think it'd be better to test the examples in the CI testing.
Just checking if they are running or not should be enough I guess.

**Comment by alykhantejani** [comment]
@keon yup, this seems like a sensible idea. once #59 is merged I will add this to the CI

**Comment by alykhantejani** [comment]
FYI: Working on fixing this now as well as the logging module
