### ISSUE TITLE
Problem with IoU

### ISSUE THREAD

**Issue by TheCodez** [pytorch/ignite#543]
I'm training a FCN on the Cityscapes dataset. All ignored classes are mapped to 255. This works perfectly fine for the loss function using ignore_index.

Using the Ignite IoU metric however results in this error:

```/pytorch/aten/src/THC/THCTensorScatterGather.cu:188: void THCudaTensor_scatterFillKernel(TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, Real, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [36,0,0], thread: [0,0,0] Assertion `indexValue >= 0 && indexValue < tensor.sizes[dim]` failed.```

triggered here:
```
y_pred_ohe = to_onehot(indices.reshape(-1), self.num_classes)
  File "/usr/local/lib/python3.6/dist-packages/ignite/utils.py", line 48, in to_onehot
    onehot = torch.zeros(indices.shape[0], num_classes, *indices.shape[1:], device=indices.device)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorMath.cu:26
```

It's probably because there are only 19 classes and some values are 255.

**Comment by vfdev-5** [comment]
@TheCodez thanks for the report! Yes, that's can be a problem if we would like to ignore an index that is not contigous... In the docs I think we mentioned that https://pytorch.org/ignite/master/metrics.html#ignite.metrics.ConfusionMatrix

But I agree that such flexibility could be helpful

**Comment by TheCodez** [comment]
@vfdev-5 it seems that the [torchvision](https://github.com/pytorch/vision/blob/master/references/segmentation/utils.py#L75-L117) implementation doesn't have this limitation.

**Comment by vfdev-5** [comment]
@TheCodez yes, I saw that they compute it too, but didn't inspect in details. It seems that if target is outside `num_classes` it is ignored as we may wish but there is no explicit definition of ignored indices... Maybe we could produce something in between... If you would like to send a PR, you're welcome !

**Comment by TheCodez** [comment]
@vfdev-5 I will create a pull request for it :+1
