### ISSUE TITLE
Any one can show a ignite example with custom dataset?

### ISSUE THREAD

**Issue by honghanchenchh** [pytorch/ignite#546]
In some time,  my custom dataset  __getitem__ function return 3 values with img,path,label

**Comment by vfdev-5** [comment]
@honghanchenchh no problems with custom datasets. Just define your update function that passed to `Engine` and that's it. Take a look here: https://github.com/pytorch/ignite/blob/master/examples/notebooks/CycleGAN.ipynb

**Comment by honghanchenchh** [comment]
@vfdev-5 
Thank you very much!

**Comment by vfdev-5** [comment]
@honghanchenchh you're welcome! I let you close the issue if it answers your question.
