### ISSUE TITLE
Compute metrics on "slices" of the data?

### ISSUE THREAD

**Issue by jayleverett** [pytorch/ignite#547]
A nifty feature in Tensorflow Model Analysis is the ability to [compute metrics on slices of a dataset](https://www.tensorflow.org/tfx/guide/tfma#slicing_metrics_tab).

Is this sort of thing possible with Ignite?

**Comment by vfdev-5** [comment]
@jayleverett interesting feature, however it is not very clear how these slices are chosen. 
Actually, ignite can compute metrics on provided data loader (by defining an evaluator with attached metrics). If a data loader can be configured such that it could provide different slices of the full dataset, than ignite can compute metrics per slice...

```python
```

**Comment by vfdev-5** [comment]
@jayleverett I close this isssue as stale. Feel free to reopen if needed
