### ISSUE TITLE
Log handlers are not up to date.

### ISSUE THREAD

**Issue by vinayakvivek** [pytorch/ignite#55]
functions like `log_training_simple_moving_average` uses `training_data` attribute of `Trainer` which does not exist.
```python
...
iterations_per_epoch = len(trainer.training_data)
...
```

**Comment by alykhantejani** [comment]
Sorry about this, the API is moving quickly. Will get these things fixed this week

**Comment by alykhantejani** [comment]
This is being addressed in #59

**Comment by alykhantejani** [comment]
Sorry for the delay on this. The new API is in now, I will get this fixed ASAP
