### ISSUE TITLE
Improve ModelCheckpoint naming

### ISSUE THREAD

**Issue by TheCodez** [pytorch/ignite#550]
The checkpointer currently appends the epoch/iteration to the filename. However this number is reset when resuming a training from a checkpoint.
This is really annoying when say for example the last checkpoint is named ```checkpoint_60.pth```, then training is stopped and later resumed. The next checkpoint will then be named ```checkpoint_1.pth```.

A solution might be to add a ```global_step_transform``` argument so that epoch/iteration from the saved checkpoint can be reused.

**Comment by vfdev-5** [comment]
@TheCodez yes I agree that we need improve `ModelCheckpoint`. Recently I worked on #387 and a flexibility is lacking in this class... That's true that in "resume" use case that internal counter inside ModelCheckpoint is not restored and this is bad.
