### ISSUE TITLE
support for torch.utils.tensorboard when using `tensorboard_logger`

### ISSUE THREAD

**Issue by budui** [pytorch/ignite#553]
With PyTorch 1.1.0, TensorBoard is now [natively supported](https://pytorch.org/docs/stable/tensorboard.html) in PyTorch. 

Can we add a new option to switch `torch.utils.tensorboard` or `tensorboardX`?

I found that `tensorboard_logger` only need `SummaryWriter` to implement `add_histogram` and `add_scalar`. It seems that we can just import `torch.utils.tensorboard` when import tensorboardX failed.

```python
try:
    from tensorboardX import SummaryWriter
except ImportError:
    from torch.utils.tensorboard import SummaryWriter
```

For now, tensorboardX:
> Support scalar, image, figure, histogram, audio, text, graph, onnx_graph, embedding, pr_curve, mesh and video summaries.

`torch.utils.tensorboard`:
> Scalars, images, histograms, graphs, and embedding visualizations are all supported for PyTorch models and tensors as well as Caffe2 nets and blobs.

**Comment by vfdev-5** [comment]
@budui yes, such switch seems ok. If you would like to send a PR for this, it could be helpful. We need however to ensure that the tests are passing for both options.
