### ISSUE TITLE
`type_as` will not move Tensor to the same device

### ISSUE THREAD

**Issue by leomao** [pytorch/ignite#554]
In some metrics, we use `type_as` to change the data type of tensors. But `type_as` does not move the tensor to the same device.
https://github.com/pytorch/ignite/blob/c92838c950699839c37f57bb50f79f84ecb71fc3/ignite/metrics/confusion_matrix.py#L73-L90
In the code above,  if `y` is on a non-default cuda device, then `confusion_matrix` will be move to the  **default** cuda device at line 87. This makes line 89 fail because two tensors are not on the same device.  I think replacing `type_as` with `to` can resolve this issue.

BTW, the `.float()` in line 89 seems unnecessary.

**Comment by vfdev-5** [comment]
@leomao thanks for the feedback. Yes, we need to reconsider ingite metrics for distributed configuration. Concerning confusion metrics implementation, probably we need to follow the code similar as in torchvision, see https://github.com/pytorch/ignite/issues/543

**Comment by vfdev-5** [comment]
@leomao I'm working on adapting all metrics to handle distributed computations when val/test data is sampled with pytorch DistributedSampler. Could you please provide some more info in which case you have `y` to be on a non-default cuda device ? Thanks

**Comment by leomao** [comment]
Actually, it was my friends who encountered this problem.  AFAIK, they have computers with multiple GPUs and they manually use a device id like 'cuda:1' to specify which GPU they want to use.  I am not sure if they are trying to use multiple GPUs at the same time.  But I think this problem is still a valid issue.

**Comment by vfdev-5** [comment]
@leomao okay, I see, thank you. Yes, you  are  right, we need to handle properly the devices. I pushed #572 PR which should fix this. And more generally there is work to adapt metrcs to distributed settings, #573

**Comment by vfdev-5** [comment]
Probably we can close this issue as solved as today Confusion Matrix was reimplemented in #572
