### ISSUE TITLE
Add GPU memory consumption as metric

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#566]
Idea is to provide used GPU max memory during the engine run.
For example,
```python
from pynvml.smi import nvidia_smi
from ignite.engine import Engine, Events
# from ignite.contrib.handlers import ProgressBar
# Here I use a custom ProgressBar to be able to log string value

import time


nvsmi = nvidia_smi.getInstance()
local_rank = 0

def update(engine, batch):
    time.sleep(0.1)
    a = torch.rand(10, 10, 10, 10).cuda()


trainer = Engine(update)


@trainer.on(Events.ITERATION_COMPLETED)
def log_gpu_mem_usage_as_metric(engine):
    
    report = nvsmi.DeviceQuery('memory.free, memory.used, memory.total')['gpu'][local_rank]['fb_memory_usage']    
    engine.state.metrics['gpu memory'] = "{} / {} MiB".format(int(report['used']), int(report['total']))

ProgressBar(persist=True).attach(trainer, metric_names=['gpu memory', ])

data = list(range(40))
trainer.run(data)
```
with output
```
Epoch
[40/40] 100%|██████████, gpu memory=493 / 11176 MiB [00:04<00:00]
```

However wrapping the handler into a class as `RunningAverage`

**Comment by Darktex** [comment]
Could this be done without depending on another library?

`torch.cuda.memory_allocated(device)` would return the currently-used memory for tensors and `torch.cuda.memory_cached(device)` would return the one currently allocated to cache, while `torch.cuda.get_device_properties(device).total_memory` would return the total memory of the GPU. All of them return ints (number of bytes), so they would have to be formatted. Might save a dep :)

**Comment by vfdev-5** [comment]
@Darktex I get more precise gpu memory usage values with pynvml vs `torch.cuda.memory_*`.
There was a similar discussion here:
https://discuss.pytorch.org/t/measuring-peak-memory-usage-tracemalloc-for-pytorch/34067
