### ISSUE TITLE
Adapt metrics to be used with distributed

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#568]
Idea is to ensure that metrics computation works correctly on multiple GPUs.

**Comment by miguelvr** [comment]
hey @vfdev-5 

This is a topic I'm very much interested and willing to help.

I just looked at the distrib branch, and I see some problems with the current implementation.

I think that we could have a decorator to mark each existing metric as distributed compatible and raise a warning / error if the user tries to use the metric in a distributed scenario.

Using a sum all reduce op, does not work for every case, so we would also have to account for that.

Let me know your thought and how I can help!

Best,
Miguel

**Comment by vfdev-5** [comment]
Hey @miguelvr yes, we are very interested in testing ignite distrib branch in various use-cases and improve the code. For example, [here](https://github.com/pytorch/ignite/pull/576) I'm trying to reproduce various benchmarks in distributed setting.

> we could have a decorator to mark each existing metric as distributed compatible and raise a warning / error if the user tries to use the metric in a distributed scenario.

Yes, my idea was to adapt all metrics be default to be compatible and if one is not compatible, we warn about this.

> Using a sum all reduce op, does not work for every case, so we would also have to account for that.

Yes, there are cases like that and we warns user about this : https://github.com/pytorch/ignite/blob/distrib/ignite/metrics/precision.py#L18

> how I can help!

It would be awesome if you could test in your cases and give a feedback.
