### ISSUE TITLE
how to use swa in ignite?

### ISSUE THREAD

**Issue by hust-kevin** [pytorch/ignite#570]
hi, swa is supported by pytorch,https://pytorch.org/blog/stochastic-weight-averaging-in-pytorch/

how can i use it in ignite?

**Comment by vfdev-5** [comment]
Hi, I tried this rapidly [here](https://github.com/vfdev-5/UDA-pytorch/blob/master/code/main.py#L186) but not sure whether it is correctly used.

**Comment by hust-kevin** [comment]
thanks, I will try it , if I use automatic  mode,https://github.com/vfdev-5/UDA-pytorch/blob/master/code/main.py#L192
the update_swa function may not need?

**Comment by hust-kevin** [comment]
hi, @vfdev-5 I try your code, there is no error,but after swa, there is no final weight generate! maybe should add code to save the final weight??

**Comment by vfdev-5** [comment]
@hust-kevin please feel free to add or modify that code as you wish. As I said I'm not sure whether SWA works correctly in that code. I have not much time to recheck this.
