### ISSUE TITLE
Basic Time Profiling into contrib

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#589]
Following https://github.com/pytorch/ignite/issues/63#issuecomment-523366321
we can provide some basic time profiling. 

cc @willprice what do you think about this profiler, any code, API updates to suggest ?

**Comment by Patil2099** [comment]
Can I work on this issue? Can you also tell on which file I have to work?
Thanks!

**Comment by vfdev-5** [comment]
@Patil2099 thanks for the proposition ! Yes, you can work on it. Please follow these guide lines : 
https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md

You can add the code from https://github.com/pytorch/ignite/issues/63#issuecomment-523366321 to `ignite/contrib/handlers/time_profiler.py` and add some tests.
The code from the comment needs some update to the current API, especially handlers removing, which is already available within Engine.
