### ISSUE TITLE
I got an error in EfficientNet notebook example

### ISSUE THREAD

**Issue by Soo95** [pytorch/ignite#591]
torch : '1.2.0+cu92'
ignite: '0.2.0'
tensorboardX: '1.8'

Hi, I just followed efficientNet notebook example in the git.
```
x = torch.rand(4, 3, 224, 224)
graph_def = graph(model, x, operator_export_type='RAW')
```

In this part, I got an error

> /opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:61: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-13-99ad14b06837> in <module>
>       1 x = torch.rand(4, 3, 224, 224)
> ----> 2 graph_def = graph(model, x, operator_export_type='RAW')
> 
> /opt/conda/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py in graph(model, args, verbose, **kwargs)
>     253     if verbose:
>     254         print(graph)

My tensorboardX version is different or is there anything I can fix?

**Comment by vfdev-5** [comment]
@Soo95 thanks for the feedback! Yes, most probably my tbX version was 1.7 at the moment of writing. Anyway, I'll check and fix this error in the coming days.

**Comment by Soo95** [comment]
@vfdev-5 
https://github.com/lanpa/tensorboardX/issues/483
This is the same issue with me. the tensorboard graph has a problem after pytorch 1.2 version.
I think I can do nothing unless this bug is fixed from tensorboard.
