### ISSUE TITLE
TensorboardLogger init - forwarding kwargs to SummaryWriter

### ISSUE THREAD

**Issue by Bibonaut** [pytorch/ignite#597]
### Problem 
When a TensorboardLogger object is created, it also initialises a SummaryWriter object. 
At the moment, the TensorboardLogger init function accepts the only argument `log_dir` that is passed to SummaryWriter but SummaryWriter accepts a lot more keyword arguments I want to make use of. 

[Link to current implementation](https://github.com/pytorch/ignite/blob/01f2f5f96f55b8358edfe280dc6852bbaf807425/ignite/contrib/handlers/tensorboard_logger.py#L402)
### Solution/Proposal
Forwarding all positional and keyword arguments to SummaryWriter. 

Would this also solve the tensorboardX compatibility issue #538?

-----------
Are there any restrictions I missed, why this is not implemented? 
If wanted, I can create a pull request.

**Comment by vfdev-5** [comment]
@Bibonaut yes, we can forward positional and kw args. Please, do no hesitate to send a PR to fix the issue :)
