### ISSUE TITLE
BaseWeightsScalarHandler has side effects on random number generation

### ISSUE THREAD

**Issue by Bibonaut** [pytorch/ignite#611]
### Problem
BaseWeightsScalarHandler uses `torch.rand` to test the reduction function that is passed as an argument. 
This is very confusing, because experiments are not reproducible when tensorboard logging is switched on or off, e.g. in debug sessions. 

### Solution
Replace the random tensor with a non random tensor.

**Comment by vfdev-5** [comment]
@Bibonaut no problem, please send a PR for that :)
