### ISSUE TITLE
Switch website theme to PyTorch?

### ISSUE THREAD

**Issue by bosr** [pytorch/ignite#625]
I am updating the docs theme to leverage [pytorch_sphinx_theme](https://github.com/pytorch/pytorch_sphinx_theme) so that Ignite docs look like PyTorch's. The diffs are minimal.

Pros:
- closer to PyTorch
- darkifiable with existing Userstyles (see screenshots)

Caveats:
- pytorch_sphinx_theme comes with footers that are not really relevant to Ignite, and I could not yet find a way to alter them.
- the links to various Ignite versions are eaten by some monster somewhere

Here are some screenshots (built with `make html` or with `sphinx-versioning ...`). What is your opinion? Should I open a PR?

## some text and code (that look nice IMO)

<img width="1348" alt="Screenshot 2019-09-14 at 20 00 54" src="https://user-images.githubusercontent.com/1936828/64912083-697e6480-d72a-11e9-8712-1bbbe64aab4b.png">

<img width="1348" alt="Screenshot 2019-09-14 at 19 44 04" src="https://user-images.githubusercontent.com/1936828/64912055-1f957e80-d72a-11e9-9478-2ae7e4891a50.png">

## the main caveat: PyTorch footer (irrelevant to Ignite)

<img width="1348" alt="Screenshot 2019-09-14 at 20 02 23" src="https://user-images.githubusercontent.com/1936828/64912094-9763a900-d72a-11e9-9eae-30cc55e67c59.png">

**Comment by vfdev-5** [comment]
@bosr yes this theme looks nicer :) I think if we can update current theme to this one !
Just I would prefer to keep:
- our versioning feature
- remove pytorch-only footer

@bosr is it possible ?

**Comment by bosr** [comment]
thanks @vfdev-5, perfect I'll try to do so, then I'll open the PR (the code is currently in bosr/ignite@doc/pytorch-theme)

**Comment by vfdev-5** [comment]
@bosr sounds good! Thank you !

**Comment by bosr** [comment]
Good opportunity to refresh my rusty Sphinx knowledge!

Among other fixes, I removed the footer and customized the header. I'm still missing the versions links. It looks like this (zoomed out 85% but that's not relevant):

<img width="1512" alt="Screenshot 2019-09-15 at 11 19 51" src="https://user-images.githubusercontent.com/1936828/64919436-f406a880-d7aa-11e9-8836-e16b9ba4ee61.png">

**Comment by vfdev-5** [comment]
Looks awesome !
