### ISSUE TITLE
save the best score in engine.state?

### ISSUE THREAD

**Issue by Soo95** [pytorch/ignite#627]
Hi, I want to print the best score at the end of training.

ModelCheckpoint handler can save the best model with the best score,
however, I just want to print the best score at the end of training.

Is it possible to save the best score till the end of training?

**Comment by vfdev-5** [comment]
@Soo95 there is nothing done for this today. I would say this can be done manually when run evaluators.
```python

@trainer.on(Events.STARTED)
def init_best_score(engine):
    engine.state.best_score = 0.0

@trainer.on(Events.EPOCH_COMPLETED)
def run_evaluation(engine):
     res = evaluator.run(val_loader)
     trainer.state.best_score = max(trainer.state.best_score, res['your_metric'])
```

HTH

**Comment by Soo95** [comment]
@vfdev-5 
I always thank for your kind replies!
