### ISSUE TITLE
[Contrib] Custom periodic event: simplify name of events:

### ISSUE THREAD

**Issue by tanguycdls** [pytorch/ignite#636]
Hi I'm currently using Custom periodic event in a wrapper however I find its usage quite complex and redundant:

When defining a custom event you write:
```
cpe_1000_iter = CustomPeriodicEvent(n_iterations=1000)
cpe_1000_iter.attach(trainer)
```
its now clear that `cpe1` should run every 1000 iterations. However when using it as an event we have to write:
```
@trainer.on(cpe_1000_iter.Events.ITERATIONS_1000_COMPLETED)
def on_every_1000_iterations(engine):
            # run a computation after 1000 iterations
            # ...
            print(engine.state.iterations_1000)
```
We have to know how the custom event was created to use it:  as in reality only  ITERATIONS_1000_COMPLETED, ITERATIONS_1000_STARTED are available. 

We can use : 
```
@trainer.on(getattr(cpe_1000_iter.Events, f"{cpe_1000_iter.custom_state_attr.upper()}_COMPLETED"))
def on_every_1000_iterations(engine):
            # run a computation after 1000 iterations
            # ...
            print(engine.state.iterations_1000)
```
But it looks quite complex and not readable. 

I would like to add the explanation that you can use
```
self._periodic_event_started = getattr(self.Events, "{}_STARTED".format(event_name))
self._periodic_event_completed = getattr(self.Events, "{}_COMPLETED".format(event_name))
```
- remove the _ to make it public 
- add an example using it and add docs

**Comment by vfdev-5** [comment]
Hi @tanguycdls thanks for the feedback. I agree that `CustomPeriodicEvent` is too ugly to use. We are working on another built-in version of periodic events in this PR : https://github.com/pytorch/ignite/pull/624.
Please join the discussions and if we could agree on easy-usage API we will merge it quickly.

**Comment by tanguycdls** [comment]
Oops sorry ! Yes I will join the conversation

Thank you !
