### ISSUE TITLE
[Feature Request] Distributed training wrapper

### ISSUE THREAD

**Issue by akurniawan** [pytorch/ignite#66]
Tensorflow has a feature called `tf.estimator` that nicely wrap the distributed training, so the user doesn't have to know which one is master, etc. Should we include that as well in ignite? Or that should be under pytorch repository?

**Comment by alykhantejani** [comment]
I believe this can already be handled at the module level (defining your network). For example see the [DistributedDataParallel module](http://pytorch.org/docs/master/nn.html#torch.nn.parallel).

This allows it to just work with the current ignite API. Is there something else you had in mind?

**Comment by akurniawan** [comment]
Ah didn't aware of that module existence, thanks for pointing out! I have never used it before so I can't say anything at this moment. We can close this issue then for now. Thanks!
