### ISSUE TITLE
how to download pytorch-ignite 0.1.0 version?

### ISSUE THREAD

**Issue by kwonjunn01** [pytorch/ignite#663]
I can' find the old version and model requirement's is 0.1.0.

Where can I download this version

plz help me..

**Comment by vfdev-5** [comment]
@kwonjunn01 
How about this command ?
```
pip install --upgrade pytorch-ignite==0.1.0
```

**Comment by vfdev-5** [comment]
Close the issue as answered. Please, feel free to reopen if needed
