### ISSUE TITLE
Add state_dict/load_state_dict to ParamScheduler

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#667]
Idea is to improve `ParamScheduler` by providing two methods : 
- state_dict
- load_state_dict
as native pytorch LRScheduler. This would help to save and restore a ParamScheduler

**Comment by PyExtreme** [comment]
Hi @vfdev-5 , I would like to take this up. I am interested to contribute to ignite and seems like a good starting point.

Thank you

**Comment by vfdev-5** [comment]
@PyExtreme sorry, this one is more tricky than I thought in the beginning. I'll handle it by myself.
Please, go ahead with Dice Coefficient as you asked yesterday, once you are OK with your code, do not hesitate to send a PR.
