### ISSUE TITLE
 CIFAR-10 example has strange event names for tb loggers

### ISSUE THREAD

**Issue by Oktai15** [pytorch/ignite#668]
https://github.com/pytorch/ignite/blob/f71fc8606c3c498d770bec6fde9869e54d8b03ac/examples/contrib/cifar10/main.py#L163

https://github.com/pytorch/ignite/blob/f71fc8606c3c498d770bec6fde9869e54d8b03ac/examples/contrib/cifar10/main.py#L169

Why has `COMPLETED` been used rather than `EPOCH_COMPLETED`? We want to get information about metrics across all epochs, not across one epoch or I don't understand what will happen?

Also, I suppose we need to update it to new approach with `global_step_from_engine(trainer)`.

**Comment by vfdev-5** [comment]
@Oktai15 this is correct, please take a look here : https://pytorch.org/ignite/faq.html#each-engine-has-its-own-events
> Evaluator has its own loop. Therefore, it runs only one epoch and EPOCH_COMPLETED is equivalent to COMPLETED.

> Also, I suppose we need to update it to new approach with global_step_from_engine(trainer).
Yes, this is correct. Just, in some sense it is much more easy to use `another_engine` vs `global_step_from_engine`. Maybe both could exist... and the warning about deprecation can be removed...

**Comment by Oktai15** [comment]
@vfdev-5 but it is not correct for this case. COMPLETED for trainer is end of training (e.g after 100 epochs), isn't it?

**Comment by vfdev-5** [comment]
@Oktai15 if I understand correctly your question, the following code is not clear for you : 
```python
tb_logger.attach(train_evaluator,
                         log_handler=tbOutputHandler(tag="train",
                                                     metric_names=list(metrics.keys()),
                                                     another_engine=trainer),
                         event_name=Events.COMPLETED)

 tb_logger.attach(evaluator,
                         log_handler=tbOutputHandler(tag="test",
                                                     metric_names=list(metrics.keys()),
                                                     another_engine=trainer),
                         event_name=Events.COMPLETED)
```
As you can see, `tbOutputHandler` via `tb_logger` is attached to `train_evaluator` and `evaluator`. These engines are configured to evaluate trained model and runs on training and test dataloaders.

Maybe this section can help to understand better : https://pytorch.org/ignite/concepts.html#timeline-and-events

**Comment by Oktai15** [comment]
@vfdev-5 Ohh, yes, you are right.

My problem was the following: I thought that `another_engine` overrides first parameter of `attach` function, i.e `event_name` is related to `another_engine` engine. But it is not true, because  `another_engine` only override output function for `tbOutputHandler`... Sorry

**Comment by vfdev-5** [comment]
No problems. Hope it is more clear now :)
