### ISSUE TITLE
Add examples into CI tests

### ISSUE THREAD

**Issue by alykhantejani** [pytorch/ignite#67]

**Comment by vfdev-5** [comment]
@alykhantejani how do you think to test it ? Something like:
```
assert os.system("python mnist.py") == 0
```
or something more sophisticated?

**Comment by alykhantejani** [comment]
@vfdev-5 in travis we can just launch the script directly (no need to write tests in python). I think we should just train for a single epoch (or even less). It's basically a smoke test to make sure the examples still run (with the changing API).

**Comment by jasonkriss** [comment]
@alykhantejani I think this one can be closed, right?

**Comment by alykhantejani** [comment]
yup, thanks @jasonkriss
