### ISSUE TITLE
TypeError: 'Events' object is not callable

### ISSUE THREAD

**Issue by RomanShen** [pytorch/ignite#670]
Hello! I'm a beginner for ignite and am still learning on it. I ran the example 'mnist_with_tensorboardx' and I came across the aforementioned problem. The error message looks like below:

`  File "mnist_with_tensorboardx.py", line 93, in run
    @trainer.on(Events.ITERATION_COMPLETED(log_interval))
TypeError: 'Events' object is not callable
`

I didn't make any change to the source code and I searched the internet and found nothing helpful. Can someone give me some help please?

**Comment by RomanShen** [comment]
After I update the ignite to dev version, the issue is resolved.

**Comment by vfdev-5** [comment]
@RomanShen yes, as you tried to run example code from master, it needs master version of the library
