### ISSUE TITLE
ConfusionMatrix is extremely slow

### ISSUE THREAD

**Issue by miguelvr** [pytorch/ignite#684]
I'm trying to do some grid search on some thresholds for the labels of my models, and the computation of 580 confusion matrices takes about 22 minutes on the GPU and about 8 minutes on CPU (yes, it is slower on the GPU).

I think the issue is probably related to `torch.bincount`

**Comment by vfdev-5** [comment]
@miguelvr thanks for the feedback, could you please provide some details on what kind of data you are using to compute CMs ?
Yes, it would be good to run profiling and benchmark execution on GPU vs CPU...

**Comment by miguelvr** [comment]
I'm putting together a small-ish code snippet with the benchmarks, I'll get back to you ASAP

**Comment by miguelvr** [comment]
the issue might be related to the fact that a lot of computations are made on the CPU (I'm using a lot of cmAccuracy, cmPrecision and cmRecall), and there the overhead of transferring data between GPU and CPU too often impacts performance significantly.

in my benchmark, the numbers are actually okay, so I'm closing this for now.

**Comment by miguelvr** [comment]
benchmark gist: https://gist.github.com/miguelvr/2ffb0c0a9d3110325e67c9278f224119

**Comment by vfdev-5** [comment]
@miguelvr OK, let's keep it as is. Could you please add your numbers for the benchmark ? 

> the issue might be related to the fact that a lot of computations are made on the CPU (I'm using a lot of cmAccuracy, cmPrecision and cmRecall), and there the overhead of transferring data between GPU and CPU too often impacts performance significantly.

Well, we need to pass the code into profiler. I can look at this as I have more free time...

**Comment by miguelvr** [comment]
```
CPU benchmarks
sklearn cm: 0.004323482513427734
ignite cm: 0.0011348721981048583
binary cm: 0.0009120926856994629

GPU benchmarks
ignite cm: 0.00042329788208007814
binary cm: 0.000345123291015625
```

**Comment by sdesrozis** [comment]
I discover this issue. Looking results, I don’t catch, GPU or CPU ConfusionMatrix is better ?

Sorry 😅
