### ISSUE TITLE
TypeError: 'Events' object is not callable

### ISSUE THREAD

**Issue by 2356852131** [pytorch/ignite#687]
please help,
when I run the code:
 @trainer.on(Events.ITERATION_COMPLETED(every=log_interval))
    def log_training_loss(engine):
        print("Epoch[{}] Iteration[{}/{}] Loss: {:.2f}"
              "".format(engine.state.epoch, iter, len(train_loader), engine.state.output))
        writer.add_scalar("training/loss", engine.state.output, engine.state.iteration)
arise the error:
Traceback (most recent call last):
  File "F:/keyan/code/cloudImagePredict/train.py", line 327, in <module>
    run(args.train_batch_size, args.val_batch_size, args.epochs, args.lr, args.log_interval, args.log_dir, args.checkpoint_dir )
  File "F:/keyan/code/cloudImagePredict/train.py", line 269, in run
    @trainer.on(Events.ITERATION_COMPLETED(every=log_interval))
TypeError: 'Events' object is not callable

**Comment by vfdev-5** [comment]
@2356852131 please use latest nightly release to have it working:
https://github.com/pytorch/ignite#nightly-releases

**Comment by vfdev-5** [comment]
I close the issue as solved, please feel free to reopen it if need more support on the issue.

**Comment by avangelizer** [comment]
Hi, I've still got the error even though I installed the latest nihtly release. I'm currently working on google colab. Don't know if that makes any difference.

**Comment by vfdev-5** [comment]
@avangelizer please take a look at this colab where it works : 
https://colab.research.google.com/drive/1nUkbM8WqatZJWYs9DfeNgJVljjk0NdBO
