### ISSUE TITLE
issue with tensorboardX

### ISSUE THREAD

**Issue by JaneEyreliu** [pytorch/ignite#693]
@g-karthik this is due to the newest tensorboardX release 1.7, https://github.com/pytorch/ignite/issues/530
Either install tensorboardX < 1.7 or install ignite from master (`pip install git+https://github.com/pytorch/ignite.git`), we fixed that recently. 
HTH

_Originally posted by @vfdev-5 in https://github.com/pytorch/ignite/issues/534#issuecomment-494994872_

**Comment by JaneEyreliu** [comment]
but i have done this ,none of it work

**Comment by vfdev-5** [comment]
@JaneEyreliu could you please provide more details on your setup and what exactly does not work for you ?

**Comment by vfdev-5** [comment]
@JaneEyreliu I close it as stale. Feel free to reopen if needed
