### ISSUE TITLE
Using progress bar for both training and validation

### ISSUE THREAD

**Issue by wangyirui** [pytorch/ignite#708]
Hi, I am trying to show the progress bar for both the training and validation process, but the examples only demonstrate how to use pbar for the trainer. 

If I directly attach both the trainer and the evaluator to the pbar, then the total number of iterations in the validation process becomes incorrect (still the number of training iteration).  

So I am wondering how to use it for both trainer and evaluator? Thanks!

**Comment by vfdev-5** [comment]
@wangyirui please take a look at [this example](https://github.com/pytorch/ignite/blob/master/examples/references/classification/imagenet):

we can setup 3 progress bars: for the trainer, for train_evaluator (validation on train subset) and evaluator (validation on test dataset):

https://github.com/pytorch/ignite/blob/5b1bcd3df3e16812a1c15543973ed8c520d97420/examples/references/classification/imagenet/code/scripts/common_training.py#L109-L114

**Comment by wangyirui** [comment]
> @wangyirui please take a look at [this example](https://github.com/pytorch/ignite/blob/master/examples/references/classification/imagenet). We setup 3 progress bars: for `trainer`, for
> `train_evaluator` (validation on train subset) and `evaluator` (validation on test dataset):
> 
> https://github.com/pytorch/ignite/blob/5b1bcd3df3e16812a1c15543973ed8c520d97420/examples/references/classification/imagenet/code/scripts/common_training.py#L79-L87
> 
> 
> Options: `with_pbars=True, with_pbar_on_iters=True`.
> For evaluators:
> https://github.com/pytorch/ignite/blob/5b1bcd3df3e16812a1c15543973ed8c520d97420/examples/references/classification/imagenet/code/scripts/common_training.py#L109-L114
> 
> HTH

Thanks for your quick reply!!!!  I will go through these examples.

**Comment by vfdev-5** [comment]
@wangyirui can we close the issue as answered ?

**Comment by wangyirui** [comment]
@vfdev-5 Sure. It works good now. Thanks!

**Comment by ismael-elatifi** [comment]
To avoid having `tqdm` printing each new iteration on a new line, use this class instead :  
```python
from ignite.contrib.handlers.tqdm_logger import ProgressBar

class ProgressBarCustom(ProgressBar):
    """To force tqdm to overwrite previous line"""

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        from tqdm import tqdm as tqdm_base

        def tqdm_custom(*args, **kwargs):
            if hasattr(tqdm_base, '_instances'):
                for instance in list(tqdm_base._instances):
                    tqdm_base._decr_instances(instance)
            return tqdm_base(*args, **kwargs)

        self.pbar_cls = tqdm_custom

ProgressBarCustom(persist=False, desc="Training").attach(self.trainer)
ProgressBarCustom(persist=False, desc="Validation").attach(self.evaluator)
```

**Comment by saskra** [comment]
> To avoid having `tqdm` printing each new iteration on a new line, use this class instead :

Thanks for the code, this actually solves the problem with new lines for each iteration! But how can I prevent the progress bar from being cleared again at the end? I would have liked to leave it in the terminal so I can track how long the validation took.
