### ISSUE TITLE
Add transform function arguments to create_supervised_evaluator

### ISSUE THREAD

**Issue by pkdogcom** [pytorch/ignite#72]
I just checked out the new API and found the new create_supervised_trainer function really helpful. For most supervised learning task, this function makes trainer definition an one-liner. However, the evaluator counterpart create_supervised_evaluator doesn't seem to be as helpful. Since in most cases during validation we only care about the finall loss/accuracy/distance rather than the raw predictions and it is also much more memory efficient to keep the metrics than the raw predictions, I suggest adding a transform function argument in the create_supervised_evaluator function, which takes both the targets and predictions as input and the create_supervised_evalutor function will return its output as output for the given batch, just like how create_supervised_trainer returning the loss data. 

BTW, I also suggest using the two factory functions in the examples so that new users can make use of them more easily without having to dig into the codes.

**Comment by alykhantejani** [comment]
Hi @pkdogcom - I think this a good idea, in fact we discussed this in #54 ([here](https://github.com/pytorch/ignite/pull/54#issuecomment-363438057)). As we already have the `ignite.metrics` module, we should try to use these as the transforms

I will also break out a separate issue to update examples to use the factory functions.

**Comment by alykhantejani** [comment]
Closing this as the approach to improving the evaluator to include metrics is being discussed in #78
