### ISSUE TITLE
Clearer separation of core and contrib

### ISSUE THREAD

**Issue by justusschock** [pytorch/ignite#720]
currently we always refer to the core and the contrib package, without the existence of a real core package (we mean `ignite.engine`, `ignite.handlers` and `ignite.metrics` if we refer to `core`). I would propose one of two things:
1.) Either create a new repo for the contrib stuff to have a clearer separation
2.) Create a real `ignite.core` which will contain the above mentioned packages.

What do you think @vfdev-5 ?

**Comment by vfdev-5** [comment]
@justusschock here I'm not sure about that. 
It seems to me having contrib in the library is rather common practice: e.g. pytorch (no public classes there), tf, ... So introducing another module `core`, IMO is a but redundant.
Spliting line between "core" functionalities and "contrib" is in:
- contrib can bring other dependencies
- contrib can contain experimental functionalities
- contrib API can have BC breaking changes

**Comment by justusschock** [comment]
I agree. And that's why I would actually prefer this to be a separate repository.

But if you don't like that, it's also fine for me. Just a suggestion :)

**Comment by vfdev-5** [comment]
Let's keep in mind this possibility :)

**Comment by justusschock** [comment]
So I'll close this for now.
