### ISSUE TITLE
__all__  for each source file

### ISSUE THREAD

**Issue by justusschock** [pytorch/ignite#725]
I want to add the `__all__` attribute to each source file in the core package, which defines, what should be imported by `*` (e.g `from ignite.metrics import *`). Per default this are all objects whose name is not starting with '_'. But this includes all imports from other files and packages, which is not desired.

**Comment by vfdev-5** [comment]
Well, we can add this and define manually `__all__` for each file. 
Personnally, I prefer not to use `from module import *` because we are not then sure where come from a class or method.

**Comment by justusschock** [comment]
I know, I don't like this as well, but many users do this nevertheless and adding that is not much effort for us.

**Comment by vfdev-5** [comment]
Okay, I'm not against this so let's add this :)
