### ISSUE TITLE
Helpers args for event filtering

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#728]
Sometimes I would like to execute some handlers since or before an iteration/epoch. Idea is to add built-in arguments like `after` and `before` to callable events. Example API
```python
@trainer.on(Events.EPOCH_STARTED(before=10)
def pretraining_var_scheduling(_):
    # setup vars

# or
@trainer.on(Events.EPOCH_STARTED(after=10)
def training_var_scheduling(_):
    # setup vars
```

**Comment by justusschock** [comment]
Isn't that somehow similar to #710 ?

Maybe one could just pass a function there, which takes in the current epoch and returns a Boolean indicating, whether the handler should be executed?

Something like:

```python
@trainer.on(Events.EPOCH_STARTED(lambda epoch: epoch<10))
def pretraining_var_scheduling(_):
    # do stuff

```

**Comment by vfdev-5** [comment]
Yes, a solution like that could work
```python
@trainer.on(Events.EPOCH_STARTED(event_filter=lambda _, event: event<10))
def pretraining_var_scheduling(_):
    # do stuff
```

Well I agree, that it could be than misleading how to use both etc. Let's close this.
