### ISSUE TITLE
Checkpoint filename not using absolute score value

### ISSUE THREAD

**Issue by Joxis** [pytorch/ignite#733]
The [Checkpoint documentation](https://pytorch.org/ignite/handlers.html?highlight=checkpoint#ignite.handlers.Checkpoint) mentions the use of the absolute value of the score in the filename. 

> If score_function not None, it is possible to store its absolute value using score_name. See Notes for more details.

> If defined score_function and score_name, then the filename will be {filename_prefix}_{name}_{score_name}={abs(score)}.{ext}.

However, it seems the score (priority) is not used as an absolute value:
https://github.com/pytorch/ignite/blob/a1cae3148a92ddc82bfb1412859e04d4b51f0f25/ignite/handlers/checkpoint.py#L186

The `abs` call was removed in #679.

**Comment by vfdev-5** [comment]
@Joxis thanks for the catch! Yes, previously, we wanted to store only positive score values. In #679 I thought that we however can also store negative value in the filename. So, we need just to fix the documentation. 

If you would like to contribute to the library and make it better, please feel free to send a PR with docs fix. Thanks !

**Comment by Joxis** [comment]
@vfdev-5 I will submit the docs fix PR.

I think it would be a nice feature to allow custom formatting of the score value in the filename. Currently I have lengthy filenames with negative loss values with over 15 decimal places. A possibility is to add an extra 'score_format' argument to the Checkpoint class. This argument would expect a function taking the score values as input and returning the desired string representation of said score. The class argument could be made optional, defaulting to the current behavior.

Example:
```
def format_score(score):
    return '{:.4f}'.format(abs(score))
```

It is related to your previous feature request in #129.

Let me know what you think. Thanks!

**Comment by vfdev-5** [comment]
> @vfdev-5 I will submit the docs fix PR.

@Joxis thanks !

> I think it would be a nice feature to allow custom formatting of the score value in the filename. 

Well, I'm hesitating to introduce another argument for that. If we hardcode the format to `{:.4f}` or `{:.5f}` maybe this could be OK for everyone ? IMO, this is only an indicator to avoid looking at the dashboard where validation score is presented... 
What do you think ?

**Comment by Joxis** [comment]
@vfdev-5 I agree that hard-coding the decimal places would be fine. I previously hesitated that some users would require more precision but as you said, the filename only serves as an indication.
