### ISSUE TITLE
RuntimeWarning: Only one class present in y_true. ROC AUC score is not defined in that case..

### ISSUE THREAD

**Issue by wangyirui** [pytorch/ignite#735]
Hi, I am using ROC_AUC metric to track the training performance. However, this warning frequently appears:

> RuntimeWarning: Probably, there can be a problem with `compute_fn`: Only one class present in y_true. ROC AUC score is not defined in that case.

It seems the ROC_AUC compute_fn will be called every time we update the (y, y_pred) accumulator. In my scenario, it's possible that one batch only contains negative samples (unbalanced classes). So this warning may be annoying. 

Is there any way to disable this warning? Or whether it's better to change the behavior of this sanity check for the AUC calculation? (e.g. check the label/pred type after collecting all the data) 

Appreciate your help!

**Comment by vfdev-5** [comment]
@wangyirui I see your problem and agree that such warnings can be annoying. 
Normally, such warning you should see once at the first update only. Idea of this sanity check is to avoid some exceptions raised (some typos, bugs) after iterating over complete epoch which can take time.

What can we do from your side is to replace that `RuntimeWarning` warning by a specific warning `EpochMetricWarning` and which can be then filtered with 
```
import warnings
warnings.filterwarnings('ignore', category=EpochMetricWarning)
```

**Comment by wangyirui** [comment]
@vfdev-5 Thanks for your suggestion! I will do so from my end.

Is it possible to change the behavior officially in the next version? Thanks!

**Comment by vfdev-5** [comment]
Yes, I can do this rather quickly. And it can be available in next nightly releases.

**Comment by wangyirui** [comment]
@vfdev-5 Appreciate it!
