### ISSUE TITLE
correct the type hints of this function

### ISSUE THREAD

**Issue by CDitzel** [pytorch/ignite#747]
https://github.com/pytorch/ignite/blob/ca738d8f3f106093aa04b6bce9506129a1059df8/ignite/engine/events.py#L81

this really should read

`    def wrapper(engine, event: int) -> bool:`

**Comment by vfdev-5** [comment]
@CDitzel Thanks for the feedback! 
@justusschock could you please take a look on that.

**Comment by justusschock** [comment]
Yep, that's right. I'll fix that
