### ISSUE TITLE
Incompatibility with Python 3.5

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#757]
Following the comment: https://github.com/pytorch/ignite/pull/745#issuecomment-580553663

**Comment by vfdev-5** [comment]
@Nic-Ma could you please provide a bit more details on how to reproduce the issue.

From my side, I do the following checking and can not reproduce the issue:
```
user:/# python --version
Python 3.5.6 :: Anaconda, Inc.

user:/# pip list | grep ignite
pytorch-ignite 0.4.0.dev20200130

user:/# python -c "import ignite; print(ignite.__version__, ignite.__file__); from ignite.engine.engine import Engine"
0.4.0.dev20200130 /opt/conda/envs/py35/lib/python3.5/site-packages/ignite/__init__.py
```

**Comment by vfdev-5** [comment]
@Nic-Ma could you please confirm that you still experience this issue ?

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 ,

We already updated all our environments to latest NVIDIA docker which uses Python 3.6.
Didn't see this issue anymore.
And according to my google check, it's related to typing.py in 3.5 which is not compatible with 3.6.
Thanks.

**Comment by vfdev-5** [comment]
Well, can we close the issue? I could not reproduce the issue and it is solved for you also.

**Comment by Nic-Ma** [comment]
Yes, please close.
Thanks.
