### ISSUE TITLE
Accuracy with no ignore_index

### ISSUE THREAD

**Issue by bernardomig** [pytorch/ignite#765]
I think it would be nice to have an `ignore_index` parameter on the accuracy metric. I know it is possible to do with the `output_transform` parameter, but it is so common (for example, in semantic segmentation), that it should be there.
Any thoughts on this?

**Comment by vfdev-5** [comment]
@bernardomig for semantic segmentation we suggest to compute [confusion matrix](https://pytorch.org/ignite/metrics.html#ignite.metrics.ConfusionMatrix) and then compute accuracy with [this function](https://github.com/pytorch/ignite/blob/master/ignite/metrics/confusion_matrix.py#L205). To remove undesired index is possible with metrics arithmetics:
https://pytorch.org/ignite/metrics.html#metric-arithmetics

**Comment by bernardomig** [comment]
Ah ok. Yeah, that makes sense. Thank you.
