### ISSUE TITLE
log_message() method fails `desc` is passed to contrib tqdm

### ISSUE THREAD

**Issue by mi-lad** [pytorch/ignite#767]
## 🐛 Bug description

If I pass a `desc` argument when instantiating a `ignite.contrib.handlers.ProgressBar` the calls to its `log_message()` method fail with this exception:

```
TypeError: write() got an unexpected keyword argument 'desc'
```

## Environment

 - PyTorch Version: 1.3.1
 - Ignite Version: 0.3.0
 - OS: Linux
 - How you installed Ignite (`conda`, `pip`, source): Conda
 - Python version: 3.7
 - Any other relevant information:

**Comment by vfdev-5** [comment]
@mi-lad could you please provide installed tqdm version ?
@maxfrei750 could you please take a look at this issue ? thanks

**Comment by mi-lad** [comment]
tqdm version: 4.36.1

**Comment by maxfrei750** [comment]
The reason for the error is, that not all optional arguments of tqdm are valid for the write method as well. I'm going to write a fix and make a PR.
