### ISSUE TITLE
why change checkpoint dict to value if only 1 item?

### ISSUE THREAD

**Issue by Nic-Ma** [pytorch/ignite#770]
## 🐛 Bug description
We found there is a logic in checkpoint handler that change the dict to value if only has 1 item.
This logic makes it's hard to restore model with unified load API(_using 'to_load' dict_).
Why did ignite design this logic?

## Environment

 - PyTorch Version (e.g., 1.4): 1.4
 - Ignite Version (e.g., 0.3.0): 0.3.0
 - OS (e.g., Linux): ubuntu
 - How you installed Ignite (`conda`, `pip`, source): pip
 - Python version: 3.6
 - Any other relevant information:
related source code in ignite checkpoint handler line 205:
```py
            if len(checkpoint) == 1:
                for k in checkpoint:
                    name = k
                checkpoint = checkpoint[name]
```

Thanks.

**Comment by vfdev-5** [comment]
@Nic-Ma the logic is the following:
if user stores a single object in the dictionary `to_save={'model': model}`, then stored filename is `model_XYZ.pth`, where `model` is the key of the single object in `to_save`. If `to_save` contains more objects `{'model': model, 'optimizer': optimizer, ...}`, then filename is `checkpoint_XYZ.pth`. 

Why it is like that ? In most of the cases, if user stores `model`, `optimizer`, `lr_scheduler`, `engine` etc, than this is, IMO, to checkpoint the training. If user stores a single `model` than mostly it is to save the best model.

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 ,

Sorry maybe I didn't make the issue clear enough.
The problem is not the filename, it's about this line in CheckpointHandler:
```py
checkpoint = checkpoint[name]
```
It change the **dict** object to **value** if only 1 item existing.
And if use **to_save={'network': net}** to save and **use to_load={'network': net}** to load, it will fail.
Because it didn't save a dict with key "network" if only has this 1 item.
But if use **to_save={'network': net, 'optimizer', optim}** to save,
and use **to_load={'network': net}** to load, it works.
Thanks.

**Comment by vfdev-5** [comment]
@Nic-Ma thanks for the details. I understand better the problem. IMO, when saving a single object as dictionary seems a bit superficial. But I see your problem with loading method. Let me see if we can improve loading method to cover this case.

**Comment by Nic-Ma** [comment]
@vfdev-5 , Yes, we use your loader.

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 ,

I checked your patch, I think it will fail for below case:
1. Save network, optimizer, engine during training.
2. Only load network for inference(length of to_load is 1).
Right?
Thanks.

**Comment by vfdev-5** [comment]
Hi @Nic-Ma 

this case is covered too:
https://github.com/pytorch/ignite/blob/9973377c8dcc10f0745238dd6ccc69a8478428e1/ignite/handlers/checkpoint.py#L245-L250
method `to_load` loads directly state_dict if key (like "model") is not found in the checkpoint. Otherwise, it falls down into previous behaviour.

In your workflow "save checkpoints and load the last checkpoint" do you save the best model ?
If so why do you save also optimizer and engine ? For example, to resume training from the best model and train differently ?

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 ,

1. OK, got it.
2. to save model with engine together, then we can know the best model epoch, etc. when do evaluation.
Thanks.

**Comment by vfdev-5** [comment]
@Nic-Ma, I see. Another way to save trainers epoch can be done in the filename too.

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 ,

Can I save a filename with 2 dynamic items? Like:

'_checkpoint_best_metric=**0.9845**\_epoch=**23**.pth_'

Thanks.

**Comment by vfdev-5** [comment]
@Nic-Ma please take a look at the last example of https://pytorch.org/ignite/handlers.html#ignite.handlers.Checkpoint
```
> ["best_model_9_val_acc=0.77.pth", "best_model_10_val_acc=0.78.pth", ]
```

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 ,

Thanks for your tips.
I checked the example but not quite understand where to get the epoch number in your example:
best_model_**9**_val_acc=0.77.pth
I think the score function can only support "val_acc=0.77" in the example.
Thanks.

**Comment by vfdev-5** [comment]
Hi @Nic-Ma , here is a complete example
```python
import torch
from ignite.engine import Engine, Events
from ignite.handlers import Checkpoint, DiskSaver, global_step_from_engine

trainer = Engine(lambda e, b: None)
evaluator = Engine(lambda e, b: None)
data_loader = [1, 2, 3, 4, 5]

val_acc = [0.5, 0.6, 0.7, 0.8, 0.9]

@evaluator.on(Events.COMPLETED)
def setup_metrics(_):
    evaluator.state.metrics['accuracy'] = val_acc[trainer.state.epoch - 1]


@trainer.on(Events.EPOCH_COMPLETED)
def run_eval(_):
    evaluator.run([0, ])
    
def score_function(engine):
    return engine.state.metrics['accuracy']


model = torch.nn.Linear(1, 1)

to_save = {'model': model}
handler = Checkpoint(to_save, DiskSaver('/tmp/models', create_dir=True), n_saved=2,
                     filename_prefix='best', score_function=score_function, score_name="val_acc",
                     global_step_transform=global_step_from_engine(trainer))

evaluator.add_event_handler(Events.COMPLETED, handler)
trainer.run(data_loader, max_epochs=5)
```
```
ls /tmp/models

> best_model_4_val_acc=0.8000.pth best_model_5_val_acc=0.9000.pth
```

To make epoch appear, you need to set `global_step_transform=global_step_from_engine(trainer)`.

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 ,

Oh, I see.
Thanks for your detailed example.
It's very implicit to get the epoch number in the evaluator.
In my practice, I tried to set trainer's **state.epoch** to evaluator's **state.epoch**,
and set evaluator's **state.max_epoch = state.epoch + 1**.
Because it's needed **not only** in Checkpoint handler but also in my Stats handler, etc.
Anyway, thanks for your sharing.
