### ISSUE TITLE
Conda package not available for Python 3.8

### ISSUE THREAD

**Issue by fdlm** [pytorch/ignite#778]
The release notes indicate that ignite 0.3 supports Python 3.8. However, there is no ignite 0.3 package for Python 3.8 available in the conda pytorch channel:

```bash
$ conda search ignite -c pytorch
Loading channels: done
# Name                       Version           Build  Channel
ignite                         0.1.0          py27_0  pytorch
[...]
ignite                         0.3.0          py35_0  pytorch
ignite                         0.3.0          py36_0  pytorch
ignite                         0.3.0          py37_0  pytorch
```

## Environment

 - OS (e.g., Linux): Linux
 - Python version: 3.8
 - Any other relevant information: looks like the conda recipe does not list Python 3.8

**Comment by vfdev-5** [comment]
@fdlm thanks for this feedback :) 
Well, the release note does not clearly indicate that we deliver python 3.8 binary package and at the release moment there were no releases of pytorch for 3.8. 
However, I agree that we can now include it to our nightly releases and stable ones.
Now, you can install ignite from pypi for 3.8 as it is a universal package, most probably, it should work.
