### ISSUE TITLE
tqdm_logger does not take epoch_length into account

### ISSUE THREAD

**Issue by remisphere** [pytorch/ignite#782]
## 🐛 `tqdm_logger` does not take `epoch_length` into account

When calling `Engine.run()` with a custom `epoch_length`,
the tqdm progress bar does not adapt and displays the full number of batches in the data.
Here is a minimal example:
```python
from ignite.contrib.handlers.tqdm_logger import ProgressBar
from ignite.engine import Engine
from torch import nn
from torch.utils.data import DataLoader

data = list(range(100))
model = nn.Identity()
engine = Engine(lambda engine, batch: model(batch))

ProgressBar(persist=True).attach(engine)
engine.run(data, epoch_length=50)
```
We have 100 items in `data` but the true end of the epoch is at 50 iterations, yet the progress is displayed over the range of 100 and just ends midway, when I expect it to be displayed over the range of 50, thus ending when the bar is full.
One can not overwrite tqdm's `total` argument by replacing
```python
ProgressBar(persist=True).attach(engine)
```
by
```python
ProgressBar(persist=True, total=50).attach(engine)
```
for it raises `TypeError: type object got multiple values for keyword argument 'total'`.

## Environment
 - PyTorch Version : 1.4.0 
 - Ignite Version : 0.3.0
 - OS : Ubuntu 19.04
 - Ignite installation method : `pip`
 - Python version: 3.7.3

**Comment by vfdev-5** [comment]
@remisphere thanks for the feedback! We need to fix it here:  
https://github.com/pytorch/ignite/blob/0f97baff7f718f2917421774e2daf7819561c047/ignite/contrib/handlers/tqdm_logger.py#L220-L221
as 
```python
return engine.state.epoch_length
```
