### ISSUE TITLE
Inconsistency when checkpointing a single object

### ISSUE THREAD

**Issue by WeirdKeksButtonK** [pytorch/ignite#789]
Hi! Let's consider the following code:
```python
handler = ModelCheckpoint('.', 'best', score_function=get_score)
checkpoint_objects = {'model': model, 'optimizer': optimizer}
evaluator.add_event_handler(
    Events.COMPLETED, handler, checkpoint_objects
)
...
ModelCheckpoint.load_objects(
    checkpoint_objects, torch.load(handler.last_checkpoint)
)
```
The problem occurs when I change the line
```python
checkpoint_objects = {'model': model, 'optimizer': optimizer}
```
to this:
```python
checkpoint_objects = {'model': model}
```
The cause of the problem is [this](https://github.com/pytorch/ignite/blob/fceb3d7ddfed1558841b880e8cd7decf7a4be924/ignite/handlers/checkpoint.py#L209).

Is it really useful to handle single-object checkpoints in some special way? I think it is rather inconvenient that my code *by default* depends on the size of the `checkpoint_objects` variable. If I ever need to have an "unpacked" checkpoint that represents exclusively the weights of my model, I can always perform the conversion by myself.

P.S. The 0.3 release is super cool, thank you!

**Comment by vfdev-5** [comment]
@WeirdKeksButtonK thanks for your feedback !
This is issue seems like to be related to https://github.com/pytorch/ignite/issues/770
and should be fixed in the master. You can use our nightly build releases with pypi or conda: https://github.com/pytorch/ignite#nightly-releases

**Comment by WeirdKeksButtonK** [comment]
Well, it solves the problem, although I don't understand why instead of removing a special case from the method `__call__`, a new special case was added in the method `load_objects` :smiley:
Moreover, it can lead to strange errors (namely, when some key in this single object's state will be the same as the only key in the `to_load` variable). So I still believe that processing all cases in the same way would be a better approach. Anyway, thank you for the answer.

**Comment by vfdev-5** [comment]
The reason for that is rather simple. In most of the cases, if user wants to checkpoint the training, he/she needs to store: model(s), optimizer(s), lr_scheduler(s), trainer, ... => dictionary of state_dicts. If he/she would like to save the best model or models, IMO it does not make sense to save either everything in a single dict (you can imagine that you can need only one model, but you should store both). If it is a single best model to save, why to wrap it in a dictionary, especially if you would like to put into then kind of "production" and just load it with `sd = torch.load(fp)` and `model.load_state_dict(sd)`. Yes, if it stored as a dict, it would be also rather simple as `model.load_state_dict(sd['model'])`, but IMO this does look nice...

**Comment by vfdev-5** [comment]
Closed the issue as answered. Feel free to reopen if needed
