### ISSUE TITLE
CONTRIBUTING questions

### ISSUE THREAD

**Issue by jasonkriss** [pytorch/ignite#79]
@alykhantejani before we start merging a bunch of new features, how do you feel about adding a CONTRIBUTING.md doc that spells things out a lil bit more? The main thing I care about right now is settling on a docstring format. I think you said you were okay with going with the google style (ala pytorch) but it'd be nice to get that down somewhere. I can then go back and update the existing docstrings.

**Comment by alykhantejani** [comment]
Hi @jasonkriss, this sounds like a good idea. Would you be able to send a PR with a draft outlining what you think should go in there?

**Comment by jasonkriss** [comment]
For sure. Putting something together now.
