### ISSUE TITLE
Add example notebooks to Google Colab

### ISSUE THREAD

**Issue by ykumards** [pytorch/ignite#797]
Similar to Pytorch [examples](https://pytorch.org/tutorials/), we should try to port most of the ignite examples (at least all the notebooks) to be runnable in Google Colab. This way it becomes more accessible to new users.

We could add an [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb) badge next to the links to notebooks in the Readme as described [here](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb).

**Comment by vfdev-5** [comment]
Totally agree with this !
