### ISSUE TITLE
argument `metrics` in method `create_supervised_trainer` ?

### ISSUE THREAD

**Issue by sdesrozis** [pytorch/ignite#823]
## ❓ Questions/Help/Support

To define evaluators using helper `create_supervised_evaluator`, metrics can be added for attachment to engine :
```python
  metrics = {
    'accuracy': Accuracy(),
    'nll': Loss(loss_fn=loss_fn),
  }

  evaluator = create_supervised_evaluator(model=model, metrics=metrics)
```
Using helper `create_supervised_trainer`, metrics have to be added by hand :
```python
  trainer = create_supervised_trainer(model=model, optimizer=optimizer, loss_fn=loss_fn)

  RunningAverage(output_transform=lambda x: x).attach(trainer, 'loss')
```
What do you think about add argument `metrics` in method `create_supervised_trainer` ?

**Comment by vfdev-5** [comment]
@sdesrozis it depends on what kind of metrics you would like to add. For `RunningAverage` it is OK. For others it was discussed several times previously, for example
- https://github.com/pytorch/ignite/pull/165
- https://pytorch.org/ignite/quickstart.html#id1 (footnote)

**Comment by sdesrozis** [comment]
@vfdev-5 Perfect. I didn't see the footnote. Adding `RunningAverage` in common helper makes sense in accordance with the footnote.
Thanks for your help.

**Comment by sdesrozis** [comment]
Sorry, I reopen :(

It seems that `create_supervised_trainer` with default `output_transform` is not compatible with `setup_common_training_handlers` and `output_names` :
```python
trainer = create_supervised_trainer(...)  
setup_common_training_handlers(trainer=trainer, output_names=['loss'])
```
is ko because default `output_transform` :
```python
output_transform: Callable = lambda x, y, y_pred, loss: loss.item()
```
To fix with API : 
```python
trainer = create_supervised_trainer(..., output_transform=lambda x, y, y_pred, loss: loss)
```
A better fix could be done in `common.py` line 125 letting `output_transform` dealing with numbers (in the same way as the tensors).

**Comment by vfdev-5** [comment]
Thanks for catching that! Could you please send a PR to fix this? And maybe we can also update the docs...

**Comment by sdesrozis** [comment]
Sure.
