### ISSUE TITLE
model is moved too early in create_supervised_trainer/evaluator

### ISSUE THREAD

**Issue by kai-tub** [pytorch/ignite#830]
Hi, first of all, thanks for the great library!
I have a general "bug" report or question on the specific implementation of `create_supervised_trainer` and `create_supervised_evaluator`.
As seen for example here:
https://github.com/pytorch/ignite/blob/master/ignite/engine/__init__.py#L64

The moment a supervised evaluator/trainer is created the model is moved to the specific device and 
*not* during the inference stage.

I agree, that this version doesn't have an impact in general, but I would argue that the model should be moved in the `_inference` function and not when I create the evaluator/trainer.
A weird example but similar to my case:
I have multiple evaluators and I would like to run one on the CPU and one on the GPU.
The reason being that a different library doesn't support GPUs yet and I would like to add it in an "ignite" style to keep the code similar.
Now, the run steps will not work, as the model is *not* moved again in the inference stage.

I can imagine that there is a reason why it is the way it is, but I am wondering if a future version couldn't do the `model.to(device)` step in the `_inference` function. :)

Thanks!

**Comment by vfdev-5** [comment]
@kai-tub thanks for awesome feedback and thanks for your remark ! I understand that this could be done in a more lazy way, for example, when engine is started (probably, calling `model.to` every iteration I think can have some performance impact.) 
Definitely, `create_supervised_*` can setup model's device in a handler:
```python
def create_supervised_trainer(
    model: torch.nn.Module,
    optimizer: torch.optim.Optimizer,
    loss_fn: Union[Callable, torch.nn.Module],
    device: Optional[Union[str, torch.device]] = None,
    non_blocking: bool = False,
    prepare_batch: Callable = _prepare_batch,
    output_transform: Callable = lambda x, y, y_pred, loss: loss.item(),
) -> Engine:

    def _update(engine: Engine, batch: Sequence[torch.Tensor]) -> Union[Any, Tuple[torch.Tensor]]:
        model.train()
        optimizer.zero_grad()
        x, y = prepare_batch(batch, device=device, non_blocking=non_blocking)
        y_pred = model(x)
        loss = loss_fn(y_pred, y)
        loss.backward()
        optimizer.step()
        return output_transform(x, y, y_pred, loss)

    trainer = Engine(_update)

    if device:
         @trainer.on(Events.STARTED)
         def setup_device(_):
              model.to(device)

    return trainer
```

In this way, certainly we can alternate for example, training on GPU and validating on CPU etc.

@justusschock @ykumards any thoughts ?

**Comment by kai-tub** [comment]
This looks great!
I don't see why this shouldn't be adapted (or are there different parts of the library that work similarly?)

And thanks for the quick reply. :)

**Comment by vfdev-5** [comment]
@kai-tub main reason for that I would say that there were no particular need to switch devices like that. For example, if we use DDP wrapper for model, we train and evaluate within the same context. And another point is that `create_supervised*` are just basic helpers, personnally I setup by myself the update function etc.

**Comment by justusschock** [comment]
I would rather move the model more often. This way the user is more flexible and also these calls become no-ops in PyTorch, when the model is already on the correct device

**Comment by kai-tub** [comment]
@vfdev-5 I agree that setting up the update function is the obvious alternative (and is what I've done).
But for someone who never used PyTorch half a year ago, I really liked to use ignite to learn Pytorch in a "top-down" fashion. I could focus more on the design of the workflow and less on the actual implementation. Afterwards I looked at the underlying implementation to understand how it works.  Plus I think that the best code is the code that was never written. 

I think that most cases are solved by `create_supervised*` and would be more applicable when the moving process is moved after the function initialization. :)

**Comment by kai-tub** [comment]
Since this is labeled as "help wanted" should I issue a PR with the changes mentioned by @justusschock?

**Comment by vfdev-5** [comment]
yes, please

**Comment by vfdev-5** [comment]
A follow up on this. There can be a potential issue of the #835 when we reload state dicts from a checkpoint:
```python
import torch
import torch.nn as nn
from torch.optim import SGD

# Create a checkpoint:
model = nn.Linear(1, 1)
opt = SGD(model.parameters(), lr=0.01, momentum=True)

t = torch.rand(1, 1).to("cuda")
model.to("cuda")

opt.zero_grad()
y = model(t)
y.sum().backward()
opt.step()

to_save = {"model": model.state_dict(), "opt": opt.state_dict()}
torch.save(to_save, "/tmp/chk.pt")

# Reload and reproduce the bug:
model = nn.Linear(1, 1)
opt = SGD(model.parameters(), lr=0.01, momentum=True)
loaded_objs = torch.load("/tmp/chk.pt")

# load on CPU
model.load_state_dict(loaded_objs["model"])
opt.load_state_dict(loaded_objs["opt"])

model.to("cuda")
params = opt.param_groups[0]['params']
print(opt.state[params[0]]['momentum_buffer'].device)

t = torch.rand(1, 1).to("cuda")
opt.zero_grad()
y = model(t)
y.sum().backward()
opt.step()
```

This is almost exactly the save what happens with delayed model move to device in `create_supervised_trainer`.

**Comment by kai-tub** [comment]
I don't know if I understand your point.
The user wants to run a training procedure with an optimizer.
So following the note from PyTorch's optimizer section:
https://pytorch.org/docs/stable/optim.html#constructing-it
The user should first move the model to the wanted device and then construct the optimizer. So wouldn't this be wrong user behavior? Although most optimizers are still working, this will change in the future:
https://github.com/pytorch/pytorch/issues/7844#issuecomment-503713840

My initial motivation for why I wanted the delayed model move was because I wanted an evaluator with a model on the GPU and one on the CPU (but I know that was a weird corner case).  So going back to the reload issue, if the user moves the model before creating the optimizer then there shouldn't be an issue.

What am I missing?

**Comment by vfdev-5** [comment]
@kai-tub thanks for the links, so according to the docs and the comment. Seems like it does not make sense at all to send model to a device in `create_supervised_trainer` while optimizer is already defined.

Concerning your use-case:
> I wanted an evaluator with a model on the GPU and one on the CPU (but I know that was a weird corner case)

How did your model get back to GPU for the training ? And according to the docs, probably, it can cause an issue with the optimizer as model's params got back on GPU may not be the same as in the optimizer...

**Comment by kai-tub** [comment]
> Seems like it does not make sense at all to send model to a device in create_supervised_trainer while optimizer is already defined.

Yes, seems like it would be better to not move the model in `trainer`.

> Concerning your use-case:

In my case, I only used these evaluators after the training procedure.
So there was no need to move the model back in-between steps.
But I initialized both at the same time and that is how I saw the "bug". 

I don't see a good way how we could still move the model in the function.
Right now, I would favor removing the model moving process and updating the docs.

But I can imagine that a lot of code uses this behavior to save one line of moving the model before initializing the optimizer.
What is your opinion of trying to catch an error due to different devices and adding more details to the exception? Or should the docs suffice? Or do you want to add a deprecation warning?

Do you have an alternative approach?
