### ISSUE TITLE
Update mnist example

### ISSUE THREAD

**Issue by jgbradley1** [pytorch/ignite#831]
## 🚀 Feature

Please update the mnist [example](https://github.com/pytorch/ignite/tree/master/examples/mnist) `mnist_with_tensorboardx.py`. Rather than depend on an external library (tensorboardX), it would be nice to have an example that utilizes the [built-in](https://pytorch.org/docs/stable/tensorboard.html) version of PyTorch.

**Comment by justusschock** [comment]
Yes, that's true, but unfortunately this would limit the users to a certain PyTorch version. But we can use a conditional import there and first check, whether the PyTorch version will be recent enough.

**Comment by sdesrozis** [comment]
@justusschock you mean something in the idea of what is done in `tensorboard_logger.py` ?
https://github.com/pytorch/ignite/blob/587644fa7ff506323b58a62e4399d798c76b9ce5/ignite/contrib/handlers/tensorboard_logger.py#L446-L456
