### ISSUE TITLE
How to set a new dataloader during training?

### ISSUE THREAD

**Issue by WeirdKeksButtonK** [pytorch/ignite#833]
## 🚀 Feature

Sometimes I want to replace my engine's dataloader with a new one during training. For example, it happens when I want to change a batch size or even change batch sampling strategy. Earlier, I used to change the field `engine.state.dataloader`, but it doesn't look correct, because there are some fields like `_dataloader_len` or `_dataloader_iter` that may need some adjustment as well.

Am I right about incorrectness of patching `engine.state.dataloader`? Is it possible to add something like `Engine.set_dataloader`?

**Comment by vfdev-5** [comment]
@WeirdKeksButtonK thanks for the feedback! Yes, in the current version it would be a bit tricky to replace the dataloader just by replacing engine.state.dataloader. There are some other issue with the current implementation that we need to fix up. 
The most "proper" way (hack?) currently to replace the dataflow is to provide a dummy list to `run(data)`:
`data=list(range(total_num_iterations))` and set batch as required by your logic:
```python

dataloader = ...
next_dataloader = ...

def cycle(dataloader):
        while True:
            for i in dataloader:
                yield i

dataloader_iter = cycle(dataloader)

def udate_fn(engine, _):
    batch = next(dataloader_iter)
    ...

trainer = Engine(update_fn)

@trainer.on(Events.EPOCH_STARTED(once=50))
def switch_dataloader(_):
    dataloader_iter = cycle(next_dataloader)

data = list(range(len(dataloader) * num_epochs))
trainer.run(data, max_epochs=num_epochs)
```

HTH

**Comment by WeirdKeksButtonK** [comment]
@vfdev-5 thanks for the idea.
Indeed, it will be more convenient if updating the dataloader is supported natively.

And here is a version without dummy data:
```python
def _cycle(iterable):
    while True:
        for x in iterable:
            yield x


class DataLoaderBox:
    def __init__(self, dataloader):
        self.set_dataloader(dataloader)

    def __iter__(self):
        return self

    def __next__(self):
        return next(self._iter)

    def set_dataloader(self, dataloader):
        self._iter = _cycle(dataloader)


def update_fn(engine, batch):
    ...


dataloader = ...
next_dataloader = ...

trainer = Engine(update_fn)

@trainer.on(Events.EPOCH_STARTED(once=50))
def switch_dataloader(engine):
    engine.state.dataloader.set_dataloader(next_dataloader)

trainer.run(DataLoaderBox(dataloader), max_epochs=num_epochs)
```

It has its own drawbacks, but one may find it sufficient.
