### ISSUE TITLE
Move FastaiLRFinder_MNIST.ipynb to examples/notebook

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#836]
## 🚀 Feature

It would be better to move FastaiLRFinder_MNIST.ipynb notebook to principal notebooks location. All those notebook already use contrib module, so there is no need to keep `examples/contrib/notebooks`

Additionally, we need to create a link colab and insert it into README.md

**Comment by mkartik** [comment]
Hi @vfdev-5 , I would like to contribute to this enhancement.

**Comment by vfdev-5** [comment]
Hi @mkartik sounds good ! Please go ahead with a PR. Feel free to ask questions if any.
