### ISSUE TITLE
Timer Exception: "reset() takes 1 positional argument but 2 were given"

### ISSUE THREAD

**Issue by pkdogcom** [pytorch/ignite#84]
I've just checked out the new timer handler and attached it to the trainer engine following the example. However, the above exception is produced when the engine fires the triggering event (which is EPOCH_STARTED in the example). 

After looking into the codes I guess the problem is that in the `_fire_event` method of engine it calls the handler method by passing the engine instance as argument:
```
func(self, *(event_args + args), **kwargs)
```
which leads to two arguments when calling Timer bound methods like reset as 
```reset(timer_instance, trainer_instance)``` and hence the above exception.

**Comment by alykhantejani** [comment]
Thanks for reporitng - will take a look now

**Comment by alykhantejani** [comment]
This is now fixed in master
