### ISSUE TITLE
When will version 0.4.0 be available on PyPi?

### ISSUE THREAD

**Issue by snie2012** [pytorch/ignite#841]

**Comment by vfdev-5** [comment]
This is a good question, we have the roadmap of issues to close here : https://github.com/pytorch/ignite/projects/7 before going to 0.4.0
Probably, engine's behaviour in 0.4.X will be changed vs 0.3.X. Thus we need to test and check a lot.

Meanwhile, we have nightly releases available on PyPi and conda:
```bash
pip install --pre --upgrade pytorch-ignite
```

**Comment by snie2012** [comment]
@vfdev-5 How about smaller versions like 0.3.1 and so on? Would like to have them on PyPi

**Comment by vfdev-5** [comment]
@snie2012 I see, but now in master we have several BC breaking changes such that 0.3.1 is not backward compatible with 0.3.0

**Comment by vfdev-5** [comment]
Here is v0.4.0 release: https://github.com/pytorch/ignite/releases/tag/v0.4.0.post1
I close the issue as solved. For other questions, please, open a new issue. Thanks
