### ISSUE TITLE
Typehint of ignite._utils._to_hours_mins_secs  not satisfied with float

### ISSUE THREAD

**Issue by sdesrozis** [pytorch/ignite#842]
## 🐛 Bug description

That is a so tiny bug. The `typehint` of the following function of `ignite._utils` is not satisfied with a `float` argument
``` python
def _to_hours_mins_secs(time_taken: Union[float, int]) -> Tuple[int, int, int]:
    """Convert seconds to hours, mins, and seconds."""
    mins, secs = divmod(time_taken, 60)
    hours, mins = divmod(mins, 60)
    return hours, mins, secs
```
We have
```python
>>> divmod(10.0,2)
(5.0, 0.0)
```

## Environment

 - PyTorch Version (e.g., 1.4): 1.4
 - Ignite Version (e.g., 0.3.0): 0.3.0
 - OS (e.g., Linux): Linux
 - How you installed Ignite (`conda`, `pip`, source): conda
 - Python version: 3.7
 - Any other relevant information:

**Comment by vfdev-5** [comment]
@sdesrozis please send a PR to fix it :) I think there could be others like that. I think typing issue is not completely done.
