### ISSUE TITLE
Multiple ProgressBars Spamming

### ISSUE THREAD

**Issue by bendboaz** [pytorch/ignite#852]
## 🐛 Bug description
When using the ProgressBar handler for both my train and my evaluation engine
`train_pbar = ProgressBar()
train_pbar.attach(train_engine)
eval_pbar = ProgressBar(desc="Evaluation")
eval_pbar.attach(eval_engine)`

Or even when using common.setup_common_training_handlers from contrib.engines:
`common.setup_common_training_handlers(train_engine, to_save=to_save, save_every_iters=saving_rate, output_path=output_path, lr_scheduler=lr_scheduler, with_pbars=True, with_pbar_on_iters=True, log_every_iters=1, device=device)`

The progress bars print a new line for every increment of the calculation (every iteration). My engines have some other handlers on both engines (early stopping handlers, some custom logging etc.), but there's no printing that's causing the error. It looks like so (for the second example, with setup_common_training_handlers):
`Epoch [1/10]: [504/6367]   8%|▊          [12:59<2:31:09]`
`Epoch [1/10]: [504/6367]   8%|▊          [13:00<2:31:09]`
`Epoch [1/10]: [505/6367]   8%|▊          [13:00<2:30:59]`
`Epoch [1/10]: [505/6367]   8%|▊          [13:02<2:30:59]`
`Epoch [1/10]: [506/6367]   8%|▊          [13:02<2:30:54]`
`Epoch [1/10]: [506/6367]   8%|▊          [13:03<2:30:54]`
`Epoch [1/10]: [507/6367]   8%|▊          [13:03<2:30:54]`
`Epoch [1/10]: [507/6367]   8%|▊          [13:05<2:30:54]`
`Epoch [1/10]: [508/6367]   8%|▊          [13:05<2:31:07]`

Is there any common cause to this? My code is inspired from the example [here](https://github.com/pytorch/ignite/issues/708#issuecomment-576360519).
The trainer is created with create_supervised_trainer and the evaluator with create_supervised_evaluator.

## Environment

 - PyTorch Version 1.4
 - Ignite Version 0.3.0
 - OS: Windows 10.0.18363 build 18363
 - Ignite installed using conda
 - Python version: 3.7.6

**Comment by vfdev-5** [comment]
@bendboaz seems like it's tqdm issue ? What is your version of tqdm ? Are you launching the code as a script or in a notebook ?

As a last resort, to avoid too much lines you can set `log_every_iters=100` and have tqdm logging every 100 iterations ...

**Comment by bendboaz** [comment]
@vfdev-5 my tqdm version is 4.42.1, I'll try and link this issue there as well (though it seems like a question for whoever implemented the ProgressBar class). The script is running in PyCharm (output goes to the PyCharm console), so tqdm_notebook doesn't seem relevant here. Thanks for the quick answer!

**Comment by vfdev-5** [comment]
@bendboaz I think your issue is related to PyCharm console. Here is a snippet executed in jupyter notebook and in a terminal.

```python
import ignite
print(ignite.__version__)

import tqdm
print(tqdm.__version__)

import time
from ignite.engine import Engine, Events
from ignite.contrib.handlers import ProgressBar


trainer = Engine(lambda e, b: time.sleep(0.1))
evaluator = Engine(lambda e, b: time.sleep(0.1))


ProgressBar(desc="Training", persist=True).attach(trainer)
ProgressBar(desc="Evaluation").attach(evaluator)

@trainer.on(Events.EPOCH_COMPLETED)
def run_eval(_):
    eval_data = list(range(20))
    evaluator.run(data)
    
    
data = list(range(50))
trainer.run(data, max_epochs=5)
```

<img width="1088" alt="Screen Shot 2020-03-26 at 19 07 05" src="https://user-images.githubusercontent.com/2459423/77681141-3ea48100-6f95-11ea-8c62-0200045b6ffb.png">
<img width="502" alt="Screen Shot 2020-03-26 at 19 03 28" src="https://user-images.githubusercontent.com/2459423/77681144-3fd5ae00-6f95-11ea-8f4a-591e64f642b4.png">

**Comment by VinhLoiIT** [comment]
I get this error as well, this is due to the tqdm module [issue](https://github.com/tqdm/tqdm/issues/630). Do you open tqdm in a small terminal? *small* means its width does not large enough to print the full line.

**Comment by bendboaz** [comment]
@VinhLoiIT On the contrary, my terminal is almost double the size of the bar. I think it's a PyCharm issue like @vfdev-5 mentioned, installing WSL stuff to check it on a normal terminal right now.

**Comment by vfdev-5** [comment]
As it is not related directly to this library, @bendboaz can we close the issue ?

**Comment by bendboaz** [comment]
@vfdev-5 definitely, thank you.

**Comment by ismael-elatifi** [comment]
To avoid having tqdm printing each new iteration on a new line, use this class instead :

from ignite.contrib.handlers.tqdm_logger import ProgressBar

class ProgressBarCustom(ProgressBar):
    """To force tqdm to overwrite previous line"""

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        from tqdm import tqdm as tqdm_base

        def tqdm_custom(*args, **kwargs):
            if hasattr(tqdm_base, '_instances'):
                for instance in list(tqdm_base._instances):
                    tqdm_base._decr_instances(instance)
            return tqdm_base(*args, **kwargs)

        self.pbar_cls = tqdm_custom

ProgressBarCustom(persist=False, desc="Training").attach(self.trainer)
ProgressBarCustom(persist=False, desc="Validation").attach(self.evaluator)
