### ISSUE TITLE
fixture 'worker_id' not found

### ISSUE THREAD

**Issue by aeklant** [pytorch/ignite#863]
## ❓ Questions/Help/Support

Hello all,

I'm new to the community. Been using pytorch for a few months and recently started using ignite for some projects and I would like to contribute.

I followed the instructions in the contributing guidelines but when I ran the tests with `pytest -vvv tests` all the ones marked as `distributed` (e.g. `tests/ignite/engine/test_engine.py::test_distrib_cpu`) fail due to what seems to be a missing fixture called '**worker_id**'. I went into the `conftest.py` file and indeed, I could not find a definition for it (even though it is being passed to another fixture `local_rank`, which is where the exception is being thrown).

``` ____________________________________________________________ ERROR at setup of test_distrib_cpu _____________________________________________________________
file /home/abraham/ignite-dev/ignite/tests/ignite/metrics/test_top_k_categorical_accuracy.py, line 110
  @pytest.mark.distributed
  def test_distrib_cpu(local_rank, distributed_context_single_node_gloo):
file /home/abraham/ignite-dev/ignite/tests/ignite/conftest.py, line 17
  @pytest.fixture()
  def local_rank(worker_id):
E       fixture 'worker_id' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, dirname, distributed_context_multi_node_gloo, distributed_context_multi_node_nccl, distributed_context_single_node_gloo, distributed_context_single_node_nccl, doctest_namespace, local_rank, monkeypatch, multi_node_conf, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```

I'm a bit confused as to how I can fix this. I went and looked at some PR that was recently merged and looked at the TravisCI report and those tests obviously pass, so I'm not quite sure what the issue might be.

Hoping someone can shed light into it for me since I'm sort of stuck at the moment.

Thanks in advance.

**Comment by vfdev-5** [comment]
Hi @aeklant, thanks for you interest to Ignite and willing to contribute 👍 

Distributed CPU tests are launched with `pytest-xdist` package like that
https://github.com/pytorch/ignite/blob/1cb8d0f78e9d4651cb55f96895e1c4ab85392903/.travis.yml#L85-L86

The last line starts 2 workers and thus `local_rank` variable appears.

If you have any other questions, do not hesitate to ask :)
What kind of contribution, I think of ?

**Comment by aeklant** [comment]
Hi @vfdev-5, 

It looks like that `pytest-xdist` dependency is exactly what I was missing. I managed to run the distributed cpu tests now as you described and they pass. `pytest tests/ -vvv` as described in the contributing guidelines works as well. 

Regarding contributions, I don't have something specific in mind but I have been looking at some of the open issues labeled with 'needs-help' and I think I can be of assistance in some of them. If you have suggestions or if there is a topic where having an extra set of coding hands could benefit the project most, feel free to let me know.

**Comment by vfdev-5** [comment]
> Regarding contributions, I don't have something specific in mind but I have been looking at some of the open issues labeled with 'needs-help' and I think I can be of assistance in some of them. If you have suggestions or if there is a topic where having an extra set of coding hands could benefit the project most, feel free to let me know.

@aeklant sounds good ! How about to start with this issue : 
- https://github.com/pytorch/ignite/issues/865  
   - this one is not technically complicated, should be rather similar to MLflow logger or similar ones.
- https://github.com/pytorch/ignite/issues/784
  - this is a simple fix, but we need to write a bit more of tests
- https://github.com/pytorch/ignite/issues/750
  - there is a PR on that, but I'm not happy with it and the person who sent it, probably, wont continue on that.

If you can take a look on them, it would be awesome !
And if by chance you are at PyTorch Slack, we can speak in #pytorch-ignite channel. 
https://github.com/pytorch/ignite#communication
