### ISSUE TITLE
Better typing for Engine

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#870]
## 🚀 Feature

Improve typing of Engine module, especially for `event_name`.
Currently, it is specified as `str`, but actually can be anything if registered:
```python
from ignite.engine.events import Events
from ignite.engine import Engine

e = Engine(lambda e, b: None)

class A: pass
a = A()

e.register_events("up", "down")
e.register_events(1, 2, 3)
e.register_events(a)

print(e._allowed_events)
e.add_event_handler("up", lambda e: print("up"))
e.add_event_handler(1, lambda e: print("1"))
e.add_event_handler(a, lambda e: print("a"))

e.fire_event("up")
e.fire_event(1)
e.fire_event(a)
```

Let's discuss here if we would like to restrict `event_type` to some subset of types or leave as any type.

@sdesrozis, @ykumards 
cc @kai-tub as you said you were big fan of typing

**Comment by sdesrozis** [comment]
First step, type `Any` should be better than nothing.

**Comment by sdesrozis** [comment]
I suggest to use `Any` rather than `str` (and used with `int`,  etc.)

@vfdev-5 @kai-tub @ykumards  ??

**Comment by vfdev-5** [comment]
@sdesrozis go ahead with a PR, please
