### ISSUE TITLE
Make epoch_length optional

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#871]
## 🚀 Feature

Following discussions and the message: https://github.com/pytorch/ignite/issues/853#issuecomment-606732951 it could be useful to make `epoch_length` optional for finite iterators.

**Comment by snie2012** [comment]
@vfdev-5 thanks for opening this issue. I'll be following on the progress. It's currently a blocker for me to move to 0.4.0. Once this is added, I can migrate.

**Comment by snie2012** [comment]
Any update on this?

**Comment by vfdev-5** [comment]
@snie2012 this is currently blocked by https://github.com/pytorch/ignite/pull/895

Once it is merged I can try integrate this option `epoch_lenght=None` for iterators and ensure that all tests are passing.

**Comment by snie2012** [comment]
@vfdev-5 Thanks for the quick response. Looking forward to the upcoming updates!
