### ISSUE TITLE
Initialize engine.state before calling run

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#880]
## 🚀 Feature

Idea is to improve flexibility of Engine and simplify user code by initializing `engine.state` before calling `run`.

What we gain:
```python
trainer = Engine(...)
trainer.state.alpha = 0.0
trainer.state.beta = 1.0
```

**Comment by sdesrozis** [comment]
Ok so, `state` should be allocated (and not `None`) in `__init__`, maybe with some initial values. Then, `state` is reset when `run` is called. Did I catch the meaning of this issue ?

**Comment by sdesrozis** [comment]
It means 
```
self.state = State(seed=seed, iteration=0, epoch=0, max_epochs=max_epochs, epoch_length=epoch_length)
```
should be replaced by an update :
```
self.state.update(seed=seed, iteration=0, epoch=0, max_epochs=max_epochs, epoch_length=epoch_length)
```
Indeed `self.state` should keep values set by users.

Is it ok?

**Comment by sdesrozis** [comment]
@vfdev-5 @ykumards ?

**Comment by vfdev-5** [comment]
> It means
> 
> ```
> self.state = State(seed=seed, iteration=0, epoch=0, max_epochs=max_epochs, epoch_length=epoch_length)
> ```
> 
> should be replaced by an update :
> 
> ```
> self.state.update(seed=seed, iteration=0, epoch=0, max_epochs=max_epochs, epoch_length=epoch_length)
> ```
> 
> Indeed `self.state` should keep values set by users.
> 
> Is it ok?

@sdesrozis maybe it wont be only that. We need to ensure that Engine follows well the requirements (https://github.com/pytorch/ignite/pull/640#issue-325080815) : 
```
    - At the first call, new state is defined by `max_epochs`, `epoch_length`, `seed` if provided.
    - If state is already defined such that there are iterations to run until `max_epochs` and no input arguments
        provided, state is kept and used in the function.
    - If state is defined and engine is "done" (no iterations to run until `max_epochs`), a new state is defined.
    - If state is defined, engine is NOT "done", then input arguments if provided override defined state.
```
It is sort of partial initialization such that state is defined for flexibility, but it has some additional field to satisfy above requirements.
