### ISSUE TITLE
utils.convert_tensor considers `device = 0` to be no device

### ISSUE THREAD

**Issue by bendboaz** [pytorch/ignite#886]
## 🐛 Bug description
In utils.convert_tensor, this line appears:
`return tensor.to(device=device, non_blocking=non_blocking) if device else tensor`

This means that for `device = 0` (as returned from `torch.cuda.current_device`) no conversion is applied, which can be very confusing. I might add a PR for that tomorrow, unless people tell me there's a reason to leave that line as it is.

For reproduction:
```python
import torch
from ignite.utils import convert_tensor

mytens = torch.zeros(2)
device = torch.cuda.current_device()
converted_tens = convert_tensor(mytens, device)
assert converted_tens.device == device
```

## Environment

 - PyTorch Version (e.g., 1.4): 1.4
 - Ignite Version (e.g., 0.3.0): 0.3
 - OS (e.g., Linux): Windows 10
 - How you installed Ignite (`conda`, `pip`, source): conda
 - Python version: 3.7.6

**Comment by vfdev-5** [comment]
Thanks for the report @bendboaz ! Yes, please send a PR to fix that with `if device is not None`
