### ISSUE TITLE
Mistake in MLflow logger documentation

### ISSUE THREAD

**Issue by Muhamob** [pytorch/ignite#898]
MLflow log_params(params: dict) method accept dict, not arguments.

https://github.com/pytorch/ignite/blob/4b311cc82fe45b3082661125cd7ee54007283fb0/ignite/contrib/handlers/mlflow_logger.py#L202

**Comment by vfdev-5** [comment]
Yes, you are right. I fixed this in the examples but forgot about the docs. If you would like to contribute, please feel free to send a PR with removing `**`. Otherwise, I can do this.

**Comment by Muhamob** [comment]
Yes, I can send PR
