### ISSUE TITLE
Host sphinx docs

### ISSUE THREAD

**Issue by alykhantejani** [pytorch/ignite#9]

**Comment by alykhantejani** [comment]
We should also figure out hosting of these

**Comment by alykhantejani** [comment]
@vfdev-5 @jasonkriss I think I know which pytorch repo to make this change in and will try to do it this week. Once this is done I will build conda tars + wheels, unless you guys think there's anything left that needs to get in before 0.1?

**Comment by alykhantejani** [comment]
submitted PR to pytorch/builder here: https://github.com/pytorch/builder/pull/48

**Comment by vfdev-5** [comment]
@alykhantejani sounds good! Today we have just GAN example with label 0.1.0 and under WIP.

**Comment by jasonkriss** [comment]
@alykhantejani I think we're ready! Sounds great.

**Comment by vfdev-5** [comment]
Docs are hosted [here](https://pytorch.org/ignite/)
