### ISSUE TITLE
Avoid moving model to device in create_supervised* 

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#902]
## 🚀 Feature

As discussed [here](https://github.com/pytorch/ignite/issues/830#issuecomment-611041703) and previous messages, according to pytorch docs on model and optimizer. User should not move model to another device after constructing an optimizer for the model: 
- https://pytorch.org/docs/stable/optim.html#constructing-it
- https://github.com/pytorch/pytorch/issues/7844#issuecomment-503713840

We need to handle this in the code:
- remove the code that moves the model to device.
- update the docstring and add a warning note on changed behaviour, cite pytorch docs.
- update all basic examples : mnist etc who currently use unwanted behaviour.

cc @kai-tub

**Comment by kai-tub** [comment]
Hi, I would like to work on this and complete the work I've started. :)
When this issue is closed I will come back to my `tiny_benchmark_wrapper`.

**Comment by vfdev-5** [comment]
@kai-tub sounds good, thanks !

**Comment by kai-tub** [comment]
One quick question, what do you mean by:
> ... add a warning note on changed behavior

Is a normal `Note:` environment in the docstrings sufficient? Or do you mean warning from `import warnings`?

**Comment by vfdev-5** [comment]
Good question, I mean this
```
.. warning::
    
     Be careful
```
which is rendered as here: https://pytorch.org/ignite/metrics.html#ignite.metrics.EpochMetric
