### ISSUE TITLE
Add examples to GPU CI

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#903]
## 🚀 Feature

Task is to setup examples smoke tests on single GPU CI.
Examples are run on Github CI : 
- https://github.com/pytorch/ignite/blob/master/.github/workflows/unittests.yml#L51
we need to be able to run them on GPU to ensure correct behaviour.

cc @ykumards @sdesrozis

**Comment by sdesrozis** [comment]
How to test a configuration in CircleCI ? I think there is a better way than submit a PR, isn't it ? :)

**Comment by vfdev-5** [comment]
@sdesrozis you can push into pytorch/ignite branch (GPU CI tests will be launched) and then PR.

**Comment by sdesrozis** [comment]
CI is enabled on PR and push actions on every branches ? Or should I push into master ?
