### ISSUE TITLE
Improve project's information

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#907]
We need to update/provide information about the project: roadmap, clear gouvernance: who are maintainers, how to become a maintainer, etc

Actions:
* [x] setup page "about us" in wiki or website like here (https://scikit-learn.org/dev/about.html), add link to README.md
* [x] update "contributing guide" based on https://scikit-learn.org/dev/developers/contributing.html
* [x] add website link to README.md/Communication like here (https://github.com/scikit-learn/scikit-learn#documentation)
  * [x] add info about stable and dev documentations 
* [x] add "roadmap" page to wiki, add link to README.md
* [x] create twitter handle, add link to README.md

cc @sdesrozis @ykumards @anmolsjoshi

**Comment by sdesrozis** [comment]
All the points are very helpful for the project :)

Really excited to see the first tweet from `ignite` :)

**Comment by vfdev-5** [comment]
All done => Close the issue
