### ISSUE TITLE
Add state_dict user keys

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#913]
## 🚀 Feature

There can be cases when user would like to save some custom state attributes when storing the engine. It can be helpful if `engine.state_dict` could return in addition user defined keys.
Proposed API:
```python
engine = Engine(...)
engine.state_dict_user_keys.append("user_value")
...

@engine.on(Events.STARTED)
def init_user_value(_):
     engine.state.user_value = ...

@engine.on(...)
def save_engine(_):
    state_dict = engine.state_dict()
    assert "user_value" in state_dict
    torch.save(state_dict, "/tmp/engine.pt")
```

**Comment by sdesrozis** [comment]
It is not wanted to save automatically all what is added in `state` ?

**Comment by vfdev-5** [comment]
No, as we can have non-serializable or other large objects that are just for exchange purposes...

**Comment by sdesrozis** [comment]
Ok an alternative could be to specify what should not be saved despite what should be saved. It depends on what the nominal scenario is.
