### ISSUE TITLE
KeyError: 'api_token' in NeptuneLogger

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#947]
## 🐛 Bug description

When I specify api_token from `os.environ["NEPTUNE_API_TOKEN"]` I have the following warning
```
WARNING: It is not secure to place API token in your source code. You should treat it as a password to your account. It is strongly recommended to use NEPTUNE_API_TOKEN environment variable instead. Remember not to upload source file with API token to any public repository.
```

When I remove `api_token`
```python
npt_logger = npt_module.NeptuneLogger(
        project_name="vfdev-5/my_project", 
        experiment_name="test",
        params=config
)
```
there is the following error:
```
  File "/opt/conda/lib/python3.7/site-packages/ignite/contrib/handlers/neptune_logger.py", line 447, in __init__
    neptune.init(api_token=kwargs["api_token"], project_qualified_name=kwargs["project_name"])
KeyError: 'api_token'
```

@jakubczakon shouldn't we explicitly set it up internally to None ?

## Environment

 - PyTorch Version (e.g., 1.4): 1.4
 - Ignite Version (e.g., 0.3.0):  0.4.0.dev20200418
- Neptune: 0.4.111

**Comment by jakubczakon** [comment]
Hi @vfdev-5 I am looking into it right away.

**Comment by jakubczakon** [comment]
Mhm, I see the problem. 
I'll fix and PR. 

The warning is on the neptune-client side, and it's not going to be converted to errors but still, it shouldn't be there.
