### ISSUE TITLE
Improve Neptune logger 

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#948]
## 🚀 Feature

Idea is to be able use neptune API directly from an instance of `NeptuneLogger`. Same is done for MLflow logger:
https://github.com/pytorch/ignite/blob/29058e2f0e7d753cbd8dbb254652288afa81bda0/ignite/contrib/handlers/mlflow_logger.py#L248-L254

**Comment by jakubczakon** [comment]
What would be the benefit @vfdev-5 ?

Currently, you can access neptune experiment directly:

```
        self.experiment = neptune.create_experiment(**self._experiment_kwargs)
```

Which gives you a lot of flexibility (not all). 

There are things that you may want to access on the project level (one above experiment) and there is an API for that but I am wondering if that is important for the ignite user.

I am fine with adding this, just would like to understand more.

**Comment by vfdev-5** [comment]
@jakubczakon idea is to simplify the usage and economize the number of chars to write
```
npt_logger.log_text(...)  # <-> neptune.log_text(...)
# vs 
npt_logger.experiment.log_text(...)
```

if user would like to access experiment's specific ops, he/she can use 
```
npt_logger.experiment.spec_exp_op
```

EDIT: Removed duplicated message

**Comment by jakubczakon** [comment]
Mhm, I understand now!

I am almost done with updating the logger and tests.

PS:
Sorry for the duplicated comments, I think github server had some problems.

**Comment by ryanwongsa** [comment]
@jakubczakon I think the recent merged PR #937 might have affected the `n_saved` parameter in the Checkpoint handler and NeptuneSaver as it seems to save more checkpoints than the number I specified for my neptune experiments. It wasn't happening a couple of days ago.

**Comment by jakubczakon** [comment]
@ryanwongsa thanks for the info!

Let me take a look, could you open a separate issue (No worries if you don't)?

**Comment by vfdev-5** [comment]
@jakubczakon @ryanwongsa sorry for breaking that ! I'll fix that

**Comment by jakubczakon** [comment]
Perfect @vfdev-5 !

**Comment by ryanwongsa** [comment]
I added the Neptune Saver issue #950
