### ISSUE TITLE
-

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#949]

**Comment by jakubczakon** [comment]
What would be the benefit @vfdev-5 ?

Currently, you can access neptune experiment directly:

```
        self.experiment = neptune.create_experiment(**self._experiment_kwargs)
```

Which gives you a lot of flexibility (not all). 

There are things that you may want to access on the project level (one above experiment) and there is an API for that but I am wondering if that is important for the ignite user.

I am fine with adding this, just would like to understand more.
