### ISSUE TITLE
TPU Example / Support

### ISSUE THREAD

**Issue by ryanwongsa** [pytorch/ignite#952]
## ❓ Questions/Help/Support

I would like to use Ignite with TPUs and was wondering if there are any examples currently available which currently use TPUs with Ignite or does Ignite have some limitations which would not allow for easy compatibility with TPUs.

**Comment by vfdev-5** [comment]
@ryanwongsa unfortunately, there is no yet examples of using Ignite with TPUs. 

I think there is no limitations on that as PyTorch xla API is rather similar to GPUs. But, yes, it will be good idea to add some example with Colab link.

**Comment by vfdev-5** [comment]
@ryanwongsa please checkout added [example](https://github.com/pytorch/ignite/blob/master/examples/mnist/mnist_with_tensorboard_on_tpu.py) or [notebook in Colab](https://colab.research.google.com/github/pytorch/ignite/blob/master/examples/notebooks/MNIST_on_TPU.ipynb) and, please, do not hesitate to give us any feedback.

**Comment by ryanwongsa** [comment]
Thanks.

I am not sure if it is suitable for including in an example notebook but there are currently Kaggle kernels which use TPU training on 8 cores, such as [bert-multi-lingual-tpu-training-8-cores](https://www.kaggle.com/abhishek/bert-multi-lingual-tpu-training-8-cores) and I was wondering what the best approach would be to do it in a similar way with Ignite.

The torch_xla `ParallelLoader` is also used on top of a `Dataloader` which might cause issues too but I am not sure.

**Comment by vfdev-5** [comment]
@ryanwongsa let me check this kernel with Ignite.
