### ISSUE TITLE
Check sync all reduce of metrics in DDP

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#964]
## 🚀 Feature

Idea is to benchmark this part of the code:
https://github.com/pytorch/ignite/blob/0b363974e93e2f79e468cf4a7851a149b96028a7/ignite/metrics/metric.py#L92-L95

and if it produce a considerable overhead, therefore make a global definition of `dist.is_available() and dist.is_initialized()` inside `Metric.__init__` instead of checking all the times.

cc @sdesrozis

**Comment by sdesrozis** [comment]
Called per epoch ? I should be surprised if it produces overhead.

**Comment by vfdev-5** [comment]
> Called per epoch ? I should be surprised if it produces overhead.

Let's consider `RunningAverage` as example.

**Comment by vfdev-5** [comment]
Closes as irrelevent due to coming `idist` branch
