### ISSUE TITLE
Setup Typing in contrib part of the library

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#977]
## 🚀 Feature

Following #651, idea is to improve contrib code by adding Typing.

**Comment by RaviTezu** [comment]
Hi @vfdev-5 Is this issue still open? If yes, I would like to give it a try. Thanks.

**Comment by vfdev-5** [comment]
@RaviTezu yes, it is still open. Sure, please go ahead ! I'll assign you to this issue.
