### ISSUE TITLE
Make EpochMetric work in DDP

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#978]
## 🚀 Feature

Currently, metrics like `EpochMetric` which store complete history of predictions and targets, are not supporting DDP setting. 
Idea is to perform [gather](https://pytorch.org/docs/stable/distributed.html#torch.distributed.gather) on zero rank process in `compute` method to accumulate all predictions and targets across all the processes and then execute metric function...
We may also need to warn about high memory consumption of this approach.

cc @sdesrozis

**Comment by sdesrozis** [comment]
Maybe this feature could be disabled by user if he can do better.

**Comment by vfdev-5** [comment]
I agree
