### ISSUE TITLE
Simplified base logger's API

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#980]
## 🚀 Feature

Idea is to simplify current logger's API by creating a shortcut methods:
Currently, to log output parameters and optmizer's params we do (example is for TB, but is generic for others too):
```python
    logger = TensorboardLogger(...)
    logger.attach(
        trainer,
        log_handler=OutputHandler(tag="training", metric_names="all"),
        event_name=Events.ITERATION_COMPLETED(every=log_every_iters),
    )
    logger.attach(
        trainer,
        log_handler=OptimizerParamsHandler(optimizer, param_name="lr", tag=k),
        event_name=Events.ITERATION_STARTED(every=log_every_iters),
    )
```
Proposed API:
```python
    logger = TensorboardLogger(...)
    logger.attach_output_handler(
        trainer,
        tag="training", metric_names="all",  # other args, kwargs of OutputHandler
        event_name=Events.ITERATION_COMPLETED(every=log_every_iters),
    )
    logger.attach_opt_params_handler(
        trainer,
        optimizer, param_name="lr", tag=k, # other args, kwargs of OutputHandler
        event_name=Events.ITERATION_STARTED(every=log_every_iters),
    )
```

In addition, this can fix "bad-practice" current implementation of `setup_any_logging` taking as input logger and logging_module:
https://github.com/pytorch/ignite/blob/d1aa5fd5e71676032c952aa7470a651c216e2dd9/ignite/contrib/engines/common.py#L209

**Comment by vfdev-5** [comment]
@sdesrozis any other suggestions for simplified API

cc @sisp (if you have any suggestions too), once this issue is solved we can fix and merge your PR #901

**Comment by sdesrozis** [comment]
I don't have any suggestion. We might have a generic attachment using `getattr`.

**Comment by vfdev-5** [comment]
> We might have a generic attachment using getattr.

@sdesrozis,  please, this point

**Comment by sdesrozis** [comment]
> > We might have a generic attachment using getattr.
> 
> 
> 
> @sdesrozis,  please, this point

Class is encoded in name of methods. Using `__getattr__`, I think that it is possible to parse the name and allocate related object in a generic way.

**Comment by vfdev-5** [comment]
@sdesrozis it's too hacky for me, such approach.

Let's implement the methods `logger.attach_output_handler` and `logger.attach_opt_params_handler`

**Comment by sdesrozis** [comment]
I will do it this week-end if nobody does ;)
