### ISSUE TITLE
Engine restarts training from scratch unexpected

### ISSUE THREAD

**Issue by H4dr1en** [pytorch/ignite#993]
## 🐛 Bug description

Engine `_is_done` function only takes into account `max_epochs` parameter read from the state of the object. This leads to the followling unexpected behavior:

1. Instantiate a simple engine, train for 2 epochs (set max_epochs=2). Save checkpoints.
2. Train for 2 more epochs (set max_epochs=4) using last checkpoint.
3. This leads to the training restarting from scratch instead of continuing from the last checkpoint.

Why?

Engine.run functions has a `max_epochs` parameter that should have the precedence over the `max_epochs` stored in the checkpoint state in the [_is_done](https://github.com/pytorch/ignite/blob/master/ignite/engine/engine.py#L605). 
Currently, at runtime, to check if the training is done, we consider `max_epochs` from the state of the checkpoint, not the `max_epochs` parameter from the user. Therefore if the user specifies a different value (in the case he wants to train for more epochs), his input is not taken into account.

Here is a possible workaround to explain how to solve the problem:
```
    @staticmethod
    def _is_done(state, max_epochs=None):
        return state.iteration == state.epoch_length * (state.max_epochs if max_epochs is None else max_epochs)
```

## Environment

 - PyTorch Version (e.g., 1.4): 1.4.0
 - Ignite Version (e.g., 0.3.0): 0.4.0
 - OS (e.g., Linux): macOS
 - How you installed Ignite (`conda`, `pip`, source): pip
 - Python version: 3.6.10
 - Any other relevant information:

**Comment by vfdev-5** [comment]
@H4dr1en thanks for the report !

I could reproduce the problem:
```python
import torch
import ignite
print(ignite.__version__)
from ignite.engine import Engine, Events
from ignite.utils import setup_logger


torch.manual_seed(12)


def train_step(trainer, batch):
    s = trainer.state
    print(
        "{}/{} : {} - {:.3f}".format(s.epoch, s.max_epochs, s.iteration, batch)
    )

trainer = Engine(train_step)
trainer.logger = setup_logger()

saved_states = []

# This emulates Checkpoint to save trainer and others
@trainer.on(Events.COMPLETED)
def save_state():
    saved_states.append(trainer.state_dict())


data = [0, 1, 2]

trainer.run(data, max_epochs=2)
print(saved_states)

# This is a workaround
# saved_states[0]['max_epochs'] = 4  
trainer.load_state_dict(saved_states[0])
trainer.run(data, max_epochs=4);
```
This looks like a bug. If run's input params override defined state, it should taken into account before checking `_is_done`.

**Comment by vfdev-5** [comment]
@H4dr1en this bug is fixed in the master and in nightly release since.

**Comment by H4dr1en** [comment]
Works like a charm @vfdev-5, thanks for the quick fix!
