### ISSUE TITLE
Metrics for GANs

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#998]
## 🚀 Feature

It would be interesting to provide metrics for generated image evaluation like here: 
- https://github.com/clovaai/stargan-v2/blob/master/metrics/
- https://github.com/Tetratrio/stylegan2_pytorch/tree/master/stylegan2/metrics

**Comment by kamahori** [comment]
@vfdev-5 
I am interested in this issue.
I think that possible metrics would be inception scores, FID, PPL, or LPIPS.
Do you have any priorities? I can start working on one of them.

**Comment by vfdev-5** [comment]
@kamahori thanks ! You can start by any metric you'd like. Maybe, those for stylegan2 would be a little bit more prioritized.

**Comment by kamahori** [comment]
@vfdev-5 Okay, then let me start with FID.

**Comment by vfdev-5** [comment]
Let's close this issue as Arpan already implemented FID and IS, available in v0.4.6
